### PR TITLE
Break out of cursor.forEach by returning false

### LINKED ISSUE #1370: Break out of cursor.forEach by returning false
It would be extremely helpful to break out of a `cursor.forEach` loop. The way some other libraries handle this, including jQuery's `.each()`, is by returning false. I quote from the [jQuery documentation](http://api.jquery.com/jQuery.each/):

> We can break the `$.each()` loop at a particular iteration by making the callback function return `false`. Returning _non-false_ is the same as a `continue` statement in a for loop; it will skip immediately to the next iteration.

EDIT: I realize that the whole point of Minimongo is that it exactly replicates the functionality of the server-side node mongo driver. I've also filed this issue request on the official node driver. When/if it gets added there, we should do it here too.

### PR DESCRIPTION
**Pull request by BenjaminRH**
Fixes #1370

### CODE REVIEW

**Comment by BenjaminRH** [comment]
Any updates?

**Comment by EMGXF** [comment]
@BenjaminRH Not to be irrelevant but do you still run Adventurize?

**Comment by BenjaminRH** [comment]
@EMGXF yes, and I've actually just begun serious work on taking it out of beta. Why do you ask?

**Comment by EMGXF** [comment]
@BenjaminRH yeeeeeeeeeeeeePEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
adBolt bans for false reasons, I need a new place.
I'm a publisher, but no ads show, so I was jsut looking to see if this is legit ad service

**Comment by EMGXF** [comment]
@BenjaminRH any ETA?

**Comment by glasser** [comment]
@BenjaminRH Well, tests and the server implementation were requested and not added.

**Comment by EMGXF** [comment]
hi

**Pull request closed without merging**
