### PR TITLE
Release 2.0

### PR DESCRIPTION
**Pull request by filipenevola**
Meteor 2.0 is coming.

We have big features coming like Hot Module Replacement and Tree-shaking.

We are not planning any breaking change but as these features are expected for a long time and they require a lot of changes in the internals we have decided it's the perfect timing for a major bump.

Also, you should expect more major bumps in the future, we don't want to hold Meteor in a major version for years like it was with Meteor 1.

Very soon we are going to start a new beta of Meteor 2.0.

---

Update 2021/01/12: Tree-shaking [implementation](https://github.com/meteor/meteor/pull/11164) is going well (tests are passing) but we still have some bug reports to fix and performance optimizations to do, so we are moving it to Meteor 2.1 as we don't want to hold HMR and Meteor free deploy including MongoDB any longer.

As we know Tree-shaking is not an easy task but we are close. 

---

Update 2021/01/17: We are also working to have Node.js 14 in a new version soon.

### CODE REVIEW

**Comment by filipenevola** [comment]
Meteor 2.0-beta.1 is available. You can try it today.

Update your app running `meteor update --release 2.0-beta.1`.

At this point the main addition is HMR, read more below and please provide feedback:

### Hot module replacement (HMR):  
  To use Hot module replacement in your Meteor app you need to add the package `hot-module-replacement`. You can do this by running `meteor add hot-module-replacement`. 
  
  This package is only for development (`debugOnly`). You don't need to worry about it affecting your production bundle.
  
  HMR updates modified files in the app without having to reload the page or restart the app. This is usually faster (many times updating the page before the build has finished), and allows state to be preserved, though it is also less reliable. In situations where HMR is not supported, it uses hot code push to update the page.

  HMR is only available for apps that use the modules package. It will probably not work correctly with apps that use globals (though globals from packages or npm dependencies are fine) since it uses import/require to detect which modules need to be re-evaluated. [more](https://github.com/meteor/meteor/pull/11117)

**Comment by StorytellerCZ** [comment]
:exploding_head: 
Since we are doing a major version bump I'm going to lobby to remove compatibility code for stuff before 1.0 release, some of which the community documented here: https://forums.meteor.com/t/stuff-to-be-removed-in-meteor-2-0/53949?u=storyteller

**Comment by sebakerckhof** [comment]
Let's maybe also think about browser support. Do we shift the edge on what is considered modern and do we keep workarounds for old IE versions?

**Comment by StorytellerCZ** [comment]
Also would like if we could get Node 14 into this release.

**Comment by jankapunkt** [comment]
Regarding old IE support - isn't that the purpose of `web.browser.legacy` or is old IE considered beyond legacy, like stone age?

If so, would it make sense to extract old IE-relevant patch code into packages? I have no overview where and how deep / tight this code is integrated but that would come into my mind at first

**Comment by sebakerckhof** [comment]
@jankapunkt It is, but it goes further than that.
There are specific IE workarounds ( https://github.com/meteor/meteor/blob/d9db4f52f2ea6d706a25156768ea42e1fbb8f599/packages/oauth/oauth_browser.js#L27 comes to mind), the build tool splits CSS into multiple files for some IE versions. Do we still want to include es5-shim by default? etc... 

Also, unless we want to introduce a third bundle, the legacy/modern is binary. This holds us back from pushing modern further. Since it might mean a slightly outdated device (especially phones) might now get all the extra polyfills etc. to make IE8 work.

**Comment by CaptainN** [comment]
There are still large corporate infrastructures running PCs stuck on IE - it'd be nice to be able to get rid of it, but I also think it's important to maintain a path for users to get to IE support if they need it.

**Comment by xet7** [comment]
I would be really worried if Meteor removed some browser support. Currently I'm trying to add support for more browsers in Meteor-based Wekan.

**Comment by stolinski** [comment]
What are everyone considering old IE here? I think specific versions are important, because to me, any IE is old IE in 2020, but I realize that's not everyone's requirements. Microsoft officially stopped supporting IE8, IE9 and IE10 over four years ago. So dropping support IMO for 8 ,9, 10 should be done.

**Comment by rj-david** [comment]
We have a forked webapp package and upgrading to the Meteor 2.0 beta is causing some version constraints. What is the best way to run a beta while maintaining our forked webapp package?

**Comment by ArchiCroc** [comment]
I updated my [boilerplate app](https://github.com/ArchiCroc/pup-plus) to 2.0-beta.3 and noticed that 
`{ "meteor": { "nodeModules": { "recompile": { "query-string": "legacy" }}}}` in package.json
isn't working to get my app  running in ie11. I did a little more digging and it is broken for me in v1.11.1 too but not v1.10.2.  I saw someone filed an issue #11215 about it.

**Comment by ArchiCroc** [comment]
> What are everyone considering old IE here? I think specific versions are important, because to me, any IE is old IE in 2020, but I realize that's not everyone's requirements. Microsoft officially stopped supporting IE8, IE9 and IE10 over four years ago. So dropping support IMO for 8 ,9, 10 should be done.

I use Meteor in enterprise and I would like to see support for IE11 for at least another year if possible.  I don't see a need to keep support for versions older than that.

**Comment by renanccastro** [comment]
Hello, all!
Version 2.0-beta.4 is released, with tree-shaking. We really need your feedback on this one. Details on how to use it can be found here: https://github.com/meteor/meteor/pull/11164 or in the PR changelog.

**Comment by afrokick** [comment]
I have an error when trying to import ts file in js file.

The error appears in Sources tab of Chrome devtools:

```
Could not load content for meteor://💻app/client/main.js (HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME)
```

Screenshot 2020-11-17 at 10 46 32

Test repo: https://github.com/afrokick/test-meteor-20-beta4

It works fine with 1.11.1

**Comment by StorytellerCZ** [comment]
Strange, starting with `beta.4` I'm getting an error on startup. The stacktrace points to GraphQL merge which is strange. Works fine in 1.11.
```
W20201118-13:00:09.073(1)? (STDERR) /home/storyteller/.meteor/packages/meteor-tool/.2.0.0-beta.4.1n9cm8t.sn5yh++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20201118-13:00:09.075(1)? (STDERR) 						throw(ex);
W20201118-13:00:09.076(1)? (STDERR) 						^
W20201118-13:00:09.076(1)? (STDERR) 
W20201118-13:00:09.076(1)? (STDERR) TypeError: Cannot read property 'definitions' of undefined
W20201118-13:00:09.076(1)? (STDERR)     at /home/storyteller/Web/Literary-Universe/app/node_modules/@graphql-tools/merge/index.cjs.js:770:25
W20201118-13:00:09.076(1)? (STDERR)     at Array.map (<anonymous>)
W20201118-13:00:09.076(1)? (STDERR)     at mergeGraphQLTypes (/home/storyteller/Web/Literary-Universe/app/node_modules/@graphql-tools/merge/index.cjs.js:770:10)
W20201118-13:00:09.076(1)? (STDERR)     at mergeTypeDefs (/home/storyteller/Web/Literary-Universe/app/node_modules/@graphql-tools/merge/index.cjs.js:737:22)
W20201118-13:00:09.077(1)? (STDERR)     at module (imports/api/graphql/index.js:141:22)
W20201118-13:00:09.077(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20201118-13:00:09.077(1)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20201118-13:00:09.077(1)? (STDERR)     at Module.moduleLink [as link] (/home/storyteller/.meteor/packages/modules/.0.16.0-beta200.4.1y9vd61.su71k++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
W20201118-13:00:09.077(1)? (STDERR)     at module (server/configs/apollo.js:37:8)
W20201118-13:00:09.077(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20201118-13:00:09.077(1)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20201118-13:00:09.077(1)? (STDERR)     at Module.moduleLink [as link] (/home/storyteller/.meteor/packages/modules/.0.16.0-beta200.4.1y9vd61.su71k++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
W20201118-13:00:09.078(1)? (STDERR)     at module (server/main.js:18:8)
W20201118-13:00:09.078(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20201118-13:00:09.078(1)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20201118-13:00:09.078(1)? (STDERR)     at require (packages/modules-runtime.js:258:21)
W20201118-13:00:09.078(1)? (STDERR)     at /home/storyteller/Web/Literary-Universe/app/.meteor/local/build/programs/server/app/app.js:29001:15
W20201118-13:00:09.078(1)? (STDERR)     at /home/storyteller/Web/Literary-Universe/app/.meteor/local/build/programs/server/boot.js:401:38
W20201118-13:00:09.078(1)? (STDERR)     at Array.forEach (<anonymous>)
W20201118-13:00:09.078(1)? (STDERR)     at /home/storyteller/Web/Literary-Universe/app/.meteor/local/build/programs/server/boot.js:226:21
W20201118-13:00:09.078(1)? (STDERR)     at /home/storyteller/Web/Literary-Universe/app/.meteor/local/build/programs/server/boot.js:464:7
W20201118-13:00:09.079(1)? (STDERR)     at Function.run (/home/storyteller/Web/Literary-Universe/app/.meteor/local/build/programs/server/profile.js:280:14)
=> Exited with code: 1
```

**Comment by renanccastro** [comment]
That's a known issue @StorytellerC, it's happening with .graphql files, follow this issue here: https://github.com/meteor/meteor/issues/11231

**Comment by renanccastro** [comment]
Related to sourcemaps failing to load, can you open an issue @afrokick , please? My guess is that it doesn't impact application load/serve, but impacts debugging.

**Comment by afrokick** [comment]
@renanccastro done https://github.com/meteor/meteor/issues/11248

**Comment by filipenevola** [comment]
Meteor 2.0 beta 6 is out 🚀 

> beta.5 was broken due to a missing file in a new package

Read this update:

> Update 2021/01/12: Tree-shaking implementation is going well (tests are passing) but we still have some bug reports to fix and performance optimizations to do, so we are moving it to Meteor 2.1 as we don't want to hold HMR and Meteor free deploy including MongoDB any longer.
> 
> As we know Tree-shaking is not an easy task but we are close.

Beta 6 includes:
- Deploy to Galaxy for free (*not available for general public yet*), `--free`
- MongoDB auto configured on Galaxy and for free (*not available for general public yet*), `--mongo`
- Hot Module Replacement support (HMR) for React apps

Please help us testing the HMR ([PR](https://github.com/meteor/meteor/pull/11117)):
```shell
meteor update --release METEOR@2.0-beta.6
meteor add hot-module-replacement
```

Then start your app as usual, you will see something like:

```shell
meteor
[[[[[ ~/Documents/meteor/ws/tests/myappbeta6 ]]]]]

=> Started proxy.                             
=> Started HMR server. 
```

And when you change React components you are going to see logs like this in your client console:
myappbeta6 2021-01-12 14-52-53

You should expect the final version pretty soon, so hurry up and report here if you find any bugs.

**Comment by filipenevola** [comment]
Meteor 2.0-beta.9 is out!

**Comment by filipenevola** [comment]
Meteor 2.0-rc.0 is published.

You can use it now updating your app:
```shell
meteor update --release 2.0-rc.0
```

Or you can create a new app:
```shell
meteor create my-app --react --release 2.0-rc.0
```

Please provide feedback here.

**Comment by jbbr** [comment]
When upgrading from `2.0-beta.6` to `2.0-rc.0` I'm experiencing some package downgrades and constraint issues.

e.g:
```
error: Conflict: Constraint logging@1.1.17 is not  satisfied by logging 2.0.0-rc200.0
...
* logging@2.0.0-rc200.0 <- webapp 1.10.0-rc200.0 <-  meteor-base 1.4.0
* logging@1.1.17 <- percolate:migrations 1.0.2
```

The packages which cause these issue do not have a strict constraint for `logging`.
They just have something like `api.use('logging')`

Workaround: Add strict version constraint for 2.0 rc, e.g `api.use('logging@2.0.0-rc200.0')`

Not sure if this is incorrect behavior or expected behavior based on the version constraints/version locks of my third party packages. Just wanted to mention - maybe this helps others who might also experience those issues.

**Comment by filipenevola** [comment]
hi @jbbr try `2.0-rc.1` please and let me know.

**Comment by jbbr** [comment]
@filipenevola thanks, now it updates without issues.

It's just mentioning potentially available 2.x versions, no hard errors though:
```
The following top-level dependencies were not updated to the very latest version available:
 * accounts-password 1.7.0-rc200.1 (2.2.0-beta.3 is available)
 ...
Newer versions of the following indirect dependencies are available:
 * logging 1.2.0-rc200.1 (2.0.0-rc200.0 is available)
```

**Comment by filipenevola** [comment]
> The following top-level dependencies were not updated to the very latest version available:
>  * accounts-password 1.7.0-rc200.1 (2.2.0-beta.3 is available)
>  ...
> Newer versions of the following indirect dependencies are available:
>  * logging 1.2.0-rc200.1 (2.0.0-rc200.0 is available)
> ```

I have cleaned up some packages with incomplete version, this shouldn't be a problem anymore.

**Comment by filipenevola** [comment]
Meteor 2.0.rc.3 is out.

**Pull request merged**
