### PR TITLE
Node Stubs dependencies update

### PR DESCRIPTION
**Pull request by StorytellerCZ**
Update dependencies that had patch and minor version releases. Additionally did a security deep update on dependencies highlighted by `npm audit`.

See: https://github.com/meteor/meteor/pull/12795#issuecomment-1827267923

### CODE REVIEW

**Comment by Grubba27** [comment]
Need to update as well where we use node stubs i think

**Comment by StorytellerCZ** [comment]
@Grubba27 done, but will require publication of the package for the tests to work.

**Comment by Grubba27** [comment]
Published!

**Comment by StorytellerCZ** [comment]
```
1 failure:
  - create.js: test:create --vue
 ```

I think we fixed this somewhere else.

**Pull request merged**
