### PR TITLE
Update Facebook API calls to v5

### PR DESCRIPTION
**Pull request by StorytellerCZ**
Updates Facebook API endpoints to v4. There are no changes in this regards since v3 upgrade. As far as I have tested everything went smoothly.

### CODE REVIEW

**Comment by filipenevola** [comment]
@StorytellerCZ v4 is 100% compatible with v3? Could you update your branch as 1.8.2 was already release? Thanks

**Comment by StorytellerCZ** [comment]
Updated.
As for compatibility, non of the changes affect us (OAuth). [V4 changes](https://developers.facebook.com/ads/blog/post/2019/07/29/introducing-graph-api-v4-marketing-api-v4/) are mainly in other areas (unless I missed something). The only concern I see is in [token depracation](https://developers.facebook.com/docs/graph-api/changelog/version4.0#access-tokens), but any concerned parties would have been notified by Facebook already.

Since I created this PR, [v5 of the API has been released](https://developers.facebook.com/blog/post/2019/10/31/introducing-graph-api-v5-marketing-api-v5/). Also in this case the breaking changes are not in OAuth so it is safe to upgrade.

**Comment by sebakerckhof** [comment]
@StorytellerCZ Could you maybe update this to v5?

**Comment by StorytellerCZ** [comment]
@sebakerckhof Done!

**Pull request merged**
