### PR TITLE
Added options to extend ddp for custom messages

### PR DESCRIPTION
**Pull request by okland**
By either giving option in connection creation `options._customMessages`.
Or dynamically by extending Meteor.connection
```
_.extend(Meteor.connection._customMessages, {
    updateBatch: function() {},
    subscriptionRedirect: function(){}
});
```

I needed this for couple of use cases :
1. Handling sending batch updates from server to client.
2. Do subscription redirect - send the client to get subscription from another server.

### CODE REVIEW

**Comment by okland** [comment]
This is a re-open of https://github.com/meteor/meteor/pull/5939

**Comment by HynesIP** [comment]
+1

**Comment by stubailo** [comment]
@okland would you mind opening a topic on the Meteor forums as well? Just want to get as many people's eyes on it, since this would be a very significant change and I want to see what people think beyond just a +1.

**Comment by okland** [comment]
@stubailo Great, i opened a topic in the Meteor forum https://forums.meteor.com/t/should-we-allow-custom-ddp-messages-a-way-to-scale-meteor-apps/17412

**Comment by knigal** [comment]
+1

**Comment by wojtkowiak** [comment]
If anybody needs this kind of functionality I am already using it for more than an year and recently published the mechanism as a package: https://github.com/wojtkowiak/meteor-custom-protocol.

**Comment by zol** [comment]
Hey, Thanks for submitting this PR. There appears to be demand for a feature like this however we're not planning on updating the DDP protocol right now so I'm going to close the PR. I realize the PR is only against the client but it doesn't make sense for us to ship just this part.

**Comment by okland** [comment]
Hey @zol, this is just part of a bigger optional PR, PR that include sending messages in batch from the server, Would you accept the bigger change ?
How do you recommend sending custom messages from server to clients ?
You can implement it in hackish ways like overriding the DDPCommon.parseDDP function but i think that each complicated app needs this feature eventually, so why not integrate it into the core ?

**Comment by zol** [comment]
Releasing a new version of DDP is a high impact change on the Meteor user base and needs to be managed carefully. When we do it we'll use the opportunity to analyze other frequently requested features as well as stuff that's on our long term roadmap and make the changes in one version bump.

**Pull request closed without merging**
