### PR TITLE
Respond to proxy requests properly (try fix #1212)

### LINKED ISSUE #1212: Meteor server exception when mistakenly used as a proxy
Even with no clients running the server throws this exception at random times but consistently. Strangely the apparently offending URL is always the same as shown below.

Error: url must be a relative URL: http://www.baidu.com/
    at _.extend.classify (app/packages/routepolicy/routepolicy.js:92:13)
    at appUrl (/root/application/.meteor/local/build/server/server.js:160:41)
    at Object.run [as handle] (/root/application/.meteor/local/build/server/server.js:310:13)
    at next (/root/.meteor/tools/cc18dfef9e/lib/node_modules/connect/lib/proto.js:190:15)
    at Router._start (app/packages/router/lib/router_server.js:83:20)

### PR DESCRIPTION
**Pull request by Tarang**
Try to fix #1212 by responding to a proxy request with an `Invalid Request` error on the browser end instead of no error and an error on the server logs.

### CODE REVIEW

**Comment by glasser** [comment]
I figured out for myself how to test this change and made my suggested changes and merged it.

**Comment by jamesfebin** [comment]
@glasser Meteor 1.0.2.1 still has this issue . My site stops running because of this. Can you tell me what to do about it ?

**Comment by glasser** [comment]
Wait until the next release?

That said I have never heard anyone say that this issue crashed their app (as opposed to just printing a stack trace and moving on). Maybe you're seeing something different.

**Comment by jamesfebin** [comment]
@glasser I only see this as the error in the logs. The site doesn't stop running as in . It won't respond to any of my meteor methods.. Like login doesn't work etc.

**Comment by jamesfebin** [comment]
Also go through comments of this https://github.com/meteor/meteor/issues/1212 .. "i've got this too, and site stop running." --  crapthings

**Comment by glasser** [comment]
If you're still seeing this issue, please file a new bug following our [bug reporting guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor).

**Pull request closed without merging**
