### PR TITLE
Support creating new meteor app in current directory

### PR DESCRIPTION
**Pull request by alanning**
Small change allowing this convenient method:

`meteor create .`

Uses 'helloApp' as the name for the app/files.

Has come up multiple times on google groups.  Mostly due to the fact that people create repo's online first (github), then `git clone` it locally and want to make it a Meteor app, which is not supported by the current 'create' command.

Most recent discussion: https://groups.google.com/forum/#!topic/meteor-core/1wlD_X3FoPc

### CODE REVIEW

**Comment by leoj3n** [comment]
+1

**Comment by applepicke** [comment]
+1 for this. Anytime you create a GitHub project initialized with a .gitignore and a README, it would be so very nice to be able to just clone it and then initialize the meteor app over top of it.

**Comment by trusktr** [comment]
I've needed this multiple times already. As a workaround I just create the project somewhere, then copy the files in.

**Comment by cryptoquick** [comment]
Agreed. I still run into this all the time, and the workaround is inconvenient, especially when lots of other framework tools have an init command.

**Comment by alanning** [comment]
Hi all, the core functionality for this is there in the branch / PR I
submitted but its out of date with latest Meteor.  If someone can update it
for Meteor-latest, I'd appreciate it!

**Comment by applepicke** [comment]
@alanning Okay i updated for the latest Meteor. Can be found at https://github.com/meteor/meteor/pull/4637

**Comment by stubailo** [comment]
This is done since Meteor 1.2!

**Comment by cryptoquick** [comment]
Nice! I just checked it out, `meteor create .` works!

**Pull request closed without merging**
