### PR TITLE
Missed filter to pass _getCollection through

### PR DESCRIPTION
**Pull request by mitar**
When making change into a pull request (#5845) I missed this file change.

This now provides a way to access collections from stores on the client.

### CODE REVIEW

**Comment by mitar** [comment]
cc @stubailo, please merge this one as well. ;-)

**Comment by mitar** [comment]
Or, not missed, but by allowing this you can also do:

```
Meteor.connection._stores['CollectioName']._getCollection()
```

Which helps a lot with current issue that you cannot register the same collection multiple times.

**Comment by dburles** [comment]
Hey, wondering why API isn't "public"? It could replace https://github.com/dburles/mongo-collection-instances

**Comment by mitar** [comment]
So that packages like mongo-collection-instances can use it and expose it and maintain a stable API despite internal API changing through time.

**Comment by dburles** [comment]
Oh cool, I had wondered if that was the idea!

**Comment by msavin** [comment]
@mitar this is client side only right? is there a server-side equivalent?

**Comment by mttstt** [comment]
ping

**Comment by mitar** [comment]
This can be on the server, if you are making a DDP client connection from the server. What do you mean by "server side equivalent"? What would you like to get?

**Pull request merged**
