### PR TITLE
Release 1.4.2.x

### PR DESCRIPTION
**Pull request by benjamn**
This release branch and pull request serve to collect important changes that should be released in the next 1.4.2.x patch release (1.4.2.4 as of this writing).

Such changes include obvious bug fixes from https://github.com/meteor/meteor/pull/8123 and other more experimental branches/PRs, where "obvious" means the changes are either extremely safe, very important, or both.

If you think an issue deserves consideration for this release branch, please ask for it to be added to the https://github.com/meteor/meteor/milestone/29 milestone.

### CODE REVIEW

**Comment by d62remi** [comment]
I think this PR is important https://github.com/meteor/meteor/pull/8142 ;-)

Thx

**Comment by d62remi** [comment]
Thx a lot ;-)

**Comment by benjamn** [comment]
Well, my hope of keeping this pull request open after 1.4.2.4 was apparently wishful thinking, since GitHub automatically closes pull requests that appear fully merged. Maybe next time I'll push a placeholder commit to the release branch and then merge the previous revision into `master`, just so that the release pull request stays open.

**Comment by janat08** [comment]
Is this not included in 1.4.3 beta then?

**Comment by benjamn** [comment]
@janat08 Everything here has been in the 1.4.3 beta branch for a while.

**Comment by abernix** [comment]
Meteor 1.4.2.4 was not (and will not be) marked as `recommended` (i.e. made official) due to the reason stated at the top of its upcoming successor: 1.4.2.5 (#8311).

Just so it's clear, 1.4.2.4 is still published and will work, however, it will require the additional step of running:

    meteor update modules-runtime

Or

    meteor update --all-packages

It's generally a good idea to do this second command during an upgrade anyway, but it's not always done in practice and we didn't want to make this (or any) upgrade more difficult than necessary.

**Pull request merged**
