### PR TITLE
Support easier creation of server side Blaze rendering

### PR DESCRIPTION
**Pull request by mitar**
This splits `templating` package into two packages, while keeping backwards compatibility.

This allows one to develop an alternative `templating` package which can for example render templates differently (see https://github.com/meteor/meteor/issues/5552 and https://github.com/peerlibrary/meteor-blaze-components/issues/99), and to provide server side compilation of templates with an alternative HTML compilation plugin. But one can still reuse code for `Template`.

Ideally, dynamic template would also be part of the base package, but it seems there is no way to add the HTML file and say "later on some other package will provide a plugin how to compile the HTML file, or to ignore it".

### CODE REVIEW

**Comment by stubailo** [comment]
OK, I think this is a good change overall (in general I think decoupling the runtime and build plugin is good as well).

I think we could could make everything work if we did this:

1. `templating-build-plugin` has just the HTML compiler
2. `templating` has just the dynamic and templating.js stuff, and depends on `templating-build-plugin`

Note that this will actually allow you to use only the compiler, or only the runtime, because the dependency on the build plugin inside templating is restricted to that package only.

**Comment by mitar** [comment]
> Note that this will actually allow you to use only the compiler, or only the runtime, because the dependency on the build plugin inside templating is restricted to that package only.

Hm, but will then this work? Because currently one makes a dependency on the `templating` (or `blaze-html-templates`) package when you want to process `*.html` in your app/package. If what you are saying is true, then dependency on the `templating` will not do this anymore? Does this mean that we also have to change that `blaze-html-templates` implies `templating-build-plugin`? But then `templating` will not have to depend on the `templating-build-plugin`?

Anyway, one other thing I would like to achieve is to be able to use all the content of the `templating` runtime also on the server side. So my build plugin works on the server side (in fact, I just removed the `archMatching` restriction and [things work](https://github.com/peerlibrary/meteor-blaze-components/blob/master/compile-templates.js)). But the issue is that by default `dynamic.html` cannot be processed on the server side. Any ideas how to make this work? One option would be that `dynamic.html` would be added as an asset which you can then compile on the server side?

Or should we remove the `archMatchin` [restriction](https://github.com/meteor/meteor/blob/devel/packages/templating/plugin/compile-templates.js#L3) and all client-only stuff in templating package and this is it? So then it is to the developers to decide to put `*.html` files only to the client side, or if they want, they can put it on the server side as well.

**Comment by mitar** [comment]
Hm, when trying to publish a package with:

```
Package.registerBuildPlugin({
  name: "compileBlazeComponentsTemplatesBatch",
  use: [
    'caching-html-compiler',
    'ecmascript',
    'templating-tools',
    'spacebars-compiler',
    'html-tools'
  ],
  sources: [
    'patch-compiling.js',
    'compile-templates.js'
  ]
});
```

I am getting:

```
error: You must specify a version constraint for package caching-html-compiler
error: You must specify a version constraint for package ecmascript
error: You must specify a version constraint for package templating-tools
error: You must specify a version constraint for package spacebars-compiler
error: You must specify a version constraint for package html-tools
```

Is this normal?

**Comment by stubailo** [comment]
Yes I don't know if versionsfrom exists for build plugins.

**Comment by stubailo** [comment]
Actually have you tried putting a versionsfrom in your package.onUse?

**Comment by mitar** [comment]
Yes, [I have it](https://github.com/peerlibrary/meteor-blaze-components/blob/master/package.js) but it is not respected. Should I open a ticket about this?

**Comment by mitar** [comment]
See also: https://github.com/meteor/meteor/issues/5911

**Comment by mitar** [comment]
See [also this for some issues with current approach](https://github.com/orionjs/orion/pull/381).

It seems that this support for multiple handlers for the same `*html` file is probably problematic. Probably most people want to imply `templating` because they want to expose `Template` automatically. But they do not really care how it is compiled or which package is compiling.

**Comment by stubailo** [comment]
OK I was wrong at first, we'd need three packages: just the runtime, just the build plugin, and then both.

And I'd say that people implying templating is just a bug in the package - there is no reason a package with useful runtime stuff should be implying a build plugin unless it's explicitly trying to be some kind of meta package.

Anyway, what changes would you need to core to export the right template stuff on the server?

**Comment by mitar** [comment]
> Anyway, what changes would you need to core to export the right template stuff on the server?

I would just remove all stuff which is limiting `templating` symbols and files to the client only. I manually copied files to Blaze Components, included them, and they work. The only tricky thing is #5913.

So I would suggest that my pull request is modified to create those three packages. And that all files and symbols are made to work both on the client and server. The only changes I had to do was:
* https://github.com/peerlibrary/meteor-blaze-components/blob/master/server.coffee
* https://github.com/peerlibrary/meteor-blaze-components/blob/master/patch-compiling.js#L87

So the problem for `<head>` is that it rendered by server, but it is added to the client to do so.

**Comment by mitar** [comment]
So, what should we do about this?

**Comment by stubailo** [comment]
Not sure. @zol ?

**Comment by zol** [comment]
This is a reasonable product change however I'd like someone technical to sign off on the PR, with an eye towards not breaking anything rather than whether it's the perfect solution. @stubailo are you in a position where you can give me the green light given you've already looked at this or should I find someone in the Meteor team?

**Comment by stubailo** [comment]
Yeah this looks fine to me. But looks like it should be in the Blaze repository now, right?

**Comment by zol** [comment]
@mitar - Could you please move this over to meteor/blaze and go ahead and merge it. I'd love to test out our process around collaborating through the split repo and iron out any wrinkles. I'm going to close it out on meteor/meteor

**Comment by mitar** [comment]
OK, but I am not completely satisfied with the design here. It would be really good to get some input here what should be the design of the solution.

**Comment by mitar** [comment]
Also, when will [blaze be removed from this repository](https://github.com/meteor/meteor/tree/devel/packages/blaze)? I am afraid this will lead to issues soon.

**Pull request closed without merging**
