### PR TITLE
Facebook oauth appId || clientId

### PR DESCRIPTION
**Pull request by d62remi**
Refers to https://github.com/meteor/meteor/issues/8381#issuecomment-280285213

### CODE REVIEW

**Comment by abernix** [comment]
@d62remi Thanks for making the change and for making your first contribution to Meteor!

Could you sign our [Contributor License Agreement](https://contribute.meteor.com/) so we can consider merging this?

**Comment by d62remi** [comment]
Voilà ! It's signed ;-)

**Comment by abernix** [comment]
I realize you did this from the "Edit" button on GitHub, so I'm not sure there's a way to "Amend" the commit message now that it's done, but in the future please provide a Git commit log message which explains the change that you're making instead of just "Update facebook_client.js". :smile:

If you can't edit it we can do it when merging, but if you'd like to close this PR and open a new one with a more explanatory commit log, that would also be fine.

(You can also `git checkout` this [`patch-1`](https://github.com/d62remi/meteor/tree/patch-1) branch (from [your repo](https://github.com/d62remi/meteor)) with `git` command line, run `git commit --amend`, expand the message, then `git push --force`)

**Comment by d62remi** [comment]
Close for this PR https://github.com/meteor/meteor/pull/8398

**Pull request closed without merging**
