### PR TITLE
Option to automatically update app node_modules to match package.json, etc.

### PR DESCRIPTION
**Pull request by mattmccutchen**
As of 2020-08-27, I'm making the motivation and design discoverable at the top.  I could file a separate issue in the meteor-feature-requests repo, but filipenevola suggests that's an unnecessary hassle.  Scroll to the bottom for recent discussion.

Meteor should have an option to make all relevant commands automatically install or update app-level npm packages to match `package.json` or similar configuration files.  After Meteor jumped through so many hoops to automate things (including updating of npm dependencies of local Atmosphere packages!) to maintain the single command to run an app from a checkout, it's deeply disappointing that Meteor abandoned this by encouraging app-level npm packages with no support for automatic updating.  In fact, my most important Meteor-based app uses a local Atmosphere package to update the npm packages it needs, and we have held off on migrating it to app-level npm packages because of the lack of automatic updating.

This feature request was originally raised in #6848; benjamn was very skeptical and closed the issue but left the door open for me to submit a PR.  Since then, filipenevola has stated a desire to add the feature.

The original design, based on benjamn's desire not to couple the feature to the npm tool at a time when it had serious limitations compared to other tools for installing npm packages, was to have the user opt in by specifying an arbitrary command to update the packages and a set of files Meteor should watch to trigger re-running the command.  However, my understanding is that since then, the npm tool has largely caught up to its competitors, so it may now make sense to add functionality to Meteor that is specific to the npm tool if there are significant benefits.

The specific proposed syntax to be placed in `package.json` was like this:
```json
  "meteor": {
    "npmAutoInstall": {
       "command": "unset TOOL_NODE_FLAGS && meteor npm prune && meteor npm install",
       "watchSpec": ["package.json", "npm-shrinkwrap.json"]
    }
  }
```
I have not yet checked whether it should be updated due to changes to Meteor since December 2016.  Suggestions welcome.

The implementation was to remember the hashes of the watched files in a hidden file in `node_modules`, not just in memory, so Meteor could avoid running the command even once on startup in case it was slow.  This assumes the user doesn't make manual changes to `node_modules` and expect Meteor to revert them, except that if the user blows away `node_modules` completely (e.g., via the version control system's "clean" command), Meteor will recreate it the next time it is started.

filipenevola notes:
> Another thing that we could try to tackle in the same PR is when you change to a Meteor version that uses a different version of Node.js, this sometimes break your binary dependencies on node_modules and just npm install is not enough to solve, you need to remove your binaries first (maybe there is a npm command for that? not sure) and install.

I have not yet learned how to implement this.

---

As described at:
https://github.com/meteor/meteor/issues/6848#issuecomment-264986992

The basic functionality seems to work, but some fine-tuning may be needed and the code could use cleanup (and probably a self-test case).  @benjamn, may I have your feedback before I put more work into refining this?  Thanks.

Test app:
https://github.com/mattmccutchen/meteor-npm-autoinstall-test

You can switch between the "master" and "with-codemirror" branches.

### CODE REVIEW

**Comment by abernix** [comment]
Sorry for not responding on this a very long time ago, with any comment at all; we realize you put some time into this.  This implementation might have some merit, especially as it seems to offer a very specific way to opt in and generally stay out of the way otherwise.

That said, it does conjure up a potential bottleneck in builds which requires additional consideration (to ensure that the blame is not put on Meteor for this slowness).  We haven't been able to give a lot of additional thought to it yet, but hope to revisit it soon.

One sub-project which should be done first would be a facility/library which handles a `meteor` section of `package.json`, watching it as appropriate (possibly as a dependency/component of [`project-context.js`](https://github.com/meteor/meteor/blob/devel/tools/project-context.js)?).

We've discussed this briefly in other issues: https://github.com/meteor/meteor/issues/6791#issuecomment-208959968, https://github.com/meteor/meteor/issues/8341#issuecomment-278747356 and (kinda, but eventually) https://github.com/meteor/meteor/issues/7829.  Perhaps we should get an issue open for that design first.

**Comment by mattmccutchen** [comment]
Thanks for the update, @abernix.  I put out a prototype in the hope of building momentum around the feature, but I don't see myself spending additional hours trying to design infrastructure to handle use cases with which I have no familiarity with no guarantee that this goes anywhere.  I went ahead and filed #8445.  If you can provide a more detailed design sketch for #8445 and give me some grounds to trust that you'd work with me to get both PRs merged, I may try my hand at it.  Otherwise, I think I'm leaving this behind unless/until the other people who claimed to want the original feature care enough to get involved.  I'm disappointed to see Meteor give up [the single command to run from a checkout](https://github.com/meteor/meteor/issues/6848#issuecomment-212184034) after having jumped through so many hoops to automate other things, but I have to go on with life.

**Comment by mattmccutchen** [comment]
I noticed the milestone settings.  Meteor maintainers, if you're serious about getting this functionality into an upcoming release, let me know and I will be happy to help.  I can rebase the change to the current "devel" branch of Meteor and retest it; then my request stands for feedback before I put more time into polishing it.

**Comment by filipenevola** [comment]
The CLA is still not signed, closing because of this.

**Comment by mattmccutchen** [comment]
I completed the process to sign the CLA, though the CLAassistant comment does not update even if I press the "recheck" link.  I'm not sure why I didn't attend to this the first time.  Please reopen this pull request unless you have also decided to reject the change on the merits; otherwise I might eventually submit a new pull request, or someone else could now that my prototype code is clearly licensed.  (I still doubt that the change will go anywhere, but I don't want it dropped from consideration for a silly reason like the CLA.)

**Comment by stolinski** [comment]
Bump bump. This was marked as closed, but would be a nice "meteor like" addition to the platform.

**Comment by filipenevola** [comment]
Hey @stolinski @mattmccutchen I like this idea my only concern is that we need to have a way to enable or disable this as in some cases you don't want this to happen automatically.

I believe Matt agrees with me as he said this feature would be opt-in:
> I don't see what the problem is when the feature is opt-in and Meteor clearly logs when it is calling the package manager.

Besides that I'm ok and we can create a new PR and start to test these changes.

Another thing that we could try to tackle in the same PR is when you change to a Meteor version that uses a different version of Node.js, this sometimes break your binary dependencies on node_modules and just npm install is not enough to solve, you need to remove your binaries first (maybe there is a npm command for that? not sure) and install.

Also I like the idea of having hooks, so anyone can customize what happens after/before these updates, like use yarn, etc.

@mattmccutchen are you willing to proceed? I can guarantee that you are going to have support from our side. I believe it would be better to open a new PR as CLA check was failing 😞 

If you prefer you could start an issue describing the solution that you would implement, the features that it would provide, the configuration options, etc.

@zodern feel free to add any ideas or concerns here as well.

**Comment by mattmccutchen** [comment]
This is a huge and welcome surprise!  I should be able to resume work on this feature in the next few days.

> Hey @stolinski @mattmccutchen I like this idea my only concern is that we need to have a way to enable or disable this as in some cases you don't want this to happen automatically.
> 
> I believe Matt agrees with me as he said this feature would be opt-in:
> 
> > I don't see what the problem is when the feature is opt-in and Meteor clearly logs when it is calling the package manager.

To clarify, I don't have a personal stance on whether the feature should be on by default but was deferring to the previous Meteor maintainers and will similarly defer to you.  At a minimum, it should be possible to turn it off.

> Another thing that we could try to tackle in the same PR is when you change to a Meteor version that uses a different version of Node.js, this sometimes break your binary dependencies on node_modules and just npm install is not enough to solve, you need to remove your binaries first (maybe there is a npm command for that? not sure) and install.

I agree we should investigate this problem, whether the solution ends up being in Meteor itself or just documenting the way users need to configure Meteor to solve the problem.  I have no prior knowledge of this problem.  Before I research it myself, would anyone care to provide links to more information?

> I believe it would be better to open a new PR as CLA check was failing

The CLA check seems to be fixed, so I think it makes sense to continue in this PR rather than force everyone to re-subscribe to a new one.  Of course, I will satisfy all the requirements that would apply to a new PR.  Let me know if you have another reason to start a new PR.

> If you prefer you could start an issue describing the solution that you would implement, the features that it would provide, the configuration options, etc.

I agree this would be appropriate and will file an issue in the meteor-feature-requests repo soon.

**Comment by filipenevola** [comment]
Hey @mattmccutchen go ahead with this PR, you don't need to open a new one. We can also discuss possible solutions here, you don't need to open a feature request.

Feel free to mention me here if necessary or DM me on [Community Slack](https://join.slack.com/t/meteor-community/shared_invite/enQtODA0NTU2Nzk5MTA3LWY5NGMxMWRjZDgzYWMyMTEyYTQ3MTcwZmU2YjM5MTY3MjJkZjQ0NWRjOGZlYmIxZjFlYTA5Mjg4OTk3ODRiOTc), I'm always around.

**Comment by mattmccutchen** [comment]
I have now summarized the motivation and old design at the top of this PR.  Feedback would be much appreciated before I set about updating the design and implementation.

**Comment by hexsprite** [comment]
> I have not yet learned how to implement this.

I believe it's: `npm rebuild --build-from-source`

that should rebuild all binaries from source for the current Node version.

So you'd want to track which node version was used to install the current `node_modules` directory, and then run that commands if the version changes (Major version change I guess?).

**Comment by filipenevola** [comment]
Hi @mattmccutchen thank you for your updates in the original description.

And I believe @hexsprite is right about his command to recompile dependencies.

**Comment by mattmccutchen** [comment]
A quick update: This is still on my to-do list.  I've had a succession of higher-priority things come up and I'm starting a part-time job, but I hope to get back to it if at all possible in the next week or two.  The textual merge with the latest upstream was relatively trouble-free and I can publish it here if anyone wants, but I hoped to put in some more work to understand the current Meteor build system and ensure that I'm integrating with it properly.  If it seems I won't be able to proceed with this work by myself in a timely manner, I can hand it off to someone else or post the specific questions I'm stuck on here for knowledgeable people to answer.  Thanks filipenevola for the encouragement!

**Comment by StorytellerCZ** [comment]
@matteodem are you still working on this?

**Comment by mattmccutchen** [comment]
I'm assuming that mention was intended for me.

Unfortunately, development on my project that uses Meteor is on indefinite hold.  As long as that remains the case, I think it's unlikely that I'll ever feel personally motivated to work on finishing this PR as opposed to my job and my many other hobby projects.  Also, I no longer feel that I have an adequate sense of how useful the feature would be to users in light of any changes to Meteor that may have occurred since I originally proposed the feature.  I went ahead and published [my rebased commit as of 2020-09-11](https://github.com/mattmccutchen/meteor/commit/d7db95e92355f8d2ac79f58357c3d3c0d941550d) in case it's helpful to anyone.

Regrets for not providing an explicit update sooner (although I suspect people could have guessed what happened on my side).  I'm guessing the inquiry was in preparation for closing the PR to get it off your list, so I'll go ahead and be the one to close it so that GitHub gives me permission to reopen it if need be. :slightly_smiling_face:  (I wish GitHub had a richer set of statuses to help keep currently unactionable items from being distracting rather than just this generic "closed" status, but that's another story...)

If someone else is interested in helping with the work, then that would be a sign that the community actually cares and I would be likely to get involved again.

**Pull request closed without merging**
