### PR TITLE
Feat migration guide for 2.8

### PR DESCRIPTION
**Pull request by Grubba27**
Relates to [this topic](https://github.com/meteor/meteor/pull/12057#discussion_r956599272])
Also corrected a typo in changelog

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
Would be nice to include how to go from sync methods, subscriptions, etc. to async.

**Comment by StorytellerCZ** [comment]
@Grubba27 yes!

**Comment by radekmie** [comment]
(Assuming that these functions are actually exposed via `Meteor.methods`.)

**Comment by Grubba27** [comment]
Yes they are! I Will open a pull request with these changes. 
I got these exemples from SimpleTasks from Fred. So I Will also link the commit where He made this change

**Pull request merged**
