### PR TITLE
Add braces to every if/for(-in)/while statement in tools directory.

### PR DESCRIPTION
**Pull request by benjamn**
This should help make ESLint (and, by extension, @stubailo) happier. The transformation was done automatically using https://github.com/benjamn/recast/blob/master/example/add-braces.

### CODE REVIEW

**Comment by Slava** [comment]
Oh, the dreams come true. Can we also transform all double quotes to single quotes please?

**Comment by benjamn** [comment]
Let's not merge this until after https://github.com/meteor/meteor/tree/batch-plugins lands. I'll run the script again after that.

**Comment by glasser** [comment]
Ooh what about this?

**Comment by benjamn** [comment]
Just seems like a lot of potential merge conflicts for dubious benefit ;)

**Comment by glasser** [comment]
Oh I thought you were going to re-run the script now that things have been merged/moved.

**Comment by stubailo** [comment]
@benjamn can you do this now? I don't think there are any big tool projects in flight at the moment.

**Comment by benjamn** [comment]
Finally made some time to review these changes in detail (in particular, for untestable things like comment movement), so I'd like to get this PR merged before it bit-rots again.

**Comment by stubailo** [comment]
Amazing!

**Comment by glasser** [comment]
is this enforced via eslint now?

**Comment by benjamn** [comment]
This is the rule we enforce: http://eslint.org/docs/rules/curly#multi-line

It allows braces to be omitted when the body is on the same line as the keyword/test, which seems to be something our style guide allows: https://github.com/meteor/javascript#blocks

**Comment by glasser** [comment]
oh, I'm just saying if you're going to go to the heroic effort of normalizing our style, hopefully the linter will maintain it?

**Comment by benjamn** [comment]
@jlukic https://github.com/meteor/meteor/blob/devel/scripts/admin/eslint/.eslintrc is the config file we're using. Do you mean, like, adding it to new projects?

**Comment by stubailo** [comment]
@jlukic we're also working on that for the Meteor Guide

**Pull request merged**
