### PR TITLE
Improve minimongo bitwise query operators

### PR DESCRIPTION
**Pull request by mbrobbel**
The current implementation of the bitwise query operators in the minimongo package behaves differently from these operators in mongo e.g. mongo supports numerical operands. This implementation passes all tests from mongo.
One thing I'm not sure about is the licensing on these tests taken from https://github.com/mongodb/mongo/blob/master/jstests/core/bittest.js.

### CODE REVIEW

**Comment by abernix** [comment]
Thanks for submitting a pull-request.

Your tests are failing, [as seen here](https://travis-ci.org/meteor/meteor/builds/216136885), for the `tinytest - minimongo - selector_compiler` test with the following:

```
C: tinytest - minimongo - selector_compiler : !!!!!!!!! FAIL !!!!!!!!!!!
getOperandBitmask@http://localhost:4096/packages/minimongo.js?hash=caecbb551830daa7b5afbb4c98e0c859ac69f15b:1804:23
compileElementSelector@http://localhost:4096/packages/minimongo.js?hash=caecbb551830daa7b5afbb4c98e0c859ac69f15b:1968:36
http://localhost:4096/packages/minimongo.js?hash=caecbb551830daa7b5afbb4c98e0c859ac69f15b:1535:98
forEach@http://localhost:4096/packages/underscore.js?hash=cde485f60699ff9aced3305f70189e39c665183c:157:26
operatorBranchedMatcher@http://localhost:4096/packages/minimongo.js?hash=caecbb551830daa7b5afbb4c98e0c859ac69f15b:1521:9
compileValueSelector@http://localhost:4096/packages/minimongo.js?hash=caecbb551830daa7b5afbb4c98e0c859ac69f15b:1433:35
http://localhost:4096/packages/minimongo.js?hash=caecbb551830daa7b5afbb4c98e0c859ac69f15b:1413:46
forEach@http://localhost:4096/packages/underscore.js?hash=cde485f60699ff9aced3305f70189e39c665183c:157:26
compileDocumentSelector@http://localhost:4096/packages/minimongo.js?hash=caecbb551830daa7b5afbb4c98e0c859ac69f15b:1400:9
_compileSelector@http://localhost:4096/packages/minimongo.js?hash=caecbb551830daa7b5afbb4c98e0c859ac69f15b:1375:35
Matcher@http://localhost:4096/packages/minimongo.js?hash=caecbb551830daa7b5afbb4c98e0c859ac69f15b:1311:43
matches@http://localhost:4096/packages/local-test_minimongo.js?hash=392da4415866302d6d6c536d400c95de1a60cb46:632:42
[native code]
http://localhost:4096/packages/local-test_minimongo.js?hash=392da4415866302d6d6c536d400c95de1a60cb46:2433:8
http://localhost:4096/packages/tinytest.js?hash=f231bd175ef7374affe6446703518b2abfd9d174:671:9
http://localhost:4096/packages/tinytest.js?hash=f231bd175ef7374affe6446703518b2abfd9d174:441:18
withValue@http://localhost:4096/packages/meteor.js?hash=eff337ceb83f8cb6772fd45f512b1a893e23964d:1077:21
http://localhost:4096/packages/meteor.js?hash=eff337ceb83f8cb6772fd45f512b1a893e23964d:464:54
http://localhost:4096/packages/meteor.js?hash=eff337ceb83f8cb6772fd45f512b1a893e23964d:1105:27
onGlobalMessage@http://localhost:4096/packages/meteor.js?hash=eff337ceb83f8cb6772fd45f512b1a893e23964d:401:23
```

Do you mind taking a look at this?

**Comment by mbrobbel** [comment]
Since the tests were not failing for me in my browser, I had to do some debugging to find that PhantomJS does not support some of the ES6 features I was using;
- https://github.com/ariya/phantomjs/issues/14014
- https://github.com/ariya/phantomjs/issues/14506

Since the `ecmascript` package uses the `es5-shim`, the required polyfills for the `Number` object are missing.

I could come up with the following possible solutions;
- Add `Npm.depends` for `core-js` in `minimongo` package, and require the specific `Number` methods in the test file.
- Update the `ecmascript` package to add the missing ES6 polyfills.
- Add `Number` polyfills to `ecmascript-runtime` package; https://github.com/meteor/ecmascript-runtime/issues/2.

How should I proceed?

**Comment by benjamn** [comment]
@mbrobbel Let's update `ecmascript-runtime` as described in https://github.com/meteor/ecmascript-runtime/issues/2! The point about *not* replacing the `Number` constructor is indeed important, but everything else in https://github.com/zloirock/core-js/blob/master/es6/number.js looks safe.

**Comment by mbrobbel** [comment]
@benjamn: https://github.com/meteor/ecmascript-runtime/pull/6

**Comment by benjamn** [comment]
@mbrobbel OK, you should be able to update [this line](https://github.com/meteor/meteor/blob/759671dc6c80a8385103d44c6e41c0ab84b002a5/packages/ecmascript-runtime/package.js#L10) to version 0.2.10 to get the new polyfills and make the tests pass.

**Comment by mbrobbel** [comment]
Now I'm missing Array.prototype.every() and Array.prototype.some(). 
@benjamn: should I open another pull-request for `ecmascript-runtime` to add these (and the other ES6 Array) methods?

**Comment by mbrobbel** [comment]
Oh, forgot that I was using a Typed Array.

**Comment by benjamn** [comment]
Hey @mbrobbel, the `ecmascript-runtime-client` package in Meteor 1.5 has everything you need for this PR, so if you don't mind waiting for that release (soon!), you can more easily rebase, and we can do a patch release of `minimongo` shortly after the 1.5 release.

**Comment by mbrobbel** [comment]
Hi @benjamn, 
Thanks, sounds good!

I'm using the following;

Constructors
- ```TypedArray```
- ```ArrayBuffer```

Methods
- ```Array.prototype.every()```
- ```TypedArray.prototype.every()```
- ```TypedArray.prototype.some()```

- ```Number.isInteger()```
- ```Number.isSafeInteger()```

Properties
- ```TypedArray.prototype.buffer```
- ```TypedArray.BYTES_PER_ELEMENT```

It looks like some of these are not included yet in https://github.com/meteor/meteor/blob/release-1.5/packages/ecmascript-runtime-client/runtime.js.

**Comment by benjamn** [comment]
The new polyfills add about 12kB of minified JS to the client bundle, which I think is acceptable. At some point in the future, it would be if `ecmascript-runtime-client` could adjust its bundled dependencies dynamically, based on the user agent, or some other signal, but that's obviously a topic for further research, and not in scope for this PR.

I'm going to check out this branch locally and try to rebase it to remove the merge commits so the history is a bit cleaner, but otherwise I think it's good to go!

**Comment by benjamn** [comment]
These changes have been pushed to `devel` as c2c7fab2ed59fb3087b7c6d53c643d2c184246a6. Thanks for your patience @mbrobbel!

**Pull request closed without merging**
