### PR TITLE
Removed cordova-plugin-console dependency

### PR DESCRIPTION
**Pull request by renanccastro**
As stated on [cordova-plugin-console](https://github.com/apache/cordova-plugin-console):

> This plugin is no longer being worked on as the functionality provided by this plugin is now included in cordova-ios 4.5.0 or greater, and support is already built in to cordova-windows > 5.0.0. You should remove this plugin from your applications.
> 
> Please file issues for this plugin against their respective platforms (cordova-ios, cordova-windows).
> 

Also on this issue: #9379

### CODE REVIEW

**Comment by skirunman** [comment]
@renanccastro I'm curious what happens if you manually install `cordova-plugin-console@1.1.0` in your app/.meteor/cordova-plugins and re-build your app. See #9300

This https://github.com/meteor/meteor/pull/9213/files updates our pinned dependency to `cordova-plugin-console@1.1.0` which I believe should not install the conflicting code when building with cordova-ios 4.5.0 or greater.

**Comment by renanccastro** [comment]
@skirunman 
Tried that. Spawns an error and doesn't install the plugin(cordova-plugin-console). Duplicated CDVLogger no longer occurs.

That's a workaround, but I think meteor should remove it and get rid of this warning/error.

> npm WARN deprecated cordova-plugin-console@1.1.0: This plugin has been deprecated since it is now included in the latest versions of cordova-ios
> %% Plugin doesn't support this project's cordova-ios version. cordova-ios: 4.5.1, failed version requirement: <4.5.0
> %% Skipping 'cordova-plugin-console' for ios

**Comment by skirunman** [comment]
See my comments in #9379. The warning may be a good thing for a least one release of the product so people manually remove any dependencies they may have in their own code, but I do agree that we can remove this dependency long term. 

In your PR you may also want to remove the version pinning of this plugin in `tools/cordova/project.js`, but I guess this is not a requirement.

**Comment by benjamn** [comment]
Let's ship @skirunman's version bump in Meteor 1.6.1, and then consider this PR for 1.6.2.

Closing this PR until then, though I've put it in the 1.6.2 milestone to make sure we don't forget it.

Thanks @renanccastro and @skirunman!

**Pull request closed without merging**
