### PR TITLE
[WIP] Refactoring: Update TypeScript to 4.5

### PR DESCRIPTION
**Pull request by afrokick**
The latest version of TypeScript: `4.5.4`

Updated packages:

- `@meteorjs/babel@7.16.0`
- `babel-compiler@7.9.0`
- `ecmascript@0.16.2`
- `typescript@4.5.4`

Announcing 4.4: https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/
**Breaking changes:** https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#breaking-changes

Some items from changelog:
- `static` Blocks in Classes: https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#static-blocks
- More-Compliant Indirect Calls for Imported Functions: https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#more-compliant-indirect-calls-for-imported-functions

Announcing 4.5: https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/
**Breaking changes:** https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#breaking-changes

Some items from changelog:

- Disabling Import Elision: https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#preserve-value-imports
- `type` Modifiers on Import Names: https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#type-on-import-names

TODO:

- [x] update all relevant places
- [ ] publish `@meteorjs/babel` to npm
- [ ] check tests
- [ ] merge and release

### CODE REVIEW

**Comment by afrokick** [comment]
@filipenevola @StorytellerCZ @vitorflores should we release first @meteorjs/babel to continue work on this PR?

**Comment by StorytellerCZ** [comment]
Yes, at least a beta version that can be used needs to be released.

**Comment by afrokick** [comment]
@filipenevola what i should do next?

**Comment by filipenevola** [comment]
@afrokick sorry for the delay.

We are going to catch up here.

**Comment by denihs** [comment]
@afrokick, I'm going to merge this on the branch [release-2.6.1](https://github.com/meteor/meteor/tree/release-2.6.1), and we proceed from there. 

I'll also finish your TODO list.

Thank you!

**Comment by denihs** [comment]
PR merged on [release-2.6.1](https://github.com/meteor/meteor/tree/release-2.6.1) in this [commit](https://github.com/meteor/meteor/commit/f00f7534a2daa430ee5b63eac427878bba694310) solving the conflict in the History.md file.

**Pull request closed without merging**
