### PR TITLE
packages/facebook: Request fields using Graph 2.4. Closes #4743

### LINKED ISSUE #4743: Meteor.loginWithFacebook not adding email address to user
Code for reproducing the issue:
https://github.com/KnutSv/Meteor-facebook-login-email-bug

When the user registers via Facebook the email from Facebook is not added to the user account.

```javascript
Meteor.loginWithFacebook({requestPermissions: ['email']}, function(error){
  if (error) {
    console.log(error);
  }
});
```

Possible cause is changes to Facebook API v. 2.4 where fewer fields are returned from graph.
I get the email returned if I add `&fields=email` to the graph url:
https://graph.facebook.com/v2.4/{{userID}}?access_token={{accessToken}}&fields=name,email

### PR DESCRIPTION
**Pull request by omeid**
This pull request fixes the issue with newest Facebook Graph API (2.4) requiring listing of necessary fields. Close #4743

### CODE REVIEW

**Comment by omeid** [comment]
Worth mentioning that I dropped "username" as it is deprecated and isn't provided anymore by facebook Graph.

**Comment by glasser** [comment]
Oh, wow.  This is a really strange behavior from Facebook: preventing new apps from using old but still supported APIs.  How do they expect people to write libraries?

**Comment by omeid** [comment]
Yeah, worst even is that they silently "upgrade" your calls without any warning or error; despite having an API version in the URL.

**Comment by glasser** [comment]
Thanks for the fix @omeid.  @dgreensp is going to look into putting out a release with just this change.

**Comment by omeid** [comment]
A release would be super.

**Comment by dgreensp** [comment]
It's now out in 1.1.0.3.

**Pull request closed without merging**
