### PR TITLE
don't re-minify .min.js files in standard-minifiers

### PR DESCRIPTION
**Pull request by jedwards1211**
fix https://github.com/meteor/meteor/issues/5363

### CODE REVIEW

**Comment by sebakerckhof** [comment]
Won't this still call the minifier?

**Comment by jedwards1211** [comment]
@sebakerckhof Whoops, yup! I forgot to copy over an else block from my package.

**Comment by jedwards1211** [comment]
Okay, now it matches how I was doing it in my own package.

**Comment by jedwards1211** [comment]
I investigated a little bit how I could write an automated test for this, but it didn't seem very obvious; if anything tests that `standard-minifiers` works, I didn't find it.

**Comment by sebakerckhof** [comment]
I could be mistaken, but I think it is still incorrect:
1) You'll end up with multiple JS files instead of one, but you probably still only want one http request
2) Js files will get out of order, which might cause errors
2) If the first JS file is a .min.js file, it will be overwritten with the allJS.

I think you need to add everything to the allJS variable, but only skip the minifying step for already minified files.

**Comment by jedwards1211** [comment]
@sebakerckhof ah, yes, good points, you are clearly more familiar with the build process than I am.  Let me update it

**Comment by jedwards1211** [comment]
Does everything look good now?

**Comment by stubailo** [comment]
This definitely needs a test. The tests are currently written in a super custom test framework called "self-test", here: https://github.com/meteor/meteor/blob/devel/tools/tests/standard-minification.js

If you can write the test, I'll accept this immediately - otherwise it will have to wait until someone writes the test.

**Comment by jedwards1211** [comment]
Okay.  Is there any way to avoid this kind of thing?
```
    run.waitSecs(60);
```
I would have thought that `run.match('Client modified -- refreshing');` waits until that gets printed to the console and the wait times are unnecessary.  No?

**Comment by stubailo** [comment]
@jedwards1211 that doesn't actually wait 60 seconds, it actually just extends the timeout of the next command since `run.match` has a built-in timeout.

I'll admit it's pretty confusingly named.

**Comment by jedwards1211** [comment]
Ahhhh, very good.  If there are any guides to self-test anywhere or if you have tips on where I can find the self-test API in the code, please let me know.

**Comment by jedwards1211** [comment]
I just realized: you can use the `.es5.js` extension to work around the hanging on large bundles issue, but then you can't use `.min.js`.  What we are creating here is **convention without configuration**.

If we really want to serve devs best, we should also make a way to turn these things on and off for any arbitrary files individually.  ESLint knows this; they let you use comments like
```js
/* eslint-disable no-console */
console.log('freedom!');
/* eslint-enable no-console */
```

We could adopt the same approach here, scanning each file for a comment:
```js
/* meteor-disable standard-minifiers */
```

**Comment by stubailo** [comment]
I see what you are saying! It would be reasonable to have a file that shouldn't be compiled or minified. In this particular case, I can't think of any reason you would want a minified file to be compiled?

**Comment by jedwards1211** [comment]
That's a good point.  So maybe a second PR to disable compilation of .min.js files?

**Comment by stubailo** [comment]
Yeah for now that could be a good workaround.

**Comment by benjamn** [comment]
Thanks for this PR, and sorry we never got around to merging it. We are currently cleaning up the repository and removing old PRs; if you think this PR still has value and are interested in resurrecting it, we encourage you to re-submit it against current `devel`.

**Pull request closed without merging**
