### PR TITLE
Revised implementation of DDP resumption

### PR DESCRIPTION
**Pull request by vlasky**
Changes to DDP resumption code in response to reviewer comments on znewsham's PR https://github.com/meteor/meteor/pull/11559/ 

- Constant MAX_QUEUE_LENGTH has been replaced with option maxMessageQueueLength
- Constant DISCONNECT_GRACE_PERIOD has been replaced with option disconnectGracePeriod
- Use of _.each() replaced with Array forEach()
- isPingPong replaced with descriptive name ignoredMsgsForSessionOutOfDateCheck

### CODE REVIEW

**Comment by denihs** [comment]
Hi @vlasky, this PR has tests failing. Could you address those?

Also, would you be able to add one test or two for your new code?

**Comment by denihs** [comment]
Hi, we still have tests that are failing, and those tests seem to be related to the changes.

So I'm closing this PR until someone fixes the tests.

**Comment by vlasky** [comment]
I have merged the fixes made by @StorytellerCZ. Can this PR be reopened or should I create a new one?

**Comment by StorytellerCZ** [comment]
I'm going to push the re-open button and see if it picks up the new changes and runs the tests.

**Comment by denihs** [comment]
Tests are still failing. I'm rerunning them, but based on the error messages, it still seems to be related to the changes.

**Comment by StorytellerCZ** [comment]
For CircleCI, it is the clean-up, so while not ideal, I don't think that is related. Looks like there is one failure in DDP limiter, I'll take a look on that one.

**Comment by StorytellerCZ** [comment]
The error is annoying. Nothing obvious is coming up right now that would explain it, but I'm working on it.

**Comment by vlasky** [comment]
Hiya @StorytellerCZ, what needs to be addressed to allow this to be merged?

**Comment by Grubba27** [comment]
hello there! @vlasky, the changes we made in 2.8 probably will make this Travis CI pass now.

**Comment by StorytellerCZ** [comment]
@vlasky, can you merge in the `release-2.7.4` branch into yours? I have already changed the target branch.

**Comment by vlasky** [comment]
@StorytellerCZ unfortunately Travis CI failed again :-(

**Comment by vlasky** [comment]
@StorytellerCZ I have merged release-2.8.1 into my ddp-resumption branch.

**Comment by StorytellerCZ** [comment]
@vlasky thank you! I'm trying to figure out why the Travis tests are failing.

**Comment by vlasky** [comment]
@StorytellerCZ I have merged release-2.9.1 into my ddp-resumption branch.

**Comment by StorytellerCZ** [comment]
Hi @vlasky, I think I will make another PR from my own branch here in the Meteor repo, so that it is easier for us to access.

**Comment by vlasky** [comment]
> Hi @vlasky, I think I will make another PR from my own branch here in the Meteor repo, so that it is easier for us to access.

Yes thanks anything that will help get this deployed sooner!

**Comment by StorytellerCZ** [comment]
Superseded by #12436

**Pull request closed without merging**
