### PR TITLE
add modifier $position to $push in minimongo

### PR DESCRIPTION
**Pull request by dferber90**
Issue meteor/meteor#4158.

Adds the `$position` modifier to `$push` in minimongo. Also adds tests.

Behavior of `$push` with multiple modifiers is documented [here](http://docs.mongodb.org/manual/reference/operator/update/push/#modifiers) as
> 1. Update array to add elements in the correct position.
> 2. Apply sort, if specified.
> 3. Slice the array, if specified.
> 4. Store the array.

**Details:**
As described in the last paragraph [here](http://docs.mongodb.org/manual/reference/operator/update/position/#up._S_position), if value of `$position` exceeds the size of the array to be modified, then the operation is the same as not using the `$position` at all.
The minimongo code I added still runs through the [`$position` code path](https://github.com/meteor/meteor/blob/d383e479b3ea5354583e7c194f80a2e6c96a59de/packages/minimongo/modify.js#L279-L282) in that case. To short-circuit, you could add `if (position < target[index].length) position = arg.$position` [here](https://github.com/meteor/meteor/blob/d383e479b3ea5354583e7c194f80a2e6c96a59de/packages/minimongo/modify.js#L242), which would result in running through the [regular code path](https://github.com/meteor/meteor/blob/d383e479b3ea5354583e7c194f80a2e6c96a59de/packages/minimongo/modify.js#L276-L277). I am not sure which behavior is desired, but it should not matter anyways.

### CODE REVIEW

**Comment by benjamn** [comment]
Looks great, thanks @dferber90!

**Comment by Slava** [comment]
But does it work when the position is `-1`? I don't remember all the details, but it used to have a special behavior like "prepend"

**Comment by benjamn** [comment]
The code currently throws if `$position < 0`.

**Comment by Slava** [comment]
Oh, I think I confused it with `{$push: { "-1": "a" }}` type of update. NVM.

**Comment by glasser** [comment]
@benjamn This new feature should be mentioned in History.md.

**Pull request merged**
