### PR TITLE
Release 1.8.4

### PR DESCRIPTION
**Pull request by filipenevola**
https://github.com/meteor/meteor/milestone/67

Versions to bump:
- [x] mobile-status-bar
- [x] launch-screen
- [x] mobile-experience
- [x] cordova-plugin-meteor-webapp

### CODE REVIEW

**Comment by rj-david** [comment]
@filipenevola, since 1.9 is in RC, does this mean we need to wait for at least 1.9.1 if we need both cordova 9 and node 12?

**Comment by filipenevola** [comment]
@rj-david, both are going to be released soon, we are not going to have weeks between them then we are going to rename the versions accordingly before releasing.

this Cordova work is going to have a beta version soon also.

**Comment by rj-david** [comment]
Great to know, @filipenevola. Love to join the test once it is available for 1.9 since we started moving to Node 12. Congrats for making this happen 👍

**Comment by benjamn** [comment]
@filipenevola Just wanted to flag that I updated the target branch from `devel` to `master`, so that this PR will show all the changes since the last release, not just the changes since the latest `devel` revision. There was also an older [Release 1.8.4 PR](https://github.com/meteor/meteor/pull/10826), but I don't see much value in reopening that, since those changes went out in Meteor 1.8.3.

**Comment by benjamn** [comment]
Oh also—can we try to review/merge some more of the TypeScript PRs in the 1.8.4 milestone?

**Comment by benjamn** [comment]
I've recreated this PR with just the Cordova 9 changes over at #10857. Please let me know if there's anything else in this PR that isn't already on `devel` that you'd like to see preserved, since it's likely we will continue working on Meteor 1.9.x or 1.10, rather than releasing 1.8.4.

**Comment by filipenevola** [comment]
Closed in favor of https://github.com/meteor/meteor/pull/10857

We will also start to use `devel` as the WIP release branch then we don't need a branch for Meteor 1.10

**Pull request closed without merging**
