### PR TITLE
Fix #10815 - add email when user hasn't any email

### LINKED ISSUE #10815: accounts-password@1.5.2: Accounts.addEmail fails if user has no emails
Since underscore was removed Accounts.addEmail fails on users without emails:
```
const didUpdateOwnEmail = user.emails.reduce(
    (prev, email) => {
...
```
due calling reduce on undefined.
Regards

### PR DESCRIPTION
**Pull request by afrokick**
- fix the issue
- add a test
- bump version of accounts-password

### CODE REVIEW

**Comment by afrokick** [comment]
@filipenevola I think we should release it ASAP

**Comment by afrokick** [comment]
@filipenevola @benjamn  Do I need to increase `accounts-password` version?

**Comment by filipenevola** [comment]
Hi @afrokick thank you for this, yes, please bump the package version.

**Comment by filipenevola** [comment]
Thanks @afrokick 

Published accounts-password@1.5.3.

**Pull request merged**
