### PR TITLE
Use true mongo binary types

### PR DESCRIPTION
**Pull request by znewsham**
When implementing manual field level encryption with mongo, the decryption function expects a Binary data type with a `sub_type` of 6. Because meteor converts `Binary` to `Uint8Array` (and vice versa) we lose that. It isn't even possible to pass in a `Binary` - because mongo returns undefined.

This PR simple says to maintain the `Binary` type in most situations. The only situation it does not is when the `sub_type` is `0`. It does this for backwards compatibility (e.g., `sub_type` 0 is still returned as a `Uint8Array`)

### CODE REVIEW

**Comment by radekmie** [comment]
The code looks fine, but it definitely needs tests - both for the backward-compatible part as well as the new functionality.

**Comment by znewsham** [comment]
@radekmie tests added - I wrongly assumed the backwards compatible piece would already have been covered by tests, from what I can tell the atom converter isn't directly covered by tests at all, it wasn't obvious where to put the tests so I put them in `collection_tests.js`

**Comment by znewsham** [comment]
Separately, can you point me to where the test results are? I see the checks CI does, but I can't tell in which of the ~15 checks actually run these tests, and I can't see the test result anywhere (the Development.md seems out of date too, pointing to a script that doesn't exist)

**Comment by Grubba27** [comment]
To check the result, you can do ``./meteor test-packages mongo`` and it will create a tab in http://localhost:3000/ running those tests

**Comment by znewsham** [comment]
I've ran them locally - I want to see the results in CI (in particular to see if the change breaks anything else) - I assume circle CI jobs are where to look at this

**Review by radekmie — APPROVED** [review]

**Pull request merged**
