### PR TITLE
Use es5-sham to polyfill Object.create and other built-ins for IE8.

### LINKED ISSUE #4574: Object.create breaks IE8 in accounts-base
https://github.com/meteor/meteor/blob/ccab6ca621e35cd65657c13ce0705de0645ded6a/packages/accounts-base/accounts_common.js#L211

### PR DESCRIPTION
**Pull request by benjamn**
Fixes #4574.

### CODE REVIEW

**Comment by benjamn** [comment]
@glasser @dgreensp @zhenyasav Is this overkill?

**Comment by dgreensp** [comment]
This looks like a case for `Meteor.makeErrorType`: https://github.com/meteor/meteor/blob/b687e10dfe5a8b373e4fa69a77a98c096ad46dfe/packages/meteor/errors.js#L5

I think `Meteor.makeErrorType` should reflect whatever we think the best way to make an error subclass is.  The current implementation has been called into question a bit because setting `__proto__` generates a warning in Firefox, so any improvements to that would be welcome.

We plan to have an `es5-shim` core package that you can add if you want React to work in IE 8 (which will include `Object.create` and `Object.freeze`).  In the future, we could change the overall policy about Meteor code to "works in IE 9, and IE 8 if you add es5-shim."  At the moment, core packages have to work in IE 8 without polyfills.

**Comment by benjamn** [comment]
Closing in favor of https://github.com/meteor/meteor/commit/f02f10e846b6f412ea4b475698df970c02fc4ab2, since I'm persuaded this approach was overkill.

Note that subclassing `Error` is possible without setting `__proto__`, and in general the tricky thing about shamming `Object.create` is making `Object.create(null)` work, which is not something we need here!

**Comment by dgreensp** [comment]
Agreed.  And (following the commits), +1 for `Meteor._inherits`!  And once we have classes, there will be less of that!

For subclassing errors, getting an object that is `instanceof Error` is the easy part.  The part that is potentially highly browser-dependent is making sure your objects gets a proper `.stack` and is treated like an Error by the browser's developer tools.  Someone thought at some point that it was important in Firefox to call `new Error` and then mutate the proto, but I'm not sure if that's necessary or not.  There's a discussion of different approaches in this SO thread, but few clear conclusions: http://stackoverflow.com/questions/1382107/whats-a-good-way-to-extend-error-in-javascript

**Pull request closed without merging**
