### PR TITLE
Support for Facebook login from mobile

### PR DESCRIPTION
**Pull request by jasper-lu**
I'm working on adding loginWithOAuth support to the [android](https://github.com/kenyee/android-ddp-client) and [iOS](https://github.com/boundsj/ObjectiveDDP) DDP clients.

I've figured out how to get the pending credentials, etc, set up before login, but the last problem to opening oAuth login for mobile is that mobile oAuth clients (I've only checked Facebook so far, but it looks similar with the other implementations of the oAuth request handlers) send long-term accessTokens instead of short ones.

This pull will add a check for a query.accessToken parameter, and if there is one, skip requesting a new accessToken in favor of requesting the expiration info for the token instead.

### CODE REVIEW

**Comment by glasser** [comment]
Thanks for the feature request! You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

Since this is security-related, we definitely need to be careful about reviewing this to make sure that this additional way to log in does not create any vulnerabilities.

Do you have documentation from Facebook that we can read that makes it clear that one can trust accessTokens received from untrusted clients?

Also, there should at the very least be a comment above the `query.accessToken` check making it clear that despite no matching client code, this is part of our (undocumented) interface to arbitrary DDP clients.  (Ideally, there'd be a test too!)

**Comment by jasper-lu** [comment]
@glasser 

Thanks for the response.

Looking through the [access token documentation](https://developers.facebook.com/docs/facebook-login/access-tokens) on Facebook while trying to implement DDP OAuth login, I ran across this line:

Mobile apps that use Facebook's mobile SDKs get long-lived tokens.

However, the current oauth implementation for Facebook in Meteor only accepts short-lived tokens. For future DDP support, I think it's important for meteor to be able to support loginWithOAuth from mobile. I'm not sure if this is the same case for other OAuth login services such as Google/GitHub, but I know for my uses, this change solved the issue for me.

I added some more security checks to my code (checking the AppID of the access token against the appID registered with the server) and added more comments as per your requests.

I'm not too sure how to write a test for this, though.

My android ddp oauth login code can be found at line 365 [here](https://github.com/jasper-lu/android-ddp-client/blob/master/src/com/keysolutions/ddpclient/android/DDPStateSingleton.java).

**Comment by glasser** [comment]
Yeah, I just don't get from the Facebook site "here's how to validate an access token". Maybe the answer is that it doesn't matter and they should always be trusted?  I don't see a reference to the `/app` that you used either.

**Comment by jasper-lu** [comment]
Ah, I'm sorry. It looks like the facebook api is very poorly documented, but I found my answer on stackOverflow [here](http://stackoverflow.com/a/8730549/1608145). After testing it on graph api explorer, I was able to get it to work on my server as well by verifying it in this way.

I think Facebook is pretty much assuming the access token is trusted, since they provide no method to request a short-lived token to exchange.

I also took a lot at other popular mobile sdks Google and Twitter and it seems like they provide methods for logging in that are in line with your handlers.

**Comment by tmeasday** [comment]
Thanks for this PR, sorry we never got around to merging it. We are currently cleaning up the repository and removing old PRs; if you think this PR still has value and are interested in resurrecting it, we encourage you to re-submit it against current `devel`.

**Comment by jasper-lu** [comment]
@tmeasday Hey! Have you ever actually made a fix to this on your end? I think that this still has value, since it would allow meteor to be used server side for more mobile apps. However, I have not used meteor in a while and would need to do some testing on this first, which I would be happy to do.

**Comment by tmeasday** [comment]
Hey @jasper-lu. 

I was basically just auto-closing a bunch of old PRs as we had an overwhelming number of them, a lot of which were out of date, and it was hard to tell which were which.

If you'd still like to get it merged, perhaps you could start by opening an issue describing the feature that this implements, and we could discuss whether it's a good idea or not. It's not totally clear to me what this PR does I guess.

**Pull request closed without merging**
