### PR TITLE
Release 1.4.2.2 (and 1.4.2.3)

### PR DESCRIPTION
**Pull request by benjamn**
Minor follow-up release to Meteor 1.4.2.1.

In addition to what's currently on `devel`, here are the issues I'm hoping to address with this release:

Detection of newly added files:
  - [x] https://forums.meteor.com/t/meteor-not-detecting-new-files/31151
  - [x] https://github.com/Akryum/meteor-vue-component/issues/80
  - [x] https://github.com/meteor/meteor/pull/7975#issuecomment-259263650
  - [x] https://github.com/meteor/meteor/issues/8008
  - [x] https://github.com/meteor/meteor/issues/7978#issuecomment-259600435

Reify-related issues (possibly to be postponed to 1.4.3):
  - [ ] https://github.com/meteor/meteor/issues/8021
  - [ ] https://github.com/meteor/meteor/issues/7662
  - [ ] https://github.com/meteor/meteor/pull/8030

### CODE REVIEW

**Comment by pozylon** [comment]
Very happy to see you guys adding new features to the accounts system and minimongo.

**Comment by laosb** [comment]
@benjamn Is it OK to add a compatibility breaking change (`accounts-facebook` splitting)in a patch version?

**Comment by benjamn** [comment]
@laosb You might be right… how much do those changes break backwards compatibility? We could always release those packages separately, later.

**Comment by laosb** [comment]
Basically if users update, they need to add one more package to get config UI.

**Comment by benjamn** [comment]
@laosb After thinking about it over the weekend, I've decided to remove the `accounts-facebook` reorganization changes from this release, so that the 1.4.2.2 will be smoother. We should still release new versions of those packages immediately after releasing 1.4.2.2.

**Comment by benjamn** [comment]
Please run `meteor update --release 1.4.2.2-rc.1` and test any functionality that's important to you. I'd like to do the final release today or tomorrow. Also please let me know about any changes that I missed that can't wait for the next release.

**Comment by abernix** [comment]
I likely won't have a chance to test this tonight (your today).

I'm not aware of any other issues which cannot wait for the next release.  The only other 'trending' issue that I've seen in the last couple weeks is that Uglify's lack of harmony features (on the published branch) seems to be rearing its head more and more (#8020, #7994, #5517).  I also haven't had an opportunity to verify that those would be fixed with the [`harmony`](https://github.com/mishoo/UglifyJS2/tree/harmony) branch though so maybe that would be a better fit for 1.4.3 (reify, babel, etc.).

**Comment by benjamn** [comment]
Yeah, last I checked the `harmony` branch of UglifyJS was not ready for production, and was not a smooth upgrade. Crazy that they've survived this long without catching up to the times.

**Comment by abernix** [comment]
@benjamn I'd suggest merging #8045 as well.  It implements code-style improvements to the new "skel"  introduced with #7807 (which is surfacing for the first time in 1.4.2.2 thanks to 0466fdd37f757efea0e70a970b4ad5f2071d9d00 above).  It'd be nice to just use the "improved" version.

**Comment by benjamn** [comment]
After taking a closer look at https://github.com/meteor/meteor/pull/8045, even though Meteor 1.4.2.2 is already final (but not yet "recommended"), I think it's worth immediately publishing a 1.4.2.3 release with those changes. Lots of folks are going to encounter those skeleton files before they know anything else about Meteor, so it seems really important to use good style and code structure.

**Comment by abernix** [comment]
Good call on the move for 1.4.2.3.  Also, if it's any assurance, I saw no issues with Meteor 1.4.2.2-rc.1 in my tests on my own apps.

**Comment by QHose** [comment]
Hi Ben,

I used your suggested beta for the file not change issue. It works better. But I noticed meteor does not recognize small changes consistently. E.g. When I make a A HREF with too much quotes. I save, then meteor shows the error. I remove the extra quote but it does not update.

```<a href="{{URL_Youtube_concept_behind}}""  target="_blank">explained in this video</a>```

to

```<a href="{{URL_Youtube_concept_behind}}"  target="_blank">explained in this video</a>```

I saw the same thing yesterday when I had too much blaze }}}. 

{{template}}}

to

{{template}}

**Comment by QHose** [comment]
mmm, could it be I press save too soon... and meteor is not yet checking my files?

**Pull request merged**
