### PR TITLE
Release 2.15.0

### PR DESCRIPTION
**Pull request by Grubba27**
Bumps embed MongoDB to 7.0.5 

To test it, you can currently run the following:

```bash

meteor update --release 2.15

```

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
Now that we are doing 2.15, can we maybe add few more things?

**Comment by StorytellerCZ** [comment]
Could we add this one as well, to reduce some dependencies security warnings:
https://github.com/meteor/meteor/pull/12912

And these types updates:
https://github.com/meteor/meteor/pull/12922
https://github.com/meteor/meteor/pull/12919

And another one for Cordova:
https://github.com/meteor/meteor/pull/12971

With the exception of the first one I think they are pretty small enough not to add too much else to this release.

**Comment by denihs** [comment]
Those look fine. I've merged them. Thanks for the suggestions! We're closing this release here.

**Comment by StorytellerCZ** [comment]
Please make sure to release as `2.15` so that we can follow previous version numbering pattern.

**Comment by rj-david** [comment]
Tested without issue. We are releasing this to production and will also start moving to MongoDB 7

**Pull request merged**
