### PR TITLE
Add the option to keep token when log out.

### PR DESCRIPTION
**Pull request by GabinH**

### CODE REVIEW

**Comment by GabinH** [comment]
Hello @StorytellerCZ, need help with this PR (about #11055 ).

Do you see what i would like to do ? How can i improve this code ?

**Comment by sebakerckhof** [comment]
Hi Gabin,

Could you explain the use case a bit? We're trying to keep the amount of options in the Meteor core limited to stuff that is generally useful and I fail to see the use case here.
Also, this has the potential to keep piling up stamped tokens, which may badly influence application performance when not careful.

**Comment by GabinH** [comment]
Hi @sebakerckhof ,

Of course ! Here is my problem : 
I would like to open a connection for people with no account during x days.

Now, I use `Accounts._generateStampedLoginToken` and `Accounts._insertLoginToken ` to create the connection with a special account and I send an URL with the auth token to this people.

Next, when they click on this URL, they can log in with `Accounts.loginWithToken`.

But, when they log out, the token is destroy in my database, so they can't use the URL again.

I am looking for a way to keep the auth token alive even after log out.

**Comment by StorytellerCZ** [comment]
@GabinH I'll take a look
@sebakerckhof The PR references to this issue: https://github.com/meteor/meteor/issues/11028

**Comment by GabinH** [comment]
@StorytellerCZ I understand, but I can't create new token each time.

 In my case, there are users (with accounts) that can send an URL to people (without account). This URL allows external people to connect to a special user account thanks to a token associated to the URL. 
If when they log out I create a new token, the URL will not work again.

**Comment by sebakerckhof** [comment]
@GabinH Another way to approach this is by using a different token instead of the Meteor's resume token. For the sake of the example let's call it a 'PermanentToken'

Meteor's user data model foresees the possibility to have multiple authentication services per user. Resume token is one, then there's potentially a password, oauth services etc.
You could generate and store a PermantentToken on the user (preferably in the services property) and add your own PermanentToken login handler via `Accounts.registerLoginHandler` on the server. The login handler would be called from the client via `Accounts.callLoginMethod` and it would then verify the PermantentToken.

**Comment by filipenevola** [comment]
I'm closing old PRs with problems like tests failing or conflicts. If you are interested in continuing this work please mention me here.

**Pull request closed without merging**
