### PR TITLE
Do not fail if meteor tool is not run from a git clone

### PR DESCRIPTION
**Pull request by mitar**
Pull request for #5144.

### CODE REVIEW

**Comment by stubailo** [comment]
Looks great, thanks!

**Comment by stubailo** [comment]
Merged: 5a36f344e8fdc9f9703e549b3728bba540f095d4

**Comment by timhaines** [comment]
@mitar Thanks, we're getting snagged on this too.  Going to cherry pick it.

**Comment by timhaines** [comment]
Actually @stubailo - it looks like the effect of this was negated by this later commit by @yyx990803: https://github.com/meteor/meteor/commit/452c839d94a053749712cf14e4cdb8ddfb47f25e

**Pull request closed without merging**
