### PR TITLE
Allow anonymous child subscriptions.

### PR DESCRIPTION
**Pull request by tmeasday**
Adds a new method `publishChild`, which establishes a new subscription “context”, which:
 - has its own readiness
 - can be stopped independently
 - can publish the same documents (i.e. is treated independently by the merge box).

This allows joins to be published relatively easily.

Notes:

1. The rationale for this functionality is discussed here: https://github.com/tmeasday/joins-experiments/tree/master/packages/publish-joins#publish-joins

2. This PR is incomplete, some more things are needed, but I'm looking for feedback at this point.

   Some things that are needed:
     - [ ] A better name than `publishChild`?
     - [ ] There are *a bunch* more tests that are needed, see https://github.com/tmeasday/joins-experiments/blob/master/packages/publish-joins/subscription-tree-tests.js for some more examples).
     - [ ] Perhaps child subscriptions should have an`_subscriptionId` like `"parentId.0.1.2"` (ala react ids).
     - [ ] audit-arguments-checks should be skipped

3. As a reference, some code that works with this branch is here: 
 - forEach implementation (referenced in readme above): https://github.com/tmeasday/joins-experiments/blob/patched-meteor/packages/publish-joins/subscription-tree.js

  - publish-joins implentation: https://github.com/tmeasday/joins-experiments/blob/patched-meteor/packages/publish-joins/publish-joins.js

  - usage: https://github.com/tmeasday/joins-experiments/blob/patched-meteor/server/publications.js

### CODE REVIEW

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

I think this is pretty interesting — it's relatively minimal and seems like it enables a lot of non-core join experimenting.  I'm not sure when we'll have time to evaluate it, though.

Is it completely impossible to do this outside of core?  It seems like you could do something like:

```js
Meteor.publish("x", function () {
  var nested = new NestedPublish;
  nested.publish(...);
  nested.publish(...);
});
```

And it could be the job of nested to figure out when it's time to call ready, to remove things when sub-subscriptions are stopped, etc.

On the other hand, it sounds like this would basically just lead to a reimplementation of the merge box inside NestedPublish.  But it does seem like a start, for until core gets a chance to work on this sort of thing.

(My personal opinion these days, which isn't necessarily shared by everyone on the team, is that eventually DDP should be reworked to drop the server-side merge box and explicitly tag data messages with their subscription.  We'll see if that's the right direction...)

**Comment by tmeasday** [comment]
Hey, thanks for taking a look @glasser.

I considered that, but I wanted to avoid re-implementing the merge box manually for two reasons:

  1. I guess it seems kind of crazy to have *another* level of caching in the stack ;)
  2. I'd rather trust your merge box implementation over my own. 

It seems like this stuff is pretty important for performance reasons so I think for a variety of technical and political reasons it would be best if it's part of core.

---

A compromise between the two approaches is for a package to subclass subscription (here's my initial implementation of that: https://github.com/tmeasday/joins-experiments/blob/master/packages/publish-joins/subscription-tree.js). 

Apart from the fact that it's difficult to get access to the `Subscription` prototype, I'd prefer to see it in core because again, I'd be worried that I do something incorrect to the subscription and blow up my (or others') apps. But I'd be open to maintaining such a package as a first step toward getting something in core.

(In general I think I'm +1 for a client-side merge box, but I would have concerns about how to achieve joins anywhere near efficiently without some kind of server-side MB, or a lot of added complexity [e.g. imagine a posts -> comments -> user join])

**Comment by tmeasday** [comment]
@glasser if I did create such a package would someone at MDG be open to doing a review of it to ensure I'm not doing anything crazy in my subscription subclass?

**Comment by glasser** [comment]
Sounds like the sort of thing I'd enjoy doing, which isn't the same thing as saying that it fits in high on the priority list.

**Comment by tmeasday** [comment]
Oh well, here goes: https://github.com/tmeasday/nested-subscriptions

**Comment by mitar** [comment]
Related, I am having something similar in https://github.com/peerlibrary/meteor-reactive-publish

**Pull request closed without merging**
