### PR TITLE
Don't reminify *.min.js

### PR DESCRIPTION
**Pull request by laosb**
#5378 Old PR
#5363 Issue

Resubmitted but I'm not ready with writing tests. Personally think that shouldn't have any problems. Pinging the member dealing with the old PR @stubailo

### CODE REVIEW

**Comment by laosb** [comment]
Personally think .min.css shouldn't be reminified too.

**Comment by benjamn** [comment]
This looks safe and beneficial to me.

**Comment by benjamn** [comment]
Feel free to submit another PR for `.min.css` :)

**Comment by laosb** [comment]
Should this be mentioned in History.md and docs? There might be some cases that people use .min.js for other reasons but still want be minified.

**Comment by stubailo** [comment]
Definitely should be in the docs regardless!

**Comment by mitar** [comment]
Yes, please add tests and docs as well, no?

**Comment by laosb** [comment]
@mitar Learning how to write tests! Is there any document about it? When comes to docs, should I simply add it to the old Meteor-based docs or to the hexo-based docs in the PR?

**Comment by mitar** [comment]
Just check how other tests are done and add to them. But I see that this package does not have them. So maybe then it is on MDG to write first ones. I do not know how to write tests for tooling.

**Comment by mitar** [comment]
For documentation, yes, that is in flux currently.

**Comment by tmeasday** [comment]
> I do not know how to write tests for tooling.

You can use `selftest` for this. I don't think it's well documented. We should fix that!

**Pull request merged**
