### PR TITLE
Provide a way to post-process emails options

### PR DESCRIPTION
**Pull request by mitar**
Alternative to #8038.

Maybe it is simpler to provide a way to code wrap a function and provide any post-processing of options it wants. It is not the best API design, but it is working well in practice to augment things with very custom things.

### CODE REVIEW

**Comment by abernix** [comment]
So the instruction to developers would be:  If you want to do more advanced stuff don't call `Accounts.sendResetPasswordEmail`, but call `Accounts._sendResetPasswordEmail` instead?

#8038 seems like a much preferable implementation.

**Comment by mitar** [comment]
I was more thinking of: monkey-patch `Accounts._sendResetPasswordEmail` to do anything you want before or after, before it is send to `Email.send`.

Yes, but `#8038` does not really allow all things wrapping allows. It allows only modifying headers. This one for example allows one to generate an extra (tracking) token and add it to both headers and e-mail content. The issue is that without this, it is hard to correlate call to header function and text/email template to be able to inject the same token into both.

**Comment by abernix** [comment]
Can we either go with #8038 or send this back to the drawing table (in an issue) to design a better plan to address the concerns?

I mean, I guess we can wait and see what MDG thinks, but I don't think making it easier to monkey-patch (and suggesting that) would be an official solution.  If anything, it seems like it'd be more reasonable to recommend developers to fork `accounts-password` and just change it as they wish.

Opening internals or recommending playing with internals just hasn't been highly-desirable methodology from past (and recent) PRs.

**Comment by mitar** [comment]
OK, #8038 should probably go in anyway.

What about `Accounts.emailTemplates.preprocess` callback function which you can set and it will be called with `user, options, type` and expect `options` to be returned before send is called?

**Comment by mitar** [comment]
I made #8065 instead.

**Pull request closed without merging**
