### PR TITLE
Provide notInclude in Tinytest

### PR DESCRIPTION
**Pull request by mitar**
Matches how `equal` and `notEqual` are done.

### CODE REVIEW

**Comment by glasser** [comment]
This seems useful but I suspect we should also allow for a message like in `equal`/`notEqual` instead of using the third argument for something else.  Can you add that?

**Comment by mitar** [comment]
Done.

**Comment by stubailo** [comment]
Merged: 5a0a0bc06126dc1e8ec3fad549c041539db61325 and 1100dec36cc1bab4e6389805e21869aee0ff8c8a

**Comment by mitar** [comment]
Should Tintytest package version be bumped now? So that we can depend on this (new) version in https://github.com/peerlibrary/meteor-classy-test?

**Comment by stubailo** [comment]
For core packages we only bump the versions for a new release - I think 1.0.4 will be soon so you can update your dependency what that comes out.

**Comment by glasser** [comment]
Yeah, relying on the version numbers on devel to change before a release ends up leading to problems unfortunately.

**Comment by mitar** [comment]
Ah, no. I was not thinking of updating before the release. I just wanted to remind you that you have to update when you release. It seems you go over all packages just before the release, not when you commit any changes.

**Comment by glasser** [comment]
This broke tests.  Investigating.

**Comment by mitar** [comment]
Oh, sorry. :-(

**Comment by mitar** [comment]
I can do that.

**Comment by glasser** [comment]
Fixed.  I guess neither @mitar nor @stubailo nor I thought to run tests while reviewing this! Oops.

**Comment by mitar** [comment]
We should have Travis CI tests. :-)

**Comment by glasser** [comment]
We do have a jenkins buildbot, which caught this.

**Comment by mitar** [comment]
But it does not add the GitHub pull request status flag. :-(

**Comment by stubailo** [comment]
Ohh - that's a good idea.

**Comment by mitar** [comment]
I opened a ticket about this some time ago: #3260

**Comment by mitar** [comment]
(And no, I didn't not sneak in this bug just to make the point. ;-) )

**Comment by mitar** [comment]
I felt bad about the bug and wanted to make a test for this for the future, but I discovered that there are not tests for Tinytest. :-) So it seems we will have just to use all methods from Tinytest in other tests and catch bugs this way. :-)

**Pull request closed without merging**
