### PR TITLE
doc: add Async methods

### PR DESCRIPTION
**Pull request by fvckDesa**
This PR resolve issue #12649

/claim #12649

### CODE REVIEW

**Comment by Grubba27** [comment]
Have you tested your solution? 

Running locally I was not able to start the website.

Screenshot 2023-08-25 at 09 11 15

**Comment by fvckDesa** [comment]
I test locally, jsdoc don't find the type declaration because the async methods not have the jsdoc comments
https://github.com/meteor/meteor/blob/527f0ffb6e050d7ed28721df31d1b1dcf2aa5ea7/packages/mongo/collection.js#L998-L1010

I can add them like this:
```js
/**
* @method findOneAsync
*/
/**
* @method createIndexAsync
*/
 ASYNC_COLLECTION_METHODS.forEach(methodName => {})
```
or removing this loop
```js
 ASYNC_COLLECTION_METHODS.forEach(methodName => {})
```

and add one by one the method with the jsdoc comment

**Comment by Grubba27** [comment]
@fvckDesa  what you think is the better approach?

**Comment by fvckDesa** [comment]
For me is better create a promisify utility function and add one by one the methods like the sync ones. So, if you want do a change in only one async method, you can do it and if you want do a common change on all async methods, you do it in the utility function

**Comment by Grubba27** [comment]
I got to run it locally, and I like how it looks in the website. I would only change the code for what you sent earlier on:

> and add one by one the method with the jsdoc comment.
Another alternative is add the comments in the constant file where ASYNC_COLLECTION_METHODS is defined like this:

I think would look better for developers maintaining our code.

**Comment by fvckDesa** [comment]
@Grubba27 like this?
```javascript
export const ASYNC_COLLECTION_METHODS = [
/**
* @method findOneAsync
*/
  'findOne',
/**
* @method insertAsync
*/
  'insert'
];
```

**Comment by Grubba27** [comment]
Nice @fvckDesa thanks for your contribution. Hope to see you soon here :)
Sorry for the delay in the feedback loop, but well done!

**Pull request merged**
