### PR TITLE
HTTP package: deprecate the package

### PR DESCRIPTION
**Pull request by StorytellerCZ**
Added debug warnings to the the http calls warning about the package's deprecation. Logging update [PR](https://github.com/meteor/meteor/pull/11068) should be probably merged before this. Fetch package also needs a proper documentation going forward.

See #10913 for more background.

### CODE REVIEW

**Comment by jankapunkt** [comment]
Would it make sense to use `fetch` under the hood? I included the http package mainly because it is a nice bridge between http calls and the calling environment. If the `http` would keep it's structure to the outside world but change it's internals to use `fetch` we would not have to change all the packages, that depend on `http` (including, among others, the accounts-<service> packages)

**Comment by jankapunkt** [comment]
@StorytellerCZ what would be the correct replacement for `HTTP` on the server?

**Review by filipenevola — APPROVED** [review]
Should we move to the deprecated folder as well?

**Comment by StorytellerCZ** [comment]
@jankapunkt That would be the fetch package (though on server you should be able to use fetch even without the package).
@filipenevola Yes, that would make sense. Expect an update with that shortly.

**Pull request merged**
