### PR TITLE
Update Roadmap to nominate lead for Vue.js

### PR DESCRIPTION
**Pull request by tsega**
I am nominating myself to be the lead in the effort to make Vue a first class citizen in the Meteor ecosystem. My plan is to emulate what has already been done for React and build the skeleton, a full tutorial and documentation. I will also reach out to great contributors to the Meteor+Vue integration such as [Guillaume Chau aka Akryum](https://github.com/Akryum) to ensure we get the best possible resources on Meteor + Vue.

### CODE REVIEW

**Comment by BrianMulhall** [comment]
i have made a simple-todos-vue repo if you want to make use of it, i also forked and updated the tutorials repo and the tutorials-viewer repo so you can run it locally and check out how it looks. It might save you some time if thats the direction you wanted to go in. I am more than willing to help out as well, let me know what you think @tsega

**Comment by tsega** [comment]
@BrianMulhall  excellent! I think it would be a great place to start. Please share your repo with me so I can take a look. 
With regards to helping out, I believe there is a requirement by the team to have at least two people. So it's great that you're available. Let's get this going!

**Comment by BrianMulhall** [comment]
that sounds great to me, i will add you to the simple-todos-vue repo @tsega

**Comment by filipenevola** [comment]
Hi @tsega and @BrianMulhall it will be a pleasure to have you helping in the Vue.js part of Meteor.

Are you already in the Meteor Community Slack? We have a channel there called #tutorials where we are discussing how to have the same pattern for new tutorials, we have the React one almost ready and the Blaze is already in progress (invite for this [slack here](https://join.slack.com/t/meteor-community/shared_invite/enQtODA0NTU2Nzk5MTA3LWY5NGMxMWRjZDgzYWMyMTEyYTQ3MTcwZmU2YjM5MTY3MjJkZjQ0NWRjOGZlYmIxZjFlYTA5Mjg4OTk3ODRiOTc)).

I believe it would be a good first step to also have the tutorial for Vue.js so we can link it in the Meteor website.

**Comment by BrianMulhall** [comment]
hey @filipenevola i can start checking the slack channel more often in the future to keep up to speed, as far as the Vue tutorial is concerned i have all the pieces made for a simple-todos step by step guide. I have tested it locally using the tutorial-viewer and it looks good. but a second set of eyes never hurts :)

**Comment by BrianMulhall** [comment]
this is the ticket i believe is being used to track Vue related improvements, if we want to track things there

https://github.com/meteor/guide/issues/950

**Pull request merged**
