### PR TITLE
oplog-converter: Handle array item updates

### LINKED ISSUE #12325: Severe oplog converter issue
We ran into a weird and quite dangerous bug yesterday. This didn't come up during local development, since we didn't use replica sets locally (we will from now on!).

*TL;DR*

Valid update operations such as ...

```js
docs.update(
      {
        _id: doc._id,
      },
      {
        $set: {
          "items.0.id": "m57DsX8g8L66bM5JX",
          "items.0.name": "John Doe",
          "items.0.bio.en": "Just John",
          "items.0.languages.0.key": "en",
          "items.0.languages.0.englishName": "English",
          "items.0.languages.0.localName": "English",
          "items.1": {
            id: "FJwSQHqwpenCN6RQH",
            name: "Bill Clinton",
            title: {
              en: "Just Bill",
              sv: "",
            },
            bio: {
              en: "Former President",
              sv: "",
            },
            avatar: null,
            languages: [
              {
                key: "sv",
                englishName: "Swedish",
                localName: "Sverige",
              },
            ],
          },
        },
      }
    );
```

...will break Meteor's oplog converter and throw:

```
Error in oplog callback TypeError: Cannot read property 'a' of null
    at isArrayOperator (packages/mongo/oplog_v2_converter.js:46:19)
    at packages/mongo/oplog_v2_converter.js:91:11
    at Array.forEach (<anonymous>)
    at convertOplogDiff (packages/mongo/oplog_v2_converter.js:71:24)
    at packages/mongo/oplog_v2_converter.js:109:9
    at Array.forEach (<anonymous>)
    at convertOplogDiff (packages/mongo/oplog_v2_converter.js:71:24)
    at packages/mongo/oplog_v2_converter.js:109:9
    at Array.forEach (<anonymous>)
    at convertOplogDiff (packages/mongo/oplog_v2_converter.js:71:24)
    at oplogV2V1Converter (packages/mongo/oplog_v2_converter.js:122:3)
    at packages/mongo/oplog_observe_driver.js:607:16
    at Object.Meteor._noYieldsAllowed (packages/meteor.js:785:12)
    at OplogObserveDriver._handleOplogEntrySteadyOrFetching (packages/mongo/oplog_observe_driver.js:579:12)
    at packages/mongo/oplog_observe_driver.js:133:20
    at packages/mongo/oplog_observe_driver.js:17:9
    at Object.Meteor._noYieldsAllowed (packages/meteor.js:785:12)
    at packages/mongo/oplog_observe_driver.js:121:16
    at packages/mongo/oplog_tailing.js:108:7
    at runWithEnvironment (packages/meteor.js:1347:24)
    at Object.callback (packages/meteor.js:1360:14)
    at packages/ddp-server/crossbar.js:114:36
```

...then:

→ client will not receive the updates made via pub/sub, **nor any errors**.
→ client will have invalid & stale data
→ client will initiate invalid & destructive write operations based on that bad data.

_Severity:_ We already know of cases where users have lost data due to to this bug, and are losing / corrupting more data as I type this.

_Sidenote:_ At least @lukejagodzinski 's `jagi:astronomy` produces (perfectly valid) db operations that currently break Meteor's oplog converter.

**Reproduction**: https://github.com/arggh/meteor-oplog-converter-issue

Confirmed with Meteors 2.6.1 ... 2.8.1 and MongoDB 5.06 ... 5.0.14 (Mac OS, Ubuntu)

### PR DESCRIPTION
**Pull request by arggh**
This was my first glance at the oplog converter, _or oplog "under the hood" in general_, so I'm not a 100% sure I got it right. I'm still running this against a real app and trying to break it, and it probably will.

That being said, all Mongo tests ran succesfully and it fixes the test case I added + the known bug in our app.

**Explanation**: It seemed like the oplog converter wasn't handling array items updates, at all, such as:

```
sitems: {
   u1: { name: 'Foo' }
}
```

which should have translated to 

```
$set: {
  'items.1': { name: 'Foo' }
}
```

_Potentially_ fixes #12325

### CODE REVIEW

**Review by Grubba27 — APPROVED** [review]
Looks good.

**Comment by Grubba27** [comment]
Taking quick glance, things look fine, and if all tests passed, including your own, I guess it is ok. I would love to hear @radekmie review.

**Comment by radekmie** [comment]
I think it should become a part of the `isArrayOperator` handling, i.e., the first `if` of the last branch of the main loop. Here's a diff that does exactly that:
```diff
@@ -36,7 +36,7 @@ function join(prefix, key) {
   return prefix ? `${prefix}.${key}` : key;
 }
 
-const arrayOperatorKeyRegex = /^(a|u\d+)$/;
+const arrayOperatorKeyRegex = /^(a|[su]\d+)$/;
 
 function isArrayOperatorKey(field) {
   return arrayOperatorKeyRegex.test(field);
@@ -111,7 +96,10 @@ function convertOplogDiff(oplogEntry, diff, prefix) {
           }
 
           const positionKey = join(join(prefix, key), position.slice(1));
-          if (value === null) {
+          if (position[0] === 's') {
+            // Nested object.
+            convertOplogDiff(oplogEntry, value, positionKey);
+          } else if (value === null) {
             oplogEntry.$unset ??= {};
             oplogEntry.$unset[positionKey] = true;
           } else {
```

It passes the test you've added, @arggh. I think it's easier and more in-align with the current code. If you agree, feel free to commit this code yourself or give me access to commit it in your fork.

**Comment by arggh** [comment]
@radekmie I agree, your suggestion is less code and more aligned with the current implementation. No change in functionality was observed in our real-world-app.

However, I did notice one of the Mongo tests (_"mongo-livedata - oplog - drop collection/db"_) was intermittently failing locally, and that it was failing with both implementations of this proposed change. 

It was not failing when tests were ran against the `devel` branch 👀

**Comment by Grubba27** [comment]
> However, I did notice one of the Mongo tests ("mongo-livedata - oplog - drop collection/db") was intermittently failing locally, and that it was failing with both implementations of this proposed change.

Yeah, it fails if you re-run the meteor tests without restarting or something like that.
But in the CI all tests have passed as I can see, will merge and proceed with release of 2.9

**Comment by arggh** [comment]
@radekmie _This is probably a nothingburger, but I thought it might still be worth mentioning, just in case it rings a bell..._

As I was running automated e2e tests today for our app, using the mongo code from this PR, a test failed:

A document was inserted to the database where one of the values (a string) started with the letter 'S'; in the failed test the expected value was presented in the UI with 'S' missing from the beginning. 

So, instead of reading "Socks" it was reading "ocks".

I re-ran the test and then it passed, reading "Socks" as expected. I couldn't repeat the fail. I tried multiple combinations of restarting server and dropping the database to initialize the tests, without and with oplog. Never happened again. Given how weird this test failure was, I thought of asking if you see any chance that the changeset you proposed might have introduced this sort of bug, and/or if you understand why it might be hard to reproduce?

Cypress tests can be flaky, but this one definitely had the Meteor app showing false content in the UI, which I found a weird coincidence.

**Comment by radekmie** [comment]
Was it a _key_ of an object or the _value_? If the latter, then it's unrelated as we only operate on keys here.

**Comment by arggh** [comment]
**Value**, and the value started with a capital 'S', so shouldn't match the regex either. My own reasoning also says it's not related, but the coincidence was strange, and since the oplog converter does all sorts of recursive slicing and dicing, I couldn't dismiss it without mentioning here.

**Pull request merged**
