### PR TITLE
[webapp] Remove underscore

### PR DESCRIPTION
**Pull request by harryadel**
This will be the very first PR of many to come in order to purge Underscore from Meteor codebase.

I must admit @filipenevola was right and I was wrong, splitting this endeavor in multiple mini-PRs is the way to go https://github.com/meteor/meteor/pull/11869 ran into a deadlock and I couldn't figure out why it was failing, just because it worked for Blaze doesn't mean it's ought to work for Meteor so credit where it's due.

One last thing, I don't have much time available so once the PRs are created whomever is reviewing these PRs please go ahead and modify them as you see fit in order to get them merged, thanks!

### CODE REVIEW

**Comment by Grubba27** [comment]
> One last thing, I don't have much time available so once the PRs are created whomever is reviewing these PRs please go ahead and modify them as you see fit in order to get them merged, thanks!

Hey @harryadel, awesome to see you here! 
thx for letting us know that.

**Comment by harryadel** [comment]
@Grubba27 The PRs are done and you may review them now. https://github.com/meteor/meteor/pull/11869 is the reference I used to create them.

**Review by StorytellerCZ — APPROVED** [review]

**Comment by Grubba27** [comment]
Sure, @harryadel, I'll look carefully at them and adjust what is needed. Again thanks a lot for the care and time spent making the PRs!

**Comment by harryadel** [comment]
I think the underscore PRs might use a second look now @StorytellerCZ @Grubba27

**Comment by Grubba27** [comment]
> I think the underscore PRs might use a second look now 

Sure! I will add them to my to-do list for the next weeks. I plan on reviewing them again and maybe working on a new release for the 2.x track with these changes as long as in the 3.x track as well

**Comment by harryadel** [comment]
@denihs I think this one is ready too. Maybe we can merge all underscore PRs and in 3.1 we do completely deprecate underscore.

**Review by leonardoventurini — APPROVED** [review]

**Pull request merged**
