### PR TITLE
Convert @ddp-server/livedata_server Instances to Classes w/ Minor Perf Improvements

### PR DESCRIPTION
**Pull request by mvogttech**
This PR will cause conflicts with @vlasky [PR](https://github.com/meteor/meteor/pull/11368), however I believe the conversion to a class structure will allow for more efficient updates. 

I also think we should explore adding hash lookup support as a new strategy for @vlasky PR by modifying the diff-sequence package to have a method that dismisses the need for object-to-object comparisons in the callback, but rather hashes the string of the two objects and compares; if they differ have the server push the data to the client.

**Overview of changes**

- Migration to Classes from Prototype Instances
-- Session / session.js
-- ServerClass / server.js (Renamed to not conflict with global var)
-- SessionDocumentView / session_document_view.js
-- SessionCollectionView / session_collection_view.js
-- Subscription / subscription.js
- Modern ES Optimizations
- Conversion of Object instances to Maps

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
I think we should hold a bit on this after 2.3 release which has some changes in these as well, mainly when it comes to modernization some of those parts.

**Comment by StorytellerCZ** [comment]
We'll also need to fix test before even considering this.

**Comment by StorytellerCZ** [comment]
@mvogttech Can you get the changes in ` packages/diff-sequence/diff.js` into another PR? We could get that one out quickly.

**Comment by mvogttech** [comment]
> @mvogttech Can you get the changes in ` packages/diff-sequence/diff.js` into another PR? We could get that one out quickly.

Of course. Working on that now.

**Comment by filipenevola** [comment]
@mvogttech could you highlight the places where you are making changes so we can pay more attention to these lines?

As the PR is moving a lot of code it's hard for us to understand where the changes are.

You could comment in the changes here in the PR files tab ;)

**Comment by filipenevola** [comment]
I'm closing this issue because we haven't heard anything from the original poster for a while.

**Pull request closed without merging**
