### PR TITLE
Allow access to build plugins

### PR DESCRIPTION
**Pull request by mitar**
See #5911 and #5552 for discussion.

cc @stubailo

### CODE REVIEW

**Comment by stubailo** [comment]
@avital - I think @mitar wants this to be able to show a better error message for conflicting build plugins, what do you think?

@mitar - I think it would be good to have a more descriptive message for the commit, so that when people look at the history for this file they can know why these methods are there. Also, would it maybe be better to have one PR for the whole thing with error messages rather than just these methods?

**Comment by avital** [comment]
I don't understand this pull request, and definitely don't understand the motivation behind it. @mitar, can you explain?

**Comment by mitar** [comment]
We can discuss it here, but I thought it is better to discuss it in relevant tickets (#5911 and #5552). I just made this pull request so that we can discuss easier there.

Anyway, the point of this pull request is that currently you have issues when two plugins are trying to handle the same file extension. This change allows for a plugin to detect that some other plugin is trying to handle its extension and adapt the behavior. So before you blindly register a plugin, you can check if plugin already exists. Maybe then you do not register anything, maybe then you replace that plugin. Or patch it, or chain it, or whatever.

**Comment by mitar** [comment]
> I think it would be good to have a more descriptive message for the commit, so that when people look at the history for this file they can know why these methods are there.

Sure. I can cleanup the pull request after we decide it is OK.

> Also, would it maybe be better to have one PR for the whole thing with error messages rather than just these methods?

The point is that error messages become a non-problem once you have these methods available.

**Comment by Slava** [comment]
> Anyway, the point of this pull request is that currently you have issues when two plugins are trying to handle the same file extension. This change allows for a plugin to detect that some other plugin is trying to handle its extension and adapt the behavior. So before you blindly register a plugin, you can check if plugin already exists. Maybe then you do not register anything, maybe then you replace that plugin. Or patch it, or chain it, or whatever.

How is allowing an auto-magical behavior like a good idea? From the app developer prospective, a random build plugin might be registered by some deep-deep dependency. And because that deep dependency is present, another build plugin decides to flip its behavior to something else?

**Comment by mitar** [comment]
That is already completely like that. Whole Meteor allows monkey-patching. I can monkey-patch Blaze and make it behave completely differently. Why would now this be an exception?

Of course, developer should make sure that things are not too unexpected. That behavior is only extended and not changed.

Do you have a better proposal how to easily allow this? I think it is the best compromise between time spend developing it, and then seeing how much demand is really for this feature. It is exactly how the rest of Meteor is done by exposing various `_internals` around which you can then monkey-patch.

So please, let's be practical here and not block innovation just because somebody can break something. This can be done on many other levels already.

**Comment by benjamn** [comment]
Thanks for this PR, and sorry we never got around to merging it. We are currently cleaning up the repository and removing old PRs; if you think this PR still has value and are interested in resurrecting it, we encourage you to re-submit it against current `devel`.

**Comment by mitar** [comment]
Can we just reopen?  There is little benefit in loosing all this conversation in the new pull request?

**Comment by benjamn** [comment]
Absolutely. Sorry the PR reaping process is kinda blunt :)

**Comment by mitar** [comment]
I think you  could achieve daily pull request closing quota by merging some of my other easier to merge and pretty straightforward pull requests. ;-)

**Comment by zol** [comment]
I'm going to close this PR for two reasons:

(1) In light of the fact that a transition to npm is on the medium term roadmap, we don't want to increase the surface area of the current build plugin APIs.

(2) There is considerable trepidation from the core team in exposing the build plugin system's internals in this way, including legitimate concerns around promoting a questionable usage pattern.

**Comment by mitar** [comment]
@stubailo, @tmeasday: I would like to bid again for reopening this pull request. Accessing other build plugins from plugins would allow us to implement `<script language="coffee"></script>` tag in Blaze. So one could during compilation of Blaze template, access build plugin for `coffee` extension and get it to build the file.

But it seems that compiles to not really have an API which allows string to string compilation? Or we could just use `File` object with `data` and pass it to `compileOneFile`.

**Comment by tmeasday** [comment]
Seems reasonable to me. What do you think @benjamn?

**Comment by mitar** [comment]
Ping? @tmeasday, @benjamn 

I am not completely sure if the above would work though, because tool chain plugin is also doing some postprocessing. But maybe with some options to plugins like "bare" it can serve as a simple compiler from strings to strings, when a different plugin needs that. But I think we can add such options later to plugins, if it will be needed.

**Comment by tmeasday** [comment]
Well I will reopen it anyway.

**Comment by mitar** [comment]
Can this get merged please? We will also need it for https://github.com/meteor/blaze/issues/110.

**Comment by benjamn** [comment]
I wanted to work out a better way to provide this functionality before closing this PR, but I haven't had a chance to work on it.

Specifically, it would be great to have a system for chaining together multiple compiler plugins to process source files in a series of steps.

Tricky aspects of that design problem include (but are not limited to): deciding how compiler plugins should specify which source/intermediate files they care about, and making sure plugins run in the right order with respect to one another.

Babel presets and plugins (if you're familiar with those) are a good example of the complexity of configuring a compiler pipeline with multiple processing steps.

It may seem like exposing source processors to package code would help solve your problem, but it creates a huge new problem for Meteor the framework, because it makes a previously internal API public, which keeps us from changing how compiler plugins work in the future, which would ironically limit our ability to provide this exact functionality in a better way.

**Comment by mitar** [comment]
This is why methods are prefixed with `_`. :-) So that we can start building this things now, see what is needed in the future, and that can inform better future design process here.

But in short, for me at the moment the interesting thing is to be able to say: please compile this string and return. No special things here like matching files and stuff you mentioned above. Just so that inside `<script>` tag in Blaze I can embed CoffeeScript, or Stylus inside `<style>` tag. And reuse existing plugins for that.

**Comment by abernix** [comment]
Housekeeping: Just tagging as related to #5618

**Pull request closed without merging**
