### PR TITLE
Fix skell wrong react url

### PR DESCRIPTION
**Pull request by vit0rr**
Fix https://github.com/meteor/meteor/issues/12676

Just replacing old URLs with the newest.
Follow the issue for more details.

Ps: I'm replacing it with `simple-todos/01-creating-app` because the old URL was sent to `react/creating-an-app`.

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
@vit0rr I don't think these and other closures were intentional.

**Comment by vit0rr** [comment]
> @vit0rr I don't think these and other closures were intentional.

Oh, thanks.
Yep, it does not intentional... I'll fork it again and re-open this and the other PR as soon as I get

**Comment by StorytellerCZ** [comment]
@vit0rr I don't see this in the latest devel. Should I re-create this PR?

**Comment by vit0rr** [comment]
> @vit0rr I don't see this in the latest devel. Should I re-create this PR?

Hello,
This PR is already re-created here: https://github.com/meteor/meteor/pull/12713

**Pull request closed without merging**
