### PR TITLE
Remove jquery from static-html

### LINKED ISSUE #5320: static-html / caching-html-compiler have a jQuery dependency
with 1.2.0.2 the jquery issue is back
see https://github.com/meteor/meteor/issues/5223

### PR DESCRIPTION
**Pull request by ozsay**
Fixes #5320

### CODE REVIEW

**Comment by stubailo** [comment]
Merged, thanks!

@Urigo I heard you were excited about this one :]

**Comment by Urigo** [comment]
I am!  ;)  thanks!

**Comment by mattiLeBlanc** [comment]
Guys, Just to be clear. Can I already use this or is it still bleeding edge? (with this I mean ditching jQuery in my Angular - Meteor project)

**Comment by stubailo** [comment]
This will come out in the next release, which is Meteor 1.3.

**Comment by mattiLeBlanc** [comment]
very good. 
In my project I noticed that when I removed jQuery ( and the template cache started complaining) that there where still 2 packages using jQuery. The jQuery namespace was also allocated in my window scope.
I can chase down which packages used jQuery. But it doens't make sense to remove jquery as a package and then still have it twice through other packages, right?


My pacakges.
```
meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
# blaze-html-templates    # Compile .html files into Meteor Blaze views
session                 # Client-side reactive dictionary for your app
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library

standard-minifiers      # JS/CSS minifiers run for production mode

accounts-password
accounts-base
http
angular
angularui:angular-ui-router
stolinski:stylus-multi
angular:angular-animate
mquandalle:jade
civilframe:angular-jade
momentjs:moment
mgcrea:angular-strap
pbastowski:typescript
kyleking:customizable-bootstrap-stylus
mquandalle:bower
stevezhu:lodash
sgi:ui-mask
aldeed:collection2
```

**Pull request closed without merging**
