### PR TITLE
Replace kadira:flow-router with ostrio:flow-router-extra in meteor create --full

### PR DESCRIPTION
**Pull request by vparpoil**
see issue https://github.com/meteor/meteor/issues/11014

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
Looks good! Maybe also add note into changelog?

**Comment by dr-dimitru** [comment]
@StorytellerCZ do not merge it! It will break

@vparpoil update layout (`/tools/static-assets/skel-full/imports/ui/layouts/body/body.html`):

```html
<template name="App_body">
  {{> yield}}
</template>
```

@vparpoil update routes (`/tools/static-assets/skel-full/imports/startup/client/routes.js`):

```js
FlowRouter.route('/', {
  name: 'App.home',
  action() {
    BlazeLayout.render('App_body', 'App_home');
  },
});

FlowRouter('*', {
  action() {
    BlazeLayout.render('App_body', 'App_notFound' });
  },
});
```

**Comment by StorytellerCZ** [comment]
@dr-dimitru Don't worry, I can't merge.

**Comment by vparpoil** [comment]
I will do the updates requested, but I have one question for @dr-dimitru : it didn't break my local **meteor create --full**. Have you tried it as is ?

**Comment by dr-dimitru** [comment]
> I will do the updates requested, but I have one question for @dr-dimitru : it didn't break my local meteor create --full. Have you tried it as is ?

You're right, it's backward compatible. After trying it I see it's working just fine.

> Edit : looking at the docs again, it seems to me that both usages are correct. Can you describe why you prefer the use of {{> yield}} over {{> Template.dynamic }} (docs)?

1. Inside of the `yield` template we can control rendering behavior via router (one of examples: re-render or do not re-render when router params are changed, or avoid re-render (e.g. blink) on different routes with same template);
2. We put a lot of work into `yield` template to enhance rendering performance;
3. Since we are moving from old router to the up-to-date version my changes follow [flowrouter-extra documentation](https://github.com/VeliovGroup/flow-router/blob/master/docs/templating.md).

**Comment by vparpoil** [comment]
Thank you for the explanations, I didn't know about performance and configuration abilities given by `yield`

**Pull request merged**
