### PR TITLE
fixes #12761

### LINKED ISSUE #12761: hotcode push is failing in Android
```
I20230829-17:46:08.777(-4)? 08-29 17:46:08.376 12135 12338 W MeteorWebApp: Download failure
I20230829-17:46:08.777(-4)? 08-29 17:46:08.376 12135 12338 W MeteorWebApp: com.meteor.webapp.WebAppException: Non-success status code 404for asset manifest
I20230829-17:46:08.777(-4)? 08-29 17:46:08.376 12135 12338 W MeteorWebApp: 	at com.meteor.webapp.AssetBundleManager$1.onResponse(AssetBundleManager.java:104)
I20230829-17:46:08.777(-4)? 08-29 17:46:08.376 12135 12338 W MeteorWebApp: 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
I20230829-17:46:08.777(-4)? 08-29 17:46:08.376 12135 12338 W MeteorWebApp: 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
I20230829-17:46:08.777(-4)? 08-29 17:46:08.376 12135 12338 W MeteorWebApp: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
I20230829-17:46:08.777(-4)? 08-29 17:46:08.376 12135 12338 W MeteorWebApp: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
I20230829-17:46:08.777(-4)? 08-29 17:46:08.376 12135 12338 W MeteorWebApp: 	at java.lang.Thread.run(Thread.java:920)
I20230829-17:46:08.777(-4)? 08-29 17:46:08.376 12135 12338 E MeteorWebApp: Download failure
I20230829-17:46:08.777(-4)? 08-29 17:46:08.376 12135 12338 E MeteorWebApp: com.meteor.webapp.WebAppException: Non-success status code 404for asset manifest
I20230829-17:46:08.778(-4)? 08-29 17:46:08.376 12135 12338 E MeteorWebApp: 	at com.meteor.webapp.AssetBundleManager$1.onResponse(AssetBundleManager.java:104)
I20230829-17:46:08.778(-4)? 08-29 17:46:08.376 12135 12338 E MeteorWebApp: 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
I20230829-17:46:08.778(-4)? 08-29 17:46:08.376 12135 12338 E MeteorWebApp: 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
I20230829-17:46:08.778(-4)? 08-29 17:46:08.376 12135 12338 E MeteorWebApp: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
I20230829-17:46:08.778(-4)? 08-29 17:46:08.376 12135 12338 E MeteorWebApp: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
I20230829-17:46:08.778(-4)? 08-29 17:46:08.376 12135 12338 E MeteorWebApp: 	at java.lang.Thread.run(Thread.java:920)
```
[Reference](https://github.com/meteor/meteor/blob/devel/npm-packages/cordova-plugin-meteor-webapp/src/android/WebAppLocalServer.java#L273)
for plugin cordova-plugin-meteor-webappin file `WebAppLocalServer.java` function `checkForUpdates` construcing the url with line of code `rootUrl.resolve("__cordova/");` which strips the suffix param from url. In our case we have the root_url `mobile-dev.xyz.com/app` 
which is resolved in `mobile-dev.xyz.com/__cordova/` but if we add forward slash in the `--mobile-server` in dev or `--server` in production it is resolved correctly into `mobile-dev.xyz.com/app/__cordova/` which then allow plugin to download correct `manifest.json` file from `mobile-dev.xyz.com/app/__cordova/manifest.json` in `checkForUpdates` [method](https://github.com/meteor/meteor/blob/devel/npm-packages/cordova-plugin-meteor-webapp/src/android/AssetBundleManager.java#L88)

### PR DESCRIPTION
**Pull request by salmanhasni**
#12761

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
I think this is something that we changed due to a bug somewhere else (or I am mistaking it with this PR). Can you please check the commit history for this line (I'm currently on vacation so I have a limited access to computer at the moment)?

**Comment by salmanhasni** [comment]
I have checked the history of archieve [repository](https://github.com/meteor/cordova-plugin-meteor-webapp) for this package, looks like it always been like that

**Comment by StorytellerCZ** [comment]
@salmanhasni how have you tested the fix? Also any way we can add tests for this to prevent regressions in the future?

**Comment by Grubba27** [comment]
Published under the cordova-plugin-meteor-webapp@2.0.2 namespace

**Pull request merged**
