### PR TITLE
Add Tool support for both 32 bit (3.2) and 64 bit (3.4) Mongo

### PR DESCRIPTION
**Pull request by hwillson**
(**Note:** I know the discussion I'm about to dive into here is likely better suited in an issue, but it relates to several issues, and ultimately leads to the PR code that is included here.)

# Backstory

As discussed in https://github.com/meteor/meteor-feature-requests/issues/129, the Meteor Tool is currently using Mongo 3.2.x, and it would be great to be able to upgrade to 3.4.x. As further discussed in PR https://github.com/meteor/meteor/pull/8864 however, we can't just update to 3.4.x as 32-bit versions of Mongo have been discontinued (as of Mongo 3.4). Since Meteor currently supports 32-bit Linux and Windows, we can't easily just upgrade to use a 64-bit version of Mongo.

We've talked about the best way to move forward with this, and ultimately decided that Meteor should ideally drop 32-bit support for all OS', as discussed in https://github.com/meteor/meteor-feature-requests/issues/152. This would definitely make the maintenance of Meteor easier moving forward, and is in-line with the approach several other open source projects are taking (like Mongo, Ubuntu, etc.).

While dropping Meteor's 32-bit support is the ultimate goal, we have heard from some community members about how this will impact them (especially those using embedded OS'). There is also a good chunk of work to complete to make this happen, as Meteor doesn't currently offer a 64-bit version for Windows (for example). While this work is pending, developers are getting more and more frustrated by not being able to (easily) use Mongo 3.4.x features, when they're already using a 64-bit OS.

# Proposal

Given the above, I think it makes sense to consider moving towards a 64-bit only Meteor in incremental steps:

- **Step 1:** Update the Meteor Tool to use Mongo 3.2.x for 32-bit based operating systems, and 3.4.x for 64-bit based operating systems. 

- **Step 2:** Start supporting 64-bit Windows as an official Meteor architecture, and provide a 64-bit Windows version of Meteor. 

- **Step 3:** Stop producing and supporting 32-bit versions of Meteor, and no longer support 32-bit architectures.

# This PR

The sooner we can start letting people use Mongo 3.4.x, the better, so the code in this PR addresses **Step 1** above. When using a 32-bit based OS, the Meteor Tool will use (and be limited to) Mongo 3.2.15. When using a 64-bit based OS, the Meteor Tool will use Mongo 3.4.9. 

| OS | Architecture | Meteor Tool Mongo Version |
| -- | ------------ | ----------------- |
| Linux | 32-bit | 3.2.15 |
| Linux | 64-bit | 3.4.9 |
| macOS | 64-bit | 3.4.9 |
| Windows | 32-bit | 3.2.15 |
| Windows | 64-bit | 3.4.9 |

A meteor build is produced and published for each OS/architecture combination in the table above (except Windows which is 32-bit only - more on this in a sec). This PR adjusts the Meteor Tool build process to use an appropriate version of Mongo based on a given OS/architecture combo. 

This PR has been tested against all supported 32/64 bit OS', and is in a runnable state (if anyone wants to try things out). I've listed a few outstanding questions below that I'd love to get feedback on. Also, the tests will fail here until a new `dev_bundle` is generated. 

**Special Considerations for Windows:**

Since we're still only building a 32-bit version of Meteor for Windows, this PR pulls both the 32 and 64 bit versions of Mongo into the 32-bit Windows Meteor Tool bundle. Then when running the tool, the appropriate version is used based on a quick check of the host OS's architecture (so even though we're still using a 32-bit version of Meteor on Windows, 64-bit Windows versions can use the latest 64-bit Mongo). This Windows approach is a stop-gap; when **Step 2** above is addressed, it will no longer be necessary. Including both the 32 and 64 bit versions of Mongo in the Windows Meteor Tool bundle is fairly harmless however, and only increases the bundle size by approximately 40 megs.

**Outstanding Questions:**

1) When using a 64-bit version of Linux with Mongo 3.4.9, depending on how the Linux environment has been setup, Mongo might output startup warnings when using Meteor's Mongo shell. For example:

```
MongoDB shell version v3.4.9                  
connecting to: mongodb://127.0.0.1:3001/meteor
MongoDB server version: 3.4.9
Server has startup warnings: 
2017-10-03T12:06:03.268+0000 I STORAGE  [initandlisten] 
2017-10-03T12:06:03.269+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2017-10-03T12:06:03.269+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2017-10-03T12:06:03.850+0000 I CONTROL  [initandlisten] 
2017-10-03T12:06:03.850+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2017-10-03T12:06:03.850+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2017-10-03T12:06:03.850+0000 I CONTROL  [initandlisten] 
2017-10-03T12:06:03.850+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2017-10-03T12:06:03.850+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2017-10-03T12:06:03.850+0000 I CONTROL  [initandlisten] 
2017-10-03T12:06:03.850+0000 I CONTROL  [initandlisten] ** WARNING: soft rlimits too low. rlimits set to 3829 processes, 65536 files. Number of processes should be at least 32768 : 0.5 times number of files.
2017-10-03T12:06:03.850+0000 I CONTROL  [initandlisten] 
```

While these warnings are valid, they're (mostly) intended for production environments. Should we consider suppressing these warnings or leave them as is?

2) When using a 3.2.x 32-bit version of Mongo (Linux and Windows) with the Meteor Tool, the Mongo shell will automatically dump a deprecation notice like:

```
MongoDB shell version: 3.2.15                 
connecting to: 127.0.0.1:3001/meteor
Server has startup warnings: 
2017-10-03T12:09:15.189+0000 I CONTROL  [initandlisten] 
2017-10-03T12:09:15.189+0000 I CONTROL  [initandlisten] ** WARNING: This 32-bit MongoDB binary is deprecated
2017-10-03T12:09:15.189+0000 I CONTROL  [initandlisten] 
2017-10-03T12:09:15.189+0000 I CONTROL  [initandlisten] 
2017-10-03T12:09:15.189+0000 I CONTROL  [initandlisten] ** NOTE: This is a 32 bit MongoDB binary.
2017-10-03T12:09:15.189+0000 I CONTROL  [initandlisten] **       32 bit builds are limited to less than 2GB of data (or less with --journal).
2017-10-03T12:09:15.189+0000 I CONTROL  [initandlisten] **       Note that journaling defaults to off for 32 bit and is currently off.
2017-10-03T12:09:15.189+0000 I CONTROL  [initandlisten] **       See http://dochub.mongodb.org/core/32bit
2017-10-03T12:09:15.190+0000 I CONTROL  [initandlisten] 
```

Should we leave this as is or make it more user friendly?

Fixes https://github.com/meteor/meteor-feature-requests/issues/129.

### CODE REVIEW

**Comment by hwillson** [comment]
This PR was just reviewed in our weekly triage meeting, and the new plan is to go straight to **Step 2** - building a 64-bit version of Meteor for Windows ( 🎉 ). I'll keep this PR open for now, since we'll be re-using parts of it shortly (and thanks for building the `dev_bundle` @abernix!).

**Comment by zimme** [comment]
1. I'm in favour of silencing these errors.
2. I don't have a problem keeping the warnings here, people should be moving to 64-bit systems.

**Comment by hwillson** [comment]
Closing for now (Windows 64-bit changes are being made elsewhere and the necessary Mongo 3.4.x changes will be included as needed).

**Comment by crapthings** [comment]
will meteor 1.6.1 shipping mongo 3.4.x

**Comment by crapthings** [comment]
mongodb@release/METEOR@1.6.1-beta.5 is still 3.2.x

https://github.com/meteor/meteor/blob/78700d772daddb1a2618ac805881e9537c695ebc/scripts/build-dev-bundle-common.sh#L9

**Comment by benjamn** [comment]
@hwillson @abernix Do we have a new issue (or PR) for the post-1.6 Mongo 3.4 update? Either way, let's get it in the [1.6.1 milestone](https://github.com/meteor/meteor/milestone/45)!

**Comment by abernix** [comment]
I've opened #9396, which was incredibly easy thanks to previous work by @hwillson in this PR.

**Pull request closed without merging**
