### PR TITLE
Throw error when EJSON.clone circular structure

### PR DESCRIPTION
**Pull request by nlhuykhang**
Check for circular structure of objects passed to `EJSON.clone`, throw error if exists.
In reference to #5964

### CODE REVIEW

**Comment by mitar** [comment]
Have you done any performance benchmarks with this change? Because it can potentially slow down cloning a lot. And Meteor is doing a lot of cloning everywhere. You are doing one extra iteration over all properties of all objects, and you are also storing all objects you see into an array which could grow a lot, not to mention that scanning the array is O(n) operation, and you scan again and again, which makes this cycle checking operation quite unoptimized.

One option would be that instead of doing one extra pass to detect cycles, you would be remembering what you already cloned and if you get back to what you cloned during cloning process, you throw an error.

Alternatively, you could extend EJSON with additional method which check for cycles. So users can run that themselves before cloning if they suspect an object they want to clone has cycles. Because sometimes you know that there are not cycles, so why checking then?

**Comment by nlhuykhang** [comment]
I did not really think about performance when working on this. I just focused on solving #5964. But you are right, this change could make a negative impact on all Meteor projects.

I will revert `.clone` to the old implementation, and add a new method to EJSON named `.isCyclic` to check for cycles. Use this new method when executing Meteor methods to resolve #5964, sound good?

**Comment by mitar** [comment]
So maybe you could add this method and then also add those checks when method arguments are getting serialized.

**Comment by abernix** [comment]
Please rebase this on `devel` now that #8204 has landed, which should fix the failing tests.

Also, it appears your CircleCI builds aren't enabled for (your) `nlhuykhang/meteor` repo so [none of those](https://circleci.com/gh/nlhuykhang/meteor) ran for this PR.  You can enable up to 4 containers for free on Meteor and it will use them all.

**Comment by nlhuykhang** [comment]
I closed this PR for now as it is not yet finished

**Comment by nlhuykhang** [comment]
After rebasing `devel`, I created a new PR here #8227. I do not know why the build keeps failing even though everything works fine and all tests are passed on my local machine.

Could anyone help me?

**Pull request closed without merging**
