### PR TITLE
Release 2.2

### PR DESCRIPTION
**Pull request by filipenevola**
###  :tada:  Meteor 2.2-beta.3 is out.

Check what is included [here](https://github.com/meteor/meteor/blob/release-2.2/History.md) and then upgrade:

`meteor update --release 2.2-beta.3`

or create a new app

`meteor create my-app --release 2.2-beta.3`

---

Hi, we are starting the branch for 2.2 Release.

The content is always up-to-date in the [milestone](https://github.com/meteor/meteor/milestone/79)

It's a minor bump because we are going to update Cordova from 9 to 10.

Also MongoDB and Typescript had relevant changes.

### CODE REVIEW

**Comment by filipenevola** [comment]
building the dev bundle to update typescript version https://github.com/meteor/meteor/pull/11329

**Comment by filipenevola** [comment]
Meteor 2.2-beta.1 is out.

More details in the description.

**Comment by brucejo75** [comment]
@filipenevola, any chance you could look deeper into #11005 for this release?  Given it is a Cordova release, very appropriate...

**Comment by filipenevola** [comment]
Meteor 2.2-beta.2 is out.

Including the new Node.js version and npm version from Meteor 2.1.1.

**Comment by mibto** [comment]
@filipenevola there was just a release of the mongodb driver. 3.6.5 -> 3.6.6
just for your information ;)

**Comment by filipenevola** [comment]
🎉 Meteor 2.2-beta.3 is out.

**Pull request merged**
