### PR TITLE
Insert default date header into emails

### LINKED ISSUE #3940: accounts-password email verification: missing date header field
When `accounts-password` sends a verification email, my SMTP provider warns that the sending date is missing from the email header :

`X-Amavis-Alert BAD HEADER SECTION, Missing required header field: "Date"`

Is there a way to add the custom header fields of the emails sent by `accounts-password`? Or even better, add custom header variables to every email sent by the `email` package?

### PR DESCRIPTION
**Pull request by AlexanderS**
This will insert a default date header into all emails, if you do not
specify such a header by your self. This way it will work for the emails
send by accounts-password and all emails from user code. So this will
fix #3940.

### CODE REVIEW

**Comment by AlexanderS** [comment]
livedata stub - reconnect non-idempotent method : !!!!!!!!! FAIL !!!!!!!!!!!

The failure does not seem to be caused by this changes.

**Comment by tmeasday** [comment]
Can you rebase this to be off of current `devel`? I think this branch is off an earlier commit with failing self tests. It should be as easy as (assuming you have a remote called `upstream` pointing here):

```
# optionally
git remote add upstream https://github.com/meteor/meteor

git fetch upstream
git rebase upstream/devel
git push --force
```

**Comment by AlexanderS** [comment]
Sure, no problem.

**Comment by AlexanderS** [comment]
@tmeasday Anything missing? It seems, that the traivis-ci build did not start.

**Comment by tmeasday** [comment]
@AlexanderS sorry I think perhaps I asked you this in between getting circle working and setting up travis. It's all good, if circle passes, then travis does too (travis is just a quicker check of the package tests)

**Comment by abernix** [comment]
Per #7123, this PR broke e-mail sending when the `headers` option is not provided when `Email.send` is invoked.  Just defaulting `headers` to empty object would fix it. 

Unfortunately, both tests in [email_tests.js](https://github.com/meteor/meteor/blob/657336451394f2f18f8300955752ff6d9ca05bec/packages/email/email_tests.js) currently pass `headers` so tests missed this.  A new test should be added that does not pass `headers` (which is probably much more typical usage).

**Comment by tmeasday** [comment]
I think I fixed this w/ https://github.com/meteor/meteor/commit/6e071838af0c9594cdbf9b23ded7ef5806510a86 but I would appreciate a test to confirm that @abernix. I was in a rush but it looked like the headers had to be set for the test to work

**Comment by abernix** [comment]
Ah, I previously missed that commit.  Yes, that would fix it.  :smile: Tests submitted which would have caught that regression.

**Pull request merged**
