### PR TITLE
Release 2.5.1

### PR DESCRIPTION
**Pull request by renanccastro**
This release brings Mac M1 support!

## Latest beta

2.5.1-beta.1 -> npm install -g meteor@2.5.1-beta.1

### CODE REVIEW

**Comment by jamesloper** [comment]
Trying it out with a few projects. 

One one project I am relying on the built-in mongo, it gets stuck here:

```
/Users/james/.meteor/meteor -s james.json --verbose
[[[[[ ~/code/hux/hux ]]]]]

=> Started proxy.
Local package version is up-to-date: accounts-base@2.2.0
Local package version is up-to-date: accounts-password@2.2.0
Local package version is up-to-date: allow-deny@1.1.0
Local package version is up-to-date: autoupdate@1.8.0
Local package version is up-to-date: babel-compiler@7.7.0
Local package version is up-to-date: babel-runtime@1.5.0
Local package version is up-to-date: base64@1.0.12
Local package version is up-to-date: binary-heap@1.0.11
Local package version is up-to-date: blaze-tools@1.1.2
Local package version is up-to-date: boilerplate-generator@1.7.1
Local package version is up-to-date: caching-compiler@1.2.2
Local package version is up-to-date: caching-html-compiler@1.2.1
Local package version is up-to-date: callback-hook@1.4.0
Local package version is up-to-date: cfs:http-methods@0.0.32
Local package version is up-to-date: check@1.3.1
Local package version is up-to-date: ddp@1.4.0
Local package version is up-to-date: ddp-client@2.5.0
Local package version is up-to-date: ddp-common@1.4.0
Local package version is up-to-date: ddp-rate-limiter@1.1.0
Local package version is up-to-date: ddp-server@2.5.0
Local package version is up-to-date: diff-sequence@1.1.1
Local package version is up-to-date: dispatch:retry-http@0.1.4
Local package version is up-to-date: dynamic-import@0.7.2
Local package version is up-to-date: ecmascript@0.16.0
Local package version is up-to-date: ecmascript-runtime@0.8.0
Local package version is up-to-date: ecmascript-runtime-client@0.12.1
Local package version is up-to-date: ecmascript-runtime-server@0.11.0
Local package version is up-to-date: ejson@1.1.1
Local package version is up-to-date: email@2.2.0
Local package version is up-to-date: es5-shim@4.8.0
Local package version is up-to-date: fetch@0.1.1
Local package version is up-to-date: geojson-utils@1.0.10
Local package version is up-to-date: hot-code-push@1.0.4
Local package version is up-to-date: html-tools@1.1.2
Local package version is up-to-date: htmljs@1.1.1
Local package version is up-to-date: http@1.4.4
Local package version is up-to-date: hwillson:stub-collections@1.0.9
Local package version is up-to-date: id-map@1.1.1
Local package version is up-to-date: inter-process-messaging@0.1.1
Local package version is up-to-date: livedata@1.0.18
Local package version is up-to-date: localstorage@1.2.0
Local package version is up-to-date: logging@1.3.1
Local package version is up-to-date: meteor@1.10.0
Local package version is up-to-date: meteor-base@1.5.1
Local package version is up-to-date: minifier-css@1.6.0
Local package version is up-to-date: minifier-js@2.7.1
Local package version is up-to-date: minimongo@1.7.0
Local package version is up-to-date: modern-browsers@0.1.7
Local package version is up-to-date: modules@0.17.0
Local package version is up-to-date: modules-runtime@0.12.0
Local package version is up-to-date: mongo@1.13.0
Local package version is up-to-date: mongo-decimal@0.1.2
Local package version is up-to-date: mongo-dev-server@1.1.0
Local package version is up-to-date: mongo-id@1.0.8
Local package version is up-to-date: mongo-livedata@1.0.12
Local package version is up-to-date: montiapm:agent@2.44.2
Local package version is up-to-date: montiapm:meteorx@2.2.0
Local package version is up-to-date: npm-mongo@3.9.1
Local package version is up-to-date: ordered-dict@1.1.0
Local package version is up-to-date: promise@0.12.0
Local package version is up-to-date: random@1.2.0
Local package version is up-to-date: rate-limit@1.0.9
Local package version is up-to-date: react-fast-refresh@0.2.0
Local package version is up-to-date: react-meteor-data@2.3.3
Local package version is up-to-date: reactive-dict@1.3.0
Local package version is up-to-date: reactive-var@1.0.11
Local package version is up-to-date: reload@1.3.1
Local package version is up-to-date: retry@1.1.0
Local package version is up-to-date: routepolicy@1.1.1
Local package version is up-to-date: server-render@0.4.0
Local package version is up-to-date: service-configuration@1.3.0
Local package version is up-to-date: session@1.2.0
Local package version is up-to-date: sha@1.0.9
Local package version is up-to-date: shell-server@0.5.0
Local package version is up-to-date: socket-stream-client@0.4.0
Local package version is up-to-date: spacebars-compiler@1.3.0
Local package version is up-to-date: standard-minifier-css@1.7.4
Local package version is up-to-date: standard-minifier-js@2.7.1
Local package version is up-to-date: static-html@1.3.2
Local package version is up-to-date: templating-tools@1.2.1
Local package version is up-to-date: tracker@1.2.0
Local package version is up-to-date: typescript@4.4.0
Local package version is up-to-date: underscore@1.0.10
Local package version is up-to-date: url@1.3.2
Local package version is up-to-date: webapp@1.13.0
Local package version is up-to-date: webapp-hashing@1.1.0
Local package version is up-to-date: xolvio:cleaner@0.4.0
Local package version is up-to-date: zodern:meteor-package-versions@0.2.1
```

I think a mongo error is getting silenced because if I set environment variable MONGO_URL to valid URL, project starts up. Meteor build works and I think everything works.

Unrelated info?!
- I have a pretty standard setup-- brew, make, rosetta, xcode...
- My path is pretty short, looks like
`/Users/james/.meteor:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin`

**Comment by renanccastro** [comment]
Hello @jamesloper thanks for the detailed report.
Can you please give it a try at 2.5.1-beta.3 ?

For installing, please uninstall all other meteor versions first:

```
meteor-installer uninstall (or remove ~/.meteor)
npm uninstall -g meteor

```
then install the beta 3 with:

`npm install -g meteor@2.5.1-beta.3`

I will post a report about the issue I've fixed later

**Comment by jamesloper** [comment]
worked perfectly @renanccastro

**Comment by jamesloper** [comment]
I've now tried it on all my meteor projects and it is working nicely.

**Comment by appigram** [comment]
Hi @renanccastro I'm trying to install 2.5.1-beta.3 
 
```
meteor-installer uninstall (or remove ~/.meteor)
npm uninstall -g meteor
```

But 

```
appigram@AppiMBPro webApp % npm install -g meteor@2.5.1-beta.3
npm ERR! code 1
npm ERR! path /opt/homebrew/lib/node_modules/meteor
npm ERR! command failed
npm ERR! command sh -c node cli.js install
npm ERR! events.js:377
npm ERR!       throw er; // Unhandled 'error' event
npm ERR!       ^
npm ERR!
npm ERR! Error: Response status was 403
npm ERR!     at ClientRequest.<anonymous> (/opt/homebrew/lib/node_modules/meteor/node_modules/node-downloader-helper/dist/index.js:1:7055)
npm ERR!     at Object.onceWrapper (events.js:520:26)
npm ERR!     at ClientRequest.emit (events.js:400:28)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
npm ERR!     at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
npm ERR!     at TLSSocket.socketOnData (_http_client.js:515:22)
npm ERR!     at TLSSocket.emit (events.js:400:28)
npm ERR!     at addChunk (internal/streams/readable.js:293:12)
npm ERR!     at readableAddChunk (internal/streams/readable.js:267:9)
npm ERR!     at TLSSocket.Readable.push (internal/streams/readable.js:206:10)
npm ERR! Emitted 'error' event on b instance at:
npm ERR!     at ClientRequest.<anonymous> (/opt/homebrew/lib/node_modules/meteor/node_modules/node-downloader-helper/dist/index.js:1:7186)
npm ERR!     at Object.onceWrapper (events.js:520:26)
npm ERR!     [... lines matching original stack trace ...]
npm ERR!     at TLSSocket.Readable.push (internal/streams/readable.js:206:10) {
npm ERR!   status: 403,
npm ERR!   body: ''
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/appigram/.npm/_logs/2021-11-06T20_44_05_557Z-debug.log
```

Works fine with meteor@2.5.1-beta.1
npm - 8.3.1
node - 14.18.1

**Comment by renanccastro** [comment]
@appigram what happened is that you had node installed, but as an x86_64 binary and it requested the tarballs for darwin x86_64, which I haven't published. I've only published the tarball for darwin arm64, which is why it worked after you installed node from brew :wink:

**Comment by brianlukoff** [comment]
Working great here too!

**Comment by DerGut** [comment]
It's working great for me! 🥳

**Comment by jamesloper** [comment]
there have been quite a few updates on npm! whats 2.5.1-beta.9?

**Comment by renanccastro** [comment]
> there have been quite a few updates on npm! whats 2.5.1-beta.9?

all beta versions of the installer after meteor@2.5.1-beta.3 only contains changes in the installer itself, like supporting install as root.

**Pull request merged**
