### PR TITLE
[meteor run --no-db] will not start the local mongo server

### PR DESCRIPTION
**Pull request by jboulhous**
Hello,
This is not the use case for an app that uses `meteor-platform`.
This useful if we don't need the local mongo server.
Regards.
Jamal

### CODE REVIEW

**Comment by jboulhous** [comment]
I should add this to help.txt

**Comment by stubailo** [comment]
@jboulhous I'm going to soon be working on a solution that simply doesn't start mongo if you don't have the `mongo` package, which seems preferable.

**Comment by stubailo** [comment]
In Meteor 1.2, we have split up meteor-platform so that removing mongo will actually be possible.

**Comment by jboulhous** [comment]
@stubailo thank you.
I think your solution is actually the best

**Pull request closed without merging**
