### PR TITLE
Open welcome links in new tabs instead of taking the user away from t…

### PR DESCRIPTION
**Pull request by wulfmeister**
…heir running app

### CODE REVIEW

**Comment by laosb** [comment]
Looks good. @stubailo seems you can deal with it.

**Comment by stubailo** [comment]
Lol, why me in particular? Looks fine to me.

**Comment by laosb** [comment]
Because normally it's you to process this kind of PRs 😀  
  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On 5月 7 2016, at 12:27 中午, Sashko Stubailo &lt;notifications@github.com&gt;
wrote:  

> Lol, why me in particular? Looks fine to me.

>

> —  
You are receiving this because you commented.  
Reply to this email directly or [view it on GitHub](https://github.com/meteor/
meteor/pull/6990#issuecomment-217605874)

**Comment by laosb** [comment]
Can we merge it?

**Comment by Primigenus** [comment]
Actually, I don't think `target=_blank` should be on any links as it's bad usability practice. Users have control over how to open links themselves (eg. by shift-clicking) and expect regular links to behave in that way. This came up a few years ago in #3288 too.

**Comment by stubailo** [comment]
I'm going to put aside my own personal hatred for `_blank` links to agree with others in this thread that you probably don't want to navigate away from the app you are currently developing.

**Pull request merged**
