### PR TITLE
Tests compilation

### PR DESCRIPTION
**Pull request by Sanjo**
As already stated in https://github.com/meteor/meteor/issues/5427, test compilation with the Meteor tool is an important missing piece for Velocity, that enables us to do performance optimizations and support ES2015 and CoffeeScript for all test frameworks.

With this pull-request the Meteor tool compiles tests also. Test files get the `isTest: true` flag in the program.json manifests and are not loaded by the Meteor app. Velocity can load the tests files when needed on demand.

Currently I'm looking for feedback on my approach.

__Still to do:__
* [ ] Test with `meteor build` / production build
* [ ] Add a selftest for this

### CODE REVIEW

**Comment by Sanjo** [comment]
> did the CI tests catch this?

Yes. But I caught it myself 5 seconds AFTER I pushed the commit :D (like always when I do something to quick).

**Comment by stubailo** [comment]
So the way I understand this design, it compiles all of the test files just the same as always, except then doesn't add them to the boilerplate for the app's HTML? Does it still compile the tests when building for production? Probably ideally it wouldn't include test files in the production bundle at all, right?

**Comment by Sanjo** [comment]
> So the way I understand this design, it compiles all of the test files just the same as always, except then doesn't add them to the boilerplate for the app's HTML? Does it still compile the tests when building for production? Probably ideally it wouldn't include test files in the production bundle at all, right?

Exactly as you wrote. The tests should only be compiled in the development buildMode. I have a new commit nearly ready that will exclude the tests from the production build. I will finish it on this weekend.

**Comment by Sanjo** [comment]
I just pushed the last thing that I have done some weeks ago. The tests indicate that it doesn't fully work.

**Pull request closed without merging**
