### PR TITLE
Making new Tinytest UI IE compatible

### PR DESCRIPTION
**Pull request by Grubba27**
As @zodern commented, the new Tiny Test Ui was not IE compatible in this PR I ensure that it will work properly by passing the same prop but without variable

### CODE REVIEW

**Comment by zodern** [comment]
Thanks for fixing this.

I haven't tried it locally, but one thing I noticed in the screenshot in #12362 is that there doesn't seem to be much contrast between some of the colors, making some of the text hard to read. For example, some of the red text, the text on top of the progress bar, and the gray detail text for each test (though that might have been changed).

**Comment by Grubba27** [comment]
I did. Let me send a print with the updated colors. I had issues with the accessibility/ contrast in the way it was.

**Comment by Grubba27** [comment]
Screenshot 2022-12-15 at 16 34 08

**Comment by Grubba27** [comment]
Screenshot 2022-12-15 at 16 35 18

**Pull request merged**
