### PR TITLE
Convert ANSI escape codes to HTML on error page

### PR DESCRIPTION
**Pull request by klaussner**
Uses the [`anser`](https://www.npmjs.com/package/anser) package to convert ANSI escape codes to HTML on the error page.

Before:
before

After:
after

### CODE REVIEW

**Comment by afrokick** [comment]
should be merged into devel branch now?

**Comment by klaussner** [comment]
Thanks, @afrokick. I changed the target to `devel`.

**Comment by filipenevola** [comment]
@klaussner the tests are failing, for example, Travis if failing with Error: Cannot find module 'anser'. I have cleaned up the caches but it is still failing https://travis-ci.org/meteor/meteor/builds/640960226?utm_source=github_status&utm_medium=notification

It's also useful to already check the others.

**Comment by klaussner** [comment]
@filipenevola The tests are failing because the changes require a new dev bundle.

**Comment by sebakerckhof** [comment]
My bad, when I rebased, the dev bundle change got lost

**Comment by filipenevola** [comment]
Hi, I just built and published a new dev bundle for this PR. I'm re-running the tests.

**Pull request merged**
