### PR TITLE
Update Google Client ID instructions

### PR DESCRIPTION
**Pull request by ocdtrekkie**
The Google API Manager has changed it's interface since this was last updated. I've corrected the instructions with as little change as possible to accurately describe the current workflow.

This issue was reported for another project, here, and I figured this was a simple fix to provide: https://github.com/sandstorm-io/sandstorm/issues/1756

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
CLA signed, sorry I didn't do it first.

**Comment by tmeasday** [comment]
Thanks for this, it looks great! Can you rebase this to be off of current `devel`? I think this branch is off an earlier commit with failing self tests. It should be as easy as (assuming you have a remote called `upstream` pointing here):

```
# optionally
git remote add upstream https://github.com/meteor/meteor

git fetch upstream
git rebase upstream/devel
git push --force
```

**Comment by ocdtrekkie** [comment]
@tmeasday I don't usually do any rebasing or anything because I never learned how to use the Git CLI. Your instructions, however, are fantastically clear. :+1:

**Comment by zol** [comment]
Looks good to me! Merging.

**Pull request merged**
