### PR TITLE
Adjusted Meteor.absoluteUrl() to use the secure setting.

### PR DESCRIPTION
**Pull request by hwillson**
Helps address the issue of accessing https://docs.meteor.com and being redirected to http://docs.meteor.com.

### CODE REVIEW

**Comment by stubailo** [comment]
What about people accessing <http://docs.meteor.com>? Will they now be redirected to <https://docs.meteor.com>? Maybe, but then we should make that redirection always happen.

**Comment by hwillson** [comment]
Yes, they will always be redirected to https://docs.meteor.com. Given that the rest of meteor.com has switched over to https though I think this makes sense. If people are checking out their own copies of the docs and running them locally, http will be preserved (since the secure flag in Meteor.absoluteUrl() doesn't affect localhost or 127.0.0.1).

The other option of course if to leave things as they are and link to **http**://docs.meteor.com from the meteor.com top menu instead.

**Comment by hwillson** [comment]
Sorry, I hadn't had my coffee yet - there is another option that should help address this. I've updated the code to only set the secure flag to true if the original URL is https based. This should fix both http://docs.meteor.com and https://docs.meteor.com.

**Comment by stubailo** [comment]
I think we should avoid having 2 URLs and just make it always use `https`. Sorry for not being clear the first time. I think we can go back to the code you had in the beginning with `secure` always being true, and then just add the `force-ssl` package so that people are always redirected to https.

**Comment by hwillson** [comment]
Hi @stubailo - no worries and good idea. I've reverted the code and added force-ssl. Thanks!

**Comment by stubailo** [comment]
Thanks for the PR!

**Comment by hwillson** [comment]
I didn't realize force-ssl sets the Meteor.absoluteUrl() secure option to true by default - good to know. Thanks!

**Comment by stubailo** [comment]
Yeah I didn't know either! David Glasser tipped me off.

**Comment by n1mmy** [comment]
This got reverted as a result of #3965 

We should re-add force-ssl to docs once the interaction with appcache is fixed.

**Pull request merged**
