### PR TITLE
Cordova improvements for Meteor 1.8.1

### PR DESCRIPTION
**Pull request by benjamn**
Incomplete list of key improvements:
- [x] Make Cordova work with Xcode 10: https://github.com/apache/cordova-ios/issues/407
- [x] Fix iOS hot code push: https://github.com/meteor/cordova-plugin-meteor-webapp/issues/56, https://github.com/meteor/cordova-plugin-meteor-webapp/pull/59
- [ ] Update Cordova to version 8.x (currently 7.1.0)?

### CODE REVIEW

**Comment by jastakhova** [comment]
Hi,  @benjamn !
Can you suggest how to include the flag "-UseModernBuildSystem=0" to meteor run for ios while this fix is getting released? I am trying to make "meteor run ios" work with the emulator.

**Comment by dagatsoin** [comment]
Maybe this could be added too: https://github.com/meteor/meteor/issues/10308
It makes impossible to use some plugin, because the generated `build.gradle` seems to generated a deprecated repository order.

**Comment by dagatsoin** [comment]
Made a PR for the repositories order problem. https://github.com/meteor/cordova-android/pull/1

**Comment by derouck** [comment]
For whose stuck with Xcode 10 issues, the easiest way is probably to downgrade Xcode for now...

https://medium.com/@tseboho/how-to-downgrade-xcode-4359df5158d5

**Comment by tromgy** [comment]
@jastakhova This is how I made `meteor run ios` work with XCode 10:

add this line 

`options.push('--buildFlag=-UseModernBuildSystem=0');`

right after

```
run(platform, isDevice, options = [], extraPaths = []) {
    return Promise.asyncApply(() => {
      options.push(isDevice ? '--device' : '--emulator');
```

in **~/.meteor/packages/meteor-tool/1.8.0_1/mt-os.osx.x86_64/tools/cordova/project.js**

**Comment by drone1** [comment]
> `options.push('--buildFlag=-UseModernBuildSystem=0');`

Bless your heart, this worked for me w/ Xcode 10.1 (10B61), Meteor 1.8.0.1.

**Pull request merged**
