### PR TITLE
Support ARM on Linux

### PR DESCRIPTION
**Pull request by aquinoit**
Hello there! We are working on ARM support to continue [PR](https://github.com/meteor/meteor/pull/11809).

Thanks, @nathan-muir, for the excellent contribution.

We decided to open a new PR from the latest devel branch, We've already made it work with **Ubuntu** and **Amazon Linux**, but we're doing more testing.

Soon we will release a beta version so we can test directly on a clean server.

I will post more details and the progress of the task soon.

Thanks.

### CODE REVIEW

**Comment by JonathanLehner** [comment]
Could it be added soon? We need it for raspberry pi

**Comment by xet7** [comment]
Also needed for Asahi Linux on M1

**Comment by xet7** [comment]
And for arm64 build server

**Comment by xet7** [comment]
Currently I'm using OrangePi arm64 that has 16 GB RAM and 128 GB microSD card. To build Meteor, I need to remote desktop with virt-manager to other server that is amd64. I can not build Meteor locally, before this is merged. Same is also at Asahi Ubuntu on M1 and at build server that is arm64.

**Comment by xet7** [comment]
OrangePi is here:
- http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/details/Orange-Pi-5.html
- I'm using Armbian Jammy distro https://www.armbian.com/orangepi-5/

**Comment by xet7** [comment]
OrangePi is connected with HDMI to my 4K LED TV currently at resolution 3840x2160 at 60 Hz. Current uptime 4 days. Works very well for development.

**Comment by JonathanLehner** [comment]
Cool thanks! Have you tried building from the branch?

**Comment by xet7** [comment]
@JonathanLehner 

Building from branch how? What commands?

**Comment by JonathanLehner** [comment]
Checkout the branch and build?

**Comment by xet7** [comment]
@JonathanLehner 

```
It's the first time you've run Meteor from a git checkout.
I will download a kit containing all of Meteor's dependencies.
##O=#    #                                                                                                                

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Failed to install dependency kit.
It's the first time you've run Meteor from a git checkout.
I will download a kit containing all of Meteor's dependencies.
##O=#    #                                                                                                                

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Failed to install dependency kit.
```

**Comment by JonathanLehner** [comment]
what do you mean dependency kit?

**Comment by JonathanLehner** [comment]
I checked out the branch and ran ./meteor and for me it didn't get stuck. I will try if it works on my raspberry pi later. Maybe you can try on a different machine?
image

**Comment by JonathanLehner** [comment]
I need to check with Pi OS 64-bit. Seems now I am running 32-bit

**Comment by xet7** [comment]
@JonathanLehner 

32-bit MongoDB processes are limited to about 2 gb of data.  That is why usually 64bit MongoDB is used on 64bit operating systems.

https://www.mongodb.com/blog/post/32-bit-limitations

**Comment by JonathanLehner** [comment]
there is some problem with the dev bundle download. https://github.com/meteor/meteor/blob/devel/DEVELOPMENT.md I possibly solved it by rebuilding it ./scripts/generate-dev-bundle.sh . It is very slow. If you know it in advance, I highly recommend to avoid meteor for deployment to raspberry pi

**Comment by xet7** [comment]
@JonathanLehner

> solved it by rebuilding it ./scripts/generate-dev-bundle.sh

Thanks ! I'll try it.

> I highly recommend to avoid meteor for deployment to raspberry pi

Deployment to raspberry works, when there is prebuilt bundle.
I have built original bundle on amd64, and made some modifications to run it on arm64:
https://github.com/wekan/wekan/blob/master/releases/build-bundle-arm64.sh

I would like to do development on arm64 computers that are faster than raspberry pi,
like:
- Asahi Linux on M1 Air
- bare metal arm64 server that has nproc 80 and 250 GB RAM
- OrangePi that has 16 GB RAM with microSD and NVME disks

**Comment by JonathanLehner** [comment]
thanks! so you run https://github.com/wekan/wekan/blob/master/releases/build-bundle-arm64.sh on amd64 and then push it to the raspberry pi to deploy?

**Comment by xet7** [comment]
@JonathanLehner 

## Developing

I use `rebuild-wekan.sh` from https://github.com/wekan/wekan

## Releasing

When I have cloned repo, I release new version like this:
```
./releases/release.sh 6.80
```
Scripts are here:
https://github.com/wekan/wekan/tree/master/releases

It builds bundle, uploads it to arm64 and s390x servers
(I don't have access to ppc64le anymore)
and I build win64 version in Win11 in VirtualBox.
Fibers (and maybe some others in scripts) is CPU-specific code.

Info about installing bundles at:
https://github.com/wekan/wekan/wiki/Raspberry-Pi

I also upload bundles to release here:
https://github.com/wekan/wekan/releases

ChangeLog here:
https://github.com/wekan/wekan/blob/master/CHANGELOG.md

For Docker, at wekan directory I run:
```
docker build .
```
And push it to Docker Hub and Quay with:
```
./releases/docker-push-wekan.sh
```
Later I will add that it also pushes to GitHub packages too.

For Snap, after I have made release, I click build and release at https://snapcraft.io login website. At https://github.com/wekan/wekan there is snapcraft.yaml and directories snap and snap-src.

Releasing for Sandstorm does not currently work, it needs adding MongoDB upgrading script.

Info how to use bundle at Windows is at:
https://github.com/wekan/wekan/wiki/Offline

**Comment by xet7** [comment]
Building with Meteor on arm64 seems to require this kind of steps for Meteor 2.11.0.

Meteor is compatible with Node.js 14 and Npm 6.
```
ssh user@arm64server

sudo apt -y install sqlite3 libsqlite3-dev build-essential curl wget zip unzip p7zip-full nano

sudo apt -y install npm

sudo npm -g install n

sudo n 14.21.3

sudo npm -g install npm@6.14.18

sudo npm -g install @mapbox/node-pre-gyp

sudo npm -g install node-gyp

git clone https://github.com/meteor/meter .meteor

cd .meteor

git checkout origin/release-2.11

git merge remotes/origin/feature-linux-arm

time ./scripts/generate-dev-bundle.sh

cd ..

nano .bashrc
```
There add at bottom, and copy paste it to bash shell to use at current bash session:
```
export PATH=~/.meteor:$PATH
```
Currently when building, I'm getting errors about missing libcrypto.so.1.1 and libhogweed.so.5:
```
/home/wekan/.meteor/dev_bundle/mongodb/bin/mongod: error while loading shared libraries:
libcrypto.so.1.1: cannot open shared object file: No such file or directory
Unexpected mongo exit code 127. Restarting.
```
So I try to install MongoDB server next to see does it have those files. I tried with some existing similarly named files, but they were for wrong MongoDB version.

To find files, I used:
```
sudo apt -y install mlocate

sudo updatedb

locate libcrypto.so.1.1
```
And result was:
```
/snap/core20/1782/usr/lib/aarch64-linux-gnu/libcrypto.so.1.1
/snap/core20/1856/usr/lib/aarch64-linux-gnu/libcrypto.so.1.1
/snap/mongo44-configurable/31/usr/lib/aarch64-linux-gnu/libcrypto.so.1.1
```
But trying to add those like thise to `~/.bashrc` did not work, and bash shell did not accept commands:
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/snap/mongo44-configurable/31/usr/lib/aarch64-linux-gnu

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/snap/mongo44-configurable/31/usr/lib/aarch64-linux-gnu
```
So I needed to modify .bashrc via scp to comment those out, and scp file back:
```
exit

scp user@arm64server:/home/user/.bashrc .

nano .bashrc

scp .bashrc user@arm64server:/home/user/
```

**Comment by xet7** [comment]
LOL I messed up my arm64 server while trying to install mongodb etc. Reinstalling.

**Comment by xet7** [comment]
Ok I found the final step. Downloading mongodb tgz for arm64, version that is statically linked with OpenSSL, it works. Existing dynamically linked does not work.

```
cd ~/.meteor/dev_bundle/mongodb/bin

cp /home/user/Downloads/mongodb-linux-aarch64-ubuntu2204-6.0.5/bin/mongo* .
```

**Comment by xet7** [comment]
I added Meteor 2.11 for arm64 `~/.meteor` directory in tar.gz to https://releases.wekan.team/raspi3/

Here I'm running WeKan Open Source kanban https://wekan.github.io on M1 Air Asahi Ubuntu:

wekan-meteor-arm64

**Comment by xet7** [comment]
Here running on OrangePi 5 arm64 that has 16 GB RAM and 128 GB microSD. Currently my 1 TB NVME disk is not connected to  other side of OrangePi 5. Running Armbian that is based on Ubuntu 22.04.2 LTS arm64.

wekan-meteor-arm64-orangepi5

**Comment by jacoatvatfree** [comment]
Voting for this to be merged please

**Comment by xet7** [comment]
# Update 2023-12-07

I did get newest Meteor 3.0 working at Linux arm64. Here are all the details.

## Screenshot of Meteor 3.0 at Linux arm64

meteor-arm

## Installing Meteor 3.0 to Linux arm64

Using Debian 12 arm64 in this case. (Could also be newest Ubuntu).
```
ssh user@arm64linux

sudo apt -y install sqlite3 libsqlite3-dev build-essential autoconf automake cmake curl wget zip unzip p7zip-full nano
```
Scripts use command /usr/bin/python , that does not exists,
so link it to /usr/bin/python3 .
```
sudo su

cd /usr/bin

ln -s python3 python

exit
```
And continue:
```
sudo apt -y install npm

sudo npm -g install n

sudo n 20.10.0

sudo npm -g install @mapbox/node-pre-gyp

sudo npm -g install node-gyp

git clone https://github.com/meteor/meteor .meteor

cd .meteor

git checkout remotes/origin/release-3.0

git merge remotes/origin/feature-linux-arm
```
There is this one merge conflict file. Edit it and remove everything between <<< and >>> lines, and those lines itself also:
```
nano -c packages/promise/.npm/package/npm-shrinkwrap.json
```
Save and exit with Ctrl-o Enter Ctrl-x Enter

Generate dev bundle, here also timing how long it takes:
```
time ./scripts/generate-dev-bundle.sh

cd ..
```
Optional is installing MongoDB 6. meteor command uses Meteor embedded MongoDB, but when not developing, and running bundle, installed version of Node and MongoDB is used at `cd armtest/.build/bundle && node main.js`.
I installed just in case, if it has some of the required dependencies.

- Debian: https://www.mongodb.com/docs/v6.0/tutorial/install-mongodb-on-debian/
- Ubuntu: https://www.mongodb.com/docs/v6.0/tutorial/install-mongodb-on-ubuntu/

Download missing MongoDB .so files. These are needed, because otherwise building with meteor command has MongoDB errors. More info at https://github.com/wekan/wekan/issues/5142#issuecomment-1773317180
```
wget https://wekan.github.io/LD_LIBRARY-linux-arm64.zip

unzip LD_LIBRARY-linux-arm64.zip

nano .bashrc
```
There add at bottom, and copy paste it to bash shell to use at current bash session:
```
export PATH=~/.meteor:$PATH

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/lib
```
Then save and exit with Ctrl-o Enter Ctrl-x

To use those paths at current bash shell (without `exit` and back with `ssh user@arm64linux`):
```
source .bashrc
```
Then create meteor project:
```
mkdir repos

cd repos

meteor create --blaze armtest

cd armtest

meteor
```

**Comment by xet7** [comment]
Currently to build for Linux arm64, this additional step is needed: https://github.com/meteor/meteor/pull/12359#issuecomment-1858321891

**Review by denihs — APPROVED** [review]

**Pull request merged**
