### PR TITLE
update minifier js

### PR DESCRIPTION
**Pull request by alextaaa**

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
Given [this](https://github.com/mishoo/UglifyJS2/issues/1370) issue with 2.7.4, I would go with 2.7.3 or wait for the next release.

**Comment by benjamn** [comment]
Please update this pull request to use `uglify-js@2.7.5` and check that the performance is acceptable.

**Comment by alextaaa** [comment]
Hi @benjamn 
Thanks for your PR review.

I made another PR https://github.com/meteor/meteor/pull/8117

Please check )

**Comment by benjamn** [comment]
Closing in favor of https://github.com/meteor/meteor/pull/8117. Thanks!

**Pull request closed without merging**
