### PR TITLE
[mongo] Remove underscore

### PR DESCRIPTION
**Pull request by harryadel**

### CODE REVIEW

**Review by denihs — APPROVED** [review]
LGTM

**Comment by StorytellerCZ** [comment]
@denihs the failing test is unrelated, correct? I would like to wait for it to be fixed upstream first. Just in case.

**Comment by denihs** [comment]
This error is with CircleCI and how it checks out to a branch. We're good here.

**Comment by harryadel** [comment]
Finally!! :sob:

**Comment by StorytellerCZ** [comment]
Next we do performance improvements by replacing `.forEach` with `for of` loops. 🤫

**Pull request merged**
