### PR TITLE
Support for publication strategies in livedata server

### PR DESCRIPTION
**Pull request by vlasky**
This PR was created in[ response to a request from @filipenevola](https://github.com/meteor/meteor/pull/11151#issuecomment-763541235) 

I have merged my last commit https://github.com/vlasky/meteor/commit/0299ce6865b9800374b179fa1f5f8333b91e2132 with the [current head of meteor/devel 0a0cae235812259414b5afd291ed7243ed37b997](https://github.com/meteor/meteor/commit/0a0cae235812259414b5afd291ed7243ed37b997).

Integrates [@sebakerckhof's code](https://github.com/meteor/meteor/pull/11151) with extracts from the client-side code in @mitar's package peerlibrary:control-mergebox.

It now provides client-side MongoDB compatibility when the publication strategy is set to NO_MERGE, by gracefully handling duplicate events without throwing an exception. Specific changes:

*When we receive an added message for a document that is already present in the client's collection, it will be changed
*When we receive a change message for a document that is not in the client's collection, it will be added
*When we receive a removed message for a document that is not in the client's collection, nothing will happen.

### CODE REVIEW

**Review by StorytellerCZ — APPROVED** [review]

**Comment by mvogttech** [comment]
An idea for a publication strategy.

MongoDB 4.4 has the aggregation feature [$function](https://docs.mongodb.com/manual/reference/operator/aggregation/function/) that allows you to execute JS.

What if we had a publication strategy that utilized this feature to calculate a hash and compare that to a local hash, when they differ send the aggregate result.

Thoughts?

**Comment by StorytellerCZ** [comment]
@vlasky Could you add an entry into `history.md` about this?

**Review by filipenevola — CHANGES_REQUESTED** [review]
Hi @vlasky I didn't see the changes that I suggested here https://github.com/meteor/meteor/pull/11151#discussion_r540351963

I believe these changes are important in order to make this code maintainable in the long term.

If my idea is not clear enough, please ask some questions ;)

**Review by filipenevola — APPROVED** [review]
The changes are looking good.

We need to have a beta to test it broadly.

**Comment by StorytellerCZ** [comment]
Sweet! I will include this in the next 2.4 beta. @vlasky could you prepare a PR for documentation?

**Comment by brucejo75** [comment]
Will the docs be updated with this info?  Maybe add it here: https://github.com/meteor/meteor/tree/devel/packages/ddp-server

I am interested in understanding what this does and reading through the code looks like the best way to find out now...

Thanks!

**Comment by sebakerckhof** [comment]
@vlasky Thanks for continuing this work, glad to see this go in.

**Comment by StorytellerCZ** [comment]
@brucejo75 the docs are updated now.

**Comment by brucejo75** [comment]
@StorytellerCZ, thanks!  I see it in the [source](https://github.com/meteor/docs/blob/master/source/api/pubsub.md#publication-strategies) but not on the [website](https://docs.meteor.com/api/pubsub.html) yet?

**Comment by StorytellerCZ** [comment]
@brucejo75 It should be: https://docs.meteor.com/api/pubsub.html#Publication-strategies
I see it. Could be a cache issue?

**Comment by brucejo75** [comment]
It is there now, not sure what happened. I didn't need to flush cache to see it.

**Pull request merged**
