### PR TITLE
Fixed: Apollo Skeleton - Apollo Client needs a cache to be setup

### PR DESCRIPTION
**Pull request by ruohki**
Addressing and fixing issue #11145

Configured the client to use the InMemoryCache

### CODE REVIEW

**Comment by filipenevola** [comment]
Thanks @ruohki 

It will be available in the next Meteor version 😉

**Comment by msgfxeg** [comment]
Just replace this:
import { ApolloProvider, ApolloClient } from '@apollo/client';
with these 2 lines:
import { ApolloProvider } from '@apollo/client';
import ApolloClient from 'apollo-boost';

**Comment by ruohki** [comment]
But that means switching to the boost library

**Comment by filipenevola** [comment]
Hi, Meteor 1.11 fixes this issue and it is already available.

**Pull request merged**
