### PR TITLE
Separate localstorage keys by path

### PR DESCRIPTION
**Pull request by spyrosk**
Pull request for #3078

### CODE REVIEW

**Comment by bradvogel** [comment]
What if I have the same app that has different routes, e.g.
```
https://app.com/dashboard/
https://app.com/secondpage/
```

Won't this require that the user log in to the second url?

**Comment by glasser** [comment]
Seems like this should be keyed off of `ROOT_URL`, not the first component of the path.

**Comment by spyrosk** [comment]
@glasser I could be mistaken, but my understanding is that since `ROOT_URL` is an environment variable on the server, it is not available on the client (unless of course you expose it via custom code).

@bradvogel hmm, yes I think you're right. I will consult with some teammates to see if there's an elegant solution for this.

**Comment by glasser** [comment]
You can access ROOT_URL in the client (if it is set) via `__meteor_runtime_config__.ROOT_URL`. That's how `Meteor.absoluteUrl()` can work in the client.

**Comment by glasser** [comment]
(Or you can just call `Meteor.absoluteUrl()`.  So maybe a reasonable key name would be something like `JSON.stringify([Meteor.absoluteUrl(), key])`)

**Comment by SierraGolf** [comment]
Hi, 
I have the exact same issue. Running multiple apps which do not share the same user space on one domain.

Why can't we just provide a hook for developers to append a string to the key?

This way the system is flexible and developers can implement whatever strategy they want.

I my case each app would just prefix the key with its name, e.g. "app", "admin", "blog", etc.

**Comment by SierraGolf** [comment]
I just realized that the hook idea is not so easy to implement because of the load-order. The localstorage.js is loaded and the `Meteor._localStorage` is used before the application code is loaded. So as long as the application can not define the load order explicitly the hook idea is not possible.

Alternatively there could be a `Meteor.settings.public.appName` or something similar which the localStorage could use to statically prefix each key name.

**Comment by stubailo** [comment]
Thanks for this PR, sorry we never got around to merging it. We are currently cleaning up the repository and removing old PRs; if you think this PR still has value and are interested in resurrecting it, we encourage you to re-submit it against current `devel`.

**Pull request closed without merging**
