### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by Primigenus**
Yep, it's another fundamental PR!

### CODE REVIEW

**Comment by zol** [comment]
Hey, Thanks for your PR. Please sign our [contributor agreement](https://contribute.meteor.com/) before we can accept it.

**Comment by Primigenus** [comment]
I already did, years ago. Has it changed?

**Comment by zol** [comment]
Hmm, I can't find it under the `primigenus` github handle. The reason I ask is we had some trouble with an internal app that implements this over the last few weeks. Do you mind filling out a new one?

**Comment by Primigenus** [comment]
Sure. Done.

**Comment by zol** [comment]
Thanks!

**Pull request merged**
