### PR TITLE
OAuth1Binding - don't mutate the rawHeaders when generating a signature

### PR DESCRIPTION
**Pull request by timhaines**

### CODE REVIEW

**Comment by timhaines** [comment]
This fixes a long-standing bug of (post body) params being added to the headers when an oauth signature is generated.  They shouldn't be.

**Comment by avital** [comment]
This looks right, and I'd like to merge it. What's a simple way I can test this behavior? Is it that any call to `new OAuth1Binding(...).call` with params failed?

**Comment by timhaines** [comment]
@avital No - calls with params did not fail.  

The issue that highlighted this problem for me was sending long DMs to Twitter.  Long as in > 2000 characters - Twitter recently updated the max length to 10k, so I was testing that.    

You can quite happily include short params, and Twitter is tolerant of them in the header that they end up in.  But Twitter does reject headers over a certain length.  When the 'text' param grows to > 2000 characters, and is included in the header, Twitter rejects the request.

If you wanted a simple test, you could check that the headers remain the same after they've been passed into this method as a parameter.

**Comment by avital** [comment]
Thanks! Merged into devel and release-1.2

**Pull request merged**
