### PR TITLE
[WIP] Email.send should return value on success

### PR DESCRIPTION
**Pull request by bhunjadi**
Currently, it is not possible to get return value from SMTP server after an email has been sent successfully. Email.send always returns **undefined**.

It looks to me that the correct behavior should be to return the value from the nodemailer's _transporter.sendMail_ method described here (**info** object): 
https://nodemailer.com/usage/#sending-mail

### CODE REVIEW

**Review by hwillson — APPROVED** [review]
Looks good @bhunjadi - thanks for working on this! It doesn't look like the failing `accounts emails - reset password flow` test is caused by these changes. I tried your branch locally and the tests all passed, so this is probably related to https://github.com/meteor/meteor/pull/9596#issuecomment-361435677. LGTM!

**Comment by StorytellerCZ** [comment]
@hwillson @bhunjadi Any update on this?

**Comment by skirunman** [comment]
@benjamn @hwillson Any chance this is going to get merged?

**Review by sebakerckhof — APPROVED** [review]

**Comment by afrokick** [comment]
@hwillson ping

**Comment by filipenevola** [comment]
The CLA is still not signed, closing because of this. We can have a new PR with similar content to move this change ahead.

**Pull request closed without merging**
