### PR TITLE
Trigger onReady callback on resubscribe

### LINKED ISSUE #1173: Subscription onReady callbacks don't fire on a re-subscription with the same arguments inside Deps.autorun
**_2 Upvotes**_ I don't know if this is the intended behavior but lets assume that the server publish is setup.

Then we do

``` coffeescript
Deps.autorun ->
  Session.set('ready', false)
  Meteor.subscribe 'call-this', Session.get('something'), ->
    Session.set('ready', true)

Session.set('something', 2)
#wait for the subscibe to complete and the page shows
Session.set('something', 2)
#Now the loading page gets stuck. Note that the loading page uses {{#if}} against the 'ready' session.
```

I don't really have time to get an example working right now but I will try to if I get time.

My current hack/fix right now is adding a non-sense field to trick meteor on tearing and setting up the subscription and calling the on finish again.

``` coffeescript
Deps.autorun ->
  Session.set('ready', false)
  Meteor.subscribe 'call-this', Session.get('something'), Math.random(), ->
    Session.set('ready', true)

Session.set('something', 2)
#wait for the subscibe to complete and the page shows
Session.set('something', 2)
#Now the loading page gets stuck. Note that the loading page uses {{#if}} against the 'ready' session.
```

### PR DESCRIPTION
**Pull request by zimme**
This fixes #1173.

Tests needs updating. I know what needs updating,
I just need to update commends and stuff before
committing.

### CODE REVIEW

**Comment by zimme** [comment]
This should be ready now.

**Comment by hwillson** [comment]
One question - do you think we need to worry about instances where people are counting on the current (buggy) behaviour? For example, https://github.com/meteor/meteor/issues/1173#issuecomment-89376651. If so this might be a breaking change.

**Comment by zimme** [comment]
I guess we might need a short discussion about if we want to keep the current behaviour and document that you can use `handle.ready()` if you want the behaviour that this PR brings instead.

However I do think this should be classified as a bug and fixed because there are more people that assume that this function would work the way it would with this PR applied.

So maybe a warning in `History.md` about a potential breaking change for people relying on this broken behaviour.

On another note, do we have any way of achieving what the developers in that comment were doing if we apply this patch?

**Comment by mitar** [comment]
I would vote for merging this in and adding a history entry.

**Comment by hwillson** [comment]
Thanks @mitar - that was the consensus on our triage call today as well (we were just waiting for the failed tests to re-run). This will be merged shortly (@abernix is planning on adding a small adjustment to the `History.md` to explain how this could break backwards compatibility in some cases).

**Comment by sebakerckhof** [comment]
Question: Why, in the case the existing subscription is not yet ready, is the ready callback overwritten instead of added? I mean the code has [this](https://github.com/meteor/meteor/blob/master/packages/ddp-client/livedata_connection.js#L580-L584) comment:
```
 the semantics we provide is
// that at the time the sub first becomes ready, we call the last
// onReady callback provided, if any.`
```

But this doesn't really make sense if you think about a component-based GUI, since the onReady callback will often be used to for example hide a loading indicator.

So that means if you have 2 different components subscribing to the same thing more or less at the same time, and both use the 'onReady' callback to hide a loading indicator inside the component, only one will be called and thus one component will keep showing the loading indicator?

**Comment by sebakerckhof** [comment]
@zimme Yeah, nevermind, I missed the `inactive` part. I thought this code was to avoid sending the same subscription twice to the server, but it's about autorun behavior.

**Comment by benjamn** [comment]
Merged into [Release 1.5.1](https://github.com/meteor/meteor/pull/8788) as part of `1.5.1-beta.3`.

**Pull request closed without merging**
