### PR TITLE
Upgrade to Mongo 3.6

### LINKED ISSUE #9623: New $v field in Mongo 3.6 oplog breaks OplogObserveDriver
Reproduction: https://github.com/benweissmann/mongo36meteorbug

Mongo 3.6 adds a new `$v` field to the `o` and `o2` fields of oplog records. This might be removed in the future (https://jira.mongodb.org/browse/SERVER-32240), but for now, it causes the OplogObserveDriver's calls to LocalCollection._modify to fail. In most cases, this is caught by the OplogObserveDriver, which then re-loads the document from the database, so it's not immediately visible. However, it's a substantial performance regression, and there are some cases in the main app that I work on where it doesn't catch the error, and causes incorrect behavior (I have not been able to reproduce this case, but the reproduction above shows the re-fetch behavior when you add breakpoints or watch the mongo logs).

I have implemented a questionable workaround: https://github.com/benweissmann/mongo36meteorbug/blob/master/server/main.js#L6, but I think a fix should make its way to the upstream OplogObserveDriver.

This occurs on (at least) Meteor 1.6.1 and 1.4.4.1, on MacOS, although I'd guess it occurs on all operating systems on all reasonable recent versions of Meteor.

### PR DESCRIPTION
**Pull request by hwillson**
Hi all - this PR reverts the revert (https://github.com/meteor/meteor/commit/85d74f8d2be3b26f29ea51723a2241441bf7aa25) of https://github.com/meteor/meteor/commit/dfc07025580960ea40833c1340217695ab9601c4, and includes fixes to address the previous test failures. I've labelled this as a work in progress, as I think it makes sense to also address the following issues, in this PR:

- ~~https://github.com/meteor/meteor/issues/9623~~ Done (https://github.com/meteor/meteor/pull/9632/commits/8a5c2e4fdf39fd97f21a3994d4b6b1a090603991)
- ~~https://github.com/meteor/meteor/issues/9591~~ Done (https://github.com/meteor/meteor/pull/9632/commits/75bd950287bc4ed184a66544d8c9c7ba4bc2c6cd)

The tests will of course fail here until a new dev_bundle is generated / published, but we can hold off on that until the above items are addressed.

I'll re-cap the previous Mongo 3.6 PR notes (https://github.com/meteor/meteor/pull/9533), so we don't have to jump around:

Fixes #9623.

----

This PR updates the Meteor Tool to use Mongo 3.6.2 for 64-bit OS' and Mongo 3.2.18 for 32-bit OS' (I've left the garbage `BUNDLE_VERSION` in place intentionally, since these changes will require a new `dev_bundle` publish from MDG). 

A few important mentions:

- As of Mongo 3.6, all Mongo binary downloads include SSL - there is no longer a non-SSL based download bundle (so it's a bit bigger, but that shouldn't be an issue).
- Using the `--nojournal` option with WiredTiger based replica sets is no longer supported (see https://jira.mongodb.org/browse/SERVER-30760). The `--nojournal` flag was added in https://github.com/meteor/meteor/commit/bcfe072d5233be5892f715d27ca9dce69089242d to help reduce the amount of disk space used by Mongo, but since this option is no longer supported, we'll have to live with the extra disk space usage.

**Mongo Node driver side note:**

The Mongo Node driver has recently jumped into the 3.x range, and has introduced a [few breaking changes](https://github.com/mongodb/node-mongodb-native/blob/HEAD/HISTORY.md). While we normally bump the Mongo Node driver to the most recent version when doing Mongo updates, I've left it in 2.x range for now. I'll submit a separate Mongo Node driver 3.x update PR, so we can keep the focus on the Mongo upgrade here. Mongo 3.6 will work with 2.x versions of the Mongo Node driver.

Thanks!

### CODE REVIEW

**Comment by abernix** [comment]
It may be worth clarifying that, while Windows and Mac do only come bundled with SSL, SSL is still not included with the Generic Linux tarball (which `scripts/generate-dev-bundle.sh` pulls in), presumably since cross-distro linking of SSL libraries is more difficult.  I snuck this change which accommodates that rule into the last PR, in order to build the dev bundle: https://github.com/meteor/meteor/pull/9533/commits/fce09acae9183067c31fd4e0d7554f9e590f344f#diff-be3b40b6bc1b45a60ad8698bc2065cb9R57.

I've built the dev bundle, though we'll want to remember to quell https://github.com/meteor/meteor/pull/9632/commits/e73013bc82ceeb800d18dbeaa13f80538bc341eb before merging (as notated with the `[DELETEME]` prefix to the commit message).

Thanks for looking at this, @hwillson!

**Comment by hwillson** [comment]
The last part of this PR is to figure out what to do about https://github.com/meteor/meteor/issues/9591. When `meteor update`'ing to a version of the Tool that uses Mongo 3.6, jumping back to run an older version of Meteor (using `meteor --release X`) can break. This happens as the Mongo 3.6 updated database is no longer directly usable by Mongo 3.4 (or earlier). Why is the database no longer directly usable? Good question - I haven't been able to track the reason down (nothing in the logs, everything looks okay with the database, etc.). This might be caused by the fact that the Mongo 3.6 database is updated to use journaling by default, then we're jumping back to a setup that expects no journaling, but my tests in this area don't point to this being a problem.

The database can be repaired (see https://github.com/meteor/meteor/issues/9591#issuecomment-367351465) and used with previous versions of Meteor, but this is a manual step. We can't really automate this as we'd then have to release new patch versions for older Meteor releases, to include the code to handle the database repair when the Mongo startup error happens. Due to the way Tool springboarding works, we can't just add code to handle the repair in Meteor 1.6.2, and expect to have it called when running `meteor --release X`. Given this, the best option here might just be to document this potential issue, as well as the `mongod --repair` fix, and make sure people are aware of the potential issue.

**Comment by hwillson** [comment]
Just re-capping the decision from our call - I'll document the potential issue mentioned in https://github.com/meteor/meteor/pull/9632#issuecomment-367372629, along with the Mongo repair fix, in the `History.md`. We should then be all set to get this merged. Updates coming shortly - thanks!

**Comment by hwillson** [comment]
This should now be ready for a new dev_bundle build/deploy (removing WIP). Thanks!

**Comment by abernix** [comment]
@hwillson I've re-published dev bundle `9999.9632.1` and the non-Windows tests passed, but I've just fixed the "merge conflict" so that AppVeyor will run.

**Comment by abernix** [comment]
Merged to `devel` as 39030204a9429f931999ccfed310f9fb77309c1c.

**Comment by bjarketrux** [comment]
> Mongo 3.6 will work with 2.x versions of the Mongo Node driver.

**Note:** According to this page [Node.js Driver Compatibility](https://docs.mongodb.com/ecosystem/drivers/driver-compatibility-reference/#node-js-driver-compatibility) MongoDB 3.6 is only compatible with Node.js Driver >= 3.0.

I havn't investigated further.

**Comment by glasser** [comment]
@bjarketrux I believe that this means that not all features of MongoDB 3.6 are supported by the 2.x driver, but it doesn't like completely break.

**Pull request closed without merging**
