### PR TITLE
Release 3.0

### PR DESCRIPTION
**Pull request by denihs**
# Still in development
Current released version: ``3.0.1``
To use it, please do a 
```bash
meteor update --release 3.0.1
```
you can also use the following command to install meteor RC

```bash
npx meteor@rc
```
## Highlights
TODO
See more in the [milestones](https://github.com/meteor/meteor/milestone/101).

Preview docs: https://v3-docs.meteor.com/

## Maintainers checklist
- [x] address comments from old [PR](https://github.com/meteor/meteor/pull/12359)

⚠️⚠️⚠️ You can follow the updates on [What's left until an official Meteor 3.0? Discussion](https://github.com/meteor/meteor/discussions/12865)

_[old pr](https://github.com/meteor/meteor/pull/12359)_

### CODE REVIEW

**Comment by leonardoventurini** [comment]
Behold, all things shall be made new 😄

**Comment by StorytellerCZ** [comment]
Got a new error that I haven't encountered before. Could be possibly still something unmigrated in my code, but want to share it just in case someone notices something:
```
=> Linted your app. No linting errors.
=> Client modified -- refreshing
<--- Last few GCs --->

[606134:0x74410c0]   777453 ms: Mark-Compact 4038.1 (4140.3) -> 4024.6 (4142.8) MB, 1480.04 / 0.67 ms  (average mu = 0.304, current mu = 0.024) allocation failure; scavenge might not succeed
[606134:0x74410c0]   779455 ms: Mark-Compact 4040.7 (4142.8) -> 4027.4 (4145.6) MB, 1964.81 / 0.59 ms  (average mu = 0.160, current mu = 0.018) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 0xb84bd6 node::OOMErrorHandler(char const*, v8::OOMDetails const&) [/home/storyteller/.meteor/packages/meteor-tool/.3.0.0-rc.3.12uwtpz.10ey++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
 2: 0xefec30 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/home/storyteller/.meteor/packages/meteor-tool/.3.0.0-rc.3.12uwtpz.10ey++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
 3: 0xefef17 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/home/storyteller/.meteor/packages/meteor-tool/.3.0.0-rc.3.12uwtpz.10ey++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
 4: 0x1110925  [/home/storyteller/.meteor/packages/meteor-tool/.3.0.0-rc.3.12uwtpz.10ey++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
 5: 0x11287a8 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/storyteller/.meteor/packages/meteor-tool/.3.0.0-rc.3.12uwtpz.10ey++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
 6: 0x10fe8c1 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/home/storyteller/.meteor/packages/meteor-tool/.3.0.0-rc.3.12uwtpz.10ey++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
 7: 0x10ffa55 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/home/storyteller/.meteor/packages/meteor-tool/.3.0.0-rc.3.12uwtpz.10ey++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
 8: 0x10dd0a6 v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/home/storyteller/.meteor/packages/meteor-tool/.3.0.0-rc.3.12uwtpz.10ey++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
 9: 0x1537e36 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/home/storyteller/.meteor/packages/meteor-tool/.3.0.0-rc.3.12uwtpz.10ey++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
10: 0x759505ed9ef6 
Aborted (core dumped)
```

**Comment by leonardoventurini** [comment]
> Got a new error that I haven't encountered before. Could be possibly still something unmigrated in my code, but want to share it just in case someone notices something:
> 
> ```
> => Linted your app. No linting errors.
> => Client modified -- refreshing
> <--- Last few GCs --->
> 
> [606134:0x74410c0]   777453 ms: Mark-Compact 4038.1 (4140.3) -> 4024.6 (4142.8) MB, 1480.04 / 0.67 ms  (average mu = 0.304, current mu = 0.024) allocation failure; scavenge might not succeed
> [606134:0x74410c0]   779455 ms: Mark-Compact 4040.7 (4142.8) -> 4027.4 (4145.6) MB, 1964.81 / 0.59 ms  (average mu = 0.160, current mu = 0.018) allocation failure; scavenge might not succeed
> 
> 
> <--- JS stacktrace --->
> 
> FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
> ----- Native stack trace -----
> 
>  1: 0xb84bd6 node::OOMErrorHandler(char const*, v8::OOMDetails const&) [/home/storyteller/.meteor/packages/meteor-tool/.3.0.0-rc.3.12uwtpz.10ey++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
>  2: 0xefec30 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/home/storyteller/.meteor/packages/meteor-tool/.3.0.0-rc.3.12uwtpz.10ey++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
>  3: 0xefef17 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/home/storyteller/.meteor/packages/meteor-tool/.3.0.0-rc.3.12uwtpz.10ey++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
>  4: 0x1110925  [/home/storyteller/.meteor/packages/meteor-tool/.3.0.0-rc.3.12uwtpz.10ey++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
>  5: 0x11287a8 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/storyteller/.meteor/packages/meteor-tool/.3.0.0-rc.3.12uwtpz.10ey++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
>  6: 0x10fe8c1 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/home/storyteller/.meteor/packages/meteor-tool/.3.0.0-rc.3.12uwtpz.10ey++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
>  7: 0x10ffa55 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/home/storyteller/.meteor/packages/meteor-tool/.3.0.0-rc.3.12uwtpz.10ey++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
>  8: 0x10dd0a6 v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/home/storyteller/.meteor/packages/meteor-tool/.3.0.0-rc.3.12uwtpz.10ey++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
>  9: 0x1537e36 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/home/storyteller/.meteor/packages/meteor-tool/.3.0.0-rc.3.12uwtpz.10ey++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
> 10: 0x759505ed9ef6 
> Aborted (core dumped)
> ```

I've seen this before when using `lru-cache@10.2.2` and using the wrong options. I checked and the options are all correct at a first glance and we had reverted to `lru-cache@6.0.0`.

**Comment by StorytellerCZ** [comment]
@denihs seems to me that not all packages got published properly. Getting resolutions errors when trying to publish package for Meteor 3 and on projects that were all set when it came to package versions. Here is one sample:

image

The correct end resolution of `meteor` should be v2.0.0.

**Comment by StorytellerCZ** [comment]
Looks like `ddp-common` v1.4.1 was published back in May for Meteor 2.16, so the correct version here should be at least 1.5.

**Comment by StorytellerCZ** [comment]
Still having issue with `facebook-oauth`:

```
* meteor@2.0.0 <- oauth 3.0.0 <- bozhao:link-accounts 3.0.0-rc.0
* meteor@1.11.4 <- facebook-oauth 1.11.3 <- accounts-facebook 1.3.4
```

**Comment by StorytellerCZ** [comment]
So I have run `meteor update` from my rc.8 app and got many of the packages updated to their release versions, then I run `meteor update --release 3.0-rc.10` and it updated the following packages:
```
accounts-facebook  upgraded from 1.3.4-rc300.8 to 1.3.4-rc300.10
facebook-oauth     upgraded from 1.11.3-rc300.8 to 1.11.3-rc300.10
```
So at least from my perspective those two still need to be manually updated.

**Comment by StorytellerCZ** [comment]
Managed to upgrade without problem to v3.0.1!

**Comment by denihs** [comment]
I'm now merging this to `master` and `devel` :tada: These two branches are now v3. We pinned the current state of version 2 on a branch called `2.x.x`.

**Pull request merged**
