### PR TITLE
Upgrade to Babel 7

### PR DESCRIPTION
**Pull request by benjamn**
Specifically, [Babel 7.0.0-beta.0](https://github.com/babel/babel/releases/tag/v7.0.0-beta.0).

Notable changes: https://babeljs.io/blog/2017/03/01/upgrade-to-babel-7

Apologies for the terse PR description; more information (and commits) to come!

### CODE REVIEW

**Comment by benjamn** [comment]
@GeoffreyBooth Not really! It's been a fairly smooth upgrade, with some minor details hidden behind the `meteor-babel` abstraction. I don't anticipate any relevant changes for `coffeescript`.

**Comment by GeoffreyBooth** [comment]
@benjamn Cool. Also did you see https://github.com/meteor/meteor/pull/6691#issuecomment-328368513? I’m wondering why the Meteor side is merging source maps, when we could be using [Babel’s `inputSourceMap`](https://github.com/babel/babel/issues/827#issuecomment-77573107).

**Comment by benjamn** [comment]
@klaussner I seem to remember you found problems with Babel's `options.inputSourceMap` (https://github.com/meteor/babel/commit/41a5514316115fbfd8710ade19e651b62cdb9358). Do you remember what the issue was, and whether it might be relevant to https://github.com/meteor/meteor/pull/6691#issuecomment-328368513?

**Comment by benjamn** [comment]
Summary of hurdles I encountered during this upgrade:
* https://github.com/babel/babel/pull/6213
* [The classes transform](https://www.npmjs.com/package/babel-plugin-transform-es2015-classes) no longer inserts `classCallCheck` in “loose” mode.
* https://github.com/meteor/babel/commit/058d3a8cbeb38faa219f9b0b54b8359b7159e35d
* https://github.com/meteor/babel/commit/9ba96f96b2519fe99677f02e2b87d2a3ef5c60c2
* https://github.com/meteor/babel/commit/8b8eb1c9a2e35490f1fe9c193547615261628a28

**Pull request merged**
