### PR TITLE
Hint adding packages at build time.

### PR DESCRIPTION
**Pull request by laosb**
#6763 Origin PR
#6826 Related Issue

This pr do it at build time.

### CODE REVIEW

**Comment by tmeasday** [comment]
@benjamn I think you should probably look at this one

**Comment by laosb** [comment]
@benjamn

**Comment by abernix** [comment]
This doesn't seem to be working as you intended right now.  Currently the PR spits out warnings about adding core packages (which are installed) on a brand new `meteor create`:
```
~/Dev/Misc/meteor-tests $ mymeteor create funfun7110
~/Dev/Misc/meteor-tests $ cd funfun7110/
~/Dev/Misc/meteor-tests/funfun7110 $ mymeteor npm install
~/Dev/Misc/meteor-tests/funfun7110 $ mymeteor -p 3400
[[[[[ ~/Dev/Misc/meteor-tests/funfun7110 ]]]]]

=> Started proxy.
=> Started MongoDB.

Unable to resolve some modules:

  templating wasn't installed
  "meteor/templating" in /Users/jesse/Dev/Misc/meteor-tests/funfun7110/client/main.js (web.browser)
  reactive-var wasn't installed
  "meteor/reactive-var" in /Users/jesse/Dev/Misc/meteor-tests/funfun7110/client/main.js (web.browser)

Looks like you imported some packages wasn't installed.
Consider running:

  meteor add templating reactive-var

If you notice problems related to these missing modules, consider running:

  meteor npm install --save meteor


Unable to resolve some modules:

  meteor wasn't installed
  "meteor/meteor" in /Users/jesse/Dev/Misc/meteor-tests/funfun7110/server/main.js (os.osx.x86_64)

Looks like you imported some packages wasn't installed.
Consider running:

  meteor add meteor

If you notice problems related to these missing modules, consider running:

  meteor npm install --save meteor

=> Started your app.

=> App running at: http://localhost:3400/
```

**Comment by laosb** [comment]
So we need to verify whether the package is installed or not actually.

**Comment by laosb** [comment]
No wonder meteor packages' "misssing" is ignored previously!

**Comment by abernix** [comment]
@laosb Any progress on this PR?  Otherwise we should close it until it's ready to be reviewed again.

**Comment by laosb** [comment]
I'll close this as I have no time dealing with this PR currently.

**Comment by abernix** [comment]
Original issue is still open so it won't be completely forgotten. :wink:

**Pull request closed without merging**
