### PR TITLE
Bumping sockjs-node to 0.3.19

### PR DESCRIPTION
**Pull request by mitar**
New version has just been released which passes some useful headers on to the server from client. (Personally, I need DNT header.)

Also, I noticed that this file has been forked in the past and a relatively old version is being used. Probably it should be updated at some point as well: https://github.com/meteor/meteor/blob/devel/packages/ddp-client/sockjs-0.3.4.js

### CODE REVIEW

**Comment by benjamn** [comment]
Can you update the client version as well, and perhaps just use `Npm.depends` instead of copying the file, and then also update the `.npm/package/npm-shrinkwrap.json` files for these packages, by running `meteor test-packages`?

Even if you don't have time for that, thanks for pointing out this upgrade!

**Comment by mitar** [comment]
So there are quiet some changes in the copied file. This is why I haven't yet done this.

Somebody should go through those changes (hopefully all are marked) and check if they are still necessary. It might be that upstream fixed it. (Also, ideally, we should probably submit changes upstream.)

**Comment by hwillson** [comment]
Just to add - this was attempted a while back via https://github.com/meteor/meteor/issues/4114, where it was noticed that the newer version (at the time) was significantly larger. Just something to keep in mind.

**Comment by hwillson** [comment]
This is also related to https://github.com/meteor/meteor/issues/8254 (upgrading the sockjs client will address that issue as well).

**Comment by hwillson** [comment]
@mitar We discussed this PR in our issue review meeting yesterday. Ideally both the client and server libraries would be updated together. As you mentioned, updating the client library will take more work due to Meteor's specific sockjs code changes (a lot of which have been accepted upstream, but someone will need to verify if any of the custom changes are still needed). Putting that aside, if we decided to update just the server library for now, do you know if it's compatible with the old client version of sockjs Meteor is using (which is a custom modified version of 0.3.4)? If `sockjs-node` 0.3.19 and Meteor's custom client sockjs version have been tested and are verified to work together, then we might proceed with merging this. Again though updating the client at the same time would be preferred - if anyone else reading this has time and is interested in helping out on updating the sockjs client library, please chime in! 🙂

**Comment by abernix** [comment]
Since `sockjs-node` is used only to provide the endpoint (internally, the [`StreamServer`](https://github.com/meteor/meteor/blob/35e70fd23d949a2b08bad86a62e9c131ef5a3509/packages/ddp-server/livedata_server.js) for the client to connect to, be it SockJS, WebSocket, or otherwise, this seems worthwhile to merge this as is, even with the outstanding possibility of also updating SockJS on the client, or even not including it at all.

I'll merge this and release new `ddp-server` versions for both 1.5.x and 1.6, since they have separate minor versions.  I'll also update and commit the `npm-shrinkwrap.json` which is necessary when bumping a npm (otherwise it would be updated at run-time by every consumer).

**Pull request merged**
