### PR TITLE
Better duplicate error checks for insertUserDoc

### PR DESCRIPTION
**Pull request by zimme**
Check the error code and just search for "email.address" or "username" in error message.

Tested with wiredTiger on mongo 3.0.3 and mmapv1 on mongo 2.6.7, which is Meteor 1.1.0.2 default db.

#4368

### CODE REVIEW

**Comment by ekatek** [comment]
(see comments on commit)

**Comment by zimme** [comment]
Do I need to test this with more versions of mongodb?

**Comment by zimme** [comment]
I think the work with case insensitive email matching in 3790e09 is "over-shaddowing" this problem if you use the accounts-password package, keep that in mind when testing.

**Comment by zimme** [comment]
@Slava, sry to ping you but you were active in the issue discussion. Do you know If i need to test with more versions of mongo?

**Comment by zimme** [comment]
@ekatek, is it possible this is being merged before 1.2?

**Comment by zimme** [comment]
@stubailo, I've tried getting some kind of response from the people involved in this PR from the start, but it's not going so well. I know that you're all busy doing some other awesome stuff somewhere :stuck_out_tongue:, but this is a pretty small fix and from what I've tested it works with mongo 2.4, 2.6, 3.0+ with both wiredTiger and mmap engines.

Without this it's not very nice to use wiredTiger as when you get a duplicate entry in the users collection you just get an unhandled exception and get Internal Server Error client side.

**Comment by stubailo** [comment]
@zimme do you have a unit test (test-packages) for this?

I've built a script that runs unit tests against three versions of Mongo at once, so I should be able to conclusively determine if it works in all versions.

**Comment by stubailo** [comment]
Here's the script, BTW: https://github.com/meteor/meteor/blob/devel/scripts/admin/test-packages-with-mongo-versions.rb

**Comment by zimme** [comment]
I've updated the tests to check for specific errors thrown.

I've run the script for testing against all 3 versions of MongoDB and the `'accounts - insertUserDoc username'` and `accounts - insertUserDoc email'` tests passes.

From what I can tell of these tests they should be enough to test the duplicate index exception thrown.

cc @stubailo

**Comment by stubailo** [comment]
This is merged now: https://github.com/meteor/meteor/commit/9fbea207d350334499e4218ff82c5928aa8dd0a9

**Pull request closed without merging**
