### PR TITLE
Include a new "devtools" package in the Meteor skeleton

### PR DESCRIPTION
**Pull request by mquandalle**
There has been a lot of discussions in the JavaScript community about how hard it is to set up a project correctly in our constantly evolving environment. In this ecosystem Meteor has always stood as a developer friendly platform to build JavaScript applications, and I believe there is an opportunity to work more in this direction.

I propose to add a package called `"debugger"` (we could find a better name) that consists of a set of tools activated in development mode only. It currently only contains the [simple:dev-error-overlay](https://atmospherejs.com/simple/dev-error-overlay) package developed by @stubailo, but in the future it could include other tools for things like type checking, hot reloading, state inspectors, etc. as these tools emerge and mature as community packages.

### CODE REVIEW

**Comment by stubailo** [comment]
I'd say it should either be called "developer-experience" or maybe just be all the packages individually. But I agree having these by default could be a nice advantage and show that meteor cares about developer experience more than almost anyone else.

**Comment by laosb** [comment]
Sounds sweet. But is it quite right to imply a **community** package in a **core** package?

**Comment by stubailo** [comment]
> is it quite right to imply a community package in a core package

I think we should start doing this more - there are a lot of community packages that are pretty essential to the Meteor experience, especially in the realm of testing. Don't have an opinion about my particular package, though.

**Comment by mquandalle** [comment]
I considered the name “developer-experience” but that sounds confusing given the parallel with “mobile-experience” which is a very different kind of package, runtime instead of build-time. Also I think it would be a bit strange to “remove developer-experience” if for some reason someone want to remove this package :-)

I propose the name “devtools”.

**Comment by stubailo** [comment]
Hmm, personally I think basically everyone should have `hot-code-push`, while the dev error overlay is a lot less universal.

Plus, hot code push actually runs in production as well!

I'd rather just add each package individually.

**Comment by laosb** [comment]
Maybe we should just mention these great packages in our Guide.
Or if we have this package, `devtool` is actually a great name.

**Comment by stubailo** [comment]
Yeah I'd be in favor of a guide article about development tools like debugging, version control, etc.

**Comment by tmeasday** [comment]
I think this should be a community package @mquandalle. (The guide article would be awesome!)

**Pull request closed without merging**
