### PR TITLE
Removing colons conversion

### PR DESCRIPTION
**Pull request by mitar**
This is probably not a correct fix, but it fixes things for me on Linux for https://github.com/meteor/meteor/issues/7675.

### CODE REVIEW

**Comment by mitar** [comment]
Or maybe in fact this is the correct fix. If paths on the file system can contain `:`, so existing paths contain them, then we should just keep them around.

BTW, how do people put packages into `packages` on Windows, if they contain `:`?

**Comment by KoenLav** [comment]
@mitar the name of the directory in packages does not define the name Meteor will recognize (rather the name listed in the package.js).

I do however agree that Meteor should be able to handle this case, as I expect many more expect the directory name to be related.

**Comment by mitar** [comment]
You are saying that I can put `foo:bar` package into `packages/something` and Meteor will detect this and use this `foo:bar` package when I do `meteor add foo:bar`? I have not seen this being the case.

**Comment by copleykj** [comment]
Correct

**Comment by KoenLav** [comment]
Exactly, nevertheless I think Meteor should be able to handle colons in directory names (if this is supported on various platforms).

**Comment by benjamn** [comment]
The way we handle colons currently is important for Windows support, and not something we are likely to change without extensive tests and validation from Windows developers.

**Comment by mitar** [comment]
Sure, but currently #7675 does not work on Linux. :-) So the question is, what to do there?

**Pull request closed without merging**
