### PR TITLE
Added an index for the users collection

### PR DESCRIPTION
**Pull request by elie222**
An example of a slow query that was slowing down my entire database that this PR should fix:

```
query wc_draft.users query: { $or: [ { services.password.reset.when: { $lt: new Date(1481501706951) } }, { services.password.reset.when: { $lt: 1481501706951.0 } } ] } plan
Summary: COLLSCAN ntoreturn:1000 ntoskip:0 nscanned:64642 nscannedObjects:64642 keyUpdates:0 numYields:208 locks(micros) r:1782624 nreturned:0 reslen:20 1028ms
```

See the discussion here:
https://github.com/meteor/meteor/issues/8158#issuecomment-267456752

### CODE REVIEW

**Comment by glasser** [comment]
Did you write that query yourself or is it part of Meteor?

**Comment by abernix** [comment]
That query is from [`expirePasswordToken` in `accounts_server.js`](https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_server.js#L1078-L1091) which I believe would be getting called at an interval in `setExpireTokensInterval`.

**Comment by glasser** [comment]
Ah, yes, looks like the new password reset token expiry feature added in 1.4.1 with https://github.com/meteor/meteor/pull/7534 should have included an index.

I do agree that #8084 suggests that indexes under arrays should be avoided, though.  The login token issue in #8084 is more likely to arise accidentally than with reset tokens but it does create a DOS risk anyway.

**Comment by elie222** [comment]
There are other problematic queries on the users collection too.

This is another one:

query: { services.accessTokens.tokens: { $exists: true, $ne: [] } }
planSummary: COLLSCAN ntoreturn:1000 ntoskip:0 nscanned:64690
nscannedObjects:64690 keyUpdates:0 numYields:1095 locks(micros)
r:3539650 nreturned:0 reslen:20 2785ms

**Comment by abernix** [comment]
@elie222 Any updates on this?  Do you think [`sparse`](https://docs.mongodb.com/manual/core/index-sparse/) is appropriate for this?

**Comment by elie222** [comment]
Yes, I think so.

**Comment by abernix** [comment]
Thanks, @laosb.  LGTM.

**Comment by glasser** [comment]
Hmm, I think this index should be added in the same package that does the query: the query is in accounts-base but the index is in accounts-password.

If you use accounts-base but not accounts-password, the interval is still going to exist but it's going to be doing an unindexed query, which is bad.

I'm not really sure I understand why this code is in accounts-base at all; it seems like it would make much more sense to have it in accounts-password, but in any case the index should be in the same place as the interval.

**Comment by glasser** [comment]
(I suppose you could also use weak dependencies or something to allow accounts-base to only run that code if accounts-password is installed, but I really don't get why it can't just be in accounts-password.)

**Comment by abernix** [comment]
@glasser I think your confusion about why this isn't in [`accounts_password`](https://github.com/meteor/meteor/tree/devel/packages/accounts-password) is warranted.  This particular issue didn't rectify the already mis-placed code, but this stems from in https://github.com/meteor/meteor/pull/7534, which put it there in the first place.

I've opened #8448 to track this.  Thanks!

**Comment by liitfr** [comment]
Hi team !
First of, thanks for your awesome work !

I've just tried Robo3T - a mongo client on my current project.  
Looks like Robo3T throws a   

> Cannot load list of indexes.
> 
> Error:
> Wrong type for field (sparse) int != 8

when I want to list user's indexes. If I drop all indexes and re-create all of them this way :

```
[
...
    {
        "v" : 1,
        "unique" : true,
        "key" : {
            "username" : 1
        },
        "name" : "username_1",
        "ns" : "meteor.users",
        "sparse" : true
    }
...
]
```

Then it works.  
Well, it's maybe not significant, but it looks like `sparse` should equal `true`, not `1` (mongo documentation uses `true` as well)

I'm a noob. Maybe it's not relevant & it's just that Robo3T is somehow too much strict ...
But it could worth this little change ...
  
Cheers & thanks again

**Comment by abernix** [comment]
@liitfr The message `Wrong type for field (sparse) int != 8` seems like an error from Robo3T.  Perhaps you could, using the regular `mongo` shell (available in Meteor with `meteor mongo` from the app root directory) show the output of `db.users.getIndexes()` before and after your changes and also include the Meteor and MongoDB version you're using?

**Pull request merged**
