### PR TITLE
[Meteor 3] Fix Meteor.subscribe() regression

### PR DESCRIPTION
**Pull request by denihs**
Issue reported on https://github.com/meteor/meteor/issues/13212.

As @radekmie [said](https://github.com/meteor/meteor/issues/13212#issuecomment-2212465898), the message order for subscriptions is inverted between Meteor 2 and 3.

In version 2, the order is: `sub` -> `unsub`. But in version 3, we have: `unsub` -> `sub`. Thus, the issue.

I narrowed it down to our new [queue system](https://github.com/meteor/meteor/blob/fd02bca8fcc857a2350b32d8c33e66fdb6288f3f/packages/ddp-client/client/queueStubsHelpers.js#L226-L240). Now in version 3 when we call Meteor.subscribe() we always [queue](https://github.com/meteor/meteor/blob/fd02bca8fcc857a2350b32d8c33e66fdb6288f3f/packages/ddp-client/client/queueStubsHelpers.js#L218-L223) the `Connection.send` method calls.

But we do not do this for the `subscription.[id].stop()`.

That's the issue. Even though we send the `sub` message before the `unsub`, the `unsub` message is sent before the `sub` message https://github.com/meteor/meteor/issues/13212#issuecomment-2212507115. 

To solve this, I've created the method `_sendQueued`, which will always queue the `Connection.send` call before sending the message. Now, when using this inside `subscription.[id].stop()`, we get the calls in the correct order:

Screenshot from 2024-07-09 08-53-23

(Descending Order)
image

Before merging this PR, we need to ensure some things:

- [x] This is the right strategy
- [x] All tests are passing
- [x] Create new tests for this method

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
As for right strategy, from my experience it is the correct one to prevent unnecessary re-renders on the client side if the subscription changes, but not the underlying data. It also saves the network traffic.

**Comment by zodern** [comment]
Queueing the unsubscribe is the right approach.

**Review by radekmie — APPROVED** [review]

**Review by leonardoventurini — APPROVED** [review]

**Review by nachocodoner — APPROVED** [review]

**Comment by JorgenVatle** [comment]
This might just be due to my application structure, but it appears that the changes introduced here can cause some inconsistent behavior with subscriptions. 

In Meteor v2 and the v3 release candidates the first DDP messages emitted are those from Meteor's core packages. Usually `connect` and `login` immediately following. After upgrading to v3.0.1 it seems user-defined subscription calls sometimes emit before the authentication calls. 

In my case this leads most subscriptions being rejected on first page load where they remain in a non-ready state until manually re-triggered after the login/resume calls have completed.

#### Meteor v3.0.1:
image


#### Meteor v3.0.0-rc.4 and earlier:
image

**Comment by brianlukoff** [comment]
We're seeing the same thing, which is causing problems on reconnect -- essentially, upon reconnect, previously logged-in users get redirected away from their page because they are temporarily seen as being logged out (since the subscriptions before `login` fail). They are eventually logged in and a page refresh fixes the problem but not an ideal UX.

**Pull request merged**
