### PR TITLE
Increase circleci timeout and disable spinner for CI tests

### PR DESCRIPTION
**Pull request by abernix**
Trying to see if re-enabling the `--headless` spinner that Ben put in place will work if combined with a longer timeout for CircleCI.

...about to find out.

### CODE REVIEW

**Comment by abernix** [comment]
This worked well – with the exception of the (separate) spinning in the package tests (container 0) the output is significantly more compact on containers 1-7.  The default timeout was 600 on CircleCI – this first test raised it to 1800.  Going to split the difference with 1200 and see how that goes.

**Comment by abernix** [comment]
1200 seconds works!  ✅

I'm not going to bother trying less than that at the moment.  I'd say this is a huge improvement already since it at least provides readable logs for 7/8 containers.  The next step would be making a similar `--headless` flag work with `test-packages`.

**Comment by benjamn** [comment]
I agree this is a huge improvement!

**Comment by benjamn** [comment]
If https://github.com/meteor/meteor/commit/05dfe244382a927fb1284162c3df0d38570a6d2b, I will cherry-pick it onto `devel`.

**Comment by abernix** [comment]
👍 My avoidance to doing this was that CI might *never* end in some bizarre cases? (resulting in queue galore).  Haven't seen runaways yet though, so have another 👍

**Pull request merged**
