### PR TITLE
vNext Cordova Android version is 6.4.0

### PR DESCRIPTION
**Pull request by paulincai**

### CODE REVIEW

**Comment by skirunman** [comment]
Looks like we are not actually using `cordova-android@6.4.0`, but instead this forked and modified version `https://github.com/meteor/cordova-android/tree/v6.4.0-with-pr-417` so might want to add that to history.

// This commit represents cordova-android@6.4.0 plus https://github.com/apache/cordova-android/pull/417

**Comment by paulincai** [comment]
@skirunman I think we're good now.

**Comment by benjamn** [comment]
I don't mind merging this and dealing with any conflicts, but I wanted to mention a similar note has been added on the `release-1.6.1` branch already: https://github.com/meteor/meteor/pull/9274/commits/322cbe8593bb33c36a43a2fd6c56dd72206d6689

**Comment by benjamn** [comment]
Sure, it might be a little easier to close this PR and wait for the official 1.6.1 release to get merged into `master` and `devel` (soon!).

**Comment by benjamn** [comment]
More importantly, please let me know soon if the latest 1.6.1 RCs are (or aren't) working for your Cordova apps!

**Comment by paulincai** [comment]
@benjamn so far so good, I am testing Push notifications in the next 1 hour. I am doing my launch screens now. Meanwhile just to let you know that I opened this: https://github.com/meteor/meteor-feature-requests/issues/255

**Comment by paulincai** [comment]
@benjamn just getting back to you with my findings with rc6. after running production grade apps (deployed with Testfairy) on Android 5.1, Android 7, Ipad Air 1 Retina with IOS 11.2.5, Iphone 6 with IOS 11.2.5.

- Not Meteor related: In general there is some mess up with google-services on Android if you install various plugins that depend on this. For instance I was not able to install the latest phonegap-plugin-push together with the latest cordova-plugin-googleplus Things got too complicated and annoying and I gave up. I reverted back to phonegap-plugin-push@1.10.5 which has a good compatibility with Meteor  RAIX:push and does the job.

- Otherwise, Android is ok, nothing to comment, everything is as expected.

- IOS: Let me avoid the technical terms and give you my experience. I start my Test app, get a splash screen, get the app... amazing. Put the Test app in background or just open something else (Whatsapp etc ) on top. 5 min later I get back to my Test app, I am right where I left it. However, if I get back to it after 10 min, I get the last screen I've had in the web view in my Test app for 2 seconds, and then a start over from splash screen.

This is the same when I use Test app, close it from Home button, switch the phone off and get back to my Test app after a while. Meanwhile there are no updates done to the code and I am connected to a production server in Heroku. 

I tested this particular issue over a day and every single time I get the same result: old view -> splash -> home screen of the app.

The expectation is that after a while I should start the app directly from the splash screen (this is fine in Android).

- Cordova in general: still getting the [facebook plugin issue](https://github.com/meteor/meteor/issues/9548#issue-289376190) . This prevents me from adding some sounds in the Android 'res' folder because every time I build for Android I need to do it right after I delete 'cordova-build' otherwise I get the facebook plugin issue.

**Comment by evolross** [comment]
It's like Clash Royale... everytime you leave that app for two seconds or more you get nailed with the splash screen again! 😝

**Comment by paulincai** [comment]
@evolross not sure I understand. Do you face some issues on one of the mobile platforms?

**Comment by evolross** [comment]
Sorry, it was a joke. I guess you don't play Clash Royale. I probably shouldn't joke in a problem thread. Ignore my comment. No, I don't have this issue you're experiencing.

**Comment by benjamn** [comment]
@paulincai From what I can tell, the iOS background restore problems can be fixed with updates to `cordova-plugin-meteor-webapp` (e.g. https://github.com/meteor/cordova-plugin-meteor-webapp/pull/30), and we can release those updates by publishing a new version of the Meteor `webapp` package at any time, so we don't have to delay Meteor 1.6.1. That's good news from my perspective, though I understand the problems are annoying and need to be fixed soon, regardless of how we do it.

**Comment by paulincai** [comment]
@benjamn was just updating my post above :)) Please come back in 5 min for the latest edit.

**Comment by paulincai** [comment]
@benjamn the only problem I still see is related to Facebook as described above.

**Comment by benjamn** [comment]
@paulincai From what I can tell, the facebook plugin has this problem because it requires `APP_ID` and `APP_NAME` to be configured in `mobile-config.js`, and just because `App.configurePlugin("cordova-plugin-facebook4", ...)` is present in `mobile-config.js`, Cordova assumes the plugin must be installed, so it tries to uninstall it when rebuilding, and fails because the uninstall operation can't handle the possibility that the plugin isn't actually installed (that is, `.meteor/local/cordova-build/plugins/cordova-plugin-facebook4` does not exist). Clearly, the uninstall operation should be more robust. Not sure how best to fix that, but I'll keep thinking about it.

**Comment by paulincai** [comment]
@benjamn things got a little bit more complex now with the evolution of some other plugins. Push plugin (> 2.0.0) requires some configurations with local files and custom gradle files ... it is becoming really difficult to do anything on the Android side having to remove the cordova android project before every rebuild. Push on its own needs some debugging to do with Android 7 and 8 and 8.1 and starting from scratch every single time has become unbearable. I feel that (to me) building the Android App takes as much as everything else together.

**Pull request closed without merging**
