### PR TITLE
not working meteor-include replaced

### PR DESCRIPTION
**Pull request by sclausen**
As described in #5250 the simple-todos-angular example has two issues. First, the ng-include in the body tag doesn't work properly, as described in #5232. Workarounds have been discussed [here](https://github.com/Urigo/angular-meteor/issues/702) and second, the `<meteor-include src="loginButtons"></meteor-include>` doesn't work. As @gjr-qm described, the solution for the last issue would be as follows: add the package `urigo:angular-blaze-template` and replace 
``` html
<meteor-include src="loginButtons"></meteor-include>
```
with
``` html
<blaze-template name="loginButtons"></blaze-template>
```
After thins changes and if #5232 is fixed, the simple-todos-angular example will work.

### CODE REVIEW

**Comment by rgoomar** [comment]
@Urigo Is this fix fine? The Angular tutorial is currently unusable and this fixes the problem.

**Comment by Urigo** [comment]
@sclausen @rgoomar  thanks for the valuable feedback!
I have fixed and updated the tutorial.
Hopefully it will be deployed soon.

**Comment by Urigo** [comment]
The updated tutorial is now deployed.
Thank you so much

**Comment by avital** [comment]
Happy to see that this was resolved!

**Pull request closed without merging**
