### PR TITLE
Minimongo support $eq operator (#4142).

### PR DESCRIPTION
**Pull request by ryneeverett**

### CODE REVIEW

**Comment by glasser** [comment]
Thanks for the pull request!  I definitely want us to support `$eq` in minimongo.

However, `canBecomeTrueByModifier` absolutely has to always return true in any case where the modifier can make the selector true.  It's OK if it sometimes returns true unnecessarily, but not if it returns false unnecessarily — oplog tailing depends on this for correctness!  So until that's fixed, we can't take this PR.

Good catch on the `'$ne'` typo.  Since that's a separate issue, maybe submit it as its own PR, ideally with tests that show the difference in behavior that the fix provides?

**Comment by ryneeverett** [comment]
I'm assuming you're referring to the lines:

```js
    // XXX this test should be T, but it is not implemented yet
    F({ a: { $eq: { x: 5 } } }, { $set: { 'a.x': 5 } }, "set of $eq");
```

Which I assumed would fail for the same reason as the existing lines:

```js
    // XXX this test should be F, but it is not implemented yet
    T({ a: { $ne: { x: 5 } } }, { $set: { 'a.x': 5 } }, "set of $ne");
```

I didn't really dig into the reason for this, but basically this `$set` equality issue needs to be resolved prior to #4142? Is there an open issue for it?

**Comment by glasser** [comment]
So, this function is used for an optimization in oplog tailing.  When the oplog says "hey, this modification happened in the database, but I'm not yet telling you the full context of the changed object", the oplog tailing code needs to be able to figure out if it cares for a given selector.

If this function says it should care, then it goes and queries the database, and does some work.  If the function says it should not care, then it ignores the change.

It's OK (though not ideal) for the function to return true even if the modifier cannot make the selector be true; it'll cause some extra work to be done, but the answers will still be correct.

It is unacceptable for the function to return false (to say "don't worry about this change, it's irrelevant to you") when the change actually is relevant.

**Comment by ryneeverett** [comment]
Beautiful explanation. It's a shame it will be buried in the unmarked tomb of PR comments.

I added a commit that causes `operatorBranchedMaster` to flip the `_isSimple` flag to `true` for the `$eq` just like it does for `$ne`. I hope that's acceptable (though not ideal).

**Comment by tmeasday** [comment]
Thanks again @ryneeverett, sorry this took so long, I made one final commit and I'll merge here: https://github.com/meteor/meteor/pull/7080

**Pull request closed without merging**
