### PR TITLE
Release 1.5.1

### PR DESCRIPTION
**Pull request by benjamn**
Thanks to an extended testing process, Meteor 1.5 was one of the least buggy major releases we've ever put out. Meteor 1.5.1 will therefore be mostly about fixing a few minor bugs, as well as collecting various improvements since Meteor 1.5.

As with previous Meteor beta testing cycles, whenever you see a commit added to this pull request with a message like `Bump package versions for 1.5.1-rc.n release.`, that means you can run `meteor update --release 1.5.1-rc.n` to update an existing app to the new version, or `meteor create --release 1.5.1-rc.n your-new-app` to create a fresh Meteor 1.5.1 (~beta~ release candidate!) app.

### CODE REVIEW

**Comment by mjmasn** [comment]
@benjamn 
> Inline process.env.NODE_ENV when minifying with UglifyJS or Babili 

Does this resolve the React-always-being-in-development-mode issue?

**Comment by stubailo** [comment]
Yes!

**Comment by vlasky** [comment]
@benjamn have you considered merging https://github.com/meteor/meteor/pull/8702 (Support for UNIX sockets)? It was given the milestone Release 1.5.1.

We have been using the code in https://github.com/meteor/meteor/commit/d9e7f8672b62217d69056c37ae6e00fe412cffb3, created following @abernix's review, in production without any issues.

**Comment by abernix** [comment]
@vlasky I will look into getting that included today!

**Comment by benjamn** [comment]
Although I'd love to keep adding to this pull request until the end of time, I think we should get that Node 4.8.4 security update out sooner rather than later, so I'm going to finalize 1.5.1 today, unless there are objections. And even if there are objections, there's always 1.5.2!

**Comment by p3pp8** [comment]
Just updated to 1.5.1, everything seems to be fine! Thanx Ben, thanx to everyone who work to thiz great project!!!

**Pull request merged**
