### PR TITLE
fix(ejson): fix equals check with Arrays

### PR DESCRIPTION
**Pull request by jankapunkt**
Fixes issue #11864

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
I think this should be released as a patch.

**Comment by filipenevola** [comment]
@jankapunkt thank you for this.

I would like to see at least one new test validating this fix, is this possible?

**Comment by jankapunkt** [comment]
Hey @filipenevola yes I can add a test or two, of course

**Comment by jankapunkt** [comment]
@filipenevola I added few tests

**Pull request merged**
