### PR TITLE
Update email dependencies

### PR DESCRIPTION
**Pull request by StorytellerCZ**
Updated dependencies of the `email` package and bumped the version to 1.3. The tests ran fine (though more testing is always encouraged). From the [changelog](https://github.com/nodemailer/nodemailer/blob/master/CHANGELOG.md) the biggest change is dropping support for Node bellow v6 (we had here a special version that supported Node v4) and various fixes and improvements.

TODO:
- [x] Update doc

### CODE REVIEW

**Comment by afrokick** [comment]
> 5.0.0 2018-12-28
>Start using dns.resolve() instead of dns.lookup() for resolving SMTP hostnames. Might be breaking change on some environments so upgrade with care

**Comment by StorytellerCZ** [comment]
@afrokick Good point, so major version bump then to be on the safe side?

**Comment by filipenevola** [comment]
hi @StorytellerCZ can you please add this possible breaking change to History.md breaking changes section?

**Comment by StorytellerCZ** [comment]
@filipenevola Done!

**Comment by StorytellerCZ** [comment]
Since we are doing 2.0.0 version I'm also thinking that it might be a good time to make the send hook public. Thoughts?

**Comment by filipenevola** [comment]
@StorytellerCZ it's up to you 😄

**Comment by StorytellerCZ** [comment]
I'll do it. It can actually be pretty useful if you want to send emails via an api or use some other custom stuff instead of `smtps`.

**Pull request merged**
