### PR TITLE
Cordova5 update

### PR DESCRIPTION
**Pull request by copleykj**

### CODE REVIEW

**Comment by particle4dev** [comment]
+1

**Comment by copleykj** [comment]
Has anyone else manually tested this.. It seems I'm getting a white bar across the top of my apps the first time they are loaded but then leaves if I close the app completely and reopen it.. Can anyone else confirm?

**Comment by copleykj** [comment]
Seems the white bar is the status bar from the mobile-status-bar package.. Not sure why it shows up now and didn't before, but calling StatusBar.hide() solves this for me.

**Comment by clayendisk** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  james.ryan.stortz@gmail.com
    Domain clayendisk.net has exceeded the max emails per hour (33/30 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:40774 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by us-tx-cp01.imbahost.com with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1YuOxq-0018F9-2s
	for {}@clayendisk.net; Mon, 18 May 2015 12:36:30 -0500
Date: Mon, 18 May 2015 10:36:32 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1431970592;
	bh=Z3ezoU6E/8p2TVLyQPNZ3omXifEIJXxDxeqBBFIsOsM=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=yz6EriqTJK1rcmFpq8U+KeO08TIbz22FyhDx4Jqv6uvEzkjql8LgbbqSwSHCydUN7
	 ckf3UuDawwZhnI2NXy9VbvTWboNEBUaf/kmygg6G5njnPB6GfJRsUlOImZ2ug3UJvr
	 TZgEHJTsb9Wpk4+yJfyyisi+yRlvkR+Mctoa7m4c=

**Comment by wojtkowiak** [comment]
One remark from me. Using `legacy-whitelist` plugin is not a good way to go. I'd like that we used the new whitelist plugin. It would require to use browser-policy package by default as the whitlelist complains if there is no Content Security Policy.

**Comment by copleykj** [comment]
@wojtkowiak yes, the whitelist plugin would be ideal. I added the legacy-whitelist plugin because it was the way that meteor had already implemented white listing and I wasn't completely comfortable modifying the code that currently generates the access tags.

**Comment by Slava** [comment]
Can somebody explain me what `legacy-whitelist` is and how it is used in this PR?

**Comment by Slava** [comment]
And also, to my knowledge, starting from Cordova 5, the cordova plugins are hosted on npm, how does it work with this PR?

**Comment by copleykj** [comment]
@slava in Cordova 5 they moved the functionality that controls access to outside resources (in Meteor's case App.accessRule) out of the core and into plugins.. The legacy version implements it in the same way that it did previously using <access> tags. This is they way Meteor currently utilizes it which is why I added this version to the webapp package. The non legacy version implements Cordova's new recomendations for limiting access to outside resources. https://github.com/apache/cordova-plugin-whitelist

**Comment by copleykj** [comment]
As for the plugins, as far as I can tell meteor adds the plugins via Cordova, so I'm guessing it fetches them?

**Comment by Slava** [comment]
Oh interesting. Looking at [this announcement](https://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html) they renamed every core plugin and implemented some kind of redirect logic in their fetcher.

**Comment by Slava** [comment]
I tried running the `localmarket` example from this branch and got this:

```
~/w/asdf> curmeteor run android
Error while running for mobile platforms: Error running /Users/imslavko/work/meteor/tools/cordova-scripts/cordova.sh
Error: 404 Not Found: cordova-plugin-console
at RegClient.<anonymous>
(/Users/imslavko/work/meteor/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:304:14)
at Request._callback
(/Users/imslavko/work/meteor/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
at Request.self.callback (/Users/imslavko/work/meteor/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/request.js:236:22)
at Request.emit (events.js:98:17)
at Request.<anonymous> (/Users/imslavko/work/meteor/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/request.js:1142:14)
at Request.emit (events.js:117:20)
at IncomingMessage.<anonymous>
(/Users/imslavko/work/meteor/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/request.js:1096:12)
at IncomingMessage.emit (events.js:117:20)
at _stream_readable.js:944:16
at process._tickCallback (node.js:442:13)


Fetching plugin "cordova-plugin-console@1.0.0" via plugin registry
```

Going to poke around to figure out if it is a fault of this PR or something else.

**Comment by Slava** [comment]
I understand why it happens now, it is because I didn't update my Cordova npm module in my dev_bundle

**Comment by copleykj** [comment]
@slava if you didn't do so you might have to run the scripts to generate
the Dev and Android bundles.

**Comment by Slava** [comment]
Any comments on Crosswalk, @copleykj? Last time I looked at it, it was very hard to compile consistently well on every dev platform people used. What is your experience with it so far?

**Comment by Slava** [comment]
I just tested it locally, the crosswalk package breaks the `todos` example on my machine:

```
BUILD SUCCESSFUL
Total time: 2.535 secs
Built the following apk(s):
    /Users/imslavko/work/asdf/.meteor/local/cordova-build/platforms/android/build/outputs/apk/android-x86-debug.apk
Installing app on emulator...
Using apk: /Users/imslavko/work/asdf/.meteor/local/cordova-build/platforms/android/build/outputs/apk/android-x86-debug.apk
/Users/imslavko/work/asdf/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Failed to launch app on emulator: Failed to install apk to emulator: WARNING: linker: libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.
	pkg: /data/local/tmp/android-x86-debug.apk
Failure [INSTALL_FAILED_CONTAINER_ERROR]
Command finished with error code 8: /Users/imslavko/work/asdf/.meteor/local/cordova-build/platforms/android/cordova/run --emulator
ERROR running one or more of the platforms: Error: /Users/imslavko/work/asdf/.meteor/local/cordova-build/platforms/android/cordova/run: Command failed with exit code 8
You may not have the required environment or OS to run this project
```

**Comment by copleykj** [comment]
@slava it has worked for me on 2 machines but both are Linux distros and I'm sure there are issues that might crop up on Mac or Windows. It has it's own commit though so we can cherry pick around it easily

**Comment by Slava** [comment]
Sure, do you have any understanding how is it working with the on-device server that Meteor ships? https://github.com/meteor/com.meteor.cordova-update Is it replacing or conflicting or it doesn't matter? (I didn't write the Android part, so I don't know)

**Comment by copleykj** [comment]
The way I understand it, it just replaces the default webview with the one crosswalk provides. Essentially  it's just like changing from one browser to the another.

**Comment by Slava** [comment]
Merged to the branch called `cordova5-update`. Merging it soon to devel. From my testing so far, everything works, except for minor broken things related to their transition from Ant to Gradle as the java build tool.

The `crosswalk` package breaks for me on half of the apps I tested, so it is unclear at this point if it is even worth putting into core. I would recommend releasing it separately under your name, @copleykj. This way you can release updates separately from Core.

I am also merging this PR over the current branch, so far everything looks working: https://github.com/meteor/meteor/pull/4229

**Comment by copleykj** [comment]
Thanks @Slava, I really appreciate the time you put into getting this into devel. As for crosswalk that's ok.. Figured since it was such a hugely requested integration I'd see about adding it but if it's not reliable then there's no sense.. I will publish it under my account for anyone to use that can get it working :-P

**Pull request closed without merging**
