### PR TITLE
Release 2.7.2

### PR DESCRIPTION
**Pull request by denihs**
2.7.2 released.

**Highlights**
- New Tailwind skeleton! To test it just run `meteor create --release 2.7.2-rc.0 myapp --tailwind`
- [Re-create index when already exists](https://github.com/meteor/meteor/pull/11995)
- [Fix reading packages installed before Meteor 1.2](https://github.com/meteor/meteor/pull/12010)

Read more in the [Milestone](https://github.com/meteor/meteor/milestone/96).

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
Given that the plan is to add new Tailwing skeleton I will check into updating the existing skeleton's dependencies. We should also consider expanding the default display page to include something more exciting. Especially to showcase the given skeleton functionality.

**Comment by maxpain** [comment]
When it will be released?

**Comment by StorytellerCZ** [comment]
When it is ready.

**Comment by StorytellerCZ** [comment]
Though I think we have enough to get the first beta out, what do you think @denihs ?

**Comment by denihs** [comment]
Yes, I think we have enough. I'll work on a first beta.

**Comment by xet7** [comment]
When I'm trying to upgrade, I get this error: https://github.com/wekan/wekan/pull/4482#issuecomment-1101670685

**Comment by denihs** [comment]
Hi @xet7, yes, we're aware of this, and we're working on it. When we have a working beta, we'll let everyone know.

**Comment by denihs** [comment]
Hi @xet7, you should be able to update your project now.

**Comment by xet7** [comment]
@denihs 

Thanks! Now upgrading did work!

**Comment by denihs** [comment]
2.7.2-beta.0 released and ready to be tested :tada:

**Comment by wreiske** [comment]
I was having this issue today: https://github.com/meteor/meteor/issues/11918

```
[wreiske@bluedev bluehive-admin]$ meteor update --release 2.7.2-rc.0
/home/wreiske/.meteor/packages/meteor-tool/.2.7.2-rc.0.wsm9nc.4x3a++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

RangeError [ERR_OUT_OF_RANGE] [ERR_OUT_OF_RANGE]: The value of "length" is out of range. It must be <= -3. Received 18
    at Object.readSync (fs.js:607:3)
    at /home/wreiske/.meteor/packages/meteor-tool/.2.7.2-rc.0.wsm9nc.4x3a++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/files.ts:1522:23
    at Object.readBufferWithLengthAndOffset (/home/wreiske/.meteor/packages/meteor-tool/.2.7.2-rc.0.wsm9nc.4x3a++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/files.ts:1431:21)
    at /tools/isobuild/unibuild.js:123:26
    at Function.each (/home/wreiske/.meteor/packages/meteor-tool/.2.7.2-rc.0.wsm9nc.4x3a++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1316:7)
    at Function.fromJSON (/tools/isobuild/unibuild.js:120:7)
    at /tools/isobuild/isopack.js:921:33
    at Function.each (/home/wreiske/.meteor/packages/meteor-tool/.2.7.2-rc.0.wsm9nc.4x3a++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1316:7)
    at Isopack._loadUnibuildsFromPath (/tools/isobuild/isopack.js:908:7)
    at /tools/packaging/tropohouse.js:518:21
    at Function.each (/home/wreiske/.meteor/packages/meteor-tool/.2.7.2-rc.0.wsm9nc.4x3a++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1316:7)
    at /tools/packaging/tropohouse.js:517:13
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at /tools/packaging/tropohouse.js:512:22
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at Object.download (/tools/packaging/tropohouse.js:424:20)
    at /tools/packaging/tropohouse.js:597:22
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at exports.Tropohouse.downloadPackagesMissingFromMap (/tools/packaging/tropohouse.js:594:20)
    at /tools/project-context.js:921:25
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at /tools/project-context.js:920:20
    at /tools/packaging/catalog/catalog.js:100:5
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at ProjectContext._downloadMissingPackages (/tools/project-context.js:919:13)
    at /tools/project-context.js:365:9
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:355:18)
    at /tools/project-context.js:347:12
    at Function.run (/home/wreiske/.meteor/packages/meteor-tool/.2.7.2-rc.0.wsm9nc.4x3a++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/tool-env/tools/tool-env/profile.ts:289:14)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:346:13)
    at /tools/cli/commands-packages.js:1722:20
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at Object.main.captureAndExit (/tools/cli/main.js:281:29)
    at maybeUpdateRelease (/tools/cli/commands-packages.js:1721:8)
    at Command.func (/tools/cli/commands-packages.js:1795:29)
    at /tools/cli/main.js:1534:15 {
  code: 'ERR_OUT_OF_RANGE'
}
```

My project is in a weird state now... I'm wondering if other users who have upgraded to 2.7.1 will be stuck in this same state.

**Comment by denihs** [comment]
Hey @wreiske, thank you for reporting this. We're going to take a look and see why this is happening...

**Comment by denihs** [comment]
Meteor 2.7.2 in up :tada:

**Pull request merged**
