### PR TITLE
Silences #2177

### PR DESCRIPTION
**Pull request by RobertLowe**
Silences the annoying "Uncaught SyntaxError: Unexpected token Y"

Cheers

@Slava you want code, you got code, any thoughts on how the user should be informed?: https://github.com/RobertLowe/meteor/blob/b90927bd2c70d0b07c5caa006f8e3289d1935449/packages/ddp-client/sockjs-0.3.4.js#L2027-L2028

:smile:

### CODE REVIEW

**Comment by Slava** [comment]
I think it is a reasonable hack to stop sockjs from throwing exceptions. But the real issue is the UX:

- when a server-side error occurs, there is no way to notice it from the browser
- when sockjs fails, it backs off for too much time, causing the retry time to be postponed for too long, which leads to the developer refreshing the page manually.

I think, even in this solution, it is better to not hard-code the display string in sockjs. That being said, this is a start :)

**Comment by RobertLowe** [comment]
> when a server-side error occurs, there is no way to notice it from the browser

Right, unless we have a 'mini-ddp' like you suggested in #2177. 

Even though the string is presently hardcoded, it still provides from method of detecting a crashed state. Also that string could from from a single source/var/setting, currently "Your app is crashing" is hardcoded in a bunch of [places](https://github.com/meteor/meteor/search?utf8=%E2%9C%93&q=Your+app+is+crashing)

Without the heavier overhead of a 'mini-ddp', we could pass along the state detected [here](https://github.com/meteor/meteor/pull/4639/files#diff-f23e48b45e7069f638988a0b49c9c450R2027)

> when sockjs fails, it backs off for too much time, causing the retry time to be postponed for too long, which leads to the developer refreshing the page manually.

I noticed this as well, at least if we handle with this solution we could potentially lower the retry while the application is in a known crashing state.

Food for though, thanks.

Cheers :smile:

**Comment by Slava** [comment]
Closing this as we are not going to merge it. @anubhav94 is working on an alternative fix for this.

**Comment by RobertLowe** [comment]
@Slava any reference to @anubhav94 fix/discussion?

**Comment by anubhav94** [comment]
Hey @RobertLowe, there is currently no fix / discussion online as of now. I'm still in the early stages of coming up with a solution that will allow users to know of compiler and server side issues within the browser, be able to fix them in their editor and continue developing without having to refresh the page manually.

**Comment by RobertLowe** [comment]
Not directly related to this issue, but closely related @stubailo created [meteor-dev-error-overlay](https://github.com/stubailo/meteor-dev-error-overlay) which tries to provide some feedback when the server is failing by [polling HTTP state](https://github.com/stubailo/meteor-dev-error-overlay/blob/master/dev-error-overlay.js#L21-L22) :+1:

**Comment by kachkaev** [comment]
@RobertLowe [meteor-dev-error-overlay](https://github.com/stubailo/meteor-dev-error-overlay) seems like a nice attempt to make error reporting more informative, but I decided to remove it from my Meteor app shortly after adding. The package triggers calls to the server every seconds (which pollutes the network log) but still does not remove an unclear error message form the console.

Can anyone suggest a way of removing the following in the browser's console log when the server crashes?
```VM1966:2 Uncaught SyntaxError: Unexpected token <```

The message does not confuse me now, but it looks quite unclear at first. Seems like a time-waster that is googled by every new developer. It can be probably easily replaced with something meaningful just with a single `try / catch`. Could anyone from MDG reconsider this issue please?

**Comment by RobertLowe** [comment]
@Slava sorry to beat a dead horse but any thoughts in regards to @kachkaev

Thanks 👍

**Comment by kachkaev** [comment]
@RobertLowe seems like @Slava [left Meteor last year](http://devblog.me/bye-meteor.html). Could anyone else from MDG share their thoughts on this please?

**Comment by RobertLowe** [comment]
Dang, hope he's having a good time at MIT, @stubailo thoughts?

**Pull request closed without merging**
