### PR TITLE
Email package improvements

### PR DESCRIPTION
**Pull request by edemaine**
I've made two changes to the Email package:
1. Using a MAIL_URL of the form `smtp://...:465` now warns that there's probably a bug (protocol should be `smtps:`). `email@1` used to automatically force `smtps:` protocol when port was 465, so this warning is useful for upgraders, without getting in the way of people who Know What They're Doing.  In response to #8696 and some later comments on #8591.
2. I tweaked `node4mailer` slightly to work on even older versions of Node 4. In response to https://github.com/chriswessels/meteor-tupperware/issues/32

I tested the warning in both activating and nonactivating cases, and tested that sending multiple messages only causes one warning.  (In fact, if `MAIL_URL` changes multiple times, each one may cause a warning.  But this seems good.)

### CODE REVIEW

**Comment by hwillson** [comment]
When you have a chance @edemaine, would you mind re-running your CircleCI build?

**Comment by abernix** [comment]
I pushed an empty commit to force the re-run and they appear to be passing now.

**Comment by edemaine** [comment]
Thanks! Sorry for losing track of this.

**Comment by abernix** [comment]
This has been published as `email@1.2.3`.  Thanks again for your attention to this, @edemaine.  😃

**Comment by edemaine** [comment]
Awesome, thanks!  Happy to help.

**Comment by edemaine** [comment]
Just a note for possible future versions of Meteor's `email` package: [nodemailer is no longer officially supported](http://nodemailer.com/status/), but [reactioncommerce is maintaining an official fork](https://github.com/chriswessels/meteor-tupperware/issues/32#issuecomment-309235420), including a Node 4 compatible version.  If there are any interesting changes in `reactioncommerce/nodemailer`, we should probably switch from my `node4mailer` to it.

**Pull request merged**
