### PR TITLE
Official roles package

### PR DESCRIPTION
**Pull request by StorytellerCZ**
Initial copy over of the roles package.
See #13357

### CODE REVIEW

**Comment by nachocodoner** [comment]
I don't have the exact steps with me since I’m traveling, but when I moved packages into the core, I ensured the history was preserved. This is crucial for maintaining the progress made by others on those packages. It also helps when fixing or expanding them, as it considers all past changes in the code. I believe this should be the standard approach for any package migration into the core.

When I’m back, I can look up my notes on how I did it and share them if we decide to follow this method.

**Comment by StorytellerCZ** [comment]
@nachocodoner that would be great!

**Comment by nachocodoner** [comment]
This is the guide I used [in the past to migrate packages into the core](https://github.com/meteor/meteor/pull/13039). 

- Fork the repository to migrate to the core. eg [`alanning:roles`](https://github.com/Meteor-Community-Packages/meteor-roles)

``` bash
git clone https://github.com/<your-username>/<package>.git
cd <path/to/package>
```

- Create and switch to a new branch

``` bash
git checkout -b <package-migrate-branch-name>
```

- Prepare package directory to mimic the Meteor core structure

``` bash
mkdir -p packages/meteor-<package-name>
git mv -k <path/to/package>/* packages/meteor-<package-name>
```

- Fork the Meteor core and prepare your branch

``` bash
cd .. # get out the package directory
git clone --recurse-submodules https://github.com/<your-username>/meteor.git
git checkout -b <core-branch-name>
```

- Add the forked package repository as a remote on your Meteor core fork

``` bash
git remote add source <path/to/package>
```

- Pull the package branch to your Meteor core fork

``` bash
git pull source <package-migrate-branch-name> --allow-unrelated-histories --no-rebase
```

- Push the new branch

``` bash
git push origin <core-branch-name>
```

Finally, create a new PR for your `<core-branch-name>` branch including the package migration changes, as well as the full history kept.

**Comment by StorytellerCZ** [comment]
Closing this PR as I attempt the above.

**Comment by StorytellerCZ** [comment]
@nachocodoner any recommendation how to handle the merge? Seems like rebase is the only option, but it gets stuck on something towards the end.
```
git pull source meteor-core-migration --allow-unrelated-histories
From ../community-packages/meteor-roles
 * branch                    meteor-core-migration -> FETCH_HEAD
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint:
hint:   git config pull.rebase false  # merge
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches.
```

**Pull request closed without merging**
