### PR TITLE
fixes #12761  url to pull manifest from correct url if parameter are used in baseurl

### LINKED ISSUE #12761: hotcode push is failing in Android
```
I20230829-17:46:08.777(-4)? 08-29 17:46:08.376 12135 12338 W MeteorWebApp: Download failure
I20230829-17:46:08.777(-4)? 08-29 17:46:08.376 12135 12338 W MeteorWebApp: com.meteor.webapp.WebAppException: Non-success status code 404for asset manifest
I20230829-17:46:08.777(-4)? 08-29 17:46:08.376 12135 12338 W MeteorWebApp: 	at com.meteor.webapp.AssetBundleManager$1.onResponse(AssetBundleManager.java:104)
I20230829-17:46:08.777(-4)? 08-29 17:46:08.376 12135 12338 W MeteorWebApp: 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
I20230829-17:46:08.777(-4)? 08-29 17:46:08.376 12135 12338 W MeteorWebApp: 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
I20230829-17:46:08.777(-4)? 08-29 17:46:08.376 12135 12338 W MeteorWebApp: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
I20230829-17:46:08.777(-4)? 08-29 17:46:08.376 12135 12338 W MeteorWebApp: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
I20230829-17:46:08.777(-4)? 08-29 17:46:08.376 12135 12338 W MeteorWebApp: 	at java.lang.Thread.run(Thread.java:920)
I20230829-17:46:08.777(-4)? 08-29 17:46:08.376 12135 12338 E MeteorWebApp: Download failure
I20230829-17:46:08.777(-4)? 08-29 17:46:08.376 12135 12338 E MeteorWebApp: com.meteor.webapp.WebAppException: Non-success status code 404for asset manifest
I20230829-17:46:08.778(-4)? 08-29 17:46:08.376 12135 12338 E MeteorWebApp: 	at com.meteor.webapp.AssetBundleManager$1.onResponse(AssetBundleManager.java:104)
I20230829-17:46:08.778(-4)? 08-29 17:46:08.376 12135 12338 E MeteorWebApp: 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
I20230829-17:46:08.778(-4)? 08-29 17:46:08.376 12135 12338 E MeteorWebApp: 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
I20230829-17:46:08.778(-4)? 08-29 17:46:08.376 12135 12338 E MeteorWebApp: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
I20230829-17:46:08.778(-4)? 08-29 17:46:08.376 12135 12338 E MeteorWebApp: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
I20230829-17:46:08.778(-4)? 08-29 17:46:08.376 12135 12338 E MeteorWebApp: 	at java.lang.Thread.run(Thread.java:920)
```
[Reference](https://github.com/meteor/meteor/blob/devel/npm-packages/cordova-plugin-meteor-webapp/src/android/WebAppLocalServer.java#L273)
for plugin cordova-plugin-meteor-webappin file `WebAppLocalServer.java` function `checkForUpdates` construcing the url with line of code `rootUrl.resolve("__cordova/");` which strips the suffix param from url. In our case we have the root_url `mobile-dev.xyz.com/app` 
which is resolved in `mobile-dev.xyz.com/__cordova/` but if we add forward slash in the `--mobile-server` in dev or `--server` in production it is resolved correctly into `mobile-dev.xyz.com/app/__cordova/` which then allow plugin to download correct `manifest.json` file from `mobile-dev.xyz.com/app/__cordova/manifest.json` in `checkForUpdates` [method](https://github.com/meteor/meteor/blob/devel/npm-packages/cordova-plugin-meteor-webapp/src/android/AssetBundleManager.java#L88)

### PR DESCRIPTION
**Pull request by salmanhasni**
the previous fix #12762 didn't fix the issue #12761

P.S I have tested this changed, in development and production ready build.
following is sample java code to test the constructed url

```
package hello;

import java.io.IOException;

import okhttp3.Call;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import org.json.JSONObject;

public class App {
    public String getUrl() {
        
        String url = "https://test.xyz.com/app";
        HttpUrl rootUrl = HttpUrl.parse(url);
        HttpUrl baseUrl = rootUrl.newBuilder().addPathSegment("__cordova").build();
        HttpUrl manifestUrl = baseUrl.newBuilder().addPathSegment("manifest.json").build();

        Request request = new Request.Builder().url(manifestUrl).build();

        OkHttpClient httpClient = new OkHttpClient();


        httpClient.newCall(request).enqueue(new okhttp3.Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                System.out.println("Error downloading asset manifest");
            }

            @Override
            public void onResponse(Call call, Response response) {
                if (!response.isSuccessful()) {
                    return;
                }

                
                try {
                    byte[] manifestBytes = response.body().bytes();
                    JSONObject json = new JSONObject(new String(manifestBytes));
                    JSONObject cordovaCompatibilityVersions = json.getJSONObject("cordovaCompatibilityVersions");
                    System.out.println(cordovaCompatibilityVersions);

                } catch (Exception e) {
                    e.printStackTrace(System.out);
                }

            }
        });
        return manifestUrl.toString();

    }

    public static void main(String[] args) {
        System.out.println(new App().getUrl());
    }
}
```

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
Not an expert on this area, so I will have to primarily go by the tests, in this case AppVeyor is failing, but that might just be a flaky test, so we will have to re-run to be sure.

**Comment by Grubba27** [comment]
We might need a commit to rerun appveyor CI.

**Comment by StorytellerCZ** [comment]
@Grubba27 since this is NPM package, was this published in a new version or not? Need to know for changelog and to make sure that we actually have published this fix.

**Comment by salmanhasni** [comment]
I think its not, becuase cordova `cordova-plugin-meteor-webapp:2.0.2`  is release 24 days before for last fix that still have that issue

**Comment by Grubba27** [comment]
Published 2.0.3

**Pull request merged**
