### PR TITLE
Added Match.Maybe to allow optional matching with null support

### PR DESCRIPTION
**Pull request by LewisW**
This pull request implements the proposed Match.Maybe suggested in #3876. Match.Maybe adds support for a null value being accepted as an optional value. This is necessary because DDP converts undefined values to null values.

I have not updated the docs yet, I wanted to check I was on the right track before adding something to the docs.

### CODE REVIEW

**Comment by stubailo** [comment]
Looks awesome!

Please update the docs and I'll merge.

**Comment by sebakerckhof** [comment]
Very useful.

**Comment by LewisW** [comment]
Documentation updated. I wasn't sure if you wanted me to recommend it over Match.Optional or just document it as an alternative and trust Meteor developers to use it themselves when appropriate.

**Comment by stubailo** [comment]
Merged as one commit: 7a80a8c8517dc721974141d77b7ee70492adcac2

Thank you!

Going to update the docs to make it stand out more, and possibly say that `Optional` is no longer recommended.

**Comment by abernix** [comment]
@stubailo had wrote:
> I don't think it would be good to silently change the behavior (of `Match.Optional`) because it could introduce undiscoverable security holes into people's apps.

Unfortunately, this PR did cause `Match.Optional` to work identical to `Match.Maybe`, even though it wasn't intended to.  There weren't any existing tests for `Match.Optional` on `null` and none were added.  Didn't find a security hole (luckily) but did find this problem. :smiling_imp: 

The current version is just setting `var Maybe = Optional;` but checking the `instanceof` in an unreachable `else if` (because of them being `===`).  Essentially the  `Match.Optional` logic was not being called at all in 1.3 code, instead always using `Match.Maybe`.

See #6735 for more information and #6736 for the PR fix.  Added a bunch of tests that prove the regression and fix too.

**Comment by stubailo** [comment]
Oh man, that's a great catch.

**Pull request closed without merging**
