### PR TITLE
Use MaxCDN as our new CDN

### PR DESCRIPTION
**Pull request by n1mmy**
MaxCDN has graciously agreed to host our compiled packages and bootstrap tarballs. Thanks, MaxCDN!

### CODE REVIEW

**Comment by laosb** [comment]
By the way, how can we set up a mirror for compiled packages (which is served on `warehouse.meteor.com` for now I think)?

**Comment by benjamn** [comment]
Awesome! I will test this out and merge it as soon as I can.

**Comment by abernix** [comment]
Something seems to be going on with this.

I've seen a few reports of failed installs and downloads in the last few days.  #6960 [#6723 (comment)](https://github.com/meteor/meteor/issues/6723#issuecomment-216144477) and I think even #6951 (it's disguised in there).  Also, [on StackOverflow](https://stackoverflow.com/questions/36989049/getting-error-while-downloading-meteor-unexpectedly-download-stops).  I'm also not sure if the Windows installer was updated already, however #6955 also speaks of download problems (2x).

Just tried 10 times and I'm not experiencing any problems with it, but as you'll see with #6960, the problem went away when the user switched URLs.

**Comment by n1mmy** [comment]
Hold off on merging this for now... we're having some issues with people in some countries (eg India) not being able to download from the new CDN.

**Comment by laosb** [comment]
China developers always have problems in downloading anything abroad. Could you provide some tips in how to set up a mirror in China? That's what most Chinese developers care about.

**Comment by n1mmy** [comment]
Hi @laosb. Sorry, I don't really have a great answer for you in terms of setting up a mirror in China. The meteor tool doesn't have built-in support for changing the base URL used (`warehouse.meteor.com`). If you run from git you can manually modify https://github.com/meteor/meteor/blob/devel/tools/packaging/warehouse.js#L46 to point elsewhere.

I'm curious, do you think a CDN edge node in Hong Kong would help? That might be an option we explore.

**Comment by laosb** [comment]
@n1mmy will you accept a pr to enable env-override for the hardcoded url?

Hk node wouldn't help much, as China restrict all aboard data transfer, including hk tw and ma. But still better then nothing.

**Comment by n1mmy** [comment]
@laosb Good question. I would think so. @benjamn @tmeasday ?

**Comment by tmeasday** [comment]
Makes sense to me

**Comment by n1mmy** [comment]
@benjamn We cut back over to MaxCDN for installers and it seems to be OK. Clear to merge.

**Comment by zol** [comment]
@n1mmy - according to @benjamn we decided not to go with MaxCDN in the end so I'm going to close this PR. Re-open it if anything changes.

**Pull request closed without merging**
