### PR TITLE
V3 Docs landing page typo

### LINKED ISSUE #13283: Minor typo on new v3 docs
Hello and congratulation on the v3 release!
I noticed a small typo on: https://v3-docs.meteor.com/

image

"Never **rebuild** an authentication system again"

### PR DESCRIPTION
**Pull request by camstuart**
Resolves #13283

### CODE REVIEW

**Review by fredmaiaarantes — APPROVED** [review]

**Comment by camstuart** [comment]
Hey @fredmaiaarantes not sure what I have done wrong on branching, can you advise?

**Comment by leonardoventurini** [comment]
I tried changing the branch to our release branch, since we might have a fix there for the docs CI on forked source branches which devel lacks... perhaps we need to cherry pick.

**Comment by leonardoventurini** [comment]
Nah, we can merge it to the release branch directly, will need to cherry pick or wait merging release for the fix to take effect anyways

**Comment by leonardoventurini** [comment]
Thanks @camstuart ! 🎉

**Pull request merged**
