### PR TITLE
Added userCollectionName to settings.json

### PR DESCRIPTION
**Pull request by Lavan**
I needed the ability to have multiple meteor applications working with the same database but with different user collections as I don't want to mix administrative users with end users.

I found that adding a public setting to the settings.json file to configure the user collection name to be both simple and practical.

I tried replacing Meteor.users and Accounts.users but that didn't work as I intended as both have already been initialized when my code gets to run.

### CODE REVIEW

**Comment by glasser** [comment]
I think the right thing here should be to make it an option to the (new) AccountsServer constructor.  (And you can't replace Meteor.users, but you can make your own separate one.)  @benjamn thoughts?

**Comment by Lavan** [comment]
Adding an option in AccountsServer is also a good idea, but in that case I think creation of the default collection must be delayed until the user has the option to set the collection name, at this time the collection is initialized some time before the app gets control.

In my usecase I have two meteor apps (admin console and client app) working with the same database but with separate user collections. The admin console must be able to access and modify the client user collection (still using the default Meteor.users collection) but I don't want the client to even know about the admin user collection (using a custom collection name).

My solution doesn't block anyone from adding an option to AccountsServer, it just adds a way to set the user collection name before any code is run.

**Comment by Lavan** [comment]
@glasser @benjamn Sorry to bother you about this but have you reached any type of decision regarding this PR?

**Comment by Lavan** [comment]
The upsteam files have changed too much so I will close this PR. Maybe I'll reopen it again later.

**Pull request closed without merging**
