### PR TITLE
Release 1.12

### PR DESCRIPTION
**Pull request by filipenevola**
Meteor 1.12 is coming.

We are adding smaller items and Typescript update here instead of grouping all together on 2.0 so we can move these items to the final version faster. 🚀 

[Release Notes](https://github.com/meteor/meteor/blob/release-1.12/History.md#v112-unreleased)
[Milestone 1.12](https://github.com/meteor/meteor/milestone/75)

Pending
- [ ] Tests on AppVeyor (Windows) are hanging to install the packages

### CODE REVIEW

**Comment by filipenevola** [comment]
Update on Windows Voyer problem: I was able to run meteor --get-ready by changing the command to write the logs directly to the console and not to the host on PowerShell but the same trick didn't work on Veyor it seems, it is still hanging there to install the packages.

I'm trying to publish a beta version to see if the problem is only in the get-ready command or something in the code changes.

**Comment by filipenevola** [comment]
Hi @afrokick and all, finally we have a beta with TypeScript 4 😉 

```bash
meteor update --release 1.12-beta.1
```

Please provide feedback.

Window users, please provide feedback as well. We are going to work on fixing the get-ready problem but we also need to know if everything is fine on runtime.

> 1.12-beta.0 was missing two packages that I decided to bring from 2.0 to 1.12

**Comment by filipenevola** [comment]
Lesson learned: beta.1 was not working because of `mongo-decimal-beta1120.1` version.

`mongo-decimal` is not a core package and because of that I believe it should not be released using beta suffixes.

**Comment by afrokick** [comment]
Shell we need to update react-meteor-data? Internally it uses typescript@3.7.6
```
accounts-base          upgraded from 1.7.0 to 1.7.1-beta112.1
accounts-password      upgraded from 1.6.2 to 1.6.3-beta1120.2
babel-compiler         upgraded from 7.5.3 to 7.5.4-beta1120.2
dynamic-import         upgraded from 0.5.3 to 0.5.4-beta1120.2
ecmascript             upgraded from 0.14.3 to 0.14.4-beta1120.2
minimongo              upgraded from 1.6.0 to 1.6.1-beta1120.2
mongo                  upgraded from 1.10.0 to 1.10.1-beta1120.2
mongo-decimal          upgraded from 0.1.1 to 0.1.2
react-meteor-data      downgraded from 2.1.2 to 2.0.1                       <-------------
reload                 upgraded from 1.3.0 to 1.3.1-beta1120.2
standard-minifier-css  upgraded from 1.6.1 to 1.7.1-beta1120.2
typescript*            upgraded from 3.7.6 to 4.0.5-beta1120.2

                                              
* These packages have been updated to new versions that are not backwards
compatible.
itgenio: updated to Meteor 1.12-beta.2.
```

**Comment by filipenevola** [comment]
@afrokick sure.

Do you have time to create the PR? Otherwise I will do later today.

BTW, good feedback here https://github.com/meteor/babel/commit/6b5cbfaf39a88b35d0b92a0a50e21787e2c9c429#commitcomment-44136372

**Comment by afrokick** [comment]
@filipenevola Sorry, i have no an idea how to properly create new version for beta.

**Comment by filipenevola** [comment]
I did try to "fix" react-meteor-data but I'm not able to override the version from the beta. I believe we will need to wait for the final one.

Not sure why exactly it's downgrading. Is it because the previous version was not using Typescript?

**Comment by chmelevskij** [comment]
when trying to run beta
```
meteor update --release 1.12-beta.2
```
got error about `accounts-ui` mismatches of less
```
=> Errors while initializing project:

While selecting package versions:
error: Conflict: Constraint less@3.0.1 is not satisfied by less 2.8.0.
Constraints on package "less":
* less@2.8.0 <- accounts-ui 1.3.1
* less@3.0.1 <- accounts-ui-unstyled 1.4.3-beta1120.2 <- accounts-ui 1.3.1
```

**Comment by rj-david** [comment]
Getting this error:

```
meteor update release=1.12-beta.2 
=> Errors while upgrading packages:           
                                              
While selecting package versions:
error: Package names can only contain lowercase
ASCII alphanumerics, dash, dot, or colon, not "=".
```

**Comment by afrokick** [comment]
@rj-david why use use = sign? 
`meteor update --release 1.12-beta.2`

**Comment by afrokick** [comment]
@filipenevola 

> Not sure why exactly it's downgrading. Is it because the previous version was not using Typescript?

Yes, 2.0.1 didn't use typescript package.

**Comment by rj-david** [comment]
> @rj-david why you use = sign?
> `meteor update --release 1.12-beta.2`

Thanks, mate. I need to rest. Small issues like this should be easily identifiable 😅

**Comment by afrokick** [comment]
I have an issue with imports.

my /xxx/imports/ui/components/avatar/editor/index.tsx:

```
import './style.less';

import { observable } from 'mobx';
import { observer } from 'mobx-react';
import React, { useCallback, useMemo } from 'react';
import Cropper from 'react-easy-crop';
import { Point } from 'react-easy-crop/types';           <------
import { IAvatarWithActionsStore } from './types';
```

```
nable to resolve some modules:

  "react-easy-crop/types" in /xxx/imports/ui/components/avatar/editor/index.tsx (web.browser)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save react-easy-crop
```

But i installed this package.

Any thoughts how to debug it?

PS On fresh project with React+TS all works fine.

**Comment by afrokick** [comment]
Found the issue.

Because we enabled emitDecoratorsMetadata, there is a line in js code:
```
__decorate([observable, __metadata("design:type", typeof (_a = typeof Point !== "undefined" && Point) === "function" ? _a : Object)], Store.prototype, "crop", void 0);
```
which requires Point from `react-easy-crop/types`.

So, babel(reify?) imports it as
```
let Point;
module.link("react-easy-crop/types", {
  Point(v) {
    Point = v;
  }

}, 4);
```

But react-easy-crop/types = react-easy-crop/types.d.ts so it was ignored

My workaround is using import type (ts3.8+),
`import type { Point } from 'react-easy-crop/types';`

@filipenevola  Maybe we should include some notice about emitDecoratorMetadata and d.ts files?

**Comment by linegel** [comment]
In our project, everything works smoothly except the already mentioned issue about the downgrading of `react-meteor-data`

**Comment by afrokick** [comment]
I suggest to update TS to 4.1 https://github.com/meteor/babel/pull/38

**Comment by renanccastro** [comment]
> Found the issue.
> 
> Because we enabled emitDecoratorsMetadata, there is a line in js code:
> 
> ```
> __decorate([observable, __metadata("design:type", typeof (_a = typeof Point !== "undefined" && Point) === "function" ? _a : Object)], Store.prototype, "crop", void 0);
> ```
> 
> which requires Point from `react-easy-crop/types`.
> 
> So, babel(reify?) imports it as
> 
> ```
> let Point;
> module.link("react-easy-crop/types", {
>   Point(v) {
>     Point = v;
>   }
> 
> }, 4);
> ```
> 
> But react-easy-crop/types = react-easy-crop/types.d.ts so it was ignored
> 
> My workaround is using import type (ts3.8+),
> `import type { Point } from 'react-easy-crop/types';`
> 
> @filipenevola Maybe we should include some notice about emitDecoratorMetadata and d.ts files?

This will only be an issue when using the new features from TS, right? There are no compatibility breaking changes? Also, about 4.1 I think it's worth it to merge and release the latest. I will generate a beta tomorrow so we can test until the end of the week.

**Comment by chmelevskij** [comment]
Regarding my comment https://github.com/meteor/meteor/pull/11230#issuecomment-727069581

☝️ I think having that error will mean people following the tutorials will have similar issue 😉 As my setup is pretty much what's in the docs.

**Comment by chmelevskij** [comment]
So anyone aware how to fix https://github.com/meteor/meteor/pull/11230#issuecomment-727069581 ? Or will it work once it's not beta?

It's pretty much the most straightforward setup from the docs/tutorial so if it will get merged as it is now I think it will brake the steps which are described in [Users and Accounts](https://guide.meteor.com/accounts.html#accounts-ui)

**Comment by afrokick** [comment]
> This will only be an issue when using the new features from TS, right? There are no compatibility breaking changes?

Its about settings for TS, emitDecoratorsMetadata, which was enabled for 1.12.
For me it is a breaking change, because my code was broken. But if we will add a notice to changelog about this flag and steps to fix an issue via import type, it can be solved easily.

> Also, about 4.1 I think it's worth it to merge and release the latest.

Awesome!

**Comment by afrokick** [comment]
@renanccastro any news?

**Comment by renanccastro** [comment]
I'm releasing it now, should be available in 1h +/- https://github.com/meteor/meteor/pull/11255

**Comment by afrokick** [comment]
After `meteor update --release 1.12-beta.3` i got
```
This project uses Meteor 1.12-beta.3, which isn't available on this platform. To work with this app on all supported platforms, use
meteor update --release METEOR@1.11.1 to pin this app to the newest compatible release.
```

Env: OSX Big Sur, MB Pro mid 2015

`1.12-beta.2` works fine.

**Comment by renanccastro** [comment]
@afrokick I'm finishing publishing it for macos, please try again in some minutes.

@chmelevskij can you try again with beta.3? It should have been fixed now.

**Comment by renanccastro** [comment]
Done, METEOR@1.12-beta.3 released.

**Comment by afrokick** [comment]
> After `meteor update --release 1.12-beta.3` i got
> 
> ```
> This project uses Meteor 1.12-beta.3, which isn't available on this platform. To work with this app on all supported platforms, use
> meteor update --release METEOR@1.11.1 to pin this app to the newest compatible release.
> ```
> 
> Env: OSX Big Sur, MB Pro mid 2015
> 
> `1.12-beta.2` works fine.

@renanccastro same result

**Comment by renanccastro** [comment]
@afrokick I've just tried on my mac and it works fine. Can you give more details on your config/try again?

**Comment by afrokick** [comment]
@renanccastro now it works, thanks

**Comment by renanccastro** [comment]
@chmelevskij how is it in the new beta? Does it work?

**Comment by chmelevskij** [comment]
@renanccastro I've actually migrated to `accounts-password` with no UI. But can revert the commits and verify tonight

**Comment by afrokick** [comment]
@renanccastro @filipenevola any updates? If any issues will occur, we always can release patch version.

**Comment by renanccastro** [comment]
@afrokick we are releasing until Monday ;)

**Comment by afrokick** [comment]
@renanccastro after upgrading to 1.12:
```
While selecting package versions:
error: Conflict: Constraint typescript@3.7.5 is not satisfied by typescript 4.1.2.
Constraints on package "typescript":
* typescript@4.1.2 <- top level
* typescript@~4.1.2 <- top level
* typescript@3.7.5 <- react-meteor-data 2.1.2
```

**Comment by renanccastro** [comment]
react-meteor-data@2.1.3 is out fixing the above @afrokick

**Pull request merged**
