### PR TITLE
Update to present media object sizes

### PR DESCRIPTION
**Pull request by paulincai**
As per IOS and Android official documentation. Related to #8297

### CODE REVIEW

**Comment by paulincai** [comment]
@hwillson hold on :). I am here. Let me have a look please.

**Comment by paulincai** [comment]
@hwillson I think we are good to go

**Comment by hwillson** [comment]
Awesome, thanks @paulincai! We're all set - LGTM!

**Comment by derwaldgeist** [comment]
Can this be downported to 1.5 please? I cannot use 1.5.1 due to #8950, but I need to submit my iOS app to the app store.

**Pull request merged**
