### PR TITLE
Make tool compatible with both old and new OAuth servers

### PR DESCRIPTION
**Pull request by estark37**
@Slava I can't remember if this was ever officially reviewed -- can you look at it? This is the tool change (already on the windows branch) that makes it so that new OAuth apps don't have to have "?close" in order for the tool to talk to them. Tested manually against a local package server with old- and new-style configuration.

Also @Slava I can't figure out how to add you to phabricator :(

### CODE REVIEW

**Comment by stubailo** [comment]
This was merged as part of the Windows code.

**Comment by estark37** [comment]
My last hurrah! :)

**Comment by Slava** [comment]
;)

**Comment by stubailo** [comment]
Yay! @estark37 I'm also building REST login which is kind of a ghost of your code :]

**Pull request closed without merging**
