### PR TITLE
Use Blaze._getTemplateHelper directly

### PR DESCRIPTION
**Pull request by mitar**
This allows one to override `Blaze._getTemplateHelper` with a custom implementation.

This is needed for my Blaze component system.

### CODE REVIEW

**Comment by mitar** [comment]
I updated the pull request. Now there are two nice (unofficial) extension points. One to lookup helpers, another to lookup templates. Please merge this in.

**Comment by dgreensp** [comment]
I would take this if you move the `instanceof Template` check into `Blaze._getTemplate` (since `in` by itself doesn't really amount to anything meaningful) and remove the `typeof ... === 'function'` check.

Also note that we won't guarantee not to break these methods or provide back-compat.

**Comment by mitar** [comment]
Updated based on your comments.

> Also note that we won't guarantee not to break these methods or provide back-compat.

I understand that. :-)

**Comment by mitar** [comment]
I updated the pull request to the latest `devel` branch.

**Comment by dgreensp** [comment]
Merged.  Sorry that took a while.

**Comment by mitar** [comment]
No problem. :-) Thanks!

Check out [Blaze Components](https://github.com/peerlibrary/meteor-blaze-components) which use these hooks to provide components around Blaze.

**Pull request merged**
