### PR TITLE
added command make clean for linux

### PR DESCRIPTION
**Pull request by MohmadAyman**
in response for feature request [#77](https://github.com/meteor/meteor-feature-requests/issues/77) 
where would the ```.meteor``` normally be on windows so I can add its support.
I'll add a test once I know what would we with windows.

### CODE REVIEW

**Comment by stubailo** [comment]
There's definitely a function somewhere in the tool code that will give you the location of the directory across all platforms. Don't have time to look for it now but we should use it for sure.

**Comment by stubailo** [comment]
Also `meteor clean` feels like it would clean the build files for the current project - since that's what something like `make clean` usually does. I'd pick a different name for a command that cleans out the global package cache.

**Comment by MohmadAyman** [comment]
according to the discussion @ #3614 cleaning would delete the ```.meteor``` not the one in the current project, I think cleaning the project would better has its own command like ``` meteor clean-project ``` , what do you think?
Thanks, found ```defaultWarehouseDir() ``` that does the job.

**Comment by stubailo** [comment]
I agree the functionality is super important, I'm just calling out that I think most people would expect a `meteor clean` command to do a different thing. That's just one person's opinion though, hope people will chime in!

**Comment by MohmadAyman** [comment]
Made some changes, Now make clean cleana the project, and make clean global deletes the global .meteor .

**Comment by abernix** [comment]
The original feature request was to clear `~/.meteor` of unused packages.  This doesn't seem to meet the criteria of that feature request.  For example, when using the `--global` flag this just recursively deletes the entire `~/.meteor/` directory, regardless of whether a package is used or not, which is a bit excessive since it also wipes the local package catalog and requires a time consuming full-sync.  This is really no different than `rm -rf ~/.meteor`.  I'll point out that there really isn't a method of determining whether a package is used.

Additionally, when running `meteor clean` without the `--global` flag, this PR (as submitted) wipes the apps entire `.meteor` directory, which completely breaks the app since multiple files which live within the `.meteor` directory are required, such as `packages`, `version`, `release`, etc.   Currently, there is already a `meteor reset` –  for the local app, doesn't this already accomplish what's necessary?

**Comment by abernix** [comment]
Thanks for the contribution effort however this doesn't really work as it should.  A future PR of this nature might try to address how to determine the necessity of a package, perhaps based on how recently it's been used, though that exact logic will need to be worked through in an issue before it gets submitted as a PR.

**Pull request closed without merging**
