### PR TITLE
[WIP] Add support for filtered positional operator to minimongo

### PR DESCRIPTION
**Pull request by mpowaga**
This implementation already works pretty well but there's lot of things to improve. Todo list:

- [ ] Improve the way `arrayFilters` option is handled
- [ ] Throw errors (for example when arrayFilter is provided but not used)
- [ ] Add tests (probably it doesn't work well with positional operator, null properties or has other issues)
- [ ] Clean up the code (`LocalCollection._modify` is pretty big now. Probably it makes sense to move some parts to separate functions)

As a side note I think it makes sense for this PR to be merged only after MongoDB 3.6 support lands in Meteor.

### CODE REVIEW

**Comment by hwillson** [comment]
Thanks for working on this @mpowaga - this looks promising! Let us know when you think this is ready to be reviewed (when you're ready to remove the WIP), and we'll dive in.

**Comment by mitar** [comment]
`arrayfilters` support would be really cool to get into Minimongo.

**Comment by afrokick** [comment]
@mpowaga any updates?

**Comment by mpowaga** [comment]
I have some changes locally on my computer which I haven't pushed yet but still need to be finished. Maybe I'll find some time this month to get back to this PR.

**Comment by filipenevola** [comment]
The CLA is still not signed, closing because of this. @mpowaga feel free to re-open this PR or create a new PR with similar content to move this change ahead.

**Comment by ruerob** [comment]
Hello @mpowaga, I think you have done great work adding this. I really would like to see this as a finished PR. Would it be possible for you to get it done? Or is it possible that you send me the changes you have locally so I can finish this PR?

**Pull request closed without merging**
