### PR TITLE
updated the doc with the dependency of --container-size on --plan flag

### PR DESCRIPTION
**Pull request by Ayushi96**
Addressing issue #12060 
Happy Hactoberfest 2022 :)

### CODE REVIEW

**Review by StorytellerCZ — APPROVED** [review]

**Comment by Ayushi96** [comment]
Hello @StorytellerCZ, thanks for approving my changes. The work is not in progress, please suggest if you see a scope of improvement.

**Review by radekmie — APPROVED** [review]
The documentation is fine, but maybe the error shouldn't say "Internal error"? @fredmaiaarantes

**Comment by fredmaiaarantes** [comment]
> The documentation is fine, but maybe the error shouldn't say "Internal error"? @fredmaiaarantes

I agree, we should validate the arguments. Can you add this to our tasks board @Grubba27?

The documentation in the PR is correct as it documents the current behavior.

**Comment by Grubba27** [comment]
Sure! I will add to our board and thanks @Ayushi96 for your contribution :)

**Comment by Ayushi96** [comment]
@Grubba27 thanks :)

**Pull request merged**
