### PR TITLE
Better boilerplate proposal

### PR DESCRIPTION
**Pull request by Maxim-Filimonov**
Ok so this is just an idea. Was pretty easy to implement so I thought I might just do PR.
Basically every meteor tutorial starts with "remove generated *.css/*.js/*.html and create client/server folders". 

I don't think that anyone will gonna create an app with if Meteor.isClient and Meteor.isServer inside one file so why not show a good way to do meteor app? 

Opinions are only based on standard meteor special folders.
Thoughts?
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/meteor/meteor/pull/3042%23issuecomment-62239291%22%2C%20%22https%3A//github.com/meteor/meteor/pull/3042%23issuecomment-67207284%22%2C%20%22https%3A//github.com/meteor/meteor/pull/3042%23issuecomment-67252803%22%2C%20%22https%3A//github.com/meteor/meteor/pull/3042%23issuecomment-67918279%22%2C%20%22https%3A//github.com/meteor/meteor/pull/3042%23issuecomment-67918794%22%2C%20%22https%3A//github.com/meteor/meteor/pull/3042%23issuecomment-68487178%22%2C%20%22https%3A//github.com/meteor/meteor/pull/3042%23issuecomment-68487213%22%2C%20%22https%3A//github.com/meteor/meteor/pull/3042%23issuecomment-68487279%22%2C%20%22https%3A//github.com/meteor/meteor/pull/3042%23issuecomment-68487418%22%2C%20%22https%3A//github.com/meteor/meteor/pull/3042%23issuecomment-68487703%22%2C%20%22https%3A//github.com/meteor/meteor/pull/3042%23issuecomment-68702655%22%2C%20%22https%3A//github.com/meteor/meteor/pull/3042%23issuecomment-69281185%22%2C%20%22https%3A//github.com/meteor/meteor/pull/3042%23issuecomment-69427578%22%2C%20%22https%3A//github.com/meteor/meteor/pull/3042%23issuecomment-70348147%22%2C%20%22https%3A//github.com/meteor/meteor/pull/3042%23issuecomment-71555221%22%2C%20%22https%3A//github.com/meteor/meteor/pull/3042%23issuecomment-71563294%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/meteor/meteor/pull/3042%23issuecomment-62239291%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22I%20really%20like%20this%20idea.%20That%20way%20users%20get%20a%20sense%20of%20how%20to%20structure%20their%20application%20from%20the%20get%20go.%20%22%2C%20%22created_at%22%3A%20%222014-11-08T01%3A25%3A42Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1437754%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/rgoomar%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20think%20it%27s%20not%20clear%20that%20this%20is%20the%20best%20idea%20for%20the%20basic%20%60meteor%20create%60%20app.%20I%20agree%20that%20we%20could%20have%20ways%20of%20generating%20more%20organized%20boilerplate%20code%2C%20but%20I%20think%20the%20basic%20%60meteor%20create%60%20should%20make%20the%20simplest%20app%20possible%20so%20that%20people%20can%20see%20that%20all%20of%20the%20boilerplate%20is%20not%20necessary.%20For%20example%2C%20when%20I%20prototype%20apps%2C%20I%20usually%20start%20with%20one%20js%20file%20and%20%60if%20%28Meteor.isClient%29%20%7B...%7D%60%22%2C%20%22created_at%22%3A%20%222014-12-16T18%3A29%3A33Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/448783%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/stubailo%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40stubailo%20how%20about%20%60meteor%20create%20--simple%60%20for%20old%20structure%3F%20This%20boilerplate%20does%20not%20create%20any%20new%20conventions%20besides%20ones%20already%20used%20by%20meteor%20itself.%20I%20feel%20like%20%60meteor%20create%60%20should%20be%20starting%20point%20for%20real%20apps%20not%20for%20quick%20prototypes%20only.%20%22%2C%20%22created_at%22%3A%20%222014-12-16T23%3A32%3A01Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/360645%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Maxim-Filimonov%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20think%20it%27s%20a%20great%20idea%20to%20have%20some%20sort%20of%20flag%20to%20switch%20between%20the%20basic%20and%20more%20advanced%20boilerplate.%20%60%60%60meteor%20create%60%60%60%20should%20still%20be%20the%20simple%20one%2C%20with%20something%20like%20%60%60%60meteor%20create%20--advanced%60%60%60%20or%20whatever%20to%20create%20a%20more%20complete%20structure.%22%2C%20%22created_at%22%3A%20%222014-12-23T03%3A19%3A59Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/463495%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/adnissen%22%7D%7D%2C%20%7B%22body%22%3A%20%22There%27s%20lots%20of%20use%20for%20simple%20one-page%20apps%3B%20whether%20they%20be%20a%20small%20project%20homepage%2C%20a%20landing%20page%2C%20a%20placeholder%20page%2C%20an%20app%20prototype%2C%20or%20whatever.%20%20And%20I%27d%20vote%20for%20an%20%60%60--advanced%60%60%20or%20%60%60--clientserver%60%60%20flag%20to%20add%20some%20default%20boilerplate%2C%20rather%20than%20a%20%60%60--simple%60%60%20flag.%20%20It%27s%20important%20to%20step%20people%20through%20a%20learning%20process%20and%20to%20build%20upon%20fundamentals.%20%20%5Cr%5Cn%5Cr%5CnAlso%2C%20lets%20please%20be%20careful%20about%20assumptions%20about%20what%20default%20boilerplate%20is%20added.%20%20%60%60/client%60%60%20and%20%60%60/server%60%60%20are%20hardcoded%20into%20the%20bundler%3B%20but%20%60%60/lib%60%60%20versus%20other%20names%20are%20a%20murky%20subject%3B%20and%20everything%20after%20that%20is%20up%20for%20discussion.%20%20%22%2C%20%22created_at%22%3A%20%222014-12-23T03%3A32%3A18Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/675910%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/awatson1978%22%7D%7D%2C%20%7B%22body%22%3A%20%22It%27s%20will%20be%20better%20if%20we%20can%20create%20an%20app%20for%20a%20community-based%20boilerplate.%5Cr%5Cn%5Cr%5Cne.g.%5Cr%5Cn%5Cr%5Cn%20%20%20%20meteor%20create%20--bp%20single-page%5Cr%5Cn%20%20%20%20meteor%20create%20--bp%20iron%3Arouter-bp%5Cr%5Cn%20%20%20%20meteor%20create%20--bp%20laosb%3Asocial-network%22%2C%20%22created_at%22%3A%20%222015-01-01T13%3A55%3A09Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2545261%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/laosb%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40laosb%20could%20we%20just%20use%20the%20built%20in%20examples%20functionality%3F%20%22%2C%20%22created_at%22%3A%20%222015-01-01T13%3A57%3A06Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/463495%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/adnissen%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40adnissen%20yes%20maybe%20just%20like%20this.%20It%20will%20be%20good%2C%20but%20we%20may%20call%20them%20boilerplates%20instead%20of%20examples.%22%2C%20%22created_at%22%3A%20%222015-01-01T13%3A59%3A58Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2545261%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/laosb%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40laosb%20I%20think%20as%20a%20first%20version%20it%20might%20be%20wise%20to%20just%20make%20them%20new%20examples.%20Meteor%20is%20supposed%20to%20be%20structure%20agnostic%2C%20so%20I%20think%20the%20example%20nomenclature%20actually%20works%20really%20well%2C%20eg%20%5C%22Here%27s%20an%20example%20of%20how%20to%20set%20up%20your%20project%20with%20multiple%20folders%5C%22%22%2C%20%22created_at%22%3A%20%222015-01-01T14%3A07%3A52Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/463495%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/adnissen%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40adnissen%20I%20think%20so.%20The%203rd-party%20boilerplate%20is%20a%20suggestion%20facing%20the%20future.%22%2C%20%22created_at%22%3A%20%222015-01-01T14%3A23%3A48Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2545261%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/laosb%22%7D%7D%2C%20%7B%22body%22%3A%20%22How%20far%20should%20the%20fancy%20boilerplate%20go%3F%20For%20example%20should%20it%20add%20%60iron%3Arouter%60%20and%20make%20a%20%60router.js%60%20file%20for%20you%3F%22%2C%20%22created_at%22%3A%20%222015-01-05T12%3A38%3A45Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/448783%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/stubailo%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40stubailo%20It%27s%20probably%20not%20necessary%20to%20add%20that%20unless%20there%20are%20two%20levels%20of%20boilerplates.%20Like%20%60--bp%60%20would%20have%20the%20absolute%20basic%20necessities%20and%20folder%20structure%20and%20%60--advancedbp%60%20or%20something%20like%20that%20would%20include%20iron%20router%20and%20an%20example%20router%20file%20as%20well.%20%5Cr%5Cn%5Cr%5CnSome%20smaller%20apps%20may%20not%20need%20a%20router.%20It%27s%20an%20edge%20case%2C%20but%20that%20makes%20the%20most%20sense%20to%20me.%22%2C%20%22created_at%22%3A%20%222015-01-09T01%3A36%3A09Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1437754%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/rgoomar%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20agree%20with%20%40adnissen%20.%20%20We%20should%20refactor%20%60create%20--example%60%20so%20that%20instead%20of%20just%20creating%20examples%20built%20into%20the%20tool%2C%20anybody%20can%20create%20examples.%20%20On%20the%20other%20hand%2C%20this%20is%20actually%20kind%20of%20complicated%20---%20figuring%20out%20how%20to%20properly%20version%20examples%20so%20that%20you%20get%20an%20appropriate%20version%20for%20your%20chosen%20meteor%20release%20is%20actually%20harder%20than%20for%20packages.%22%2C%20%22created_at%22%3A%20%222015-01-10T00%3A52%3A59Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/16724%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/glasser%22%7D%7D%2C%20%7B%22body%22%3A%20%22Ok%20i%27ve%20updated%20the%20PR%20to%20avoid%20changing%20default%20behaviour%20and%20introduce%20the%20new%20option%20--clientserver%20%28similar%20to%20--package%29.%5Cr%5Cn%60meteor%20create%20--clientserver%60%20will%20create%20the%20client/server%20structure%20and%20corresponding%20folders.%5Cr%5CnI%20would%20suggest%20to%20look%20at%20https%3A//github.com/RailsApps/rails-composer%20as%20example%20of%20how%20to%20make%20fancy%20generator.%20Actually%2C%20there%20is%20already%20some%20work%20done%20in%20this%20area%20for%20meteor%20by%20the%20EventedMind%20team%20-%3E%20https%3A//github.com/EventedMind/em%22%2C%20%22created_at%22%3A%20%222015-01-17T01%3A24%3A41Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/360645%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Maxim-Filimonov%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40stubailo%20any%20feedback%20on%20new%20submission%3F%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222015-01-26T22%3A48%3A43Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/360645%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Maxim-Filimonov%22%7D%7D%2C%20%7B%22body%22%3A%20%22Thanks%20for%20the%20feature%20request%21%20You%20might%20be%20interested%20in%20reading%20our%20%5Bfeature%20request%20guidelines%5D%28https%3A//github.com/meteor/meteor/wiki/Contributing-to-Meteor%23feature-requests%29.%22%2C%20%22created_at%22%3A%20%222015-01-26T23%3A48%3A50Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/16724%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/glasser%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/meteor/meteor/pull/3042#issuecomment-62239291'>General Comment</a></b>
- <a href='https://github.com/rgoomar'></a> I really like this idea. That way users get a sense of how to structure their application from the get go.
- <a href='https://github.com/stubailo'></a> I think it's not clear that this is the best idea for the basic `meteor create` app. I agree that we could have ways of generating more organized boilerplate code, but I think the basic `meteor create` should make the simplest app possible so that people can see that all of the boilerplate is not necessary. For example, when I prototype apps, I usually start with one js file and `if (Meteor.isClient) {...}`
- <a href='https://github.com/Maxim-Filimonov'></a> @stubailo how about `meteor create --simple` for old structure? This boilerplate does not create any new conventions besides ones already used by meteor itself. I feel like `meteor create` should be starting point for real apps not for quick prototypes only.
- <a href='https://github.com/adnissen'></a> I think it's a great idea to have some sort of flag to switch between the basic and more advanced boilerplate. ```meteor create``` should still be the simple one, with something like ```meteor create --advanced``` or whatever to create a more complete structure.
- <a href='https://github.com/awatson1978'></a> There's lots of use for simple one-page apps; whether they be a small project homepage, a landing page, a placeholder page, an app prototype, or whatever.  And I'd vote for an ``--advanced`` or ``--clientserver`` flag to add some default boilerplate, rather than a ``--simple`` flag.  It's important to step people through a learning process and to build upon fundamentals.
Also, lets please be careful about assumptions about what default boilerplate is added.  ``/client`` and ``/server`` are hardcoded into the bundler; but ``/lib`` versus other names are a murky subject; and everything after that is up for discussion.
- <a href='https://github.com/laosb'></a> It's will be better if we can create an app for a community-based boilerplate.
e.g.
meteor create --bp single-page
meteor create --bp iron:router-bp
meteor create --bp laosb:social-network
- <a href='https://github.com/adnissen'></a> @laosb could we just use the built in examples functionality?
- <a href='https://github.com/laosb'></a> @adnissen yes maybe just like this. It will be good, but we may call them boilerplates instead of examples.
- <a href='https://github.com/adnissen'></a> @laosb I think as a first version it might be wise to just make them new examples. Meteor is supposed to be structure agnostic, so I think the example nomenclature actually works really well, eg "Here's an example of how to set up your project with multiple folders"
- <a href='https://github.com/laosb'></a> @adnissen I think so. The 3rd-party boilerplate is a suggestion facing the future.
- <a href='https://github.com/stubailo'></a> How far should the fancy boilerplate go? For example should it add `iron:router` and make a `router.js` file for you?
- <a href='https://github.com/rgoomar'></a> @stubailo It's probably not necessary to add that unless there are two levels of boilerplates. Like `--bp` would have the absolute basic necessities and folder structure and `--advancedbp` or something like that would include iron router and an example router file as well.
Some smaller apps may not need a router. It's an edge case, but that makes the most sense to me.
- <a href='https://github.com/glasser'></a> I agree with @adnissen .  We should refactor `create --example` so that instead of just creating examples built into the tool, anybody can create examples.  On the other hand, this is actually kind of complicated --- figuring out how to properly version examples so that you get an appropriate version for your chosen meteor release is actually harder than for packages.
- <a href='https://github.com/Maxim-Filimonov'></a> Ok i've updated the PR to avoid changing default behaviour and introduce the new option --clientserver (similar to --package).
`meteor create --clientserver` will create the client/server structure and corresponding folders.
I would suggest to look at https://github.com/RailsApps/rails-composer as example of how to make fancy generator. Actually, there is already some work done in this area for meteor by the EventedMind team -> https://github.com/EventedMind/em
- <a href='https://github.com/Maxim-Filimonov'></a> @stubailo any feedback on new submission?
- <a href='https://github.com/glasser'></a> Thanks for the feature request! You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

<a href='https://www.codereviewhub.com/meteor/meteor/pull/3042?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/meteor/meteor/pull/3042?approve=1'></a>&nbsp;<a href='https://github.com/meteor/meteor/pull/3042'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by laosb** [comment]
It's will be better if we can create an app for a community-based boilerplate.

e.g.
    meteor create --bp single-page
    meteor create --bp iron:router-bp
    meteor create --bp laosb:social-network

**Comment by adnissen** [comment]
@laosb could we just use the built in examples functionality?

**Comment by laosb** [comment]
@adnissen yes maybe just like this. It will be good, but we may call them boilerplates instead of examples.

**Comment by adnissen** [comment]
@laosb I think as a first version it might be wise to just make them new examples. Meteor is supposed to be structure agnostic, so I think the example nomenclature actually works really well, eg "Here's an example of how to set up your project with multiple folders"

**Comment by laosb** [comment]
@adnissen I think so. The 3rd-party boilerplate is a suggestion facing the future.

**Comment by stubailo** [comment]
How far should the fancy boilerplate go? For example should it add `iron:router` and make a `router.js` file for you?

**Comment by rgoomar** [comment]
@stubailo It's probably not necessary to add that unless there are two levels of boilerplates. Like `--bp` would have the absolute basic necessities and folder structure and `--advancedbp` or something like that would include iron router and an example router file as well. 

Some smaller apps may not need a router. It's an edge case, but that makes the most sense to me.

**Comment by glasser** [comment]
I agree with @adnissen .  We should refactor `create --example` so that instead of just creating examples built into the tool, anybody can create examples.  On the other hand, this is actually kind of complicated --- figuring out how to properly version examples so that you get an appropriate version for your chosen meteor release is actually harder than for packages.

**Comment by Maxim-Filimonov** [comment]
Ok i've updated the PR to avoid changing default behaviour and introduce a new option (similar to --package).
`meteor create --clientserver` will create the client/server structure and corresponding folders.
I would suggest to look at https://github.com/RailsApps/rails-composer as example of how to make fancy generator. Actually, there is already some work done in this area for meteor by the EventedMind team -> https://github.com/EventedMind/em

**Comment by Maxim-Filimonov** [comment]
@stubailo any feedback on new submission?

**Comment by glasser** [comment]
Thanks for the feature request! You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by stubailo** [comment]
Hey this popped up in my notifications because of the edited description. I think we should close this in favor of writing a new boilerplate that follows practices encoded in the Meteor guide. Issue here: https://github.com/meteor/guide/issues/59

**Pull request closed without merging**
