### PR TITLE
Webapp upgrade useragent

### LINKED ISSUE #13341: ReDoS in 3rd party module.
The flaw is in `useragent` module [here](https://github.com/3rd-Eden/useragent).

Meteor Framework always parse new User-Agent Header string by using useragent module, that could lead to Application HTTP Regex DoS following this [issue](https://github.com/3rd-Eden/useragent/issues/147).

The vulnerable code: https://github.com/meteor/meteor/blob/d3d191b8c4ba525ec178013d541c79f81e973de3/packages/webapp/webapp_server.js#L126

Recommend to limit length of User-Agent Header from user's request.

### PR DESCRIPTION
**Pull request by StorytellerCZ**
This PR replaces `useragent` package with `useragent-ng`. It also adds a workaround for potential ReDoS attacke reported in #13341 and
https://github.com/3rd-Eden/useragent/issues/147

Not sure if the workaround is needed anymore (or if we can't find a better solution) as the issue has been fixed in the upstream packages from `useragent` (https://github.com/ua-parser/uap-core/issues/495).

This is a quick solution to the issue and I think we should find a better maintained library to handle useragents string resolution.

### CODE REVIEW

**Comment by denihs** [comment]
The tests are failing for this one:

image

Can you take a look?

**Comment by StorytellerCZ** [comment]
No idea why it couldn't install `cookie-parser`. Will take a look another day, hopefully tomorrow, with a fresh head.

**Comment by denihs** [comment]
Hey @StorytellerCZ, any news on this one?

**Comment by wkeithchau** [comment]
Can this fix be used with Meteor@2.16? Would it just work or have there been updates to webapp since meteor@3.0.0 that includes breaking changes?

**Comment by StorytellerCZ** [comment]
@wkeithchau I think this can be back-ported. I don't have time to allocate for this this week though.

-------
If you would like to help me spend more time to work on Open Source, please sponsor me:
https://github.com/sponsors/StorytellerCZ

**Comment by denihs** [comment]
@StorytellerCZ I think [this](https://github.com/meteor/meteor/pull/13355/commits/51d529b0149ffb02cd892d9eaf01b6cba0339825) should solve the issue. As soon as tests pass, we'll merge this PR.

**Comment by StorytellerCZ** [comment]
Added a check if the user agent string is undefined to prevent errors, which is the last failing test.

**Pull request merged**
