### PR TITLE
Add in environment flag to assume package cache always valid

### PR DESCRIPTION
**Pull request by chrishowes**
(Side note: guidelines say to post to meteor-core ML first, which doesn't exist anymore - so apologies if there was a prereq for this PR)

I noticed slowness on restarts when changing meteor code.. debugging took me to find that Meteor (the constraint solver in particular) is hitting a rather large SQLite table of packages on every code change. 

I'm not familiar enough with the codebase yet, but possible solutions in my mind are:
- Trimming the SQLite `packages` table to only include local packages and not the entire atmosphere
- Being smarter about determining when to run this constraint solver (only when the local package list changes?)

For now - I've added in a flag that will assume that your last package cache is valid every time. I know this might not be the best option, but my hope is this will at least start the discussion as to the best way to solve this in the short / long term. 

Related issues:
https://github.com/meteor/meteor/issues/4284
https://github.com/meteor/meteor/issues/2950

### CODE REVIEW

**Comment by glasser** [comment]
Can you share measurements of how this improved performance on your test cases?

**Comment by chrishowes** [comment]
On lib/ js file change:

w/o flag:
| Select Package Versions: 1033.9
|     new CS.Input: 14.7
|     Input#loadFromCatalog (sqlite): 971.3
|     other Select Package Versions: 47.9
|
| Input#loadFromCatalog (sqlite): 971.3
| other Select Package Versions: 47.9
| new CS.Input: 14.7
| Total: 1033.9

w/ flag:
| Select Package Versions: 29.0
|     new CS.Input: 28.8
|
| new CS.Input: 28.8
| Total: 28.8

Interestingly enough, Input#loadFromCatalog (sqlite) was pretty variable, approaching 7s for me last night. Today it's down to 1s. Must be because I'm watching it :smile:

**Comment by aofrozen** [comment]
I solved that slow solver issue. Cache will be enabled when packages list is not changed. I will create a branch and commit my work.

| Select Package Versions: 207.5
|     new CS.Input: 89.9
|     Input#loadFromCatalog (sqlite): 21.4
|     other Select Package Versions: 96.2
| 
| other Select Package Versions: 96.2
| new CS.Input: 89.9
| Input#loadFromCatalog (sqlite): 21.4
| Total: 207.5

**Comment by benjamn** [comment]
Thanks for this PR, and sorry we never got around to merging it. We are currently cleaning up the repository and removing old PRs; if you think this PR still has value and are interested in resurrecting it, we encourage you to re-submit it against current `devel`.

**Pull request closed without merging**
