### PR TITLE
Modernize standard-minifier-css and update dependencies

### PR DESCRIPTION
**Pull request by sebakerckhof**
This modernizes the standard-minifier-css package. 
It should also have a performance improvement on css heavy projects because of the updated source-map package which now works with the wasm-based sourcemap consumer.

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
I guess the tests fail because of dev bundle. @filipenevola

**Comment by sebakerckhof** [comment]
@StorytellerCZ Nope, because it needed this:
https://github.com/meteor/meteor/commit/46e00a875726dff078c59eaf7fdc7b956cf0a996

**Review by StorytellerCZ — APPROVED** [review]

**Review by filipenevola — APPROVED** [review]

**Comment by filipenevola** [comment]
Hi, as this is a minor bump we need a new Meteor version, so it's going to be included in 2.0

**Comment by filipenevola** [comment]
Cherry-picked to 1.12

**Pull request merged**
