### PR TITLE
Document parameters passed to Template helpers towards #3017

### PR DESCRIPTION
**Pull request by dandv**

### CODE REVIEW

**Comment by stubailo** [comment]
@dandv it looks like you deleted your fork, this isn't mergeable anymore.

**Comment by dandv** [comment]
That's a bit odd... the diffs do show up here in GitHub - https://github.com/meteor/meteor/pull/3018/files

**Comment by stubailo** [comment]
yep, but I can't pull it from the command line.

**Comment by stubailo** [comment]
Maybe re-submit the PR? Otherwise I'll have to copy-paste everything into new commits

**Pull request closed without merging**
