### PR TITLE
Release 2.5.4

### PR DESCRIPTION
**Pull request by renanccastro**
# Beta

We had a problem with 2.5.4 to generate the Windows tarball, this problem was fixed [here](https://github.com/meteor/meteor/pull/11859/commits/b3dee1c98ae1c340b32ff16b4861a6ac2197a739).

2.5.5 is coming soon to replace 2.5.4.

# Changelog
  - Bump node version to 14.18.3 - security patch
  - Change the tar implementation for streams, used on deploying and unpacking packages. Reduced "upload bundle" time when deploying is expected.

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
Got this when I tried to deploy to Galaxy:
```
Preparing to build your app...                
/home/storyteller/.meteor/packages/meteor-tool/.2.5.4-beta.0.yuqsvy.vjjm9++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

TypeError: Cannot read property 'id' of null
    at InputFile.resolve (/tools/isobuild/compiler-plugin.js:405:61)
    at packages/babel-compiler.js:574:23
    at Array.some (<anonymous>)
    at requireWithPrefixes (packages/babel-compiler.js:569:26)
    at requireWithPath (packages/babel-compiler.js:487:14)
    at resolveHelper (packages/babel-compiler.js:459:24)
    at resolveHelper (packages/babel-compiler.js:450:21)
    at packages/babel-compiler.js:432:19
    at Array.forEach (<anonymous>)
    at walkHelper (packages/babel-compiler.js:431:10)
    at walkBabelRC (packages/babel-compiler.js:417:24)
    at BabelCompiler.BCp._inferHelper (packages/babel-compiler.js:514:17)
    at BabelCompiler.BCp._inferFromPackageJson (packages/babel-compiler.js:381:14)
    at BabelCompiler.BCp.inferExtraBabelOptions (packages/babel-compiler.js:334:10)
    at BabelCompiler.BCp.processOneFileForTarget (packages/babel-compiler.js:209:10)
    at packages/babel-compiler.js:123:25
    at /home/storyteller/.meteor/packages/meteor-tool/.2.5.4-beta.0.yuqsvy.vjjm9++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Promise.await (/home/storyteller/.meteor/packages/meteor-tool/.2.5.4-beta.0.yuqsvy.vjjm9++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
    at JsOutputResource.finalize (/tools/isobuild/compiler-plugin.js:931:12)
    at JsOutputResource.hasPendingErrors (/tools/isobuild/compiler-plugin.js:936:10)
    at JsOutputResource.reportPendingErrors (/tools/isobuild/compiler-plugin.js:941:14)
    at ImportScanner.scanFile (/home/storyteller/.meteor/packages/meteor-tool/.2.5.4-beta.0.yuqsvy.vjjm9++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1083:14)
    at /home/storyteller/.meteor/packages/meteor-tool/.2.5.4-beta.0.yuqsvy.vjjm9++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1142:14
    at each (/home/storyteller/.meteor/packages/meteor-tool/.2.5.4-beta.0.yuqsvy.vjjm9++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1321:7)
    at ImportScanner.scanFile (/home/storyteller/.meteor/packages/meteor-tool/.2.5.4-beta.0.yuqsvy.vjjm9++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1105:5)
    at /home/storyteller/.meteor/packages/meteor-tool/.2.5.4-beta.0.yuqsvy.vjjm9++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1142:14
    at each (/home/storyteller/.meteor/packages/meteor-tool/.2.5.4-beta.0.yuqsvy.vjjm9++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1321:7)
    at ImportScanner.scanFile (/home/storyteller/.meteor/packages/meteor-tool/.2.5.4-beta.0.yuqsvy.vjjm9++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1105:5)
    at /home/storyteller/.meteor/packages/meteor-tool/.2.5.4-beta.0.yuqsvy.vjjm9++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1142:14
    at each (/home/storyteller/.meteor/packages/meteor-tool/.2.5.4-beta.0.yuqsvy.vjjm9++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1321:7)
    at ImportScanner.scanFile (/home/storyteller/.meteor/packages/meteor-tool/.2.5.4-beta.0.yuqsvy.vjjm9++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1105:5)
    at /home/storyteller/.meteor/packages/meteor-tool/.2.5.4-beta.0.yuqsvy.vjjm9++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1142:14
    at each (/home/storyteller/.meteor/packages/meteor-tool/.2.5.4-beta.0.yuqsvy.vjjm9++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1321:7)
    at ImportScanner.scanFile (/home/storyteller/.meteor/packages/meteor-tool/.2.5.4-beta.0.yuqsvy.vjjm9++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1105:5)
    at /home/storyteller/.meteor/packages/meteor-tool/.2.5.4-beta.0.yuqsvy.vjjm9++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1142:14
    at each (/home/storyteller/.meteor/packages/meteor-tool/.2.5.4-beta.0.yuqsvy.vjjm9++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1321:7)
    at ImportScanner.scanFile (/home/storyteller/.meteor/packages/meteor-tool/.2.5.4-beta.0.yuqsvy.vjjm9++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1105:5)
    at /home/storyteller/.meteor/packages/meteor-tool/.2.5.4-beta.0.yuqsvy.vjjm9++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1142:14
    at each (/home/storyteller/.meteor/packages/meteor-tool/.2.5.4-beta.0.yuqsvy.vjjm9++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1321:7)
    at ImportScanner.scanFile (/home/storyteller/.meteor/packages/meteor-tool/.2.5.4-beta.0.yuqsvy.vjjm9++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1105:5)
    at /home/storyteller/.meteor/packages/meteor-tool/.2.5.4-beta.0.yuqsvy.vjjm9++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:740:14
    at Array.forEach (<anonymous>)
    at ImportScanner.scanImports (/home/storyteller/.meteor/packages/meteor-tool/.2.5.4-beta.0.yuqsvy.vjjm9++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:738:22)
    at /tools/isobuild/compiler-plugin.js:1381:17
    at Array.forEach (<anonymous>)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:1346:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:1161:8)
    at /tools/isobuild/bundler.js:864:12
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at ClientTarget.make (/tools/isobuild/bundler.js:852:18)
    at /tools/isobuild/bundler.js:3260:14
    at /tools/isobuild/bundler.js:3413:25
    at Array.forEach (<anonymous>)
    at /tools/isobuild/bundler.js:3367:14
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at bundle (/tools/isobuild/bundler.js:3241:31)
    at /tools/isobuild/bundler.js:3184:32
    at Slot.withValue (/home/storyteller/.meteor/packages/meteor-tool/.2.5.4-beta.0.yuqsvy.vjjm9++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.esm.js:69:29)
    at Object.withCache (/home/storyteller/.meteor/packages/meteor-tool/.2.5.4-beta.0.yuqsvy.vjjm9++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/files.ts:1601:39)
    at Object.bundle (/tools/isobuild/bundler.js:3184:16)
    at /tools/meteor-services/deploy.js:610:36
    at /home/storyteller/.meteor/packages/meteor-tool/.2.5.4-beta.0.yuqsvy.vjjm9++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (/home/storyteller/.meteor/packages/meteor-tool/.2.5.4-beta.0.yuqsvy.vjjm9++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:56:12)
    at /tools/cli/commands.js:1495:19
    at Function.run (/home/storyteller/.meteor/packages/meteor-tool/.2.5.4-beta.0.yuqsvy.vjjm9++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/tool-env/tools/tool-env/profile.ts:289:14)
    at /tools/cli/commands.js:1493:18
    at /home/storyteller/.meteor/packages/meteor-tool/.2.5.4-beta.0.yuqsvy.vjjm9++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Promise.await (/home/storyteller/.meteor/packages/meteor-tool/.2.5.4-beta.0.yuqsvy.vjjm9++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
    at /tools/cli/main.js:1535:7

```

**Comment by StorytellerCZ** [comment]
Never mind, it looks like that is something new that has popped up in my application. Tried to downgrade and still run into this.

**Comment by StorytellerCZ** [comment]
Tried, looks good.

**Comment by harryadel** [comment]
@renanccastro since this PR already includes bundle packages update can we include #11837 too?

**Comment by filipenevola** [comment]
This version is not going to be published due to an error in Windows tarball (read the description)

**Comment by harryadel** [comment]
The link is broken.

**Pull request closed without merging**
