### PR TITLE
Allow `meteor mongo` to connect to any MONGO_URL

### PR DESCRIPTION
**Pull request by nicodmf**
Hello,

The command `meteor mongo` should wwork with variable MONGO_URL and now do.

Normally no change on actual process.

I don't see tests on this part. As the change is little and i have no time to redraw test for all this command, i pull request as it. (but if you will indicate tests that i can to complete quickly, I will do.).

Best Regards

Link to #7064

### CODE REVIEW

**Comment by nicodmf** [comment]
it's done.

So after read the tests, it is only one error : 

tinytest - mongo-livedata - oplog - drop collection/db : !!!!!!!!! FAIL !!!!!!!!!!!
{"groupPath":["tinytest","mongo-livedata","oplog"],"test":"drop collection/db","events":[{"sequence":8747,"type":"fail","details":{"type":"assert_equal","expected":"[\"removed\",\"xuLgcmT7reAe7zTyT\"]","not":false}}],"server":true}i have one error : 

i don't see the link with the mongo command to be honestly...

**Comment by abernix** [comment]
Thanks for taking the time to make a pull-request.

Don't worry about the failed test – that one test (unfortunately) fails once in a while.  I re-ran it for you and it ran fine.

But!  This will need to be discussed in the original issue and agreed upon before it will be accepted and some changes might be necessary!

**Comment by tmeasday** [comment]
Thanks for this PR. As outlined in the [Contribution guide](https://github.com/meteor/meteor/blob/devel/Contributing.md#submitting-pull-requests) we are now waiting for features to be confirmed before we consider merging a PR.

I'm going to close this now, we can re-open it once the feature has been confirmed.

**Comment by nicodmf** [comment]
I'm not sure that is just a feature, for me at least at beginning this was more a bug or a correction as the process is unclear : 

- you can connect distant db on deployment
- but not near db in dev

This is at least a strange effect.

**Comment by abernix** [comment]
@nicodmf Let's discuss in the issue not in this PR.

**Pull request closed without merging**
