### PR TITLE
update actions used in GitHub workflows to newest versions

### PR DESCRIPTION
**Pull request by striezel**
- bump actions/checkout to v3
- bump actions/setup-node to v3
- bump actions/labeler to v4
- bump nwtgck/actions-netlify to v1.2.4

### CODE REVIEW

**Review by StorytellerCZ — APPROVED** [review]
This is pretty neat!

**Comment by striezel** [comment]
> This is pretty neat!

:)

Well, it's just some maintenance work, but it should be done to keep the CI pipelines up to date.

**Comment by striezel** [comment]
@Grubba27:
Friendly reminder, because it's been more than a month now, so it looks like this PR somehow slipped through.
Or is there something here that needs to be fixed before this PR can be merged?

**Comment by Grubba27** [comment]
Sorry! It did got lost while I was working other things, I only have second thoughts on if upgrading things to v2 it may break things?

**Comment by striezel** [comment]
> I only have second thoughts on if upgrading things to v2 it may break things? (it did passed all the ci , just checked)

Yes, the CI checks have passed.

As for "upgradding things to v2" I am not sure to which upgrade you are referring, because there is no upgrade to v2. However, `actions/checkout` is upgrade _from_ v2 to v3, so I guess you mean that one? The relevant changes for [actions/checkout](https://github.com/actions/checkout) are:

> ## v3.1.0
> - Use @actions/core `saveState` and `getState`
> - Add `github-server-url` input
>
> ## v3.0.2
> - Add input `set-safe-directory`
>
> ## v3.0.1
> - Fixed an issue where checkout failed to run in container jobs due to the new git setting `safe.directory`
> - Bumped various npm package versions
>
> ## v3.0.0
>
> - Update to node 16

From experience with my own GitHub repositories as well as with some others where I performed that update I can say that the update of `actions/checkout` did not break anything. And due to the fact that the checks here have passed, I do not expect that upgrade to break anything here as well.

**Comment by striezel** [comment]
Meteor 2.9 has been released a few days ago, so what's the status on this?

**Comment by Grubba27** [comment]
> does you like it to be rebased on top of the current devel? (It should merge without conflicts, even without a rebase.)
Yes! please!

**Comment by striezel** [comment]
> Yes! please!

Done. :)

**Pull request merged**
