### PR TITLE
CS: Skips loading of the dependency cache if nothing has changed.

### PR DESCRIPTION
**Pull request by devgrok**
This is an alternate solution to https://github.com/meteor/meteor/issues/2950

A fix for issue https://github.com/meteor/meteor/issues/5764

An optimisation of the "preparing packages" stage from 2600ms (in release 1.2.1) to 800ms (in local-dev).

Skips loading of the dependency cache if nothing has changed.
Excludes the cache from equality check as it shouldn't have changed.

### CODE REVIEW

**Comment by tmeasday** [comment]
Thanks @devgrok, this seems reasonable but I'll need someone to take a closer look.

**Comment by avital** [comment]
Thanks @devgrok, this looks really great! I'm going to merge it in with an additional comment.

**Comment by avital** [comment]
Merged in a576bda03a584dda3ac5e6200bb207008cefd482

**Comment by platea** [comment]
Thanks @devgrok it really works!

**Pull request closed without merging**
