### PR TITLE
Update meteor-babel to 7.10.0 and TypeScript to 4.0.3

### PR DESCRIPTION
**Pull request by afrokick**
<del>Blocked by https://github.com/meteor/babel/pull/35</del>

### CODE REVIEW

**Comment by Julusian** [comment]
Whats the status of this?
It looks like the PR this was blocked on has been merged, so could this be merged too?

**Comment by afrokick** [comment]
@Julusian thanks. I think we should waiting for https://github.com/meteor/babel/pull/35 merge

@filipenevola FYI

**Comment by filipenevola** [comment]
@afrokick meteor-babel 7.10.0 is published.

**Comment by afrokick** [comment]
@filipenevola ready to review&merge

**Comment by filipenevola** [comment]
I would prefer minor versions (and not patch) and then include in the next beta of 2.0, is that ok @afrokick ?

**Comment by afrokick** [comment]
@filipenevola great

**Review by filipenevola — APPROVED** [review]

**Comment by rijk** [comment]
@filipenevola Would it make sense to keep the major version aligned with the Typescript major version? So make this update package version `4.0.0` for instance?

**Comment by Julusian** [comment]
@rijk I agree with you there. It threw me at first when I found that 3.7.6 is actually typescript 3.8

**Comment by filipenevola** [comment]
We are going to release this update in a special release to unblock this, 1.12

**Comment by filipenevola** [comment]
It will continue here #11225

**Comment by rijk** [comment]
Will we get it in the Meteor 2 beta as well?

**Comment by filipenevola** [comment]
Hi @rijk, @afrokick asked to have this available before 2.0 so we are going to have it in a beta soon, on 1.12 😉 

I'm just fixing some tests that are broken, when they are passing I'm going to publish the first beta of 1.12 and hopefully releasing the final version tomorrow or around that.

Check the progress here #11225

**Pull request closed without merging**
