### PR TITLE
Fix for #6191

### LINKED ISSUE #6191: meteor add [package] command omits Description
If I compare .meteor/packages output and meteor list command it is clear that meteor add [package] command omits important part of package - its description.

.meteor/packages 

```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
blaze-html-templates    # Compile .html files into Meteor Blaze views
session                 # Client-side reactive dictionary for your app
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library

standard-minifiers      # JS/CSS minifiers run for production mode
es5-shim                # ECMAScript 5 compatibility for older browsers.
ecmascript              # Enable ECMAScript2015+ syntax in app code

autopublish             # Publish all data to the clients (for prototyping)
insecure                # Allow all DB writes from clients (for prototyping)
ovcharik:alertify
accounts-password
```

meteor list

```

accounts-password     1.1.4  Password support for accounts
autopublish           1.0.4  (For prototyping only) Publish the entire d...
blaze-html-templates  1.0.1  Compile HTML templates into reactive UI wit...
ecmascript            0.1.6* Compiler plugin that supports ES2015+ in al...
es5-shim              4.1.14  Shims and polyfills to improve ECMAScript ...
insecure              1.0.4  (For prototyping only) Allow all database w...
jquery                1.11.4  Manipulate the DOM using CSS selectors
meteor-base           1.0.1  Packages that every Meteor app needs
mobile-experience     1.0.1  Packages for a great mobile user experience
mongo                 1.1.3  Adaptor for using MongoDB and Minimongo ove...
ovcharik:alertify     0.3.11  JavaScript Alert/Notification System for M...
session               1.1.1  Session variable
standard-minifiers    1.0.2  Standard minifiers used with Meteor apps by...
tracker               1.0.9  Dependency tracker to allow reactive callbacks
```

### PR DESCRIPTION
**Pull request by lassombra**
This should do the trick.  I don't know whether you'd prefer the output use tab characters or spaces.  This version uses tab characters.  Fixes #6191.

### CODE REVIEW

**Comment by stubailo** [comment]
@lassombra it looks like this will add the descriptions for all packages listed. Can we add the description just for the new packages added with `meteor add`?

**Comment by lassombra** [comment]
@stubailo That is correct, it does affect all of them.  

The tool chain at the point of "add" doesn't actually have the catalog contents, so doesn't know the description.  I'll have to look for a point that has the catalog information loaded, has the list of parameters added, and has the line definitions.  I'll see if I can get to that either this evening or tomorrow evening and let you know what I come up with.

**Comment by stubailo** [comment]
Yeah, I just think it would be really weird if your whole `.meteor/packages` file was rewritten every time you use `meteor add`.

**Comment by lassombra** [comment]
Interestingly, technically it is fully rewritten every time.  Like I said though, I'll dig a bit deeper and see what I can find for a more opportune time to make the change.

**Comment by zol** [comment]
Hey, Thanks for the PR. I'm going to close it as it hasn't had activity for a long time. Please re-base your additional work off the current `devel` and ping me here on this issue or open a new one PR.

**Pull request closed without merging**
