### PR TITLE
Make check check inherited properties

### PR DESCRIPTION
**Pull request by sebakerckhof**
Fixes https://github.com/meteor/meteor/issues/6140

### CODE REVIEW

**Comment by stubailo** [comment]
Merged! Thanks!

https://github.com/meteor/meteor/commit/eb897bc91744946390bf38e56f80780a9786b801

**Comment by mitar** [comment]
This goes directly against current documentation. Citing:

> Matches an Object with the given keys, with values matching the given patterns. If any pattern is a Match.Optional, that key does not need to exist in the object. The value may not contain any keys not listed in the pattern. **The value must be a plain Object with no special prototype.**

Also, the `Object` documentation says:

> Matches any **plain** Object with any keys;

Personally, I have been using this property of `check` to make sure nobody gives me any fancy object which has overridden not just property, but getters, setters, and other fancy stuff which might have side effects and so on.

I think this is pretty drastic backwards incompatible change and I would vote to revert it.

If people need this feature, make something like `Match.FullObject({key1: pattern1, key2: pattern2, ...})` and `Match.FullObjectIncluding({key1: pattern1, key2: pattern2, ...})`.

**Comment by sebakerckhof** [comment]
> Personally, I have been using this property of check to make sure nobody gives me any fancy object which has overridden not just property, but getters, setters, and other fancy stuff which might have side effects and so on.

Well, then you might have security issues, because check just ignored the prototype before this PR.

**Comment by mitar** [comment]
Yes. The fix should probably then be that it throws an error if it is not a plain object.

**Comment by sebakerckhof** [comment]
But checking if an object is a plain object is quite tricky (You'd have to check all property descriptors, what if `Object` itself is modified, etc.) While on the other hand if you really want to ensure an object is a plain object, you can easily sanitize it before giving it to check (`JSON.parse(JSON.stringify(foo))`)

**Comment by mitar** [comment]
> But checking if an object is a plain object is quite tricky

I have the following functions in my code often:

```
function isTrueObject(value) {
  return _.isObject(value) && !_.isArray(value) && !_.isFunction(value);
}

function isPlainObject(obj) {
  if (isTrueObject(obj)) {
    return false;
  }
  if (obj.constructor !== Object) {
    return false;
  }
  return true;
}
```

I assume `Object` is not changed because it is on the server.

> you can easily sanitize it before giving it to check

The whole point of calling `check` is to have a simple one command to verify arguments of methods. Not that I have first to sanitize and then call `check`.

> I do agree I should have modified the docs with this PR, because currently the docs are not correct.

Yes, by that you are introducing backwards incompatibility. It is not just changing docs.

**Comment by stubailo** [comment]
> The fix should probably then be that it throws an error if it is not a plain object.

I agree, my mistake on accepting a PR that doesn't do this. Is this an easy check to make? @mitar should/can we just add the above code to check?

**Pull request closed without merging**
