### PR TITLE
Explain why package is top level

### PR DESCRIPTION
**Pull request by zodern**
When there are conflicts in the version constraints for a package, Meteor lists all of the constraints along with the path. Sometimes the path is simply `top level`. The meaning of `top level` doesn't seem to be common knowledge anymore (if it ever was), so this PR adds an explanation for why the package is top level (it is either a local package, or the constraint is from the release).

I haven't tested the code for top level packages from a release since when running Meteor locally every core package is a local package. I thought the meteor-tool might have a way to test this, but I didn't find one.

``` 
=> Errors while adding packages:             
                                              
While selecting package versions:
error: Conflict: Constraint caching-html-compiler@2.0.0-alpha300.16 is not satisfied by caching-html-compiler 1.2.1.
Constraints on package "caching-html-compiler":
* caching-html-compiler@=1.2.1 <- top level (is local package)
* caching-html-compiler@2.0.0-alpha300.16 <- static-html 1.3.3-alpha300.19

Conflict: Constraint templating-tools@2.0.0-alpha300.16 is not satisfied by templating-tools 1.2.2.
Constraints on package "templating-tools":
* templating-tools@=1.2.2 <- top level (is local package)
* templating-tools@2.0.0-alpha300.16 <- static-html 1.3.3-alpha300.19
* templating-tools@1.2.1 <- caching-html-compiler 1.2.1 <- static-html 1.3.3-alpha300.19

Conflict: Constraint caching-compiler@1.2.2 is not satisfied by caching-compiler 2.0.0-alpha300.19.
Constraints on package "caching-compiler":
* caching-compiler@=2.0.0-alpha300.19 <- top level (is local package)
* caching-compiler@1.2.2 <- caching-html-compiler 1.2.1 <- static-html 1.3.3-alpha300.19
```

### CODE REVIEW

**Review by Grubba27 — APPROVED** [review]

**Comment by zodern** [comment]
There's some edge cases this won't show the correct message for. This needs more work and testing.

**Comment by jankapunkt** [comment]
How is top-level defined, when being in a package (no .versions file present in folder; no Meteor project in parent folder)?

I currently can't publish a migrated package, which runs locally in a Meteor 3.0-beta.0 project fine but when publishing I get issues with "top level":

<details>
<summary>error output</summary>

```
=> Errors while initializing project:         
                                              
While selecting package versions:
error: Conflict: Constraint mongo@2.0.0-beta300.0 is not satisfied by mongo 1.16.8.
Constraints on package "mongo":
* mongo@~1.16.8 <- top level
* mongo@2.0.0-beta300.0 <- lai:collection-extensions 1.0.0-beta300.0
* mongo@1.10.1 || 1.12.0 || 2.0.0-beta300.0 <- aldeed:collection2 4.0.0-beta.7 <- local-test:lai:collection-extensions
1.0.0-beta300.0
* mongo@1.16.8 <- accounts-base 2.2.9 <- lai:collection-extensions 1.0.0-beta300.0
* mongo@2.0.0-beta300.0 <- dburles:mongo-collection-instances 1.0.0-beta300.0 <- local-test:lai:collection-extensions
1.0.0-beta300.0

Conflict: Constraint accounts-base@3.0.0-beta300.0 is not satisfied by accounts-base 2.2.9.
Constraints on package "accounts-base":
* accounts-base@~2.2.9 <- top level
* accounts-base@3.0.0-beta300.0 <- lai:collection-extensions 1.0.0-beta300.0
* accounts-base@3.0.0-beta300.0 <- local-test:lai:collection-extensions 1.0.0-beta300.0
```
</details>

packages point all to the latest dependencies. You can see the latest state in [this PR](https://github.com/Meteor-Community-Packages/meteor-collection-extensions/pull/26)

**Comment by zodern** [comment]
You probably are publishing with Meteor 2.14, which uses `mongo@1.16.8`. You can see this by running `meteor --version` to see what version is being used, and then `meteor show METEOR@2.14` to see what the constraints are. The uppercase `METEOR` is for viewing the meteor release track instead of the meteor package.

You can use `meteor publish --release 3.0-beta.0` to publish with Meteor 3.

**Comment by jankapunkt** [comment]
Thank you, it worked! I assumed that it was due to the 2.14 release being pinned globally, which is [why I was asking on the forums how to make the global Meteor point to 3.0](https://forums.meteor.com/t/how-to-update-global-meteor-to-3-0-beta/61091/2), which I couldn't work out but I didn't know that I can pin a specific release for publishing, since`--release` is not documented when typing `meteor publish --help`.

**Comment by StorytellerCZ** [comment]
@zodern can we get an update on this?

**Comment by zodern** [comment]
This uses the wrong approach. I think we need to instead track where top level packages come from instead of it trying to figure it out in the constraint solver.

**Pull request closed without merging**
