### PR TITLE
Added in missing Meteor.isDevelopment.

### PR DESCRIPTION
**Pull request by hwillson**
Hi guys - just a small change; `Meteor.isDevelopment` was missing in the docs. I've added it in below `Meteor.isCordova`. Thanks!

### CODE REVIEW

**Comment by reohjs** [comment]
There's also `Meteor.isProduction` too!

**Comment by stubailo** [comment]
Looks like it's already got docs, they just aren't included in the app!

https://github.com/meteor/meteor/blob/devel/docs/client/names.json

**Comment by hwillson** [comment]
@stubailo I noticed that as well, so I've just updated the docs to include the proper `autoApiBox` calls. Thanks!

**Comment by hwillson** [comment]
Thanks @reohjs - I've added `Meteor.isProduction` as well.

**Comment by stubailo** [comment]
Currently working on this PR!

**Comment by hwillson** [comment]
@stubailo I just noticed I missed the table of contents; I can submit the necessary changes unless you're working on them?

**Comment by stubailo** [comment]
Nah, I got it. This app is so convoluted, we really need to dispose of it asap and get a real docs app...

**Comment by hwillson** [comment]
Haha - I agree! Sorry, I noticed the missing bits afterwards - thanks for adding this in!

**Comment by stubailo** [comment]
It's OK, I actually had to upgrade JSDoc to a git branch version just to get it to read `async`/`await`, so it wasn't trivial.

**Pull request merged**
