### PR TITLE
Update test-in-browser dependencies 

### PR DESCRIPTION
**Pull request by harryadel**
- Update Blaze from 2.3.4 to 2.6.1
- Update https://github.com/JackuB/diff-match-patch library to latest version

I also thought about removing bootstrap since it's used for minimal stuff that can be easily replaced, what do you think?

### CODE REVIEW

**Comment by Grubba27** [comment]
sounds good! Thx a lot for your contruibuiton. I will check what is making the tests fail

**Comment by harryadel** [comment]
Most likely because of the exports, I don't have access to a computer so
please remidate it yourself, thank you!

**Comment by harryadel** [comment]
@Grubba27 Looks good?

**Comment by Grubba27** [comment]
Now looks good. Will make a remainder for this one. I'm thinking of making a 2.9.2, maybe this could go in that one.
Thanks a lot again for this PR @harryadel

**Pull request merged**
