### PR TITLE
Fix #9960 by adding hot-code-push to minimal skelet

### LINKED ISSUE #9960: Meteor create --minimal is forcing meteor server restart on client changes
I have been using --minimal template on my project and starting to notice some strange behavior - every time I change a template or CSS file meteor restarts the whole server which leads to full page reload.
`--full` template doesn't have the same problem when used with the same version - edit any style it triggers `client modified` and hot reload instead of full server restart.
I have just tried it on [a newly created](https://github.com/Maxim-Filimonov/meteor_bug_minimal_server_restart) project and it's still the same problem. 
```
=> meteor
# edit main.css in any way
=> Server modified -- restartin  [ProgressDisplayFull keepalivI20180607-17:54:37.161(8)? Greetings from /server/main.js!
=> Meteor server restarted
```
Do I need to add an extra package to make it work without full server restart?

### PR DESCRIPTION
**Pull request by StorytellerCZ**
Adding `hot-code-push` to minimal skeleton fixes and issue where the server would reload when a change occurred on client.

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
@filipenevola @renanccastro what are your thoughts on this change?

**Comment by filipenevola** [comment]
I believe the root cause is the same problem that I'm fixing here https://github.com/meteor/meteor/pull/11381

This PR is going to be closed as @zodern is going to implement a different approach to solve the same issue.

@zodern do you agree with me? Because if your fix is going to fix this restart for the minimal as well, so we don't need to merge this PR.

**Comment by zodern** [comment]
If an app doesn't have the `autoupdate` package, Meteor always does a full rebuild: https://github.com/meteor/meteor/blob/ffcfa5062cf1bf8a64ea64fef681ffcd99fe7939/tools/runners/run-app.js#L657-L660 If `hot-code-push` fixes the issue, then this is a good solution since it should only include `autoupdate` in development, and maybe this also solves https://github.com/meteor/meteor-feature-requests/issues/354

**Review by zodern — DISMISSED** [review]

**Comment by zodern** [comment]
Is the reason `hot-code-push` is missing because it increased the production bundle size?

If that is still a concern, one option might be to add Autoupdate as a dependency to `hot-module-replacement` (I'm not sure why it isn't already), and add `hot-module-replacement` instead. Since it is a dev dependency, it and `Autoupdate` should be excluded from the production bundle. This might also solve https://github.com/meteor/meteor-feature-requests/issues/354.

**Comment by zodern** [comment]
> @zodern do you agree with me? Because if your fix is going to fix this restart for the minimal as well, so we don't need to merge this PR.

Meteor always does a full rebuild unless the app uses the `autoupdate` package:
https://github.com/meteor/meteor/blob/ffcfa5062cf1bf8a64ea64fef681ffcd99fe7939/tools/runners/run-app.js#L657-L660

The changes I am making to watching won't change that.

**Comment by StorytellerCZ** [comment]
Changing for `autoupdate` package.

**Comment by filipenevola** [comment]
@StorytellerCZ let's resume what is going on here.

Did you try to add hot-code-push to minimal but it added more code to the bundle size, is that the issue with this approach? How much was added?

I would like to hear from people using the minimal in production. Is it a real use case? I will ask about this in our community [Slack](https://join.slack.com/t/meteor-community/shared_invite/enQtODA0NTU2Nzk5MTA3LWY5NGMxMWRjZDgzYWMyMTEyYTQ3MTcwZmU2YjM5MTY3MjJkZjQ0NWRjOGZlYmIxZjFlYTA5Mjg4OTk3ODRiOTc).

**Pull request merged**
