### PR TITLE
Error improvements

### PR DESCRIPTION
**Pull request by lalomartins**
Partial attempt at https://github.com/meteor/meteor/issues/2232, also removing some browser warnings by eliminating `__proto__` manipulation

### CODE REVIEW

**Comment by stubailo** [comment]
This looks like the beginning of a good change, since error reporting is something that could be much improved in Meteor.

However, it probably won't be possible to accept this without a good set of tests ensuring that errors are printed correctly - then we can run them in all browsers through our testing system and make sure that we don't break it in the future.

Do you have any ideas about how to test this?

**Comment by lalomartins** [comment]
For a more reliable test, we'd want to hook up webdriver and check the actual console output. I think it might be overkill in this case, though.

What's the level of isolation in tinytest? A quick look at the source indicates it's zero… hmm. The straightforward way to test these is to stub/replace console.log, but I can see that having all sorts of side effects.

On the other hand, maybe adding a test-friendly console object in tinytest itself could be a good idea? But that would be a separate project.

**Comment by stubailo** [comment]
> The straightforward way to test these is to stub/replace console.log, but I can see that having all sorts of side effects.

I think that could be sufficient, but would that method work in IE8/9?

**Comment by lalomartins** [comment]
I just had a chance to check it, and yes, it works on 8 and 9.

I'll try to set aside some time this weekend to work on this — both the tests and refreshing the branch.

**Comment by lalomartins** [comment]
For the record — I'm not using Meteor enough ATM that I can justify the time investment, or in fact, that I'd remember how to do this. Next time I have a project, I'll refresh this branch and give the testing a go. Might be later this month, but it's not certain yet.

**Comment by stubailo** [comment]
OK, going to close it for now then.

**Pull request closed without merging**
