### PR TITLE
Allow all pending observe callbacks to be run before stop

### PR DESCRIPTION
**Pull request by mitar**
This allows fixing a really nasty race-condition between when observe callbacks are scheduled and when they are run. Currently, you can get observe callbacks scheduled, you can call stop, and then callbacks are run. Which can be quite surprising (that callbacks are run after observe was stopped). Especially if code around stop also cleaned some things observe callbacks expect to still have.

Alternatively, we might want to expose a `flush` method on the handle, which flushes pending callbacks when called?

Also, should handle stop in fact remove all pending callbacks? So I think there should be maybe three options:
* leave callbacks to run after stop
* run all callbacks before stop
* drop all pending callbacks

### CODE REVIEW

**Comment by stubailo** [comment]
Hey @mitar, this is a great idea. I would be happy to accept this feature, but we can't merge it without tests/documentation. If you can add those, I will take a deeper look.

**Comment by mitar** [comment]
BTW, I was thinking of maybe making this into a separate handler method. So `flush`. So that you can call it even without `stop`.

**Comment by mitar** [comment]
I have no idea how to do tests, because this is very asynchronous. :-)

**Comment by mitar** [comment]
I improved implementation and the API.

**Comment by mitar** [comment]
No idea how to make a test for this though. It involves two fibers for the complicated code path.

**Comment by tmeasday** [comment]
Thanks for this PR, sorry we never got around to merging it. We are currently cleaning up the repository and removing old PRs; if you think this PR still has value and are interested in resurrecting it, we encourage you to re-submit it against current `devel`.

**Comment by mitar** [comment]
Done: https://github.com/meteor/meteor/pull/6917

Not sure why resubmitting is necessary, I could just push to the same branch and update this pull request.

**Pull request closed without merging**
