### PR TITLE
Enable Android development on Windows

### PR DESCRIPTION
**Pull request by sedouard**

### CODE REVIEW

**Comment by martijnwalraven** [comment]
Wow, really happy with this! Great work! I hope we can get some people testing this.

One comment I have is that before we merge the PR it would be nice to split the single commit up a little bit. In particular, maybe we could separate removing checks for Windows support from actual fixes. And there seem to be some unrelated code formatting/whitespace changes in there that might be better to leave out so as not to be confusing.

**Comment by martijnwalraven** [comment]
Oh, and I think there are more places where we check for Windows and block certain features or print a warning. But I could take a look at those myself.

**Comment by sedouard** [comment]
ugh yeah i'm noticing those tabbing diffs. didn't show up on my local diff. I'll split up the fixes between commits.

**Comment by martijnwalraven** [comment]
Thanks! Here is one more place where we check for Windows: https://github.com/meteor/meteor/blob/devel/tools/cli/commands.js#L864-L867

**Comment by Testato** [comment]
+1

**Comment by ritazh** [comment]
:+1:

**Comment by Tibo46** [comment]
Hi !
How can we test that?
I'll be happy to give it a try :)

**Comment by sedouard** [comment]
Hey @tibo!

Here's what you gotta do:

Install the [Java JDK](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)
Install [Android Studio for Windows](http://developer.android.com/sdk/index.html)

Create a new android emulator, ensure it works, or alternatively plug in your android device. (Needs to be API version 22).

```bash
# clone my repo
git clone https://github.com/sedouard/meteor.git
# checkout the feature branch
git checkout fix_4155
# use meteor from source
cd .\meteor
.\meteor create <project name>
# add android platform
cd <project name>
..\meteor add-platform android
# run on emulator
..\meteor run android
# run on device
..\meteor run android-device
```

@martijnwalraven can correct me if I'm wrong.

**Comment by martijnwalraven** [comment]
That sounds about right. I've been thinking though, and testing it on top of Meteor 1.2 might not make much sense at this point. Maybe I should just go ahead and merge it on my branch so we can release it as part of the next Meteor 1.3 beta.

**Comment by sedouard** [comment]
I thought the `devel` branch is where 1.3 is being developed? The changes are against that branch...

**Comment by tibo** [comment]
@sedouard for a second I though I was doing some Android development on Windows.
I think you meant @Tibo46 :)

**Comment by martijnwalraven** [comment]
@sedouard: The Cordova work hasn't been merged yet, it's on the `cordova-improvements` branch for now.

**Comment by sedouard** [comment]
ah ok.  @martijnwalraven if you merge, I can commit to fixing any issues that pop up from beta testers

**Comment by nirajpd** [comment]
I am going to give it a try, good work guys!

**Comment by martijnwalraven** [comment]
@sedouard: Great, thanks!

**Comment by martijnwalraven** [comment]
@sedouard: I just released `1.3-cordova-beta.3`, which includes your pull request. Thanks again for your work, really looking forward to having more people test this. The CI failures are probably not your fault, there are existing issues with the testing infrastructure.

**Comment by Tibo46** [comment]
Guys, amazing job! It's working :D
I had problems to make it works at the beginning, my app was inside my "Google Drive" folder and "meteor run android" device was not working.
So i moved the app inside "C:/userName/myApp" and from there i was able to run it easily.

**Comment by nirajpd** [comment]
@martijnwalraven  , I was using the checkout procedure given by @sedouard :
================================
 # clone my repo
git clone https://github.com/sedouard/meteor.git
# checkout the feature branch
git checkout fix_4155
=========================
Now that the 1.3-cordova-beta.3 is out, how does the process change? I would appreciate any help on that. I thought I downloaded the 1.3-cordova-beta.3 , but meteor  --version continues to display Meteor 1.2.1. Any help would be appreciated.

**Comment by martijnwalraven** [comment]
'meteor update --release 1.3-cordova-beta.3' from your app directory should do the trick.

**Comment by nirajpd** [comment]
Awesome, that did it!

**Comment by nirajpd** [comment]
Seems to be quitting at the last stage- I see the simulator come up, but then the meteor app exitwithcode 1
nirajpd@ACERMINI C:\meteor\myapp                                                  
> meteor run android                                                            
[[[[[ C:\meteor\myapp ]]]]]                                                     
                                                                                
=> Started proxy.                                                               
=> Started MongoDB.                                                             
=> Started your app.                                                            
                                                                                
=> App running at: http://localhost:3000/                                       
   Type Control-C twice to stop.                                                
                                                                                
=> Errors executing Cordova commands:                                           
                                                                                
   While running Cordova app for platform Android with options --emulator:      
   Error: Command failed:                                                       
   C:\meteor\myapp\.meteor\local\cordova-build\platforms\android\cordova\run    
   --emulator --emulator                                                        
   No emulator specified, defaulting to                                         
   AVD_GalaxyNexus_ToolsForApacheCordova                                        
                                                                                
   FAILURE: Build failed with an exception.                                     
                                                                                
   * What went wrong:                                                           
   Unable to start the daemon process.                                          
   This problem might be caused by incorrect configuration of the daemon.       
   For example, an unrecognized jvm option is used.                             
   Please refer to the user guide chapter on the daemon at                      
   http://gradle.org/docs/2.2.1/userguide/gradle_daemon.html                    
   Please read the following process output to find out more:                   
   -----------------------                                                      
   Error occurred during initialization of VM                                   
   Could not reserve enough space for object heap                               
   Error: Could not create the Java Virtual Machine.                            
   Error: A fatal exception has occurred. Program will exit.                    
                                                                                
                                                                                
   * Try:                                                                       
   Run with --stacktrace option to get the stack trace. Run with --info or      
   --debug option to get more log output.                                       
   { [Error: cmd: Command failed with exit code 1] code: 1 } 'Error: cmd:       
   Command failed with exit code 1\n    at ChildProcess.whenDone                
   (C:\\meteor\\myapp\\.meteor\\local\\cordova-build\\platforms\\android\\cordov
a\\node_modules\\cordova-common\\src\\superspawn.js:139:23)\n                   
   at ChildProcess.emit (events.js:98:17)\n    at maybeClose                    
   (child_process.js:766:16)\n    at Process.ChildProcess._handle.onexit        
   (child_process.js:833:5)'                                                    
   at ChildProcess.exitCallback (C:\tools\utils\processes.js:151:23)            
   at ChildProcess.emit (events.js:98:17)                                       
   at Process.ChildProcess._handle.onexit (child_process.js:820:12)             
                                                                                
ExitWithCode:1

**Comment by sedouard** [comment]
@nirajpd it is a requirement from Cordova, not meteor that you use API version 22. That could be causing the problem

**Comment by martijnwalraven** [comment]
Actually, we upgraded to the latest Cordova version in Meteor 1.3, do the requirement is now API 23.

**Comment by sedouard** [comment]
@martijnwalraven what branch is the beta built from?

**Comment by martijnwalraven** [comment]
'cordova-improvements'

**Comment by lgframe** [comment]
Not able to get android build either by 1) 'meteor update --release 1.3-cordova-beta.3'  as per by martijnwalraven  nor 2)  git clone https://github.com/sedouard/meteor.git  process outlined by sedouard 

On my windows 8 professional, I have java 1.8.0.25 and Android SDK tool 24.4.1, 22.0.1 and 21.1.2 installed and on command "meteor add-platform android",  I get an error "This command is not yet available on Windows._"

Please direct...

**Comment by nirajpd** [comment]
What is the output of:

meteor --version

This would tell us if your update to 1.3- Cordova - beta. 3 was successful
or not.

**Comment by martijnwalraven** [comment]
@Igframe: Are you sure you've performed `meteor update --release 1.3-cordova-beta.3` inside your app directory? You will have to do this for every app you want to upgrade.

**Comment by martijnwalraven** [comment]
A new Meteor 1.3 beta is now available, please give it a try: https://github.com/meteor/meteor/issues/6266.

I would love to hear from Windows users whether this is working for them.

**Comment by y01s** [comment]
It worked for me! I built an android app and run it on my phone.

**Comment by nirajpd** [comment]
Did you use an Android emulator or a physical device during the development?

**Comment by y01s** [comment]
physical device. I tried the android emulator first, but there was an error and it was very slow. then I ran on my phone, and it just worked

**Comment by nirajpd** [comment]
Thanks, I ran into same issue, the app wouldn't load on the emulator!

**Comment by y01s** [comment]
what did the error say? something about a "file://app" error? because that's what happened to me on the emulator and on the first try on my phone

**Comment by nirajpd** [comment]
I recall it just doing nothing, the emulator had a blank screen with
Android logo.

**Comment by y01s** [comment]
for my case It showed a splash screen first with meteor logo on it

**Pull request closed without merging**
