### PR TITLE
Minimongo separation

### PR DESCRIPTION
**Pull request by Slava**
Extract diff functions and MongoId with `idStringify` and `idParse` functions to separate packages.

@glasser @justinsb

### CODE REVIEW

**Comment by RobertLowe** [comment]
Nice refactoring :+1: 

When I was refactoring the `ddp` it felt odd that it depended on `minimongo`. Nice @Slava.

**Comment by glasser** [comment]
Looks good on the whole.  Only comments are a few naming things:

- Reading `MongoId.ObjectID` looks *weird*, with the inconsistent capitalization of the `d`. I guess we get the capital `D` from [the Node Mongo driver](http://mongodb.github.io/node-mongodb-native/1.4/api-bson-generated/objectid.html) which is actually inconsistent with [the Mongo shell](http://docs.mongodb.org/manual/reference/object-id/).  Anyway, `Mongo.ObjectID` is part of our public API so we probably should stick with the capital D... just wondering if maybe it should be `MongoID` too?
- idStringify and idParse probably should be non-underscored on `MongoId`. Makes sense for them to be hidden on LocalCollection, where they're a weird inner detail that's not really about being a local collection, but they fit in fine on `MongoId` and are used from other packages.  If the whole point of this change is to turn weird internal APIs on the wrong package into public APIs in their own package, might as well not have underscored things still be called across package boundaries.

**Comment by Slava** [comment]
@glasser addressed both of your points with a mass search-replace

**Comment by glasser** [comment]
lgtm

**Comment by Slava** [comment]
thanks, merged

**Pull request merged**
