### PR TITLE
[wip] mongo: restart underlying oplog tail every 30 seconds without a doc

### LINKED ISSUE #8598: Oplog tailing stalls (usually during MongoDB failover) (maybe primarily with Compose Classic)
Using the `replicaSet=...` option in `MONGO_URL` or `MONGO_OPLOG_URL` causes auto-reconnects to be disabled on that connection. Since including this parameter is the officially recommended approach, most people using Meteor in prod don't have auto-reconnecting DB connections. I am using Meteor 1.4.3.2, but I think this bug has pretty much always existed.

The bug is very easy to reproduce. Locally set `MONGO_URL` to a mongo url that includes `replicaSet=...`. Open up the meteor shell and do a find on a collection; the query should successfully complete. Now reset the network connection on your computer. Try the query again; the query should hang and eventually fail. Now try this same series of steps after removing the `replicaSet` parameter from `MONGO_URL`; notice that the query won't fail. The steps for replicating the problem for `MONGO_OPLOG_URL` is exactly the same.

Note: If removing the `replicaSet` parameter crashes your server, then make sure there is only a single host referenced in `MONGO_URL` and that this host is the primary. 

The main thing going on here is that by passing in the `replSet` parameter the Mongo driver uses the `replset` connection type rather than the `server` connection type. As you can see [here](https://github.com/mongodb/node-mongodb-native/blob/2.2/lib/replset.js#L135) `replset` connections ignore the auto-reconnect property, but `server` connection types [do not](https://github.com/mongodb/node-mongodb-native/blob/2.2/lib/server.js#L129).

You can view info about the `MONGO_URL` connection by typing `Meteor.users._driver.mongo.db.serverConfig` into the meteor shell, and info about `MONGO_OPLOG_URL` by typing `Meteor.users._driver.mongo._oplogHandle._oplogTailConnection.db.serverConfig` into the meteor shell.

This may be due to a relatively recent change in the mongo driver that happened on June 14th, 2016. [Here is the commit](https://github.com/mongodb/node-mongodb-native/commit/412b50d53dc8e958d3b726fc7f66fe0447b9da66#diff-3995a38a37cf6b7ad44d4c8e63893046R131). But it is also possible that auto-reconnect was never supported for `replset` connections, and that commit is just refactoring the code to reflect that fact. Hard to tell exactly. In any case, it isn't supported anymore. 

Seems like this problem is related to a bunch of issues people have been having, #5773 being the most popular.

Not really sure the best way to fix this. For now I've just dropped the `replicaSet` parameter and made sure that each connection URL only references the primary host, not the secondary. 

What is the purpose of passing in info about the secondary node (which is the only thing that is forcing us to use the `replicaSet` parameter)? It doesn't really seem to be used for anything except for failover support, and Meteor can't handle failover. I guess if you keep both hosts in the connection URL, Meteor will connect to the new primary upon restart.

The only solutions I can think of are:
  (1) Stop passing in the `replicaSet` parameter
  (2) Patch the mongo driver so that `replset` connections support auto-reconnects.
  (3) Handle reconnects at the Meteor level

Anyways, this is a pretty important bug. We had some serious outages over the past week because Compose reset all db connections a few times while debugging something unrelated on their end.

### PR DESCRIPTION
**Pull request by glasser**
Workaround for #8598: the Node Mongo driver has at least one bug that can lead
to query callbacks never getting called (even with an error) when leadership
failover occur.

Note that while we did fix one Node Mongo driver bug and close #8598, we've
heard reports that there are more similar issues, so this workaround seems like
a good plan.

### CODE REVIEW

**Comment by glasser** [comment]
I haven't seriously tested this in production — it's left over from my original work on #8598 before finding a different bug. If you'd like to test this out, try:

```
meteor add mongo@1.4.6-oplogrestart.0
```

**Comment by veered** [comment]
I'm the original opener of https://github.com/meteor/meteor/issues/8598 and I can verify that we are still experiencing this issue. It wasn't much of a problem for a long time, but recently we've started having many more leadership failovers.

It seems that particular oplog-enabled observes get stuck in the "QUERYING" phase on the initial query. I've never been able to reproduce locally but it happens in production to a couple observes almost every time theirs a leadership failover.

**Comment by veered** [comment]
Also, is it the case that upgrading the mongo driver to the newest version will fix the issue? https://github.com/mongodb-js/mongodb-core/pull/224

**Comment by glasser** [comment]
@veered No, we already have the fix that you linked, in npm-mongo@2.2.31.  There probably are just more similar bugs.

It is conceivable that upgrading will help anyway (there have been some big changes to the driver, and hopefully some of them have been to connection management, but who knows).

For what it's worth, I don't work regularly on the Meteor framework these days, so I'd really like other folks who are seeing this issue to evaluate this PR and see if it helps the problem without causing other issues.

**Comment by benjamn** [comment]
Is there any chance this could be related to (or might help mitigate) [this problem](https://forums.meteor.com/t/meteor-login-method-never-invokes-callback-blocks-all-future-rpc-calls/36305) with login callbacks?

**Comment by glasser** [comment]
Very likely.

**Comment by veered** [comment]
I've been in correspondence with our Mongo support rep about this, and they have opened an issue in JIRA.

https://jira.mongodb.org/browse/NODE-1388

**Comment by ubercolin** [comment]
@glasser The symptoms here sound awfully similar to what we've been experiencing with our production setup on Galaxy. The original issue #8598 made reference to this being primarily a Compose issue; do you think this is still the case (we're on Atlas)?
The other problem we've had with our issue is that we've never found a way to reproduce this on demand. I'd love to try out the 1.4.6 fix, but it'd be helpful to have a way to put our staging server into this state so that we could verify it is the same issue (and verify the fix). Any suggestions on a way to reproduce the problem?

**Comment by glasser** [comment]
The bug I fixed previously was definitely not a Compose issue — it was a bug in the upstream Mongo driver for Node. The connection management code is not very carefully written and there are almost certainly more bugs in it. We aren't on the latest version of the upstream module, but unless it has been rewritten from scratch it most likely still has similar bugs.  This PR is an attempt to avoid the worst impact of these bugs in Meteor.

**Comment by abernix** [comment]
@veered @ubercolin Have you been able to try `mongo@1.4.6` to see if it helps your issue?  Unfortunately, I don't have a way to reliably reproduce the problem.

**Comment by ubercolin** [comment]
@abernix Yes, we deployed this to our production system about 10 days ago, and it seems like it's helping. I'm still not positive this is the same issue we were seeing, but not having seen the issue for that period is very encouraging (it was rare that we could run that long without seeing the issue; usually happened multiple times a day).
So, anecdotally, I'd say this appears to be solving the problem and we haven't seen any new issues crop up as a result of the change.

**Comment by glasser** [comment]
I haven't had the chance to look into it myself, but a user who tried 1.4.6 did say that they are seeing the hit client-side timeout error every 30 seconds in the logs.

**Comment by veered** [comment]
Will this make it into Meteor 1.7?

**Comment by benjamn** [comment]
@veered It got cherry-picked, I believe? https://github.com/meteor/meteor/commit/afb7d23d045602cd7f9d4b7ae61081c4bcc3b12f

**Comment by veered** [comment]
Awesome :)

**Comment by benjamn** [comment]
This should be fixed in Meteor 1.7 (using `mongo@1.5.0`). Thanks @glasser!

**Pull request closed without merging**
