### PR TITLE
Tree shaking

### PR DESCRIPTION
**Pull request by renanccastro**
Tree shaking! 😄 

In this PR the focus will be on removing unused exports and code from the final bundle.

## Description
Tree-shaking is a technic that the bundler uses to remove unused files and code from the final bundle. This PR implements 2 strategies:

1. Remove unused Files, by checking es6 imports/exports
2. Remove unused exports, by checking used imports.

This PR does not implement yet a verification for actual usage in the code, for tree shaking. It is restricted to imports, and also deals with dynamic and nested imports.

### app
For enabling tree shaking in your app, simply add the flag:
> sideEffects: false

to your package.json.
### packages
For packages, you can use on package.js the following:
>  api.setSideEffects(false);

inside the Package.onUse section.

## Checklist
- [x] Get a map of imports by static analyzing all isopacks
- [x] Convert relative import paths to absolute ones
- [x] Transform the resulting tree in the bundler to remove unused reify transformed exports: module.exports({ a => ...}).
- [x] Create a flag for packages.js to mark side effect free
- [x] Exclude packages with side effects from the elimination
- [x] Deal with const { ClientStream } = require("meteor/socket-stream-client");

## Improvements

- [ ] Improve import-scanner performance. Today, it's necessary to get rid of AST cache, as we need to check every possible usage for import/exports. One option is to use as the key, the parent->file path, instead of just the file key.
- [ ] Do static analysis to detect unused/used variables and use this info for tree shaking

## Current issues/decisions:
- Packages global variables: today, when adding a new meteor package, ex: meteor/logs, it will end up polluting the global scope and it's not even necessary to import it to use it's exported symbols. Solution: Only make tree shaking available for "es6" ready meteor packages, they will have to signal the package as side effects free, and all imports/exports will have to be done.
- [X] Missing bare files from client/compatibility folders.
- [X] "undefinedundefined" symbol on dynamic imports - it was caused by source maps missing after removing symbols
- [X] Aliases causes loop on some modules

Pending Decisions:
- [ ] Only run it on production builds? If we have a major "wrong" import, the local development build can have bad performance, or not be responsive at all. Think about import @material-ui/icons, for example.

Results until now:
- importing from lodash-es is getting only what is imported, ex: import { add } from 'lodash-es', is bundling only the add.js file and the add() function.

### CODE REVIEW

**Comment by sebakerckhof** [comment]
Won't all packages need to keep the side effects for backwards compatibility?

**Comment by renanccastro** [comment]
> Won't all packages need to keep the side effects for backwards compatibility?

Yes, that's the idea @sebakerckhof. We will keep packages as sideEffects: true, unless specified with api.setSideEffects(false) inside package.js

**Comment by sebakerckhof** [comment]
@renanccastro But is there a difference between api.sideEffects(false) and not having any api.exports() ? And if not, does it make sense to introduce the additional call ? Since that would also imply existing packages which might be side-effect free already need to be updated before benefiting from tree-shaking.

**Comment by renanccastro** [comment]
> @renanccastro But is there a difference between api.sideEffects(false) and not having any api.export() 's ? And if not, does it make sense to introduce the additional call ? Since that would also imply existing packages which might be side-effect free already need to be updated before benefiting from tree-shaking.

Yes, I think so. Even if you don't specify an api.exports() and your package doesn't have a global namespace, when including it, Meteor will add it to the bundle. If this file has side effects, aside from adding the namespace, things can go wrong. But it's less common, I agree. It's more or less the way package.json has sideEffects on webpack, but here we are certain that when we see an api.exports(), sideEffect is true. When we don't see it, it can be false/true.

**Comment by santiagopuentep** [comment]
I think it's EXTREMELY important that this doesn't impact rebuild performance in development, which is by far the worst part of Meteor, especially on Windows.

**Comment by sebakerckhof** [comment]
Did a quick try with importing one function from lodash-es. Is it normal to see this in dev mode. Sure, terser would purge this in production mode minification step, but is this to be expected in dev mode ?:
```
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                     //
// node_modules/lodash-es/lodash.js                                                                                    //
//                                                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                                       //
false;
false;
false;
false;
false;
false;
false;
false;
false;
false;
false;
...
false;
false;
false;
false;
false;
false;
false;
false;
false;
false;
false;
false;
false;
false;
false;
false;
false;
false;
false;
false;
false;
module.link('./fill.js', {
  default: "fill"
}, 61);
false;
false;
false;
false;
false;
false;
false;
false;
false;
false;
false;
false;
false;
...
```

**Comment by renanccastro** [comment]
I've left it on dev mode for checking which imports/modules are actually removed. We can replace it with an empty statement, but leaving it like this makes it easier to debug.

**Comment by minhna** [comment]
How is this going? It's now painful working with material-ui icons and react-bootstrap, react-bootstrap-icons.

**Comment by renanccastro** [comment]
> How is this going? It's now painful working with material-ui icons and react-bootstrap, react-bootstrap-icons.

Hi @minhna. It's currently on 2.0.beta-4, and you can already try it out. We are working on performance improvements for this feature to be ready.

**Comment by appigram** [comment]
Hi @renanccastro , thanks for your work! I try to update to meteor 2.0.beta-4, but the error appears in terminal. It's fine on 2.0.beta-3
```
/Users/macbook/.meteor/packages/static-html/.1.2.2.1jjdtwi.j0m5j++os+web.browser+web.cordova/plugin.compileStaticHtmlBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

TypeError: Cannot read property 'map' of undefined
    at Object.removeIdentifiers (/tools/isobuild/js-analyze.js:385:43)
    at Object.visitCallExpression (/tools/isobuild/js-analyze.js:420:26)
    at Object.visitWithoutReset (/Users/macbook/.meteor/packages/meteor-tool/.2.0.0-beta.4.1lkow5l.su8e++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/reify/lib/visitor.js:77:16)
    at Visitor.visitWithoutReset (/Users/macbook/.meteor/packages/meteor-tool/.2.0.0-beta.4.1lkow5l.su8e++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/reify/lib/visitor.js:23:25)
    at FastPath.call (/Users/macbook/.meteor/packages/meteor-tool/.2.0.0-beta.4.1lkow5l.su8e++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/reify/lib/fast-path.js:46:20)
    at Object.visitChildren (/Users/macbook/.meteor/packages/meteor-tool/.2.0.0-beta.4.1lkow5l.su8e++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/reify/lib/visitor.js:194:12)
    at Object.Visitor.visitChildren (/Users/macbook/.meteor/packages/meteor-tool/.2.0.0-beta.4.1lkow5l.su8e++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/reify/lib/visitor.js:27:21)
    at Object._visitChildrenIfPossible (/Users/macbook/.meteor/packages/meteor-tool/.2.0.0-beta.4.1lkow5l.su8e++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/reify/lib/visitor.js:159:12)
    at Object.visitWithoutReset (/Users/macbook/.meteor/packages/meteor-tool/.2.0.0-beta.4.1lkow5l.su8e++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/reify/lib/visitor.js:82:14)
    at Visitor.visitWithoutReset (/Users/macbook/.meteor/packages/meteor-tool/.2.0.0-beta.4.1lkow5l.su8e++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/reify/lib/visitor.js:23:25)
    at FastPath.each (/Users/macbook/.meteor/packages/meteor-tool/.2.0.0-beta.4.1lkow5l.su8e++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/reify/lib/fast-path.js:72:7)
    at Object.visitWithoutReset (/Users/macbook/.meteor/packages/meteor-tool/.2.0.0-beta.4.1lkow5l.su8e++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/reify/lib/visitor.js:72:12)
    at Visitor.visitWithoutReset (/Users/macbook/.meteor/packages/meteor-tool/.2.0.0-beta.4.1lkow5l.su8e++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/reify/lib/visitor.js:23:25)
    at FastPath.call (/Users/macbook/.meteor/packages/meteor-tool/.2.0.0-beta.4.1lkow5l.su8e++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/reify/lib/fast-path.js:46:20)
    at Object.visitChildren (/Users/macbook/.meteor/packages/meteor-tool/.2.0.0-beta.4.1lkow5l.su8e++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/reify/lib/visitor.js:194:12)
    at Object.Visitor.visitChildren (/Users/macbook/.meteor/packages/meteor-tool/.2.0.0-beta.4.1lkow5l.su8e++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/reify/lib/visitor.js:27:21)
    at Object._visitChildrenIfPossible (/Users/macbook/.meteor/packages/meteor-tool/.2.0.0-beta.4.1lkow5l.su8e++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/reify/lib/visitor.js:107:19)
    at Object.visitWithoutReset (/Users/macbook/.meteor/packages/meteor-tool/.2.0.0-beta.4.1lkow5l.su8e++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/reify/lib/visitor.js:82:14)
    at Visitor.visitWithoutReset (/Users/macbook/.meteor/packages/meteor-tool/.2.0.0-beta.4.1lkow5l.su8e++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/reify/lib/visitor.js:23:25)
    at FastPath.call (/Users/macbook/.meteor/packages/meteor-tool/.2.0.0-beta.4.1lkow5l.su8e++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/reify/lib/fast-path.js:46:20)
    at Object.visitChildren (/Users/macbook/.meteor/packages/meteor-tool/.2.0.0-beta.4.1lkow5l.su8e++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/reify/lib/visitor.js:194:12)
    at Object.Visitor.visitChildren (/Users/macbook/.meteor/packages/meteor-tool/.2.0.0-beta.4.1lkow5l.su8e++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/reify/lib/visitor.js:27:21)
    at Object._visitChildrenIfPossible (/Users/macbook/.meteor/packages/meteor-tool/.2.0.0-beta.4.1lkow5l.su8e++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/reify/lib/visitor.js:107:19)
    at Object.visitWithoutReset (/Users/macbook/.meteor/packages/meteor-tool/.2.0.0-beta.4.1lkow5l.su8e++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/reify/lib/visitor.js:82:14)
    at Object.Visitor.visitWithoutReset (/Users/macbook/.meteor/packages/meteor-tool/.2.0.0-beta.4.1lkow5l.su8e++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/reify/lib/visitor.js:23:25)
    at Object.visit (/Users/macbook/.meteor/packages/meteor-tool/.2.0.0-beta.4.1lkow5l.su8e++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/reify/lib/visitor.js:66:10)
    at Object.Visitor.visit (/Users/macbook/.meteor/packages/meteor-tool/.2.0.0-beta.4.1lkow5l.su8e++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/reify/lib/visitor.js:19:13)
    at removeUnusedExports (/tools/isobuild/js-analyze.js:342:32)
    at /tools/isobuild/bundler.js:1256:57
    at Array.forEach (<anonymous>)
    at /tools/isobuild/bundler.js:1248:40
    at Array.forEach (<anonymous>)
    at ServerTarget._emitResources (/tools/isobuild/bundler.js:1238:19)
    at /tools/isobuild/bundler.js:862:12
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at ServerTarget.make (/tools/isobuild/bundler.js:850:18)
    at /tools/isobuild/bundler.js:3344:14
    at /tools/isobuild/bundler.js:3478:24
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at bundle (/tools/isobuild/bundler.js:3301:31)
    at /tools/isobuild/bundler.js:3244:32
    at Slot.withValue (/Users/macbook/.meteor/packages/meteor-tool/.2.0.0-beta.4.1lkow5l.su8e++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.js:73:29)
    at Object.withCache (/Users/macbook/.meteor/packages/meteor-tool/.2.0.0-beta.4.1lkow5l.su8e++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/fs/tools/fs/files.ts:1659:39)
    at Object.bundle (/tools/isobuild/bundler.js:3244:16)
    at /tools/runners/run-app.js:579:24
    at Function.run (/Users/macbook/.meteor/packages/meteor-tool/.2.0.0-beta.4.1lkow5l.su8e++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/tool-env/tools/tool-env/profile.ts:289:14)
    at bundleApp (/tools/runners/run-app.js:578:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:625:35)
    at AppRunner._fiber (/tools/runners/run-app.js:940:28)
    at /tools/runners/run-app.js:408:12
```

**Comment by renanccastro** [comment]
Hi @appigram, can you open a separate issue for this? It will be easier to track and also please consider attaching a repro project.

**Comment by appigram** [comment]
Hi @renanccastro . Does tree shaking included to `beta.6`? I did upgrade with `meteor update --release METEOR@2.0-beta.6` recently and it works fine, without any issues

**Comment by filipenevola** [comment]
@appigram no, it's not included, read more here https://github.com/meteor/meteor/pull/11206#issuecomment-758865607

> Update 2021/01/12: Tree-shaking implementation is going well (tests are passing) but we still have some bug reports to fix and performance optimizations to do, so we are moving it to Meteor 2.1 as we don't want to hold HMR and Meteor free deploy including MongoDB any longer.
>
> As we know Tree-shaking is not an easy task but we are close.

**Comment by appigram** [comment]
@filipenevola got it, thanks! I'll try to create repro project to track my issue. Thanks for your awesome work!

**Comment by rj-david** [comment]
Looking forward to test this on a beta build.

**Comment by StorytellerCZ** [comment]
@jirikrepl It is still in plans, but right now there are other priorities which pushed this back for now.

**Comment by hubyhuby** [comment]
Concerning tree shaking: do you refer aswell to the front end ?
For example our first production app gets a LOW score of 50/100  on google insight because of "Script Evaluation".
We use Vue.js + vuetify. This app is for now just a landing page.
image
Script bundel size is 300ko ziped and 1 800 kb unziped
image

**Comment by filipenevola** [comment]
Hi, sorry for the absence of comments and activity here.

Let's me summarize what we are waiting here:

- We still have 1 or 2 bugs to fix.
- We still have to optimize performance as we are doing more work the build time is increased
  - We are awaiting the final result of this PR https://github.com/benjamn/reify/pull/246 because it could open doors for some options, if this PR really solve the problem of importing huge libraries, like Material UI, from root so we could opt to have a version of tree-shaking that runs only for production builds. This change would allow us to accept, maybe, a performance that is not the best possible, as it could run just in production builds and behind a flag. This would open the option of exploring optimizations in tree-shaking but without holding more its release as it would not affect development and also it could be turned off for production. Without this Reify PR it would not be a good option to run tree-shaking only in production as importing a huge library from the root would still cause problems in development.

So our plan about tree-shaking is to wait this PR final result, check the performance of imports from root in huge libraries, retest tree-shaking after this PR is merged to Reify and used by Meteor and then decide next steps.

The bugs that we still have in tree-shaking are not the major issue, the major issue is the runtime performance.

I hope this comment here provides more visibility on what is going on in this PR.

And again, sorry for the delay explaining it here.

**Comment by harryadel** [comment]
Now that the [Optimizations](https://github.com/benjamn/reify/pull/246) PR got merged in. Can we expect this to ship in 2.4?

**Comment by StorytellerCZ** [comment]
@harryadel that will depend on @renanccastro if not 2.4, it will most likely be the center piece for 2.5. More likely the second. I would like for 2.4 to be a bit of a smaller release.

**Comment by diavrank** [comment]
Hello, I was wondering if **treeshaking** would help to **skip** optional dependencies in **package.json**?

I ask it because it could solve this [issue](https://github.com/disney/meteor-base/issues/55#issuecomment-880132379).

**Comment by csillag** [comment]
@renanccastro what is the current status for this? Now that the reify fix has landed on the latest 2.4 beta, think are no longer terrible, but still it would be great to have this performance improvement, too..

**Comment by zodern** [comment]
We might also need https://github.com/benjamn/reify/pull/291 for it to be fast enough in development without tree shaking.

**Comment by renanccastro** [comment]
> Hello, I was wondering if **treeshaking** would help to **skip** optional dependencies in **package.json**?
> 
> I ask it because it could solve this [issue](https://github.com/disney/meteor-base/issues/55#issuecomment-880132379).

No, that won't solve it! Tree shaking will only remove code from your bundle, not act before the compilation of npm dependencies.

----

Exactly, without https://github.com/benjamn/reify/pull/291 we can't split tree shaking only to production builds, and right now, it's too expensive for running in development.

You might also want to check out this discussion here, where we talk about build improvements: https://github.com/meteor/meteor/discussions/11587

**Comment by make-github-pseudonymous-again** [comment]
I have a use case and a question.

  - use case: date-fns locales. `import {enUS, nlBE, fr} from 'date-fns/locale'` METEOR@2.2.3 bundles ALL locales
date-fns
  - question: why are `package.json` files part of the bundle? This is an example of a rather large one
babel-runtime

`@material-ui` is also a nice use case but I believe it is already known.

**Comment by renanccastro** [comment]
@make-github-pseudonymous-again 
Good news is that this use-case is also covered by this PR:
image

```js
  import {enUS, nlBE, fr} from 'date-fns/locale'
  console.log(enUS);
```
It is only including enUS nlBE and fr code.

----
Your question about why we include package.json in the bundle can be answer by looking at the install module, which is our module system in the client side: https://github.com/benjamn/install#usage

We use it for identifying entry points in the client, but for sure, there is something odd in your picture. There is no way this package.json is this large, so I would guess it's something in bundle visualizer graph not updating accordingly.

**Comment by make-github-pseudonymous-again** [comment]
What's the status of conditionals on `Meteor.isServer`. Here is an example https://forums.meteor.com/t/idiomatic-method-client-simulation-opt-out/56546/7

**Comment by renanccastro** [comment]
Hi @make-github-pseudonymous-again 
This PR also solves this, but changing this variables in bundle time and removing the unused code with terser minifying. Ex on the server:
```js
	if (true) {
		Meteor.methods({
			[name]: serverImplementation,
		});
	}
	else {
		Meteor.methods({
			[name]: clientImplementation,
		});
	}
```
Then, the else is removed when minifying.

**Comment by appigram** [comment]
Hi guys, are there any blockers to finish it still? I read the discussion about build improvements [#11587](https://github.com/meteor/meteor/discussions/11587), And I think if it brings improvements for current projects already, 
 can we see it in the next release? 😇

**Comment by make-github-pseudonymous-again** [comment]
> Hi @make-github-pseudonymous-again This PR also solves this, but changing this variables in bundle time and removing the unused code with terser minifying. Ex on the server:
> 
> ```js
> 	if (Meteor.isServer -> becomes true) {
> 		Meteor.methods({
> 			[name]: serverImplementation,
> 		});
> 	}
> 	else {
> 		Meteor.methods({
> 			[name]: clientImplementation,
> 		});
> 	}
> ```
> 
> Then, the else is removed when minifying.

I am also interested in hoisting the client/server dichotomy. What about this example code, would it shake? Do we need to drop in some @@@INLINE@@@ hints to rollup? Does it work with/without explicit `Meteor` import?

```js
import {Meteor} from 'meteor/meteor';
const define = ({server, client}) => {
    return Meteor.isServer ? server : Meteor.isClient ? client : undefined;
};
export const x = define({server: () => { console.log('server'); }, client: () => { console.log('client'); });
```

Rationale: this allows more elegant abstractions than having to shove everything under a `Meteor.isServer` conditional. The code sample above is obviously oversimplified but I think it captures the indirection I think tree-shaking could have problems with.

**Comment by make-github-pseudonymous-again** [comment]
> Your question about why we include package.json in the bundle can be answer by looking at the install module, which is our module system in the client side: https://github.com/benjamn/install#usage
> 
> We use it for identifying entry points in the client, but for sure, there is something odd in your picture. There is no way this package.json is this large, so I would guess it's something in bundle visualizer graph not updating accordingly.

I just checked, [the `package.json` file for `@babel/runtime` is really that large](https://github.com/babel/babel/blob/main/packages/babel-runtime/package.json).

**Comment by tcastelli** [comment]
Would be good to get a summary of the status of this one @renanccastro! Would really benefit from tree-shaking for many alread-covered cases  👍

**Comment by renanccastro** [comment]
The bulk work here is done, but it impacts speed in dev mode.
What we have pending:
- Only run it on production builds as there was a series of improvements on Reify making it possible to omit tree-shaking in dev (like this [one](https://github.com/meteor/reify/pull/1))
- Support custom compiler and custom file formats, like (.graphql) - issue [here](https://github.com/meteor/meteor/issues/11231)

**Comment by simplecommerce** [comment]
@renanccastro stupid question, how can I test this feature in my project to see the impact it does on the bundle size when building? I haven't done it before so I am not sure how.

**Review by varevarao — APPROVED** [review]

**Comment by jankapunkt** [comment]
What's the status of this PR?

**Comment by Saeeed-B** [comment]
> What's the status of this PR?

?

**Comment by denihs** [comment]
Hi, sorry for the delay here. I had to check with Renan to be sure of the status here, and it's still this https://github.com/meteor/meteor/pull/11164#issuecomment-1033173493.  

This is still in our roadmap, we didn't forget about it, but it's paused at the moment.

**Comment by jankapunkt** [comment]
thank you @denihs I think it's totally okay to omit it in dev mode, thanks to recent improvements and if someone wants to test it, they can still use the `--production` flag, right?

**Comment by radekmie** [comment]
The only downside I can imagine is a potential tree-shaking bug, that won't come up during tests. _(We're not the only ones running tests **without** `--production`, right?)_

**Comment by jankapunkt** [comment]
Good point, that could indeed be an issue.

**Comment by denihs** [comment]
Yeah... that's a downside that we'll have to look into it. But for now, you should be able to test it with `--production`.

**Comment by welkinwong** [comment]
What's the status of this PR……

**Comment by jamauro** [comment]
Would love to see this finalized and merged

**Comment by jamauro** [comment]
Understandably the focus is on finishing 3.0, but I'm wondering if there's any chance this could be merged in parallel? I think the main outstanding decision is:

> Only run it on production builds? If we have a major "wrong" import, the local development build can have bad performance, or not be responsive at all. Think about import @material-ui/icons, for example.

Maybe it could be an opt-in for now, e.g. `--treeshake`, that way people could test it.

The other issue linked in [Renan's comment](https://github.com/meteor/meteor/pull/11164#issuecomment-1033173493) has since been closed.

If merging is not planned for a while, is there a way to test the PR as is?

@denihs @Grubba27 @fredmaiaarantes

**Comment by StorytellerCZ** [comment]
Ping to everyone involved here. We need to put this on the roadmap.

**Comment by jankapunkt** [comment]
I would also consider thinking about this in context of using vite or other external bundlers that already implement tree shaking

**Comment by renanccastro** [comment]
I know there has been a long discussion on whether Meteor Software wants to keep evolving the build system, implement Vite, or some other existing build system.
We need to have a clear answer to that. I'm back working with Meteor again, after long years :slightly_smiling_face: [Quave](https://quave.dev/) can keep this rolling.

**Comment by leonardoventurini** [comment]
Awesome @renanccastro, we already have Vite officially in the roadmap, that should apply to the client bundles. We probably can do something similar to the server bundle by using an existing tool like `esbuild --bundle`, should be easier since we have control of the Node.js runtime.

Perhaps this PR is not viable anymore, the goal is to simplify as much as possible, and make it less coupled as possible, so let's say 3 years into the future there is a better tool out there and we can replace it easily again.

There is a seedling workgroups initiative taking shape, this work can be coordinated with other people/organizations too. Researching and implementing such a tool for the server specifically could be a great start. Will give this some thought.

I will be updating the official roadmap page soon with more details about it.

**Comment by renanccastro** [comment]
Got it! Thanks for the explanation @leonardoventurini . I'm closing this PR for the time being.

**Pull request closed without merging**
