### PR TITLE
Handle force_login parameter in Twitter package

### PR DESCRIPTION
**Pull request by nuvipannu**
Adding support for force_login:  
https://dev.twitter.com/oauth/reference/get/oauth/authenticate :sparkle:

### CODE REVIEW

**Comment by IonicaBizau** [comment]
@zol Any idea why the `Property description must be an object.` error appears in the tests? :thought_balloon:

**Comment by benjamn** [comment]
@IonicaBizau that's an unrelated failure that should have been fixed by this recent commit: https://github.com/meteor/meteor/commit/263c45b919bbd3c028ff75acc89853681b16ea89 (In other words, if you rebased against `devel` now and re-pushed this pull request branch, that test would almost certainly pass).

**Comment by IonicaBizau** [comment]
@benjamn I just rebased and force pushed here. Should I update any docs regarding this change? :books:

**Comment by tmeasday** [comment]
Thanks for this PR, sorry we never got around to merging it. We are currently cleaning up the repository and removing old PRs; if you think this PR still has value and are interested in resurrecting it, we encourage you to re-submit it against current `devel`.

**Comment by IonicaBizau** [comment]
@tmeasday Addressed in #6987. Hopefully that will work...

**Pull request closed without merging**
