### PR TITLE
Remove built in regex validations

### PR DESCRIPTION
**Pull request by vit0rr**
closes https://github.com/meteor/meteor/issues/12689

This pull request updates the no longer supported regEx built-in expressions from SimpleSchema.
The purpose here is to define a regular expression and link the SimpleSchema doc. that explains why it no longer supports built-in expressions.

### CODE REVIEW

**Review by StorytellerCZ — CHANGES_REQUESTED** [review]
See my comment in the issue. Latest version of Simple Schema does not work in Meteor, so you have to stick with v1 where this functionality is still present. Until we have a community solution to this I would propose that instead guide gives a recommendation to use custom regEx and list regEx for Meteor related functionality like ids.

**Comment by vit0rr** [comment]
> See my comment in the issue. Latest version of Simple Schema does not work in Meteor, so you have to stick with v1 where this functionality is still present. Until we have a community solution to this I would propose that instead guide gives a recommendation to use custom regEx and list regEx for Meteor related functionality like ids.

Well pointed @StorytellerCZ.
So, If I understood, a better approach is to keep the `SimpleSchema.RegEx.Id`, but add some line explaining that we encourage to create of custom regEx for fields like email and amount, for security reasons, and link the official doc. of [simpl-schema](https://github.com/longshotlabs/simpl-schema#regex)?

**Comment by StorytellerCZ** [comment]
Yes, point out that `simpl-schema` only works with Meteor on the 1.x branch, but that they should switch to their own regexes regardless.

**Review by StorytellerCZ — APPROVED** [review]

**Review by Grubba27 — APPROVED** [review]
LGTM! This will be on 2.14 I think

**Comment by StorytellerCZ** [comment]
Since it is in docs, can't we get it into 2.13?

**Comment by Grubba27** [comment]
> Since it is in docs, can't we get it into 2.13?

Yeah! I read and thought it was code, this can go today to devel

**Pull request closed without merging**
