### PR TITLE
Extract handler result publish code

### PR DESCRIPTION
**Pull request by mitar**
This allows easier extending by packages.

### CODE REVIEW

**Comment by mitar** [comment]
cc @stubailo 

This would make it really easy for my server-side reactive publish package to not have to duplicate core code. :-)

**Comment by stubailo** [comment]
So the idea is that your package runs the handler reactively and uses the factored out publish result function? Makes sense to me.

**Comment by mitar** [comment]
Yes. It should not change anything for you. But if we get this out in 1.2, then it will be great to release out reactive server side publish shortly afterwards. :-)

**Comment by stubailo** [comment]
Merged: 60eaf91624831bee84f32b09aed66b881cd9b87f

Thanks!

Sorry I couldn't get it in before 1.2.

**Pull request closed without merging**
