### PR TITLE
Release 1.4.1

### PR DESCRIPTION
**Pull request by benjamn**
It's time to begin the beta testing process for Meteor 1.4.1!

If you'd like to participate, as usual, keep an eye on the [releases page](https://github.com/meteor/meteor/releases) for new entries with names like `release/METEOR@1.4.1-beta.n`, and update to the latest release by running `meteor update --release 1.4.1-beta.n` in a test application.

Note that this release will not ship until Node 4.5.0 is released, but [that seems imminent](https://github.com/nodejs/node/pull/7688).

### CODE REVIEW

**Comment by abernix** [comment]
Btw, Node CTC Meeting notes last week they just needed more folks to test the 4.5.0-rc as it had some important changes and hadn't got many folks on the RC yet.  During yesterday's meeting, IBM said they have been using it internally without problems.  It's still on the agenda for next week right now.  I don't know how willing Meteor is to test the `rc`. :wink:

**Comment by benjamn** [comment]
@abernix I don't see why not!

**Comment by benjamn** [comment]
Hmm, sadly, `node-gyp` doesn't know how to download RC versions of Node.

**Comment by nicolaslopezj** [comment]
@benjamn I think #6576 should be included in this version. Any time we save a client file we have to wait like 40 seconds... Just imagine all the time wasted...

**Pull request merged**
