### PR TITLE
Release 3.1.0

### PR DESCRIPTION
**Pull request by denihs**
# Still in development
Current released version: **3.1**.

To use it, please do a

```
meteor update --release 3.1
```

you can also use the following command to install this meteor version

```
npx meteor@rc
```

# Highlights
* `webapp`, `test-helpers`, `boilerplate-generator-tests` underscore removed by @harryadel

### CODE REVIEW

**Comment by harryadel** [comment]
3.0 is a gift that keeps on giving :sob: Is this related to monti @zodern?




EDIT: Commenting out `montiapm:agent` package fixed the error exception but now we've this warning on booting our application `[DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternati
ve instead.`

**Comment by harryadel** [comment]
tried

**Comment by leonardoventurini** [comment]
> 3.0 is a gift that keeps on giving 😭 Is this related to monti @zodern?
> 
> 
> EDIT: Commenting out `montiapm:agent` package fixed the error exception but now we've this warning on booting our application `[DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternati ve instead.`

Perhaps the hijacks will need to be updated, we will check if is something on our end.

The punycode warning comes from Node.js 22, we could disable it in the tool but opted to leave it for userland code.

**Comment by nachocodoner** [comment]
> 3.0 is a gift that keeps on giving 😭 Is this related to monti @zodern?
> 
> EDIT: Commenting out `montiapm:agent` package fixed the error exception but now we've this warning on booting our application `[DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternati ve instead.`

@zodern already fixed the issue in the new version published. https://forums.meteor.com/t/weekly-update-november-4th-2024/62507/8

**Comment by wreiske** [comment]
```
wreiske@Wills-MacBook-Pro bluehive-ai % ./build-mobile.sh
--server=https://ai.bluehive.com
WARNING: android_mdpi_portrait: unknown key in App.launchScreens configuration. The key may be deprecated.
WARNING: android_mdpi_landscape: unknown key in App.launchScreens configuration. The key may be deprecated.
WARNING: android_hdpi_portrait: unknown key in App.launchScreens configuration. The key may be deprecated.
WARNING: android_hdpi_landscape: unknown key in App.launchScreens configuration. The key may be deprecated.
WARNING: android_xhdpi_portrait: unknown key in App.launchScreens configuration. The key may be deprecated.
WARNING: android_xhdpi_landscape: unknown key in App.launchScreens configuration. The key may be deprecated.
WARNING: android_xxhdpi_portrait: unknown key in App.launchScreens configuration. The key may be deprecated.
WARNING: android_xxhdpi_landscape: unknown key in App.launchScreens configuration. The key may be deprecated.
WARNING: android_xxxhdpi_portrait: unknown key in App.launchScreens configuration. The key may be deprecated.
WARNING: android_xxxhdpi_landscape: unknown key in App.launchScreens configuration. The key may be deprecated.
%% config file *-Info.plist requested for changes not found at /Users/wreiske/prj/bluehive-ai/.meteor/local/cordova-build/platforms/android/*-Info.plist, ignoring
%% config file *-Info.plist requested for changes not found at /Users/wreiske/prj/bluehive-ai/.meteor/local/cordova-build/platforms/android/*-Info.plist, ignoring
%% config file *-Info.plist requested for changes not found at /Users/wreiske/prj/bluehive-ai/.meteor/local/cordova-build/platforms/android/*-Info.plist, ignoring
%% config file *-Info.plist requested for changes not found at /Users/wreiske/prj/bluehive-ai/.meteor/local/cordova-build/platforms/android/*-Info.plist, ignoring
%% config file *-Info.plist requested for changes not found at /Users/wreiske/prj/bluehive-ai/.meteor/local/cordova-build/platforms/android/*-Info.plist, ignoring
Checking Java JDK and Android SDK versions   /
ANDROID_HOME=/Users/wreiske/Library/Android/sdk (recommended setting)
ANDROID_SDK_ROOT=/Users/wreiske/Library/Android/sdk (DEPRECATED)
Using Android SDK: /Users/wreiske/Library/Android/sdk
   Building Cordova app for Android          -
BUILD SUCCESSFUL in 355ms
1 actionable task: 1 up-to-date

> Task :app:mergeReleaseResources FAILED
/Users/wreiske/.gradle/caches/transforms-4/03d10d25bdf91f1e03a4061a4963807b/transformed/appcompat-1.6.1/res/values/values.xml:27:4: Invalid <color> for given resource value.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable
   > Resource compilation failed (Failed to compile values resource file /Users/wreiske/prj/bluehive-ai/.meteor/local/cordova-build/platforms/android/app/build/intermediates/incremental/release/mergeReleaseResources/merged.dir/values/values.xml. Cause: java.lang.IllegalStateException: Can not extract resource from com.android.aaptcompiler.ParsedResource@5046fd06.). Check logs for more details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.      -
> Get more help at https://help.gradle.org.

BUILD FAILED in 6s
33 actionable tasks: 8 executed, 25 up-to-date
=> Errors executing Cordova commands:         
                                              
   While building Cordova app for platform Android:
   Error: Command failed with exit code 1: /Users/wreiske/prj/bluehive-ai/.meteor/local/cordova-build/platforms/android/tools/gradlew :app:bundleRelease
   at makeError (/Users/wreiske/prj/bluehive-ai/.meteor/local/cordova-build/node_modules/execa/lib/error.js:60:11)
   at handlePromise (/Users/wreiske/prj/bluehive-ai/.meteor/local/cordova-build/node_modules/execa/index.js:118:26)
   at processTicksAndRejections (node:internal/process/task_queues:95:5)
   at ProjectBuilder.build (/Users/wreiske/prj/bluehive-ai/.meteor/local/cordova-build/node_modules/cordova-android/lib/builders/ProjectBuilder.js:326:20)
   at /tools/cordova/project.js:332:7
   at CordovaProject.runCommands (/tools/cordova/project.js:954:14)
   at CordovaProject.buildForPlatform (/tools/cordova/project.js:330:5)
   at /tools/cli/commands.js:1468:15
   at Object.enterJob (/tools/utils/buildmessage.js:387:12)
   at /tools/cli/commands.js:1451:9
   at Object.capture (/tools/utils/buildmessage.js:282:5)
   at Object.main.captureAndExit (/tools/cli/main.js:275:16)
   at buildCommand (/tools/cli/commands.js:1425:5)
   at /tools/cli/commands.js:1212:18
   at Command.func (/tools/cli/commands.js:1210:10)
   at /tools/cli/main.js:1546:15
wreiske@Wills-MacBook-Pro bluehive-ai % meteor update --release 3.1-beta.0
                                                                                   
Changes to your project's package version selections from updating the release:
                                              
babel-compiler  upgraded from 7.11.1 to 7.11.2-beta310.0
ddp-client      upgraded from 3.0.2 to 3.0.3-beta310.0
ddp-server      upgraded from 3.0.2 to 3.0.3-beta310.0
email           upgraded from 3.1.0 to 3.1.1-beta310.0
meteor          upgraded from 2.0.1 to 2.0.2-beta310.0
minimongo       upgraded from 2.0.1 to 2.0.2-beta310.0
modules         upgraded from 0.20.2 to 0.20.3-beta310.0
mongo           upgraded from 2.0.2 to 2.0.3-beta310.0
mongo-decimal+  upgraded from 0.1.4 to 0.1.6-beta310.0
typescript      upgraded from 5.4.3 to 5.6.3-beta310.0
underscore      removed from your project
webapp          upgraded from 2.0.3 to 2.0.4-beta310.0

                                              
+ In order to resolve constraints, we had to use experimental versions of these
packages.
bluehive-ai: updated to Meteor 3.1-beta.0.    
wreiske@Wills-MacBook-Pro bluehive-ai % ./build-mobile.sh                 
--server=https://ai.bluehive.com
WARNING: android_mdpi_portrait: unknown key in App.launchScreens configuration. The key may be deprecated.
WARNING: android_mdpi_landscape: unknown key in App.launchScreens configuration. The key may be deprecated.
WARNING: android_hdpi_portrait: unknown key in App.launchScreens configuration. The key may be deprecated.
WARNING: android_hdpi_landscape: unknown key in App.launchScreens configuration. The key may be deprecated.
WARNING: android_xhdpi_portrait: unknown key in App.launchScreens configuration. The key may be deprecated.
WARNING: android_xhdpi_landscape: unknown key in App.launchScreens configuration. The key may be deprecated.
WARNING: android_xxhdpi_portrait: unknown key in App.launchScreens configuration. The key may be deprecated.
WARNING: android_xxhdpi_landscape: unknown key in App.launchScreens configuration. The key may be deprecated.
WARNING: android_xxxhdpi_portrait: unknown key in App.launchScreens configuration. The key may be deprecated.
WARNING: android_xxxhdpi_landscape: unknown key in App.launchScreens configuration. The key may be deprecated.
%% config file *-Info.plist requested for changes not found at /Users/wreiske/prj/bluehive-ai/.meteor/local/cordova-build/platforms/android/*-Info.plist, ignoring
%% config file *-Info.plist requested for changes not found at /Users/wreiske/prj/bluehive-ai/.meteor/local/cordova-build/platforms/android/*-Info.plist, ignoring
%% config file *-Info.plist requested for changes not found at /Users/wreiske/prj/bluehive-ai/.meteor/local/cordova-build/platforms/android/*-Info.plist, ignoring
%% config file *-Info.plist requested for changes not found at /Users/wreiske/prj/bluehive-ai/.meteor/local/cordova-build/platforms/android/*-Info.plist, ignoring
%% config file *-Info.plist requested for changes not found at /Users/wreiske/prj/bluehive-ai/.meteor/local/cordova-build/platforms/android/*-Info.plist, ignoring
Checking Java JDK and Android SDK versions   /
ANDROID_HOME=/Users/wreiske/Library/Android/sdk (recommended setting)
ANDROID_SDK_ROOT=/Users/wreiske/Library/Android/sdk (DEPRECATED)
Using Android SDK: /Users/wreiske/Library/Android/sdk
   Building Cordova app for Android          \
BUILD SUCCESSFUL in 367ms
1 actionable task: 1 up-to-date

> Task :app:mergeReleaseResources FAILED
/Users/wreiske/.gradle/caches/transforms-4/03d10d25bdf91f1e03a4061a4963807b/transformed/appcompat-1.6.1/res/values/values.xml:27:4: Invalid <color> for given resource value.

FAILURE: Build failed with an exception.

* What went wrong:a app for Android          /
Execution failed for task ':app:mergeReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable
   > Resource compilation failed (Failed to compile values resource file /Users/wreiske/prj/bluehive-ai/.meteor/local/cordova-build/platforms/android/app/build/intermediates/incremental/release/mergeReleaseResources/merged.dir/values/values.xml. Cause: java.lang.IllegalStateException: Can not extract resource from com.android.aaptcompiler.ParsedResource@471e1962.). Check logs for more details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 980ms
37 actionable tasks: 6 executed, 31 up-to-date
=> Errors executing Cordova commands:         
                                              
   While building Cordova app for platform Android:
   Error: Command failed with exit code 1: /Users/wreiske/prj/bluehive-ai/.meteor/local/cordova-build/platforms/android/tools/gradlew :app:bundleRelease
   at makeError (/Users/wreiske/prj/bluehive-ai/.meteor/local/cordova-build/node_modules/execa/lib/error.js:60:11)
   at handlePromise (/Users/wreiske/prj/bluehive-ai/.meteor/local/cordova-build/node_modules/execa/index.js:118:26)
   at processTicksAndRejections (node:internal/process/task_queues:105:5)
   at ProjectBuilder.build (/Users/wreiske/prj/bluehive-ai/.meteor/local/cordova-build/node_modules/cordova-android/lib/builders/ProjectBuilder.js:326:20)
   at /tools/cordova/project.js:333:7
   at CordovaProject.runCommands (/tools/cordova/project.js:957:14)
   at CordovaProject.buildForPlatform (/tools/cordova/project.js:331:5)
   at /tools/cli/commands.js:1468:15
   at Object.enterJob (/tools/utils/buildmessage.js:387:12)
   at /tools/cli/commands.js:1451:9
   at Object.capture (/tools/utils/buildmessage.js:282:5)
   at Object.main.captureAndExit (/tools/cli/main.js:275:16)
   at buildCommand (/tools/cli/commands.js:1425:5)
   at /tools/cli/commands.js:1212:18
   at Command.func (/tools/cli/commands.js:1210:10)
   at /tools/cli/main.js:1546:15
   ```
   
   Both 3.0.4 and 3.1-beta.0 have build issues on android cordova. 
   
   Line 27 is:
```
    <color name="background_material_dark">@color/material_grey_850</color>
```

I'm going to bang my head on it more tonight before opening an issue, but figured I'd post here since there's a lot of cordova fixes going into 3.1.0 it might be nice to include this if it's a core meteor / cordova issue.

The line 27 can be found here:
https://android.googlesource.com/platform/frameworks/base/+/master/core/res/res/values/colors_material.xml#22

**Comment by wreiske** [comment]
I'm running into this issue now after blowing away my cordova-build folder.  https://github.com/meteor/meteor/issues/13303

```
wreiske@Wills-MacBook-Pro bluehive-ai % ./build-mobile.sh           
--server=https://ai.bluehive.com
=> Errors executing Cordova commands:         
                                              
   While getting installed version for platform android in Cordova project:
   Error: Command failed: /Users/wreiske/prj/bluehive-ai/.meteor/local/cordova-build/platforms/android/cordova/version 
   node:internal/modules/cjs/loader:1252
   throw err;
   ^
   
   Error: Cannot find module 'cordova-android'
   Require stack:
   - /Users/wreiske/prj/bluehive-ai/.meteor/local/cordova-build/platforms/android/cordova/Api.js
   - /Users/wreiske/prj/bluehive-ai/.meteor/local/cordova-build/platforms/android/cordova/version
   at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)
   at Function._load (node:internal/modules/cjs/loader:1075:27)
   at TracingChannel.traceSync (node:diagnostics_channel:315:14)
   at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
   at Module.require (node:internal/modules/cjs/loader:1340:12)
   at require (node:internal/modules/helpers:141:16)
   at Object.<anonymous> (/Users/wreiske/prj/bluehive-ai/.meteor/local/cordova-build/platforms/android/cordova/Api.js:20:18)
   at Module._compile (node:internal/modules/cjs/loader:1546:14)
   at Object..js (node:internal/modules/cjs/loader:1689:10)
   at Module.load (node:internal/modules/cjs/loader:1318:32) {
   code: 'MODULE_NOT_FOUND',
   requireStack: [
   '/Users/wreiske/prj/bluehive-ai/.meteor/local/cordova-build/platforms/android/cordova/Api.js',
   '/Users/wreiske/prj/bluehive-ai/.meteor/local/cordova-build/platforms/android/cordova/version'
   ]
   }
   
   Node.js v22.11.0
   at ChildProcess.exitCallback
   (/Users/wreiske/.meteor/packages/meteor-tool/.3.1.0-beta310.0.qd4idg.0eqor++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/tools/utils/tools/utils/processes.ts:174:23)
   at ChildProcess.emit (node:events:518:28)
   at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
   at Process.callbackTrampoline (node:internal/async_hooks:130:17)
wreiske@Wills-MacBook-Pro bluehive-ai % meteor add-platform android
                                              
                                              
While adding platforms:
error: android: platform is already added

wreiske@Wills-MacBook-Pro bluehive-ai % meteor --version
Meteor 3.1-beta.0 
```

I'm going to try and check out this PR locally and use it as my source for meteor, or maybe if you could tag a Meteor 3.1-beta.1 release I can try that? 🙏

**Comment by wreiske** [comment]
OK... I may have found a regression. 

I use git urls for cordova versions for some packages. You can see the documentation on how this works here:  https://guide.meteor.com/cordova#installing-plugins under the heading "Installing a plugin from Git". 

`.meteor/cordova-plugins`:

```
cordova-plugin-audioinput@1.0.3
cordova-plugin-background-mode@git+https://github.com/katzer/cordova-plugin-background-mode.git#ef65179886c10775f5054de38e1b5d700ee19844
cordova-plugin-customurlscheme@git+https://github.com/bluehive-health/cordova-plugin-customurlscheme.git#3736b14f87957705fac024b4175ff000ea4bf358
cordova-plugin-inappbrowser@6.0.0
cordova-plugin-media-capture@5.0.0
cordova-plugin-statusbar@4.0.0
```

Note: I have tried both with git+ and without it. 

When I do this, I get errors:
```
wreiske@Wills-MacBook-Pro cordova-build % meteor npm install
npm error code ETARGET
npm error notarget No matching version found for cordova-plugin-customurlscheme@6.0.0.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.
npm error A complete log of this run can be found in: /Users/wreiske/.npm/_logs/2024-11-08T20_37_02_361Z-debug-0.log
```

in `.meteor/local/cordova-build/package.json` it shows this:
```
    "cordova-plugin-splashscreen": "6.0.0",
    "cordova-plugin-background-mode": "0.7.3",
    "cordova-plugin-customurlscheme": "6.0.0",
    "cordova-plugin-inappbrowser": "6.0.0",
    "cordova-plugin-media-capture": "5.0.0",
```

If I change it to this:
```
    "cordova-plugin-customurlscheme": "git+https://github.com/bluehive-health/cordova-plugin-customurlscheme.git#3736b14f87957705fac024b4175ff000ea4bf358"
```

It works! The package installs correctly. 

Is there something new in 3.1.0 that changes how these dependencies get sucked in?

---

Also noting that I'm still getting the error here: https://github.com/meteor/meteor/pull/13358#issuecomment-2463493381

**Comment by nachocodoner** [comment]
@wreiske: There have been changes to how Cordova dependencies are installed in Meteor, addressing a build issue with indirect dependencies. Described here, https://github.com/meteor/meteor/issues/13303

This could be the issue you're encountering and as a regression for the next 3.1.0 version. I'll try to reproduce it and provide a fix if it's straightforward.

Before that, can you confirm that with version 3.0.4, you don't face the problem with Cordova dependencies specified as Git URLs? I understand that there you get the `Error: Cannot find module 'cordova-android'` and when using 3.1.0 that error is fixed but you get another. Is it like this?

**Comment by nachocodoner** [comment]
@wreiske: I tested using your Corddova plugins.

With only `cordova-plugin-background-mode@git+https://github.com/katzer/cordova-plugin-background-mode.git#ef65179886c10775f5054de38e1b5d700ee19844`, it resolves properly.

But with `cordova-plugin-customurlscheme@git+https://github.com/bluehive-health/cordova-plugin-customurlscheme.git#3736b14f87957705fac024b4175ff000ea4bf358`, I get an error that is more about on how that puglin is configured.

```
Cordova error: CordovaError: Variable(s) missing (use: --variable URL_SCHEME=value).
```  

How have you configured it? I tried several things on the docs, but I can't seem to surpass the error. Just in case you have it there.

**Comment by nachocodoner** [comment]
@wreiske : Found the fix, https://github.com/meteor/meteor/pull/13455/files

We will include for the release. Could you test the branch?

**Comment by wreiske** [comment]
> @wreiske : Found the fix, https://github.com/meteor/meteor/pull/13455/files
> 
> We will include for the release. Could you test the branch?

Amazing! I will make some time today to test this out. Thank you.

**Comment by wreiske** [comment]
Running the latest 3.1-rc.0 and stuck getting cordova to run on ios. The app builds and installs, but I'm just stuck at a white screen.
Screenshot 2024-11-12 at 10 35 11 PM

Screenshot 2024-11-12 at 10 37 08 PM

Found this ticket about it: https://github.com/meteor/meteor/issues/13450

FWIW, cloning the "url" package and removing the line https://github.com/meteor/meteor/blob/5e5d437c6ac79b61f3f750bc022f95fe5b83a961/packages/url/package.js#L17 fixes it!

**Comment by nachocodoner** [comment]
@wreiske: Thank you.

It looks like you've identified the issue caused by the `accounts-base` package. This issue has likely been around since the early versions of Meteor 3, not just from the 3.1.0 fixes, as it also appears in version 3.0.4, according to the GitHub issue.

I'll work on a fix for the next release, so we don't delay 3.1. Good that a workaround is available.

**Comment by nachocodoner** [comment]
@wreiske: I’ve found the solution. It may be safe to include it under 3.1, but I’ll need to test if it validates proper account behavior across apps after this fix. Could you assist?

You should check out the branch https://github.com/meteor/meteor/pull/13459 and test your app, ensure it functions as expected.

If I get your feedback we can more safely include it on 3.1.

**Comment by MarcoTribuz** [comment]
@nachocodoner i can confirm that with a boilerplate app such as simple-todos-vue, and my app it works well :)

**Comment by wreiske** [comment]
I can’t express enough how much joy it brings me to see all the incredible work being put into Meteor. I've been a proud user since 2014—10 years, wow! Over the years, I’ve built projects that have reached millions of users, and with each new release, Meteor just keeps getting better. It’s so exciting to think about all the possibilities it opens up for future projects. Huge thanks to everyone contributing to this amazing platform—I’m beyond excited for 3.1 and what’s next! 🥳

**Comment by nachocodoner** [comment]
@wreiske:

The issue you reported with Cordova has been fully resolved and [is available in Meteor 3.1](https://dev.to/meteor/meteorjs-31-a-new-dawn-for-full-stack-javascript-development-4a13).

Update your app and share any feedback.

```shell
meteor update --release 3.1
```

**Pull request merged**
