### PR TITLE
Allow dynamic headers and return options

### PR DESCRIPTION
**Pull request by mitar**
This allows dynamic headers (like per e-mail unsubscribe link inside headers), and returns information about the e-mail so that for same caller can log all e-mails or in some other way post-process sending of e-mails.

### CODE REVIEW

**Comment by mitar** [comment]
Documentation: https://github.com/meteor/docs/pull/104

**Comment by abernix** [comment]
Could tests be added for this?

**Comment by mitar** [comment]
Added tests.

**Comment by tmeasday** [comment]
I think this change looks pretty good but maybe let's hold off merging while we discuss https://github.com/meteor/meteor/pull/8065

**Comment by mitar** [comment]
Closing in favor of #8207.

**Comment by ayhid** [comment]
@mitar hello sorry for commenting on a closed PR.
but when looking at #8207  it does not support dynamic headers.
Is there any reason this feature was abandoned?

**Comment by mitar** [comment]
I think that this might still be done, despite customization paths added through #8207. Open a feature request and ask MDG to maybe make it pull requests encouraged.

**Pull request closed without merging**
