### PR TITLE
Allow for multiple Accounts.onLogin callbacks on the client.

### PR DESCRIPTION
**Pull request by wbyrnetx**
- Needed to return true in onLoginHook and onLoginFailureHook
iterators.

### CODE REVIEW

**Comment by stubailo** [comment]
LGTM; @dgreensp?

**Comment by wbyrnetx** [comment]
Agreement has been signed.

**Comment by dgreensp** [comment]
LGTM.  Looks like this is a straight-up bug caused by not adhering to the weird contract of `Hook#each` (where you have to return true to keep iterating).

**Comment by stubailo** [comment]
Merged: 36ece1f957b6b7777915cfdcb69dbdf686effa34

Thanks!

**Pull request closed without merging**
