### PR TITLE
Documentation of how to use 1.3 modules in CoffeeScript

### PR DESCRIPTION
**Pull request by GeoffreyBooth**
Resubmitting #6382 per @benjamn, updated for new docs structure. Original description: Per [discussion](https://github.com/meteor/meteor/issues/5788#issuecomment-181988193) with @avital, some documentation of how to use CommonJS to work with modules in CoffeeScript in Meteor 1.3.

### CODE REVIEW

**Comment by lorensr** [comment]
Hi, thanks for the info! I'm getting the error `ReferenceError: require is not defined`. Any idea why? I upgraded to 1.3, did `npm init` and `npm i elasticsearch --save`, and added the line `elasticsearch = require 'elasticsearch'` on the server.

**Comment by benjamn** [comment]
@lorensr what's in your `.meteor/packages` file?

**Comment by lorensr** [comment]
Thanks @benjamn – I hadn't added the `modules` package 😳

**Comment by lorensr** [comment]
@GeoffreyBooth Sorry it's taken so long, but if you happen to be inclined to resubmit a *third* time, it should go to the new docs repo, and I promise to merge it quickly 😝 If not, lmk and I'll write it

https://github.com/meteor/docs/

Also, would be good for the bulk of it to talk about how to use commonjs in general, for non-ecmascript js, and then point to it from / add examples to the coffeescript section. see https://github.com/meteor/docs/issues/3

**Comment by GeoffreyBooth** [comment]
@lorensr sure, I'll revise and resubmit soon.

If submitting it to a new repo means I don't get to become a contributor to the main Meteor repo, you'll have to also accept #6691 soon so that I can become a Meteor contributor :)

**Comment by rijk** [comment]
Any idea how to do this on the client? It says `require is not defined`, probably because CommonJS is not used on the client side?

**Comment by benjamn** [comment]
@rijk `meteor add modules`

**Comment by rijk** [comment]
Ha, I had no idea that existed! Thanks @benjamn , works!

**Pull request closed without merging**
