### PR TITLE
Update Node to version 8.12.0 (prerelease).

### PR DESCRIPTION
**Pull request by benjamn**
As explained by @MylesBorins in [the proposal PR for Node 8.12.0](https://github.com/nodejs/node/pull/21593), the Node team is planning to have a longer Release Candidate process this time, to give contributors a chance to test everything more thoroughly.

This sounds like a great idea to us! In the spirit of thorough testing, this PR is intended to help vet the Node 8.12.0 changes in the context of Meteor, by running our extensive test suite using the new Node version.

Note: since there isn't an official RC release of Node 8.12.0 yet (keep an eye on https://nodejs.org/download/rc/ for that), and we only have a functional Node build system for Unix platforms, this PR currently applies only to Linux and Mac builds, with Windows still using Node 8.11.3.

I'm not sure what version of Meteor the Node 8.12.0 changes will land in, given the uncertainty of the Node release timeline, and given that https://github.com/meteor/meteor/pull/9942 is looking pretty stable these days. We'll put this PR into a milestone once we have a better idea about the timing.

### CODE REVIEW

**Comment by veered** [comment]
This only works in dev mode, right?

**Comment by benjamn** [comment]
If you mean it only works when running Meteor from a checkout, then yes. We haven't released a prerelease version of Meteor with these changes yet.

**Comment by benjamn** [comment]
Are there any specific changes you're excited about in Node 8.12.0?

**Comment by veered** [comment]
A fix for fiber hell: https://github.com/nodejs/node/pull/20727

The change has been backported to 8.12.0. I think it'll be a massive performance improvement in many meteor apps (and maybe rebuilds as well). 

It'll also fix some of the issues people have been having where the CPU gets pegged to 100%.

**Comment by benjamn** [comment]
Another change that I would very much like to get into V8 and then Node 8.12.0 and then Meteor 1.7.1: https://chromium-review.googlesource.com/c/v8/v8/+/833260

The good news is that we can potentially build our own Node with those changes in the meantime, if the backporting process takes too long.

**Comment by veered** [comment]
The first 8.12.0 RC has been released, and has a target release date of September 4th!

https://nodejs.org/download/rc/v8.12.0-rc.1/

**Comment by benjamn** [comment]
Now available by running
```bash
meteor update --release 1.7.1-rc.10
```

**Pull request closed without merging**
