### PR TITLE
Rails reminders - 'Did you mean?' reminders for users more familiar with Rails

### PR DESCRIPTION
**Pull request by mbrookes**
Meteor command line reminders for users more familiar with Rails:

`$ meteor server`
Did you mean 'meteor run'?

`$ meteor console`
Did you mean 'meteor shell'?

`$ meteor new`
Did you mean 'meteor create'?

`$ meteor dbconsole`
Did you mean 'meteor mongo'?"

### CODE REVIEW

**Comment by stubailo** [comment]
I'd change the word refugee since it's overly political for this code - perhaps "for people who are used to the Rails CLI?"

**Comment by stubailo** [comment]
Also, can we put all aliases in a separate file? Just so they don't get lost between all of the real commands.

**Comment by mbrookes** [comment]
> I'd change the word refugee since it's overly political

Sure can - I was referring to myself! :grinning:

> Also, can we put all aliases in a separate file? Just so they don't get lost between all of the real commands.

No problem - I weighed grouped the in their own section against collocating with their related meteor command, and it was a toss of the coin in the end!

**Comment by mbrookes** [comment]
Done.

**Comment by stubailo** [comment]
Looks cool to me!

**Comment by stubailo** [comment]
BTW, you should configure the email in your local git.

**Comment by mbrookes** [comment]
> BTW, you should configure the email in your local git.

It is configured... just with a specific email address that lets me know where recruiters or other spammers got it from.

**Comment by stubailo** [comment]
Then you could add that email to your GitHub account so that it associates you with your commits.

**Comment by mbrookes** [comment]
Good point - done. Sorry for any extra overhead. 

And I see github now (or maybe always?!) also offers a similar mail alias...

**Pull request closed without merging**
