### PR TITLE
Patch http package to use fetch

### PR DESCRIPTION
**Pull request by jankapunkt**
Until full migration of the internal packages, that still use `http` is done, we might want to patch `http` in order to prevent the usage of the deprecated `request` npm package.

Related:

https://github.com/meteor/meteor/issues/10913
https://github.com/meteor/meteor/pull/11305
https://github.com/wekan/wekan/issues/3524
https://forums.meteor.com/t/replacement-for-http-package-using-fetch/54388

### CODE REVIEW

**Comment by filipenevola** [comment]
Hi @jankapunkt I see that you are considering this PR still in draft.

What is the work left here? How could we help?

**Comment by jankapunkt** [comment]
I want to make sure the wekan issue (#11314) is not related to this PR because I asked @xet7 to build using this PR Branch to see If the deprecation issue is fixed but then we faced the jquery issue.

Now when I try to test the package of this PR with `./meteor test-packages http` and Open the Browser then I am actually getting jquery errors as well, however the Ci is running fine so I am a bit stuck where to investigate further.

**Comment by jankapunkt** [comment]
@filipenevola the Wekan issue has been resolved. The tests are running on my local package end but I can't get them to run when I am in the Meteor dev project (on the client the browser then says there are dozens of packages missing).

Do you know how that could be? I mainly followed all the instructions from the dev guide but I can't run the package test. Are these covered in the CI as well?

**Comment by xet7** [comment]
@filipenevola @jankapunkt 

Wekan issue for building Wekan was solved with `chmod u+w *.json`:
https://github.com/wekan/wekan/commit/ea697f2238842893953dee76bed03ffd5b4a107e

That issue was because of package.json etc were read-only.

But, that does not solve updating to use fetch. There is still error about that in browser console.

**Comment by xet7** [comment]
Just a moment I'll try does this patch work for using fetch.

**Comment by xet7** [comment]
Oops running from checkout brings jquery errors back:
```
$ meteor
=> Running Meteor from a checkout -- overrides project version (Meteor 2.0)
[[[[[ ~/repos/wekan ]]]]]                     

=> Started proxy.                             
=> Errors prevented startup:                  
   
   While selecting package versions:
   error: No version of jquery satisfies all constraints: @1.11.10, @=3.0.0
   Constraints on package "jquery":
   * jquery@1.11.10 <- top level
   * jquery@=3.0.0 <- top level
   * jquery@1.11.3-plugins.0_3 <- blaze 2.1.3-plugins.0
   * jquery@1.0.1 <- kadira:blaze-layout 2.3.0
   * jquery@1.0.1 <- tap:i18n 1.4.1
   * jquery@1.0.0 <- mquandalle:jquery-textcomplete 0.3.6_1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker 1.7.1
   * jquery@1.0.0 || 1.0.1 <- mquandalle:moment 0.0.1
   * jquery@1.0.0 || 1.0.1 <- easylogic:summernote 0.8.1
   * jquery@1.0.1 <- twbs:bootstrap 4.0.0-alpha2 <- easylogic:summernote 0.8.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-fi 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-ar 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-bg 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-br 1.7.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-ca 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-cs 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-da 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-de 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-el 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-en-gb 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-eo 1.7.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-es 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-eu 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-fa 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-fr 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-gl 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-he 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-hi 1.7.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-hu 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-hy 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-id 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-it 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-ja 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-ka 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-km 1.7.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-ko 1.7.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-lv 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-mk 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-mn 1.7.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-nb 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-nl 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-oc 1.7.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-pl 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-pt-br 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-pt 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-ro 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-ru 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-sl 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-sr 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-sv 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-sw 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-ta 1.7.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-th 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-tr 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-uk 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-vi 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-zh-cn 1.4.1
   * jquery@1.0.0 <- rajit:bootstrap3-datepicker-zh-tw 1.4.1
   * jquery@1.0.0 <- staringatlights:inject-data 2.0.1 <- staringatlights:fast-render 2.16.1
   
=> Your application has errors. Waiting for file change.
```

**Comment by filipenevola** [comment]
> (on the client the browser then says there are dozens of packages missing).

Which packages are missing? Did you clone including submodules?

**Comment by xet7** [comment]
@filipenevola 

When I did `git submodule init && git submodule update` on that meteor repo and tried again, there are still those jquery dependency errors, it did not make any difference.

**Comment by jankapunkt** [comment]
@filipenevola the following errors appear in all my efforts to test with `tinytest` in 2.0 (devmode, as well as relase):

```
The jquery npm package could not be found in your node_modules directory.
Please run the following command to install it:

  meteor npm install jquery

If you previously relied on a specific version of jquery, it may be important
to install that version; for example:

  meteor npm install jquery@1.12.1
jquery.js:33:11
Uncaught Error: jQuery not found
    module dombackend.js:8
    fileEvaluate modules-runtime.js:346
    require modules-runtime.js:248
    require modules-runtime.js:268
    <anonymous> blaze.js:3729
    <anonymous> blaze.js:3747
dombackend.js:8:8
Uncaught TypeError: Package.blaze is undefined
    <anonymous> http://localhost:3000/packages/test-helpers.js?hash=f88f09175d9f1fb693dd8a9bf4a5cbc87ba0ebf0:23
    <anonymous> http://localhost:3000/packages/test-helpers.js?hash=f88f09175d9f1fb693dd8a9bf4a5cbc87ba0ebf0:838
test-helpers.js:23:13
Uncaught TypeError: Package.blaze is undefined
    <anonymous> http://localhost:3000/packages/spacebars.js?hash=da5eec90fbd51a8135bcdf5e00721f572914e7fd:22
    <anonymous> http://localhost:3000/packages/spacebars.js?hash=da5eec90fbd51a8135bcdf5e00721f572914e7fd:327
spacebars.js:22:13
Uncaught TypeError: Package.blaze is undefined
    <anonymous> http://localhost:3000/packages/templating-runtime.js?hash=59e4d378637c728490431629cc7f3857d44a6798:18
    <anonymous> http://localhost:3000/packages/templating-runtime.js?hash=59e4d378637c728490431629cc7f3857d44a6798:230
templating-runtime.js:18:13
Uncaught TypeError: Package['templating-runtime'] is undefined
    <anonymous> http://localhost:3000/packages/templating.js?hash=096eff953747941ab270ec181ccdce958402906f:14
    <anonymous> http://localhost:3000/packages/templating.js?hash=096eff953747941ab270ec181ccdce958402906f:23
templating.js:14:16
Uncaught TypeError: Package['test-helpers'] is undefined
    <anonymous> http://localhost:3000/packages/local-test_blaze.js?hash=baec1c7393a9e3632b31a80e9745650becc8cee3:18
    <anonymous> http://localhost:3000/packages/local-test_blaze.js?hash=baec1c7393a9e3632b31a80e9745650becc8cee3:930
local-test_blaze.js:18:17
Uncaught TypeError: Package.spacebars is undefined
    <anonymous> http://localhost:3000/packages/local-test_spacebars.js?hash=9a4d7a15d139615e6daf37d9b0cec77e82dc3b11:18
    <anonymous> http://localhost:3000/packages/local-test_spacebars.js?hash=9a4d7a15d139615e6daf37d9b0cec77e82dc3b11:96
local-test_spacebars.js:18:17
unreachable code after return statement
local-test_spacebars-tests.js:6944:4
Uncaught TypeError: Package['test-helpers'] is undefined
    <anonymous> http://localhost:3000/packages/local-test_spacebars-tests.js?hash=64751885597c93f986315548ce084cac2324adce:21
    <anonymous> http://localhost:3000/packages/local-test_spacebars-tests.js?hash=64751885597c93f986315548ce084cac2324adce:9089
local-test_spacebars-tests.js:21:17
Uncaught TypeError: Package['test-helpers'] is undefined
    <anonymous> http://localhost:3000/packages/local-test_templating-runtime.js?hash=9d4e400c5c050a67c69c933a0e46a1b434e683ac:18
    <anonymous> http://localhost:3000/packages/local-test_templating-runtime.js?hash=9d4e400c5c050a67c69c933a0e46a1b434e683ac:507
local-test_templating-runtime.js:18:17
Uncaught TypeError: Package.blaze is undefined
    <anonymous> http://localhost:3000/packages/test-in-browser.js?hash=b32a19353fed798e2ded1ea8b416505c978ee93a:22
    <anonymous> http://localhost:3000/packages/test-in-browser.js?hash=b32a19353fed798e2ded1ea8b416505c978ee93a:3320
test-in-browser.js:22:13
Uncaught TypeError: Package['test-in-browser'] is undefined
    <anonymous> http://localhost:3000/global-imports.js?hash=5c2ddab1722124ac4c6b801cfc6084cc45cc1d7d:4
global-imports.js:4:1
Uncaught Error: Can't find test driver package: test-in-browser
    <anonymous> http://localhost:3000/packages/meteor.js?hash=d522625a3ade81e56b990f2722ff3ed57f63222d:1148
    maybeReady http://localhost:3000/packages/meteor.js?hash=d522625a3ade81e56b990f2722ff3ed57f63222d:938
    loadingCompleted http://localhost:3000/packages/meteor.js?hash=d522625a3ade81e56b990f2722ff3ed57f63222d:950
meteor.js:1148:13
```

**Comment by jankapunkt** [comment]
@filipenevola I think the Wekan issues resolved due to different cirumstances. I also worked with the HTTP replacement for a while and had no further issues. I am, however, not sure how the above mentioned errors happened. I can't reproduce them anymore.

**Comment by xet7** [comment]
Yes, while Wekan does build OK currently, Meteor does not use fetch yet.

**Comment by jankapunkt** [comment]
@StorytellerCZ just re-ran the tests and they were passing in the CI again (:tada:) and I will tomorrow run them locally again with a fresh new clone and see if it works out. If nothing fails it should be ready to merge.

**Comment by StorytellerCZ** [comment]
@jankapunkt fixed the tests so that they run now. The issue was that the package was in the deprecated folder where apparently tests don't run.

**Comment by jankapunkt** [comment]
@filipenevola @StorytellerCZ the tests now succeed locally and should also pass in the ci.

There were several issues we did not quite cover. 1st, @StorytellerCZ discovered, that packages in the deprecated folder were not covered by the ci (which is why it never failed before). 2nd the tests still included test code that checked against npmRequestOptions, which is part of the request package and not present in the code anymore. Fix was to update the tests to be in line with fetch. 3rd two of the the tests (check for errors on server, on client) had about 130 seconds of timeout until the response for false ip hits in. This may be a local issue on my machine, however.

**Comment by jankapunkt** [comment]
@filipenevola @StorytellerCZ has one of you access to the circle logs? I wonder how/why travis and appveyor succeed but circle fials after 42min (seems to be a timeout?)

**Comment by StorytellerCZ** [comment]
@jankapunkt 
```
Error: Cannot find package "ejson". Try "meteor add ejson".
```

**Comment by jankapunkt** [comment]
:facepalm: forgot to commit package.js

**Comment by StorytellerCZ** [comment]
Still missing `ejson` somewhere.
`packages/http/httpcall_server.js:1:81`

**Comment by jankapunkt** [comment]
Actually I checked and EJSON was introduced in `jkuester:http` and does not provide any further useful functionality. I remove it and re-run the tests.

**Comment by StorytellerCZ** [comment]
This is going to pass, so I'm going to merge it in afterwards.

**Pull request merged**
