### PR TITLE
Print link to meteor.com/learn when a new app is created

### PR DESCRIPTION
**Pull request by stubailo**
I'm glad we have that awesome page to link to.

### CODE REVIEW

**Comment by Primigenus** [comment]
It would be nice if Meteor would likely only print this if it thinks you may be new to Meteor. Is there a way to guess that?

**Comment by stubailo** [comment]
@Primigenus I feel like this wouldn't affect experienced users too much - two lines of output could be pretty easy to ignore. Do you disagree?

**Comment by Primigenus** [comment]
@stubailo I feel like from a UX point of view it's good to anticipate what situation the user is in, so if for example we're dealing with a more advanced user maybe we can tell them something in those two lines that they can use rather than skip. That's why I was wondering out loud about it. :)

**Comment by stubailo** [comment]
@Primigenus what would be a more useful thing to print for advanced users?

**Comment by stubailo** [comment]
I didn't hear anything new, so I am merging: 927745a5d5e6c121b9b9582d212502947d836fa8

**Comment by Primigenus** [comment]
Oops. Sorry about that, I was going to think about it and get back to you and then I forgot. Apologies!

**Pull request closed without merging**
