### PR TITLE
added basic attachments handling

### PR DESCRIPTION
**Pull request by tomarcafe**
now Email.send(options) options support options.attachments, which is assumed to be [] of attachment objects.

see here https://github.com/andris9/mailcomposer#add-attachments for supported attachment object structure.
tested it at my current project. going to propose pull request.

### CODE REVIEW

**Comment by stubailo** [comment]
@glasser seems good to me, what do you think? Should we add it to the docs with a link to the mailcomposer documentation?

**Comment by tomarcafe** [comment]
btw 
there s comments in code 

 // setup message data
// XXX support attachments (once we have a client/server-compatible binary
// Buffer class) 
(https://github.com/meteor/meteor/blob/devel/packages/email/email.js#L133-L135)

what does it mean? i.e. won't this break smth or so?

**Comment by stubailo** [comment]
@tomarcafe it looks like that comment is from back in the day when `Email.send` was supported on the client? Now that it is server-only, I think it is not an issue at all.

**Comment by stubailo** [comment]
Merged in the above commit

**Pull request closed without merging**
