### PR TITLE
Make Script More Portable With #!/usr/bin/env

### PR DESCRIPTION
**Pull request by TomFreudenberg**
To make the scripts more compatible on different linux environments, shebang should be changed in general to `#!/usr/bin/env bash` instead `#!/bin/bash`

### CODE REVIEW

**Comment by TomFreudenberg** [comment]
Hmm, I checked the errors on `ci/circleci`. I am currently not able to see if this is something which comes through my changes or are invalid in `devel` branch currently.

If you guide me, I will test and provide a patch if something is wrong in this PR.

**Comment by stubailo** [comment]
Looks great. Apparently there is some history here: https://github.com/meteor/meteor/pull/1148

But we're going to accept it now since you're doing some great work around making Meteor run on different platforms.

**Comment by TomFreudenberg** [comment]
Hi Sashko ( @stubailo ) thanks ... I am sorry hadn't seen that PR before but it is great that you accepted and merged.

**Comment by stubailo** [comment]
Would it be possible to elaborate here on which environments this is necessary for? Just for historical value.

**Comment by TomFreudenberg** [comment]
Hi Sashko, yes, I will write it down here. I started a compatible check issue and will go thru a number of distros to check where meteor / meteor universal will run. For those are popular and not yet official supported, we will provide a dev_bundle on bintray - We like the idea of meteor everywhere :-).

**Comment by TomFreudenberg** [comment]
Here are the first one's

FreeBSD, OpenBSD, NetBSD

**Comment by TomFreudenberg** [comment]
Next: busybox / debootstrap

**Comment by tangorri** [comment]
So this mean I can try to compile/run rocketchat on freebsd now ?

**Pull request merged**
