### PR TITLE
Relax release constraints for #7004

### PR DESCRIPTION
**Pull request by tmeasday**
Ready for review @benjamn

### CODE REVIEW

**Comment by benjamn** [comment]
I've read over the code and everything makes sense to me. I'd like to play with it a bit more just to make sure the workflow for updating packages is smooth, but I don't have an objection to merging this to `devel` if the tests pass.

**Comment by tmeasday** [comment]
Oh, I think maybe we should merge it to `release-1.4` actually? not sure.

We should probably do a proper beta release with it in it so we can test the code for real before merging to devel

**Comment by tmeasday** [comment]
Oh and I expect the tests to pass, I'm rerunning them

**Comment by abernix** [comment]
I re-ran this on CI 2.5x last night unsuccessfully.  Mostly CI silliness (consider merging #7063 with Ben's 05dfe244382a927fb1284162c3df0d38570a6d2b cherry-picked on top), but `autoupdate` fails on my local box too so that's probably an actual issue.

**Comment by tmeasday** [comment]
Yes, I've concluded this is a real failure too. In fact I'm no longer sure
auto update is a flaky test

**Comment by tmeasday** [comment]
@benjamn If you are happy with this, let's merge it to `release-1.4`. Tests are now passing.

**Comment by tmeasday** [comment]
Merged to `release-1.4`!!

**Comment by benjamn** [comment]
@tmeasday It looks like some of these commits made it into `release-1.4` but not all of them. Whatever happened happened before I closed https://github.com/meteor/meteor/pull/7035. If you have any idea what happened, I'm curious, but it seems to be sorted out now.

**Pull request closed without merging**
