### PR TITLE
Release 2.16

### PR DESCRIPTION
**Pull request by nachocodoner**
```
meteor update --release 2.16
# or 
meteor create appname --release  2.16
```

We'll make sure Meteor 3.x isn't affected by new additions in this release. Tracking progress on PR https://github.com/meteor/meteor/pull/13098.

### Best Candidates

These are the top PR candidates for the next release, focusing on Meteor 3.x migration. Original authors will address any necessary checks, with the core team reviewing for compatibility with both 2.x and future 3.x versions.

- [x] [339 Support observeChangesAsync and observeAsync [Meteor 2.x]](https://github.com/meteor/meteor/pull/13025)

- [x]  New mongo package options to optimize Oplog tailing performance to include/exclude certain collections
https://github.com/meteor/meteor/pull/13009

### Quick Gains

These PRs are straightforward and expected to integrate smoothly into Meteor 3.x, offering immediate benefits. We will double check them on a release-3.0 based-branch.

- [x] chore: remove repetitive words
https://github.com/meteor/meteor/pull/13093

- [x] Get default options from meteor settings
https://github.com/meteor/meteor/pull/13005

- [x] Session storage option for accounts
https://github.com/meteor/meteor/pull/13046

- [x] check - throw all errors
https://github.com/meteor/meteor/pull/12970

- [x] Add nodemailer-openpgp
https://github.com/meteor/meteor/pull/12991

### Hotfixes

Update terser to v5.31.0
https://github.com/meteor/meteor/pull/13120

### Discarded

Other PRs are currently excluded from the upcoming release due to the effort needed for verification and potential impact on Meteor 3.x transition, which remains our primary focus.

DDP resumption
https://github.com/meteor/meteor/pull/12436

Update Accounts with Async methods
https://github.com/meteor/meteor/pull/12647

Remove underscore
https://github.com/meteor/meteor/pull/12245
https://github.com/meteor/meteor/pull/12261
https://github.com/meteor/meteor/pull/12259
https://github.com/meteor/meteor/pull/12238
https://github.com/meteor/meteor/pull/12267

Asyncify _checkForCaseInsensitiveDuplicates
https://github.com/meteor/meteor/pull/13076

-----------------------------

Any other PR to be considered for including in 2.16 release must point `release-2.16` branch, update to latest changes, have green checks on that branch, and ask for a review keeping the PR alive.

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
How much of the other features can we put in?

**Comment by harryadel** [comment]
@StorytellerCZ Yup, would like to know too! it'd be nice to lump in the remaining underscore PRs

**Comment by nachocodoner** [comment]
For the 2.16 release, our primary aim is to merge PRs labeled as "Best candidates" on the description above. We'll also review PRs tagged as "Quick gains" as they appear low-risk and straightforward to implement. However, we've sidelined several others requiring extensive verification and transition to Meteor 3.x, our current priority, to avoid delays.

Our primary focus remains on Meteor 3.x RC's, with ongoing merging of changes to 2.16. Release date pending.

**Comment by StorytellerCZ** [comment]
Got an interesting error when trying to update:
```
While selecting package versions:
error: No version of logging satisfies all constraints: @1.3.4-beta2160.1, @=1.3.3, @~1.3.4-beta2160.1
Constraints on package "logging":
* logging@1.3.4-beta2160.1 <- top level
* logging@=1.3.3 <- top level
* logging@~1.3.4-beta2160.1 <- top level
* logging@1.3.3 <- webapp 1.13.8 <- accounts-oauth 1.4.4-beta2160.1 <- accounts-facebook 1.3.3
* logging@1.3.3 <- webapp 1.13.8 <- communitypackages:fast-render 3.3.1
* logging@1.3.4-beta2160.1 <- mongo 1.16.10-beta2160.1
* logging@1.1.17 <- percolate:migrations 1.0.3
* logging@1.1.20 || 1.3.1 || 1.3.3-beta300.6 <- reywood:publish-composite 1.8.8
* logging@1.3.4-beta2160.1 <- email 2.2.6-beta2160.1
* logging@1.3.3 <- oauth 2.2.1 <- accounts-oauth 1.4.4-beta2160.1 <- accounts-facebook 1.3.3
* logging@1.3.3 <- oauth 2.2.1 <- bozhao:link-accounts 2.8.0
```

Given that this is a patch update, I wonder if this one is the issue:
```
logging@1.1.20 || 1.3.1 || 1.3.3-beta300.6 <- reywood:publish-composite 1.8.8
```
This looks like an issue with the 3.0 release having an overlap with an existing package release.

**Pull request merged**
