### PR TITLE
Expose fields automatically published for the logged-in user

### PR DESCRIPTION
**Pull request by mitar**
Addresses #7743.

### CODE REVIEW

**Comment by laosb** [comment]
Should we make it a public API instead of an underscore-prefixed *private* API?

**Comment by stubailo** [comment]
I think an underscored name is fine for this. We can always add a non-underscored version later.

**Comment by stubailo** [comment]
@mitar is this intended to be the _default_ set of published fields? Or should it represent the current set, if it's modified?

**Comment by mitar** [comment]
Current set. The goal is that you can override the prototype to configure the current set. Which is then published. So you should override the prototype before publish happens. (Hm, now I am not 100% sure that you can really do that in practice.)

**Comment by stubailo** [comment]
Hmm, is overriding methods the right API for this kind of thing? I guess that's how overriding stuff like the Accounts URLs works.

Is the publication inside Meteor.startup at least?

**Comment by mitar** [comment]
It is inside [constructor](https://github.com/peerlibrary/meteor/blob/ff66df982ec6f4275bcd237736843d0288c4e7bb/packages/accounts-base/accounts_server.js#L35). I am not sure where is that called from though.

**Comment by stubailo** [comment]
Looks like it's called synchronously, so you probably wouldn't be able to override this from app code: https://github.com/meteor/meteor/blob/be986fd70926c9dd8eff6d8866205f236c8562c4/packages/accounts-base/server_main.js#L9

**Comment by stubailo** [comment]
Let's close this PR and talk on the issue?

**Pull request closed without merging**
