### PR TITLE
Release 1.4.3

### PR DESCRIPTION
**Pull request by benjamn**
Meteor 1.4.3 will be an incremental release to fix bugs and address production performance issues (especially client page load time), along with any additional (re)build performance improvements that can be identified.

I'm creating this pull request relatively early in the release process so that we can go ahead and put out some betas with the bug fixes that have been merged to `devel` recently.

See the [1.4.3 milestone](https://github.com/meteor/meteor/milestone/25) for a growing list of issues that will be addressed before the final 1.4.3 release.

Note that [upgrading to Node 6](https://github.com/meteor/meteor/pull/6923) is also in progress, but probably will not be appropriate for 1.4.3.

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
> especially client page load time

@benjamn what thoughts do you have around improving client load times?

**Comment by mitar** [comment]
Should also other accounts packages be split in the same way as `facebook` was? So that everything is part of the same release?

**Comment by laosb** [comment]
@mitar I guess so, but currently I have no time in submitting PRs. Sorry!

**Comment by glasser** [comment]
Is the link in the description to "upgrading to Node 6" correct? It points to the 1.4.3 milestone.

**Comment by abernix** [comment]
@glasser Yup. Fixed.

**Comment by janat08** [comment]
Did any1 run benchmarks for how much faster it is?

**Comment by benjamn** [comment]
@GeoffreyBooth @klaussner I'm going to republish `coffeescript` once this PR is merged (soon, probably Monday), so that packages used by `cofeescript` (like `babel-compiler`) will have non-prerelease versions when the publish happens.

**Comment by mitar** [comment]
Just make sure to use `_X` suffixes when wrapping other programs. :-)

**Comment by benjamn** [comment]
@mitar You may find [this discussion](https://github.com/meteor/meteor/pull/8298#issuecomment-279012565) relevant to your interests.

Specifically, with Meteor 1.4.3, core¹ Meteor packages that wrap other libraries will be constrained by the release to be patch-compatible with whatever version of the package was current when the release was published. So if you want to bump a library version to a new minor or major version, and you want to use the same version for a core Meteor package, then you will have to wait for a new Meteor release.

This is similar to how things worked before Meteor 1.4, when the Meteor release constrained the exact version of every core package, except that it's not quite as strict (any patch-compatible version is allowed).

———
1. Note that the new version constraints only apply to core packages. The Blaze packages are no longer in core, for example, so you have nothing to worry about. This is also why I just moved `coffeescript` into `packages/non-core`, so that project can keep releasing new minor/major versions without waiting for Meteor releases.

**Comment by mitar** [comment]
> This is also why I just moved coffeescript into packages/non-core, so that project can keep releasing new minor/major versions without waiting for Meteor releases.

Yes, I like that change.

But then inside non-core, cofeescript will have `<upstream>_<patch>` structure?

I really think this is very useful for many many packages. For example, mongo driver?

**Comment by benjamn** [comment]
> But then inside non-core, coffeescript will have `<upstream>_<patch>` structure?

That's right.

**Pull request merged**
