### PR TITLE
Update to cli tool help text

### PR DESCRIPTION
**Pull request by yauh**
inspired by issue #3566 (Simplify `meteor help`) and
http://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap12.html

### CODE REVIEW

**Comment by lorensr** [comment]
Thanks, looks good! Perhaps you can take out the last line that reiterates the help command, since it's prominent twice at the start? What are people's thoughts on:

- Ordering commands by prevalence versus alphabetical
- Adding empty lines before sections ("Projects:" etc) for readability versus conserving vertical space?

**Comment by yauh** [comment]
Yeah, the last line should probably go.
I did not want to mess with the ordering beyond alphabetical listings because I think it will be extremely hard to decide on an actual order to prevalence, especially should there be more commands coming. To me the help is more of an index which I'd expect to be alphabetical.
I tried with and without empty lines, but as my terminal window is usually quite small I though the additional whitespace was rather distracting and indenting was sufficient for giving the help text some structure. But then again, I looked at `nmap --help` for inspiration, which is probably not a good role model ;)

**Comment by stubailo** [comment]
It would be great if this auto-generated the summaries from: https://github.com/meteor/meteor/blob/devel/tools/help.txt

Otherwise it might be hard to keep things updated.

**Comment by yauh** [comment]
@stubailo Agreed that automated creation would be best. This would require adding an attribute to identify a group for each command. As a first step I wanted to keep things simple, also based on @glasser comment here https://github.com/meteor/meteor/issues/3566#issuecomment-71744160

It's probably not a big thing to add a new field to each command as a group, unless anyone has a reason against it. I could take a stab on it in the next couple of days probably.

**Comment by glasser** [comment]
Well, my suggestion was that you'd still manually lay out the order and grouping of commands like you did in this change, but the actual line itself would be generated automatically (using the summary from help.txt).  Currently this is implemented for `{{commands}}` which inserts a list of all commands with the summaries; instead you could have some new `{{command deploy}}` thing that inserts the line that `{{commands}}` would have inserted for `deploy`.

**Comment by yauh** [comment]
@glasser I see, that seems like a compromise though. It would still require manually modifying the `help.txt` file every time a new command is added. Wouldn't it be better to extend the `command` object to include a `group` and possibly a `visibility` field? Then extending the `{{commands}}` helper to take a group as an argument to have at least some automation for the help text.
I'd love some feedback before I sprint ahead and put this into code.

On second thought I am not so sure whether `visibility` is necessary at all - could rather put them in an `internal` group and not add them to the main `help` command.

**Comment by glasser** [comment]
Sure, but I think that having the ability to control the order within the group is nice too, if we're doing this.

**Comment by stubailo** [comment]
We can't accept this because it isn't maintainable. We would need a system that generates a nice list from the help text, or a metadata file.

**Pull request closed without merging**
