### PR TITLE
Docs quick start cordova

### PR DESCRIPTION
**Pull request by nachocodoner**

### CODE REVIEW

**Review by denihs — APPROVED** [review]

**Comment by harryadel** [comment]
@nachocodoner Is this out yet??

**Comment by denihs** [comment]
Yes https://docs.meteor.com/about/cordova.html

**Comment by harryadel** [comment]
I've trying to apply this one https://guide.meteor.com/cordova the entire day :sob:
Should we remove/update it now that we have a newer version?

**Comment by denihs** [comment]
I'm not sure if the new guide setup would work with Meteor 2. 

@nachocodoner could you confirm?

If not, we can add a warning message at the top of this guide to point people to the new solution.

**Comment by harryadel** [comment]
I was applying both guides to 2.15 application and Nacho's version worked wonderfully.

**Pull request merged**
