### PR TITLE
Fixes #5776: Test app debugger listens TOOL_NODE_FLAGS debug port + 1

### LINKED ISSUE #5776: TOOL_NODE_FLAGS="--debug-brk" makes self-test fail due to port collision.
While developing for the feature #5512, I encountered an issue while trying to use `node-inspector` to debug the spawned CLI call on a `self-test` test.

In few words, the issue is that if the env variable `TOOL_NODE_FLAGS="--debug-brk"` to run the `self-test`, the spawned test app will try to bind to the same port, creating a loop of failures and not letting you debug the test application.

In order to reproduce it: `TOOL_NODE_FLAGS="--debug=6060" ./meteor self-test 'custom minifier - devel vs prod'`.

This is the output:
```
$ TOOL_NODE_FLAGS="--debug=6060" ./meteor self-test 'custom minifier - devel vs prod'
debugger listening on port 6060
custom-minifier: custom minifier - devel vs prod ...
  ... fail!
  => wrong-exit-code at ../../../../tools/tool-testing/selftest.js:665
  => Expected: 0; actual: 1
  => Last 100 lines:
  2| debugger listening on port 6060
  2| => Errors while initializing project:
  2|
  2| While loading plugin `minifyCustom` from package `custom-minifier`:
  2| error: Plugin.registerMinifier does not accept `filenames`
  2|
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying

Skipped 147 non-matching tests (don't match specified pattern)

1 failure:

```

I already found a fix though, and I will submit a PR soon where we could review the implementation.

### PR DESCRIPTION
**Pull request by carlosbaraza**
This pull request fixes the issue #5776.

I did not write tests for the pull request but if the MDG considers they are needed for this modifications, I will work on them.

### CODE REVIEW

**Comment by carlosbaraza** [comment]
I think I should also update this https://github.com/meteor/meteor/blob/dc3cd6eb92f2bdd1bb44000cdd6abd1e5d0285b1/tools/README.md#debugging

**Comment by stubailo** [comment]
Hmm, this logic looks pretty complicated/brittle. Would it be possible instead to have a separate env variable to set the debug port of the app inside?

**Comment by carlosbaraza** [comment]
Hi @stubailo, 

I actually though about that in the first place. It's not a bad approach but I thought that if the user didn't set the variable we should still do something to avoid the port collision. That way I came up with this.

However, I agree it is not very reliable solution because there is some complex logic, and because the node cli debug api might change in the future, breaking this.

Any proposal for the env variable name?

**Comment by stubailo** [comment]
Hmm, maybe something super specific like `SELF_TEST_APP_DEBUG_PORT`?

**Comment by carlosbaraza** [comment]
@stubailo, great. I will work on this as soon as I have some time :)

**Comment by carlosbaraza** [comment]
@stubailo, I added the possibility to configure the `TOOL_NODE_FLAGS` env variable of the self-test meteor calls using the env variable `SELF_TEST_TOOL_NODE_FLAGS`.

**Pull request merged**
