### PR TITLE
Blaze parent document

### PR DESCRIPTION
**Pull request by jchristman**
Pull request for #3891.

In this pull request I have:

 - Update Blaze.render and Blaze.renderWithData to include an optional 'parentDocument' argument that will generate the elements with the appropriate document context. Per the discussion in #3891, I refactored the two functions to use an 'options' parameter due to the large number of arguments. On that note, I made a design choice on Blaze.renderWithData to put the arguments as ```Blaze.renderWithData(options, data)``` instead of ```Blaze.renderWithData(data, options)```. I know this runs contrary to the [MDG Style Guide](https://github.com/meteor/meteor/wiki/Meteor-Style-Guide#keyword-arguments-with-options), but I felt it made more sense in this case. I also felt having the data argument separate from the options field made a bit more sense than including it as a field.
 - I maintained backwards compatibility by automatically converting the arguments to an object if the first argument to the function is not an object. I use Blaze._warn to notify the developer of the new calling convention. I figure at some point in the future, removing the backwards compatibility should be very straightforward.
 - I updated all tests that use Blaze.render to use the new calling convention, though I did ensure [one of the tests](https://github.com/meteor/meteor/compare/devel...jchristman:blazeParentDocument#diff-1d3a61d10a8b5dbbbba98f2e5a8fbf66R134) used a backwards compatible call to make sure the old way still works.
 - I created a [new test](https://github.com/meteor/meteor/compare/devel...jchristman:blazeParentDocument#diff-1d3a61d10a8b5dbbbba98f2e5a8fbf66R716) to demonstrate the new functionality provided by the update.
     - A design question here: this test fails if popups are blocked by the browser. Throw a meteor error if the new window (which opens as a tab) is undefined. Is this sufficient or is it bad to have a test fail if the popup is blocked?
 - I updated the documentation to reflect the appropriate calling conventions.

If you have any questions, please let me know!

### CODE REVIEW

**Comment by Slava** [comment]
Thank you for a very well constructed PR. Unfortunately, right now we don't have anyone working on the Blaze project, so we would review it later.

**Comment by jchristman** [comment]
Sounds good! Look forward to the new feature.

**Comment by dgreensp** [comment]
If we're moving to an `options` style, then we should deprecate `renderWithData` while we're at it, and `data` should just be an option to `render`.  (That's probably what we should have done in the first place, rather than coming up with the awkwardly-named `renderWithData`.)  The `templateOrView` and `parentNode` arguments are required and should not be options.  (While there is some leeway in the style guide for special cases, this is a normal case of "Keep the most important arguments in the signature".  It becomes harder to understand that the function takes a template or view, renders it, and inserts it into the DOM if the arguments that fill these roles are buried under "options".)

I propose either:

* `Blaze.render(templateOrView, parentNode, [nextNode], [options])`; or
* `Blaze.render(templateOrView, parentNode, [options])`

... with everything else (including `data`) as an option.

**Comment by jchristman** [comment]
Ok so that would be pretty easy to implement I think. I think I'm in favor of the ```Blaze.render(templateOrView, parentNode, [options])``` syntax, but I suppose that's up to MDG, not me. Let me know which you would like and I'll implement it.

One quick question, should the new Blaze.renderWithData method look something like this?

```js
Blaze.renderWithData = function(templateOrView, data, parentNode, nextNode, parentView) {
    Blaze._warn("Blaze.renderWithData is now deprecated in favor of calling " +
                         "Blaze.render(templateOrView, parentNode, [options]) with " +
                         "the 'data' field in options.");
    options = { 'nextNode': nextNode, 'parentView': parentView, 'data': options };
    Blaze.render(templateOrView, parentNode, options);
}
```

Then, we will just not support an options object (and thus not #3891 fix) on Blaze.renderWithData?

Lastly, are the variable names templateOrView and parentNode preferable over content and parentElement respectively?

**Comment by dgreensp** [comment]
* `content` and `parentElement` sounds good.  The type of `parentElement` in the docs should be "DOM Element" since that is what we do in other calls!

* Let's not do `Blaze._warn` here.  We don't warn about all API changes, only when we really want to force people to port their apps.  We do put a comment like `// XXX COMPAT WITH x.x.x` (the release version can be filled in later) in the code so that we can track these things, and we'll warn before we actually remove the old API (which so far we have done very reluctantly).  In the long run, we want the meteor tool to help you migrate your app rather than issuing warnings when we change an API.

* `Blaze.render(templateOrView, parentNode, [options])` sounds good

Thanks!

**Comment by jchristman** [comment]
- Reworked [Blaze.render](https://github.com/jchristman/meteor/commit/0adea8d789e0945b3895732415d36cfc420116e6#diff-61be8b0b328aaf8a6ae2f89b67662389R607) per the discussion. Left a [COMPAT comment](https://github.com/jchristman/meteor/commit/0adea8d789e0945b3895732415d36cfc420116e6#diff-61be8b0b328aaf8a6ae2f89b67662389R605) to deprecate the old syntax in favor of the [options] syntax.
 - Reworked [Blaze.renderWithData](https://github.com/jchristman/meteor/commit/0adea8d789e0945b3895732415d36cfc420116e6#diff-61be8b0b328aaf8a6ae2f89b67662389R672) to just call Blaze.render with the correct order of variables. This function is now exactly one line. Left a [COMPAT comment](https://github.com/jchristman/meteor/commit/0adea8d789e0945b3895732415d36cfc420116e6#diff-61be8b0b328aaf8a6ae2f89b67662389R670) to deprecate the use of Blaze.renderWithData entirely.
 - Reworked all tests to reflect syntax. Left [one test with Blaze.renderWithData](https://github.com/jchristman/meteor/commit/0adea8d789e0945b3895732415d36cfc420116e6#diff-d511f478a512464236a0964733ee4f76R2508)
 - All tests passed on my end

**Comment by tmeasday** [comment]
Thanks for this PR, sorry we never got around to merging it. We are currently cleaning up the repository and removing old PRs; if you think this PR still has value and are interested in resurrecting it, we encourage you to re-submit it against current `devel`.

I'd suggest re-opening this PR against https://github.com/meteor/blaze

**Pull request closed without merging**
