### PR TITLE
Added Tracker.afterRun and fixed onRendered callbacks

### LINKED ISSUE #4410: Parent onRendered triggers before child's
The short version is that Blaze.View.prototype.onViewReady uses Tracker.afterFlush to queue the rendered callbacks. This opens up the possibility of a parent's rendered callback to run before a child's one, even though the child already rendered.

This creates issues if you're processing elements on the onRendered functions. The typical example is "locate all unprocessed elements and do something with them, then flag them as processed". If onViewReady uses Tracker.afterFlush then a parent template can process an element before a child template can do it.

Here's a repro: https://github.com/ManuelDeLeon/blaze-rendering-issue

The hierarchy is:

```
body 
  -> editContact 
    -> card
    -> editContactForm
```

`editContact` only displays `card` if `editContactForm` has rendered.

When you run it the output is:

```
editContact.onCreated
editContactForm.onCreated
editContactForm.onRendered
card.onCreated
editContact.onRendered
============= editContact rendered with a card! =============
card.onRendered
```

In other words, `card` renders on the page but `card.onRendered` is called after `editContact.onRendered` (the parent).

The problem is that Tracker.afterFlush sets functions to run in the next cycle, but it allows other computations to be injected into the current queue while the queue is being processed .

The problem is fixed if you use a setTimeout instead of Tracker.afterFlush. The onRendered functions are still set to run on the next cycle but they don't allow other functions to be injected in the queue before they're processed.

So instead of:

```
Blaze.View.prototype.onViewReady = function (cb) {
  var self = this;
  var fire = function () {
    Tracker.afterFlush(function () {
      if (! self.isDestroyed) {
        Blaze._withCurrentView(self, function () {
          cb.call(self);
        });
      }
    });
  };
  self._onViewRendered(function onViewRendered() {
    if (self.isDestroyed)
      return;
    if (! self._domrange.attached)
      self._domrange.onAttached(fire);
    else
      fire();
  });
};
```

You would have:

```
Blaze.View.prototype.onViewReady = function (cb) {
  var self = this;
  var fire = function () {
    setTimeout(function () {
      if (! self.isDestroyed) {
        Blaze._withCurrentView(self, function () {
          cb.call(self);
        });
      }
    }, 0);
  };
  self._onViewRendered(function onViewRendered() {
    if (self.isDestroyed)
      return;
    if (! self._domrange.attached)
      self._domrange.onAttached(fire);
    else
      fire();
  });
};
```

The only change is that `Tracker.afterFlush` becomes `setTimeout`.

onCreated and onDestroyed could get the same treatment (haven't looked at how they're triggered).

Maybe there's another way of dealing with this issue.

### PR DESCRIPTION
**Pull request by mitar**
Fixes #4410 by implementing #5354.

### CODE REVIEW

**Comment by dgreensp** [comment]
I just left a comment in #4410.  On the PR, ideally we would solve this without a new Tracker API method.

**Comment by mitar** [comment]
That Tracker API method is then useful for me also for [server-side autorun](https://github.com/peerlibrary/meteor-server-autorun).

That is why I think it is necessary/useful to have it. And can solve both problems.

**Comment by benjamn** [comment]
Thanks for this PR, and sorry we never got around to merging it. We are currently cleaning up the repository and removing old PRs; if you think this PR still has value and are interested in resurrecting it, we encourage you to re-submit it against current `devel`.

**Comment by mitar** [comment]
This should probably go against https://github.com/meteor/blaze now, no?

**Pull request closed without merging**
