### PR TITLE
Update to Cordova 6.4.0

### PR DESCRIPTION
**Pull request by wojtkowiak**
This is a Cordova update made according to #8155
Testing it right now.

### CODE REVIEW

**Comment by wojtkowiak** [comment]
I have finished testing

**Comment by abernix** [comment]
Apologies for the delay on reviewing this.  This took me quite some time to evaluate (due to environmental delays, mostly: VirtualBox, Windows, Android SDK, etc.) but I'm fairly confident that these changes are all correct.  I tested on Mac (Android and iOS) and Windows (Android only, as no iOS).  Some points worth discussing before introducing this to (hopefully?) Meteor 1.4.3:

* This upgrade requires installation of Android SDK 25, something which I don't think the last Android changes (6.2.0, for example) required (23 has been the "norm" for a while, I think).  As seen in the changes for this PR, this was Meteor's first entry into the 6.x branch of `cordova-lib`.  Cordova doesn't really make it clear [on this page](https://cordova.apache.org/docs/en/latest/guide/platforms/android/) what is the correct API platform for the 6.x branch, though I believe after reading their blog that "API 25" is the correct move.  This will need to be updated in the [Android Prereqs of the Meteor Guide](https://guide.meteor.com/mobile.html#installing-prerequisites-android).
* For whatever reason, in order to build for iOS, I needed to `gem install cocoapods`.  I'm not sure if this is a new requirement or not, but it's not mentioned in the [iOS Prereqs in the Meteor Guide](https://guide.meteor.com/mobile.html#installing-prerequisites-ios) and I don't recall needing this in the past (though it's been a while since I've built an iOS Cordova app and I'm on a new machine).
* I'm fairly sure (though not certain) this will (intentionally) block hot-code push functionality (due to changing native code, etc.).  I'm fairly sure that would have been the case during the upgrade to 6.2.0 as well (which landed in 1.4.2), but I guess it's worth mentioning.

**Comment by wojtkowiak** [comment]
Thanks for the review. I have conducted tests on Windows 10, Xubuntu 16.04 and newest MacOS.

Yeah, cordova page seems to be outdated. The SDK needed is indeed 25 -> https://github.com/apache/cordova-android/commit/35b0ba6d07e7afce3554dc02458ecead76c1b0b5#diff-6899c18ece5b4dbbb91204b8356126d1 I will make PR to the guide. 

`gem install cocoapods` not sure about this one. I do not have an access to OSX right now, but I will try to verify it this week.

About HCP - yes, it changes the compatibility version for sure because the plugin versions used by the packages like webapp, statusbar etc have been changed.

**Comment by GeorgeCalvert** [comment]
FYI, phonegap-plugin-push v1.9.0 uses CocoaPods.  See [this](http://stackoverflow.com/questions/40426460/taco-support-for-cordova-6-4-0-and-ios-4-3-0-cocoapods-doesnt-seem-to-work).

**Comment by abernix** [comment]
@GeorgeCalvert What does that have to do with this Pull Request?

**Comment by GeorgeCalvert** [comment]
@abernix, your review noted the unexpected dependency on CocoaPods.  @wojtkowiak intended to verify but I didn't find any further comment.  I just wanted to close the loop for others as our team too found the dependency unexpected.  Maybe this warrants a note in history.md, but since that references this PR, a quick comment here seemed sufficient.

**Comment by abernix** [comment]
@GeorgeCalvert Ah, right! Did you also have to take action (e.g. `gem install cocoapods`)?

**Comment by GeorgeCalvert** [comment]
Yep :-)   Annoying move by Cordova IMHO.

**Pull request merged**
