### PR TITLE
Add separate SERVER_NODE_FLAGS envar

### PR DESCRIPTION
**Pull request by sebakerckhof**
Since Meteor 0.5.3, Meteor allowed to pass node command line flags to the server node process via the `NODE_OPTIONS` environment variable.

However, as I found out by triaging https://github.com/meteor/meteor/issues/10964 , since Node version 8 / Meteor 1.6 this has become a default node envar with the same behavior:
https://nodejs.org/api/cli.html#cli_node_options_options

The side effect is that this now also affects Meteor tool.

The command line parameters could already be set separately via the `TOOL_NODE_FLAGS` envar.
This makes it also possible (again) for the server.

### CODE REVIEW

**Comment by sebakerckhof** [comment]
Well, it is fully backwards compatible, since node flags keeps working. The breaking change happened in meteor 1.6, when it started to get applied to meteor tool as well dhe to tge chanfes in node

**Comment by StorytellerCZ** [comment]
@sebakerckhof Maybe it happened then, but if it kept working for some now renaming the var is breaking now.

**Comment by sebakerckhof** [comment]
No, since the old var keeps working. People can keep using the old var, and it will keep on working exactly as in meteor 1.6 to 1.10

**Comment by StorytellerCZ** [comment]
:man_facepalming: Of course. Sorry. Well, anyway fixing the merge conflict is I think the only remaining issue here.

**Pull request merged**
