### PR TITLE
Expose SessionDocumentView

### PR DESCRIPTION
**Pull request by mitar**
Useful for some hacking. Style is the same as exposing `SessionCollectionView`.

### CODE REVIEW

**Comment by mitar** [comment]
Used in https://github.com/peerlibrary/meteor-control-mergebox.

**Comment by mitar** [comment]
cc @stubailo ;-)

**Comment by stubailo** [comment]
Looks fine to me!

**Comment by stubailo** [comment]
Merged as 5b4e1c6d39f846198ea3fc987bbca6c1a5293131

**Pull request closed without merging**
