### PR TITLE
Update history.md to include proper release command

### PR DESCRIPTION
**Pull request by wreiske**
The 3.1.0 doesn't work, it has to be 3.1

```
wreiske@removed:~/prj/bluehive-provider$ meteor update --release=3.1.0
Meteor 3.1.0: unknown release.
wreiske@removed:~/prj/bluehive-provider$ meteor update --release=3.1
   Selecting package versions                \
```

### CODE REVIEW

**Review by leonardoventurini — APPROVED** [review]

**Comment by wreiske** [comment]
The build preview doesn't show the updated changelog... is there something I need to do to rebuild the docs site?

**Comment by wreiske** [comment]
Looks good!

https://docs.meteor.com/history.html

🚀 

image

**Comment by leonardoventurini** [comment]
This file is auto-generated. I fixed the root file here a9ecfa9ca57097f799b319fc9b091b49b8794bee

**Comment by Shelagh-Lewins** [comment]
The Migration guide is also incorrect.
[https://v3-migration-docs.meteor.com/](https://v3-migration-docs.meteor.com/)
Meteor doc error

The given command is:
`meteor update --release 3.1.0`

This failed with:
`Meteor 3.1.0: unknown release.`

**Pull request merged**
