### PR TITLE
Instant ready subscriptions

### PR DESCRIPTION
**Pull request by radekmie**
Implement #7878.

### CODE REVIEW

**Comment by radekmie** [comment]
Tests failed because:

```
While selecting package versions:
error: Conflict: Constraint facts@1.0.9 is not satisfied by facts 1.0.9-beta.5.
Constraints on package "facts":
* facts@=1.0.9-beta.5 <- top level
* facts@1.0.9 <- mongo 1.1.12_2
```

Any advice?

**Comment by abernix** [comment]
That test failure was not due to your change.  I re-submitted the test to TravisCI and ran it locally and it passed without fail.

**Comment by radekmie** [comment]
Thanks @abernix!

**Comment by tmeasday** [comment]
Sorry to close this otherwise good change (see reasons on the issue).

If you think this feature is useful, I would suggest making a package that wraps `Meteor.subscribe` is  the way to go.

**Pull request closed without merging**
