### PR TITLE
Use npm bcrypt instead of meteor's

### PR DESCRIPTION
**Pull request by harryadel**
https://github.com/meteor/meteor/issues/11466

### CODE REVIEW

**Comment by harryadel** [comment]
How do I trigger a rebuild?

**Comment by StorytellerCZ** [comment]
Did it for you. It is AppVeyor, it is a bit weird.

**Review by StorytellerCZ — CHANGES_REQUESTED** [review]
`npm-bcrypt` package should be flagged as deprecated in `package.js`.

**Comment by harryadel** [comment]
BTW same can be done to [npm-mongo](https://github.com/meteor/meteor/tree/devel/packages/npm-mongo) would you be interested in such PR? 
And while we're on the topic of depreciation what do you think of https://github.com/meteor/meteor/pull/10936#issuecomment-840334817?

**Review by filipenevola — APPROVED** [review]

**Comment by StorytellerCZ** [comment]
Since @filipenevola has approved it, go ahead @harryadel with npm-mongo as well. I'll change the target branch to 2.3 release and get everything else sorted.

**Review by StorytellerCZ — APPROVED** [review]

**Pull request merged**
