### PR TITLE
Fix #13001

### LINKED ISSUE #13001: Underscore 1.6.0 `_.intersection` bug (Meteor package)
Meteor 2.15 with Underscore 1.6.0

The Meteor version of of the `_.intersection` function in the underscore package returns unexpected results.

https://github.com/meteor/meteor/blob/master/packages/underscore/underscore.js#L528-L535

In the copy of the function below, `_.contains` returns boolean, so the `>= 0` comparison should be removed:

```
_.intersection = function(array) {
  var rest = slice.call(arguments, 1);
  return _.filter(_.uniq(array), function(item) {
    return _.every(rest, function(other) {
      return _.contains(other, item) >= 0;
    });
  });
};
```

Interestingly the v1.6.0 commit in the underscore repo doesn't have this problem:

https://github.com/jashkenas/underscore/blob/1f4bf626f23a99f7a676f5076dc1b1475554c8f7/underscore.js#L506

### PR DESCRIPTION
**Pull request by StorytellerCZ**
A quick fix in underscore. Recommend releasing this as a patch asap.

### CODE REVIEW

**Comment by Grubba27** [comment]
Just making a new underscore release should work?

**Comment by Grubba27** [comment]
Screenshot 2024-02-15 at 09 29 09

underscore@1.6.1 is out!

**Comment by StorytellerCZ** [comment]
Should we merge this now into devel or create 1.16 branch? I think this should be merged now into devel.

**Comment by Grubba27** [comment]
Sorry for the delay! 

We can merge this for sure

**Pull request merged**
