### PR TITLE
Release branch targeting Node 14 update

### PR DESCRIPTION
**Pull request by filipenevola**
Work on upgrading to Node v14. 

This is the PR to centralize all the changes targeting Node 14 update.

Tasks:
- [x] Upgrade Node.js to 14 https://github.com/meteor/meteor/pull/11191
- [x] Unix 14.13.0.0 dev bundle build
- [x] SKIPPED - Node 14.13 because 14.15.4 is working => Windows 14.13.0.0 dev bundle build is failing [log](https://gist.github.com/filipenevola/c41981ba87fa03bfaa25f0b6ec03b746)
- [x] Upgrade dependencies https://github.com/meteor/meteor/pull/11192 and #11398
- [x] Unix 14.15.4.0 dev bundle build
- [x] Windows 14.15.4.0 dev bundle build 
- [x] Tests failing
  - [x] MongoDB is not starting: fixed, the problem was a Number where Node.js was expecting a String.
  - [x] Isolated tests [link](https://circleci.com/api/v1.1/project/github/meteor/meteor/52846/output/106/0?file=true&allocation-id=6050921282e92870538aa386-0-build%2F68D7FF2C): 
    - autoupdate.js: test:autoupdate (OK locally)
    - releases.js: test:springboard (OK locally)
    - releases.js: test:writing versions file (OK locally)
    - run.js: test:update during run (OK locally)
    - source-maps.js: test:source maps from an app (OK locally)
    - source-maps.js: test:source maps from a build plugin implementation (OK locally)
  - [x] Group 0 [link](https://circleci.com/api/v1.1/project/github/meteor/meteor/52848/output/105/0?file=true&allocation-id=6050921382e92870538aa389-0-build%2F4ABBD1B1): 
    - create.js: test:create main (OK locally)
    - shell-tests.js: test:meteor shell (OK locally)
    - update-tests.js: test:'meteor update' alters constraints in `.meteor/packages` (OK locally)
  - [x] Group 5 [link](https://app.circleci.com/pipelines/github/meteor/meteor/687/workflows/bbebdb1f-fde5-4af4-a949-a8dc148b57f9/jobs/52847/parallel-runs/0/steps/0-105?invite=true): 
    - update-tests.js: test:'meteor update' adds constraints to `.meteor/packages` (OK locally)
  - [x] Group 3
- [x] Repeat failing tests from Groups locally 
- [x] Update Docker image on CircleCI to Node.js 14
- [x] Update fibers on meteor-babel https://github.com/meteor/babel/commit/3334fb028cbee663374ea2743c1e1430e5b1083c
```bash
./meteor self-test "<failing test name>" --retries 0 --headless --without-tag "custom-warehouse"
```

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
I'll take a look on addition dependencies to see if we can upgrade them as well and get some performance improvements.

**Comment by sebakerckhof** [comment]
regarding the windows failure, you'll need to update node-gyp dependencies on the build slave:
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(67,5): error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\jenkins\workspace\meteor-dev-bundle-windows\platform\windows_x64\gdbXXX\lib\node_modules\sqlite3\build\deps\action_before_build.vcxproj]
npm.cmd : gyp ERR! build error 
```

I believe running 
`npm install --global windows-build-tools` as admin should do the trick.

**Comment by harryadel** [comment]
Maybe update to Node 15? Also, is there a possibility we get this update before 2.0 release? Thanks!

**Comment by sebakerckhof** [comment]
@harryadel Node odd-numbered releases are typically experimental versions and even-numbered once are meant for (eventual) LTS. That's why we always jump to the next even-numbered one.

**Comment by diavrank** [comment]
I'm excited to use the [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) in Node 14-15. It's too useful.
 
Anyone knows if I can deploy a meteor app (in v1.11.1) with Node 14+? (In dev mode the optional chaining operator works well but I don't know for production environment).

**Comment by afrokick** [comment]
> I'm excited to use the [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) in Node 14-15. It's too useful.
> 
> Anyone knows if I can deploy a meteor app (in v1.11.1) with Node 14+? (In dev mode the optional chaining operator works well with Node 15 in my meteor app but I don't know for production environment).

Optional chaining and other stuff from es2020 works in 12.x+.

**Comment by StorytellerCZ** [comment]
@filipenevola Can you please make the new bundle?

**Comment by filipenevola** [comment]
> @filipenevola Can you please make the new bundle?

Building now. Let's see how it goes.

**Comment by filipenevola** [comment]
> > @filipenevola Can you please make the new bundle?
> 
> Building now. Let's see how it goes.

The dev bundle was created correctly, now let's wait our tests here.

**Comment by filipenevola** [comment]
Actually the Docker image [api-28-node](https://hub.docker.com/layers/circleci/android/api-28-node/images/sha256-8050fd6f31683c57e8bad0c1da1a16083674b5d8144c45a623dacf47c6b5c3ef?context=explore) used by [Meteor CircleCI](https://github.com/meteor/circleci) image is using Node 14.

**Comment by ignl** [comment]
Maybe this PR could be released as 2.1 while other updates could wait until 2.2? I think everyone is eager to get some free performance from new node version :)

**Comment by filipenevola** [comment]
> Maybe this PR could be released as 2.1 while other updates could wait until 2.2? I think everyone is eager to get some free performance from new node version :)

Sure, we are going to release as soon as it's ready.

We have many updates in this branch so we need to test carefully first.

**Comment by zvictor** [comment]
Now that Meteor has changed ownership I wonder what will happen to some of the projects surrounding Meteor once breaking releases make them outdated, such as https://github.com/abernix/meteord.

@abernix sorry to bother, but  do you plan on releasing updates to **meteord** in the future?
If not, would you recommend a way out? Do we have any other docker image providing the same characteristics?

**Comment by harryadel** [comment]
@zvictor The community isn't solely dependent on [abernix/meteord](https://github.com/abernix/meteord). Check https://github.com/urigo/awesome-meteor#docker-images

**Comment by diavrank** [comment]
> Now that Meteor has changed ownership I wonder what will happen to some of the projects surrounding Meteor once breaking releases make them outdated, such as https://github.com/abernix/meteord.
> 
> @abernix sorry to bother, but  do you plan on releasing updates to **meteord** in the future?
> If not, would you recommend a way out? Do we have any other docker image providing the same characteristics?

I recommend you disney/meteor-base docker image. It's always updated.

**Comment by ignl** [comment]
Node 16 was released today. Maybe PR for it could be started right away to not fall back too much as with 14 version?

**Comment by sebakerckhof** [comment]
@ignl At this moment node 16 has not reached LTS status yet and there's also the issue that fibers is not compatible with node 16

**Comment by StorytellerCZ** [comment]
@sebakerckhof is correct, but given fibers issue we will have to start working on Node 16 immediately after this as replacing or working around the removal of fibers is going to be a grand task.

**Comment by ignl** [comment]
Yeah that's what I meant, to start it earlier so that once LTS is ready meteor is ready too. Even more important with breaking changes in new version.

**Comment by vlasky** [comment]
@ignl @filipenevola @StorytellerCZ @sebakerckhof I want to draw your attention to this discussion on what would be needed to rescue node-fibers support in Node.js 16.

The V8 developer who committed the change that inadvertently broke node-fibers has [expressed a willingness to consider implementing a public API that would provide the functionality required to enable node-fibers to work again](https://github.com/laverdet/node-fibers/commit/8f2809869cc92c28c92880c4a38317ae3dbe654d#commitcomment-49505363).

https://github.com/laverdet/node-fibers/commit/8f2809869cc92c28c92880c4a38317ae3dbe654d

**Comment by StorytellerCZ** [comment]
@vlasky I think @benjamn mentioned that in the Fibers discussion thread https://github.com/meteor/meteor-feature-requests/issues/392

**Comment by filipenevola** [comment]
🎉  All the tests are passing as you can see here https://github.com/meteor/meteor/pull/11197/commits/d6aeaf391d80f0085d8f362f5d184538501785bf

🎉

**Pull request merged**
