### PR TITLE
Drop buggy appcache path route support

### PR DESCRIPTION
**Pull request by awwx**
Despite best efforts, we've failed to get URL path routes to work bug free across browsers.

Path routes use the path part of the URL to express "where" or "which page" is being displayed in the application, such as http://example.com/one and http://example.com/two.

The attempt was to support path routes with a application cache manifest fallback entry of "/ /", which caused paths which didn't otherwise match to fall back to the root URL "/", and so load the application HTML.

However Chrome at least adds each and every such encountered path to the manifest as a "master" entry. This slows code update reload times (Chrome will re-download each master entry), and has the danger of eventually running out of space in the application cache (which will cause code updates to fail).

Recent versions of Firefox also appear to have a bug where fallback entries are prioritized above network entries, which causes oauth to fail.  (https://github.com/meteor/meteor/issues/3154)

See https://groups.google.com/forum/#!topic/meteor-core/bUTOXugc5qE and
https://groups.google.com/forum/#!topic/meteor-core/tFXZkhIWeKk
for discussion.

The current best known approach is to use hash fragment routes instead when using the application cache.

For example, http://example.com/#!one and http://example.com/#!two.

The Iron Router package plans to automatically support hash fragment routes when the appcache package is used.  (EventedMind/iron-location@ea5085d)

I've also renamed the appcache-* (with a dash) source code files to appcache_* (with an underline) for naming consistency with the other Meteor core packages.

### CODE REVIEW

**Comment by glasser** [comment]
Hi @awwx! Sorry we took so long to get to this --- you filed it the day before 1.0, and we ended up with a pretty big backlog after this.

Normally we trust your appcache suggestions since you are really the expert on that package.  Here, though, there's a bit of reticence because this is actually a pretty big backwards-compatible change, right?  appcache sites now have to use an entirely different URL scheme?

On the other hand, it sounds like things basically just don't work well with appcache without this change anyway.

One thing that seems clear: we should probably disable Firefox appcache by default (like we used to). There's #3154, and we got lots of reports of problems with docs.meteor.com on Firefox and recently disabled Firefox appcache on it.  Do you agree?

As far as the rest of this goes --- has anything changed in the past 3 months or do you still recommend this change?  eg, does Chrome still have the same bad behavior?  I think that the Iron PR you referred to got released, right?  So most appcache users (using `iron:router`) are just automatically getting hash URLs anyway, right?

**Comment by awwx** [comment]
Well, for me personally, if I had known what I know now back when I first implemented the appcache, I wouldn't have attempted to support path routes.  When I release software, I want to release software that I have confidence I can get to work correctly.  I don't have that confidence about path routes.  There are so many bugs, and the bugs are so heinous (for example, if you exceed the browser's appcache size limit, the browser gets stuck running old code, regardless of what you do from the server), that I feel it would be a major QA effort, a research project really, to figure out how to have confidence that path routes can be made to work correctly.

I haven't in fact tested Chrome recently because I don't have time to do such a major QA effort in my spare time.

I also don't see big companies using path routes either.  Why doesn't gmail use a path route to refer to a specific email?  Why doesn't Amazon use a path route for their Kindle cloud reader web app to refer to a particular book?  And I don't find solutions on the web on Stackoverflow or in blog posts.

So for me, to claim that I can support path routes just because I've been claiming that for a year is a sunk cost fallacy.  Better to say, "whoops, I made a mistake".

On the other hand, I'm not sure *I'd* describe myself as an "expert" on the application cache.  :)  I wrote the original appcache package after reading "Dive Into HTML5".  Then when things didn't work I Googled for answers, found claimed solutions, tried them, and found they didn't work either.  I Googled some more, didn't find anything else, and gave up on path routes.  So I wouldn't be surprised if someone else with some fresh energy and some time to look into it might figure something out.

> One thing that seems clear: we should probably disable Firefox appcache by default (like we used to). There's #3154, and we got lots of reports of problems with docs.meteor.com on Firefox and recently disabled Firefox appcache on it. Do you agree?

As far as I know #3154 is avoided by this PR.  However, with regards to your reports of problems with docs.meteor.com, you now have more information about the real-world performance of Firefox's application cache implementation than I do.  So I agree, best to disable by default, unless and until you have confidence that Firefox can be made to work correctly.

Speaking of disabling by default, if you do want to support path routes for backwards compatibility, I'd suggest making it opt-in and having path routes disabled by default, but something someone can turn on if they're willing to take the risk.  Not everyone uses iron:router, and I think for Meteor it would be better for the defaults to "just work" for people.

**Comment by glasser** [comment]
Yeah. I guess part of the excitement of the `appcache` package is how simple and magic it is --- just type one command and suddenly your app has offline support!  Whereas "type one command, oh also now all of your URLs are changed" is less attractive.

But maybe that's not really the fault of the appcache package... maybe that's the fault of the appcache spec or its support in major browsers.

When you give the examples of Gmail and Kindle, are those examples of the use of AppCache? (I really don't know. While you may not feel like an expert, you still are more of one than I am!)  And your  point is: when my Gmail URL looks like `https://mail.google.com/mail/u/0/#inbox/142533991de5b381`, it's not a surprise that the pre-`#` part is relatively fixed and the varying part is post-`#`?

I appreciate all the work you've put into appcache and Meteor in general over the years.  Certainly you have no obligation to support it in your spare time; let me know if this is feeling like too much of a burden.

That said, maybe it would make sense for people who rely on appcache in their production apps to take over non-core maintenance of the package.

**Comment by awwx** [comment]
> maybe that's the fault of the appcache spec or its support in major browsers.

Yeah, I recall there was a web standards mailing list thread "let's fix the app cache" that got started at one point, but it seems to have died.

> When you give the examples of Gmail and Kindle, are those examples of the use of AppCache?

The Kindle Cloud Reader (read.amazon.com) uses the application cache to support reading books offline.  I don't actually know what gmail does... ;)
 
> And your point is

My point is that I'm not aware of any major web application published by a large company which uses path routes with the application cache.  Meteor's promise is that the individual developer can build client apps like the big companies can; but path route application cache support is going beyond that.  As far as I know no one has figured out how to get path routes to work with the application cache as currently implemented in browsers.

> I appreciate all the work you've put into appcache and Meteor in general over the years. Certainly you have no obligation to support it in your spare time; let me know if this is feeling like too much of a burden.

Well, there's support, and there's major research projects into uncharted territory :D  My original appcache package didn't have path route support, it was someone at Meteor who said "look we can use FALLBACK and support path routes" and I said "Cool!" :)  So now I'm supporting the appcache by submitting this PR saying, "whoops, it didn't work, here's something that does".

> That said, maybe it would make sense for people who rely on appcache in their production apps to take over non-core maintenance of the package.

*shrug*  The browser's application cache does as much as it does, and companies such as Amazon use it successfully for products such as the Kindle Cloud Reader.  I think it's up to you whether you want to have feature parity, given it doesn't have the magical experience you wish it did ;)

**Comment by awwx** [comment]
@glasser 
> we should probably disable Firefox appcache by default

Well, I notice the Amazon Cloud Reader app (read.amazon.com) supports offline reading using the application cache.  (Just as an example of somebody using the application cache for a widely used application on Firefox, apparently without serious bugs).  So if you have the resources and want to support the appcache, it would be useful to find out what the bug is with the appcache package and Firefox and if it can be fixed.

**Comment by tmeasday** [comment]
Thanks for this PR, sorry we never got around to merging it. We are currently cleaning up the repository and removing old PRs; if you think this PR still has value and are interested in resurrecting it, we encourage you to re-submit it against current `devel`.

**Comment by awwx** [comment]
Hey @tmeasday, just to let you know the history, I had submitted this PR as a courtesy.  I had originally included the path route feature at the request of MDG, and when I discovered that it could not be made to work, I submitted this PR to reverse my mistake.  However... I did not sign up to be the unpaid maintainer of a core Meteor package forever.  So I won't be chasing this further: if MDG wants to have a non-buggy appcache as part of core Meteor, you can go ahead and drop the broken feature yourself if you want to; or, if the appcache is no longer on your roadmap for what makes sense to include in core Meteor, you could drop the appcache entirely as a core package and let someone in the community take it over (if anyone cares enough about it to do that).

**Comment by awwx** [comment]
@glasser 

@tmeasday 

Hey guys, it seems to me (in my opinion) that there are two reasonable approaches for you to take:

* Decide that the appcache technology in the browser isn't good enough to support the "magic" you want for Meteor, and drop support for the appcache.  Remove the package from core, and let someone in the community take it on as a community package (if there's someone who cares enough to do that); or,

* Decide that while it's unfortunate the appcache doesn't support path routes, that you do want to support the appcache anyway.  Which, for example, by my suggestion at the time, iron:router did by converting path routes to hash routes.

The *current* situation, where MDG *claims* that the appcache magically works while *knowing* that it doesn't, strikes me as bordering on unethical.  I realize that's a strong statement, but you *publicize* on docs.meteor.com that with the magic of Meteor a developer can "simply add the appcache package to your project"; but, if a developer actually does that, they run the risk of the appcache on their user's browser running out of space, refusing further updates, and then the developer can no longer push updates to the affected users.

To respond to your comment that I might resubmit this PR if "I think it still has value", I submitted this PR as a courtesy, since I had originally included the path route feature at MDG's request, and so when I discovered that it could not be made to work, I submitted this PR to correct my mistake.  But that's as far as my courtesy extends... I'm happy to answer questions if there's anything more I can share (I think I've already told you everything I know), but I didn't sign up to be the ongoing maintainer of the appcache package, so I won't be chasing this PR by rebasing it against current devel as you suggested.

**Comment by awwx** [comment]
@tmeasday  @glasser  I apologize for my previous grumpy reply.  (Must have gotten out the wrong side of the bed that morning or something!)  I added an issue (#6936) as a more productive and um, mature, way of being helpful in, well, tracking the issue ^_^

**Comment by tmeasday** [comment]
Appreciate it @awwx. Actually I found your previous reply helpful, thank you for providing that context :)

Part of the idea of closing a bunch of old PRs was to flush out important ones like this one, and I think it worked in this case. Thanks again.

**Pull request closed without merging**
