### PR TITLE
Expire password reset token

### PR DESCRIPTION
**Pull request by alphanso**
Draft fix for issue #6462. This fix is not ready for merge yet.

- [ ] Get a sign off that approach in theory is correct
- [ ] Add test case for configuration
- [ ] Add test case for token expiration error

### CODE REVIEW

**Comment by alphanso** [comment]
@data I have created this draft pull request to get a sign-off that approach is right. Please provide guidance :)

**Comment by tmeasday** [comment]
@alphanso this looks generally sensible. I think apart from a test for expired reset tokens (I'm not sure we need one for the configuration part, but if you are keen..) it would be good to also clean up old tokens like we do here: https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_server.js#L1084

**Comment by tmeasday** [comment]
Also, there are some failing tests. I'd rebase off current devel as some of those failures look like flakey ones that have been tightened up, but there are some accounts related ones there worth looking at.

**Comment by tmeasday** [comment]
@alphanso, thanks again for this PR. We're still waiting to hear about the comments above--just to let you know, we'll be closing this PR in a week if not.@alphanso

**Pull request closed without merging**
