### PR TITLE
Update to MongoDB  v3.2.15

### PR DESCRIPTION
**Pull request by skirunman**
Install latest version of MongoDB 3.2.x by default.

### CODE REVIEW

**Comment by skirunman** [comment]
Should have done this in a branch I guess.

**Comment by holmrenser** [comment]
I guess this is related to the upgrade to Mongo 3.4. Just wanted to point out that Mongo 3.2 will go end-of-life in little over a year. https://www.mongodb.com/support-policy.

**Comment by hwillson** [comment]
👋 @abernix @benjamn - would one of you be able to publish a new `dev_bundle` with this change? Thanks!

**Comment by abernix** [comment]
I can't make any modifications to this pull-request since it's not on a branch that I have access to.  I've reopened this as #8946.

**Pull request closed without merging**
