### PR TITLE
Move needed files for static-html into static-html-tools

### PR DESCRIPTION
**Pull request by StorytellerCZ**
Following from #11997 I have created a new package `static-html-tools` that houses the needed functionality from Blaze packages. This results of removal of 6 Blaze packages from Meteor projects that don't use Blaze and only use `static-html`.

When running this on my React project:
```
babel-compiler         downgraded from 7.9.2 to 7.9.0
blaze-tools            removed from your project
caching-html-compiler  removed from your project
html-tools             removed from your project
htmljs                 removed from your project
spacebars-compiler     removed from your project
static-html            upgraded from 1.3.2 to 1.4.0
static-html-tools      added, version 1.0.0
templating-tools       removed from your project
```

I would greatly appreciate more testing.

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
As I was fixing the broken test app I have noticed that most of those test apps are outdated when it comes to base Meteor and package version. This means, that on start it has to go through all the upgrades and in some cases like here where there is a significant change. I was thinking that if we update them the test might run a bit faster as the package upgrades won't have to do so much extra work. Thoughts?

**Comment by StorytellerCZ** [comment]
@jankapunkt I did some testing with Blaze and I don't see any impact on it, but I would appreciate your expertize on this as well.

**Comment by jankapunkt** [comment]
@StorytellerCZ any branch on Blaze to check this out?

**Comment by StorytellerCZ** [comment]
@jankapunkt I haven't changed anything in Blaze. I will have to check if there is anything to change.

**Comment by henriquealbert** [comment]
Hey @StorytellerCZ, apologies for checking this PR only now. I believe it may be feasible to launch it on Meteor 3.0's upcoming alpha release. What do you think? Do you know if the changes here are still relevant?

**Comment by StorytellerCZ** [comment]
@henriquealbert yes, they are still relevant, but I will have to resolve the conflicts, but on first look it is just package lock files or similar, so that should make it quick.

**Comment by StorytellerCZ** [comment]
OK, did the merge, but I will monitor the tests.

**Comment by henriquealbert** [comment]
Great @StorytellerCZ! It looks like some tests are failing. Are you able to work on those?

**Comment by StorytellerCZ** [comment]
Those failing tests are not related to the PR, it is an error with puppeteer Node initialization. Had to be fixed in devel first.

**Comment by StorytellerCZ** [comment]
Updated it as part of my stream: https://www.youtube.com/watch?v=cr-Nm0YFb1w
I think this will be ready to go now. If tests pass, which I think they will.

**Review by denihs — APPROVED** [review]
LGTM, let's include this in the next release

**Comment by dr-dimitru** [comment]
@StorytellerCZ Hey I tried this package but getting the next error on latest stable meteor@3.3.2:
```
packages/core-runtime.js:189
            throw error;
            ^
ReferenceError: Plugin is not defined
    at module.wrapAsync.self (packages/caching-compiler/caching-compiler.js:1:12)
    at Module.wrapAsync (/Users/drdimitru/.meteor/packages/modules/.0.20.3.73pbya.lc2yq++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:252:8)
    at module (/Users/drdimitru/Sites/meteor-files-website/.meteor/local/build/programs/server/packages/caching-compiler.js:22:9)
    at fileEvaluate (packages/modules-runtime.js:335:7)
    at Module.require (packages/modules-runtime.js:237:14)
    at Module.mod.require (/Users/drdimitru/.meteor/packages/modules/.0.20.3.73pbya.lc2yq++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:30:33)
    at Object.require (packages/modules-runtime.js:257:21)
    at evaluateNextModule (packages/core-runtime.js:167:26)
    at runEagerModules (packages/core-runtime.js:206:3)
    at processNext (packages/core-runtime.js:128:3)
    at packages/core-runtime.js:138:5
    at runEagerModules (packages/core-runtime.js:144:12)
    at processNext (packages/core-runtime.js:128:3)
    at packages/core-runtime.js:138:5
    at evaluateNextModule (packages/core-runtime.js:163:14)
    at evaluateNextModule (packages/core-runtime.js:202:7)
Node.js v22.18.0
```

**Pull request merged**
