### PR TITLE
Update Cordova Android to 10.1.2

### PR DESCRIPTION
**Pull request by matheusccastroo**
As described on https://github.com/meteor/meteor/issues/12126, updating the cordova-android version to 10.1.2 fixes this issue, since this flag is added automatically by cordova.

This is the release notes for 10.1.2: https://github.com/apache/cordova-android/blob/master/RELEASENOTES.md#1012-apr-11-2022.

Note: we don't need to update the CircleCI image, since it already uses Java 11 and we can still use the build-tools 30.

### CODE REVIEW

**Review by Grubba27 — APPROVED** [review]
LGTM!

**Review by fredmaiaarantes — APPROVED** [review]

**Comment by paulincai** [comment]
@fredmaiaarantes are there any limitations/incompatibilities/challenges to take this to version 11.0.0?

**Comment by Nauzer** [comment]
@matheusccastroo are you able to run meteor run android-device using java 11 and this or the workaround in place? I seem to get only those scenarios to work:

- Using java 1.8 (8) - meteor run android-device  - targetSDK 30 runs fine.
- Use java 11 - meteor build ... builds an APK/AAB with targetSDK 31 fine. Can manually install to device and run.
- Not working java 11 - meteor run android-device with targetSDK 31 in mobile-config give the following error:

```
✗ Android target: Command failed with exit code 1: avdmanager list target
            Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
                at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
                at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
                at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
                at com.android.sdklib.tool.AvdManagerCli.run(AvdManagerCli.java:213)
                at com.android.sdklib.tool.AvdManagerCli.main(AvdManagerCli.java:200)
            Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
                at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
                at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
                at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
```

Any thoughts?

**Comment by matheusccastroo** [comment]
@Nauzer Hello! Yeah, it works with both `meteor build` and `meteor run` .

Did you update the command line tools too? Seems that your meteor command is failing when running the `avdmanager list target`. Are you able to run this as a standalone command?

**Comment by Nauzer** [comment]
No I can't run it.

Tried to follow steps from
https://github.com/meteor/meteor/issues/12126#issuecomment-1211985978
But somehow can't get it to work.

**Comment by Nauzer** [comment]
Here's what I've done so far:

cd $ANDROID_HOME (android sdk location)
execute ./tools/bin/sdkmanager --install "cmdline-tools;4.0"

Add to ~/.zshrc --> export PATH="${ANDROID_SDK_ROOT}/cmdline-tools/4.0/bin:${PATH}"
source ~/.zshrc 

Getting the same error if I run meteor run android-device...

**Pull request merged**
