### PR TITLE
Feature/fibers check enabled by flag

### PR DESCRIPTION
**Pull request by edimarlnx**
Create method to check if Fibers is enabled by flag `DISABLE_FIBERS`.

### CODE REVIEW

**Comment by radekmie** [comment]
What is this for, actually?

**Comment by denihs** [comment]
Hi @radekmie, 

As you may know, we'll not remove Fibers at once. Instead, we'll have both Fibers and non-fibers code running together.

We will use this EV to know if Fibers is disabled or not and, based on that, take the necessary action.

**Comment by zodern** [comment]
The [plan](https://github.com/meteor/meteor/discussions/11505#discussioncomment-2737839) was to create a new Meteor package, for example `fibers`, and use its existence to know if fibers are enabled for an app. Is using an environment variable temporary until that is implemented or is the plan changing?

**Comment by denihs** [comment]
We wanted to start with a flag because it's simpler to test. So AFAIK, it's temporary, and the way it's done now, it's really simple to change it to the package option later.

**Review by denihs — APPROVED** [review]

**Pull request merged**
