### PR TITLE
[backport] Facebook API changes for 1.4.2.x accounts-facebook users.

### PR DESCRIPTION
**Pull request by abernix**
This addresses an issue reported [in this thread](https://github.com/meteor/accounts/issues/23#issuecomment-289889019) (on another repo, which was not meant to track `accounts-*` bugs), in relation to [Facebook's deprecation of the v2.2 API on March 25th, 2017](https://developers.facebook.com/docs/apps/changelog#versions).

For those on Meteor 1.4.**2**.x, this PR represents the release of `accounts-facebook@1.0.12` (already published) which back-ports fixes from meteor/meteor@873f13d743053fc080b5562dec786784bc52a610 and meteor/meteor@2c5dda1675a9e3526e3a926d3ec2b45d0fab14c6 which we released last month.  Developers on 1.4.x Meteor apps who have not updated to Meteor 1.4.3.x can add this to their projects without updating to a newer version of Meteor (although we highly recommend you do that as well!) by running:

    meteor add accounts-facebook@1.0.12

This will support the new Facebook API up to version 2.8 which is due to be supported until ["at least October 2018"](https://developers.facebook.com/docs/apps/versions#howlong) by Facebook

(Those using the latest version of Meteor in the 1.4.**3.x**-series will already have this update with the inclusion of `accounts-facebook@1.1.x` or `facebook-oauth@1.3.0`, which were released with Meteor 1.4.3.1.)

### CODE REVIEW

**Comment by janjackson** [comment]
I am on Meteor 1.3.4 and cannot upgrade for the next few weeks. What can I do in the mean time?

**Comment by abernix** [comment]
@janjackson Meteor 1.3.4 users should be able to clone a copy of the [`facebook` package folder from Meteor 1.3.4](https://github.com/meteor/meteor/tree/release-1.3.4/packages/facebook) into their own `packages/facebook` folder within their app and then apply the two commits in the original message of this PR (meteor/meteor@873f13d743053fc080b5562dec786784bc52a610 and meteor/meteor@2c5dda1675a9e3526e3a926d3ec2b45d0fab14c6).  Both commits are suggested, but on Meteor 1.3.4, you can probably get away with just the first.

You'll note that those commits are on the `facebook-oauth` package, but you should apply them to your `facebook` package (the name changed in Meteor 1.4.3)

**Comment by semeano** [comment]
@abernix I have version 1.4.1.3, and upgrading meteor is not an option for now.
I've done what you've mentioned (but grabbed the 1.4.1.3 release) on the previous comment without any luck... I'm still getting this error:

> Error in OAuth Server: Failed to complete OAuth handshake with Facebook.

**Comment by abernix** [comment]
@semeano Is there anything else after that error message?  Can you provide a reproduction repo on a fresh Meteor 1.4.1.3 project which includes your cloned & fixed copy in your `packages` directory?

**Comment by semeano** [comment]
Hi @abernix, here the full error message:

> => App running at: http://localhost:3000/     
> W20170418-09:50:51.555(1) (oauth_server.js:398) Error in OAuth Server: Failed to complete OAuth handshake with Facebook. {"access_token":"EAAIuzxbHtXwB...M6UTBsZD","token_type":"bearer","expires_in":5119186}
> I20170418-09:50:51.894(1)? Exception while invoking method 'login' Error: Failed to complete OAuth handshake with Facebook. {"access_token":"EAAIuzxbHtXwB...M6UTBsZD","token_type":"bearer","expires_in":5119186}
> I20170418-09:50:51.896(1)?     at getTokenResponse (packages/facebook/facebook_server.js:73:1)
> I20170418-09:50:51.896(1)?     at Object.handleOauthRequest (packages/facebook/facebook_server.js:28:1)
> I20170418-09:50:51.897(1)?     at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:8:1)
> I20170418-09:50:51.897(1)?     at middleware (packages/oauth/oauth_server.js:173:1)
> I20170418-09:50:51.898(1)?     at packages/oauth/oauth_server.js:146:1

Do I have to add the package "facebook"?
I did that but nothing has changed.

Meanwhile let me work on that reproduction repo and I'll get back to you.

**Comment by semeano** [comment]
@abernix got it. All working now :)

**Pull request merged**
