### PR TITLE
Regression test for #2691

### PR DESCRIPTION
**Pull request by mitar**
cc @avital 

It does not pass. I think because your fix is not correct.

### CODE REVIEW

**Comment by avital** [comment]
Yes, you're right. My fix was incorrect and I reverted it. I'll link to this from #2691

**Comment by avital** [comment]
.

**Comment by avital** [comment]
.

**Comment by avital** [comment]
Leaving this open for some future time when we address #2691

**Comment by benjamn** [comment]
Thanks for this PR, and sorry we never got around to merging it. We are currently cleaning up the repository and removing old PRs; if you think this PR still has value and are interested in resurrecting it, we encourage you to re-submit it against current `devel`.

**Comment by keyscores** [comment]
@benjamn I think this test should be included since the original issue that motivated this test is still open. It's not a trivial bug.

**Pull request closed without merging**
