### PR TITLE
[Work in progress] Upgrade to Node 4

### PR DESCRIPTION
**Pull request by benjamn**
This pull request targets the [`wip-upgrade-node`](https://github.com/meteor/meteor/tree/wip-upgrade-node) branch, and will include any changes that help with upgrading Meteor's bundled version of Node to version ~4.4.3, which is the latest LTS release.

This PR will remain open until Meteor is completely stable on Node 4, but changes that make sense for any version of Node (4, 5, or 6) will get merged into the target branch earlier.

Equivalent PR for Node ~5.11.0: https://github.com/meteor/meteor/pull/6922
Equivalent PR for Node ~6.0.0: https://github.com/meteor/meteor/pull/6923

### CODE REVIEW

**Comment by benjamn** [comment]
Once the tests go green, I'm going to merge this pull request into `wip-upgrade-node` and then rebase https://github.com/meteor/meteor/pull/6923 against that.

**Comment by nathan-muir** [comment]
Hey @benjamn I was about to create a nice clean PR for some of those changes.

1. You don't need 	3221b53  as it's patched in faye-websocket v0.11.0 - https://github.com/faye/faye-websocket-node/commit/d3340cdd63364323a1add936c5576c730f9ccdef

2. Looks like you fixed f03de3f in e3c46b6 anyway

3. Missing patch - I still had errors with `node-aes-gcm`, which were resolved by updating from `0.1.3` to `0.1.6` - try `meteor add oauth-encryption` or something else that uses it to see the `node-(pre-)gyp` errors.

**Comment by nathan-muir** [comment]
@benjamn https://github.com/nathan-muir/meteor/commit/659ad5db3087f8fbd50ed0f48e63dc750a24ffbe

**Comment by benjamn** [comment]
Tests are green! Merged onto `wip-upgrade-node`!

**Comment by rickmed** [comment]
@benjamn should this work? I tried the wip-upgrade-node branch on windows but I get 
```
meteor\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
  throw error;
      ^

TypeError: p.replace is not a function
```

Sorry if this is not the issue to put this.

**Comment by benjamn** [comment]
Try the `release-1.4` branch?

**Comment by rickmed** [comment]
@benjamn no dice, same error....

**Pull request merged**
