### PR TITLE
Allow access to Tinytest internals to be able to extend it

### PR DESCRIPTION
**Pull request by mitar**
So we are building an improved version of Tinytest, which has some setup and tearing down capabilities, and would like just to extend Tinytest. So I am proposing that those internals are exposed, but clearly marked as internal with `_`.

### CODE REVIEW

**Comment by glasser** [comment]
Thanks for the feature request! You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by mitar** [comment]
Not sure what exactly more should I do about it? Or are you saying that I should just wait and that this is an example of such less prioritized pull request?

**Comment by glasser** [comment]
Yes.

**Comment by mitar** [comment]
No problem. :-) We are currently doing a workaround by using whole Meteor as a git submodule: https://github.com/peerlibrary/meteor-classy-test Not pretty. But that how it is with Meteor.

**Comment by stubailo** [comment]
@mitar I love your package, looks like a great API improvement to Tinytest, which is kind of undocumented and somewhat inconsistent. Hopefully in the near future (after Windows ships) I will have some time to focus on testing, and then I will take a look at all of this stuff.

**Comment by RobertLowe** [comment]
I like this, `setup` and `teardown` callbacks would be great. 

The only thing I'm not a fan of is the classiness (and I love CS).

I'm rather see something like this:

    Tinytest.setup({
      onSetup: function(){},
      onSetupClient: function(){},
      onSetup Server: function(){},
      onTeardown: function(){},
      onTeardownClient: function(){},
      onTeardownServer: function(){},
      label: 'mypackage'  //save from writing '<package> - ' in every test
    }, function(suite){
      suite.add("something", function (test) {
         // do some testing
      })
    })

**Comment by mitar** [comment]
By exposing this things from this pull request, you can create your own style of a testing framework. :-)

**Comment by mitar** [comment]
BTW, @stubailo such pull requests could really be merged faster. ;-)

**Comment by mitar** [comment]
(Maybe some extra labels would be useful for pull requests. Like a label that a pull request is waiting author to do something. Or that it is waiting for MDG to do something.)

**Comment by stubailo** [comment]
We're working on a Waffle board for this: https://waffle.io/meteor/meteor (not ready yet though!)

In general, it's a real problem and hopefully we can improve the sitation.

**Comment by mitar** [comment]
Hm, that is for all issues, not just pull requests? But it looks great! (I would still hope that GitHub labels would be enough though.)

**Comment by stubailo** [comment]
> (I would still hope that GitHub labels would be enough though.)

It does work through github labels! Each column assigns a label.

**Comment by mitar** [comment]
It seems I will have to look into waffle more. I tried it once but I didn't get it. :-) Thanks.

**Comment by stubailo** [comment]
Yeah it's just a nicer view on data which is present on GitHub, and syncs both ways, for example you can add a label on GitHub to put something in a column. We're also using it for the guide.

I think these tools are the best because you don't _need_ to use them if you don't want to. And if someone else invents something which also displays data from github, you can use it together.

**Comment by mitar** [comment]
Yea! I like that as well.

Although, I would love pull requests merged in sooner as well. ;-)

**Comment by stubailo** [comment]
> I would love pull requests merged in sooner as well. ;-)

Yes, those things are connected.

**Pull request closed without merging**
