### PR TITLE
Track number of documents in SessionCollectionView

### PR DESCRIPTION
**Pull request by koszta**
Fixes issue #9828

### CODE REVIEW

**Comment by veered** [comment]
@koszta You verified that this resolved your performance issues?

**Comment by koszta** [comment]
@veered Yes, thanks for the hint!

In the reproduction repo there is a fix branch using the patched ddp-server:
https://github.com/fuww/blocked-unsub/tree/fix

Now it is not blocking the event loop for more than ~20-30ms while unsubscribing with 2000 published documents.

**Comment by nathan-muir** [comment]
Awesome! Removing the call to `_.isEmpty` reduces the time to unsub from 5s to 500ms (for a production dataset)

Just a thought: instead of the counter, we could also use a [`Map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) which has a `.size` property & better suited to adding/removing items and iteration. (eg. https://github.com/nathan-muir/meteor/commit/d511e551df1c22d7687056a7fd8cb41a8a995e6b)

**Comment by veered** [comment]
This definitely seems worth merging (perhaps after making the change suggested by @nathan-muir )!

**Comment by benjamn** [comment]
I agree that using a `Map` would make this easier!

**Comment by koszta** [comment]
I also agree, but there is `DiffSequence.diffObjects` called with `self.documents`, which I assume would not work with a `Map`

**Comment by koszta** [comment]
Closing this in favor of #10053

**Pull request closed without merging**
