### PR TITLE
Fixes #4522: Mongo upsert with dotted keys

### LINKED ISSUE #4522: upsert: MongoError: The dotted field is not valid for storage
### Steps to reproduce:

```JavaScript
test = new Mongo.Collection("test");
test.update({"subdocument.field": "value1"}, {$set: {"foo": "baz"}}, {upsert: true});
```
### Expected result:

Inserts a document:

```json
{"_id":  "EQawgZfPaYszG9FYA",  "subdocument": {"field": "value1"}, "foo": "baz"}
```

### Actual Result:

```
MongoError: The dotted field 'subdocument.field' in 'subdocument.field' is not valid for storage.
    at Object.Future.wait (/home/gsuess/WebstormProjects/meteor/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
    at [object Object].<anonymous> (/packages/meteor/helpers.js:119:1)
    at [object Object].MongoConnection.(anonymous function) [as update] (/packages/mongo/mongo_driver.js:698:1)
    at [object Object].Mongo.Collection.(anonymous function) [as update] (/packages/mongo/collection.js:575:1)
    at repl:1:7
    at /home/gsuess/WebstormProjects/meteor/examples/leaderboard/.meteor/local/build/programs/server/shell-server.js:264:23
    - - - - -
    at Object.toError (/home/gsuess/WebstormProjects/meteor/examples/leaderboard/.meteor/local/isopacks/npm-mongo/npm/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at /home/gsuess/WebstormProjects/meteor/examples/leaderboard/.meteor/local/isopacks/npm-mongo/npm/node_modules/mongodb/lib/mongodb/collection/core.js:577:27
    at /home/gsuess/WebstormProjects/meteor/examples/leaderboard/.meteor/local/isopacks/npm-mongo/npm/node_modules/mongodb/lib/mongodb/db.js:1195:7
    at /home/gsuess/WebstormProjects/meteor/examples/leaderboard/.meteor/local/isopacks/npm-mongo/npm/node_modules/mongodb/lib/mongodb/db.js:1903:9
    at Server.Base._callHandler (/home/gsuess/WebstormProjects/meteor/examples/leaderboard/.meteor/local/isopacks/npm-mongo/npm/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /home/gsuess/WebstormProjects/meteor/examples/leaderboard/.meteor/local/isopacks/npm-mongo/npm/node_modules/mongodb/lib/mongodb/connection/server.js:487:18
    at [object Object].MongoReply.parseBody (/home/gsuess/WebstormProjects/meteor/examples/leaderboard/.meteor/local/isopacks/npm-mongo/npm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at [object Object].<anonymous> (/home/gsuess/WebstormProjects/meteor/examples/leaderboard/.meteor/local/isopacks/npm-mongo/npm/node_modules/mongodb/lib/mongodb/connection/server.js:445:20)
    at [object Object].emit (events.js:95:17)
    at [object Object].<anonymous> (/home/gsuess/WebstormProjects/meteor/examples/leaderboard/.meteor/local/isopacks/npm-mongo/npm/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/home/gsuess/WebstormProjects/meteor/examples/leaderboard/.meteor/local/isopacks/npm-mongo/npm/node_modules/mongodb/lib/mongodb/connection/connection.js:440:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)
```

### Notes:

When running the same query on mongo directly, it works just fine:

```JavaScript
db.test.update({"subdocument.field": "value1"}, {$set: {"foo": "baz"}}, {upsert: true})
```

```JavaScript
WriteResult({
        "nMatched" : 0,
        "nUpserted" : 1,
        "nModified" : 0,
        "_id" : ObjectId("5574737b843753e392cfa920")
})
```

### PR DESCRIPTION
**Pull request by gsuess**
Fixes #4522:
Break down dotted key-value pairs into an object when simulating an insert.

### CODE REVIEW

**Comment by rclai** [comment]
Nice! Was suffering this myself.

By the way, they might need you to write a test.

**Comment by gsuess** [comment]
@rclai yes I did try to write some tests, but then I figured that the entire mongo-driver is not covered by tests at all...

**Comment by Slava** [comment]
There are plenty of tests. Here is one of several test files: https://github.com/meteor/meteor/blob/devel/packages/mongo/mongo_livedata_tests.js

**Comment by gsuess** [comment]
Ah sorry, didn't realize that all the tests were hidden in there. I was looking for a file name "mongo-driver-test.js"...

**Comment by glasser** [comment]
Hmm, applying the expansion after the dollar operators seems to get the wrong answer for:

```
    collection.upsert({
      "subdocument.a": 1
    }, {
      $set: {'subdocument.a': "upsert 1"}
    });
```

Can you fix this and add tests for this and related cases?

**Comment by gsuess** [comment]
Should be fixed now. Nice catch.

**Comment by gsuess** [comment]
Are there any other test-cases that you would like to add?

**Comment by gsuess** [comment]
@glasser we've been using the forked package for a while now. It seems quite stable. Is there anything else you would like to have covered in the unit test? Is there anything keeping you from merging it?

**Comment by dgreensp** [comment]
@glasser, great catch!  LGTM.

**Comment by dgreensp** [comment]
Merged as e02bf0fb30ed67e4f45417986a548b04de802e1d.

**Pull request closed without merging**
