### PR TITLE
new package binary | replace EJSON and base64 imports

### PR DESCRIPTION
**Pull request by mvogttech**
Two functions shared across many packages are isBinary and newBinary.

Package tests are passing, however self-test is failing. I think the tests need to be rewritten?

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
I don't follow. Why is this desired? Is this going to decrease the number of packages depending on EJSON?

**Comment by mvogttech** [comment]
> I don't follow. Why is this desired? Is this going to decrease the number of packages depending on EJSON?

Exactly.

**Comment by denihs** [comment]
Hi @mvogttech, if you can fix the failing tests, it would be great. Then I will proceed with the review.

 Thank you.

**Comment by Grubba27** [comment]
Hey, @mvogttech hope you are doing well! 
Is there anything we can do to help you to move this pr forward?
If you have found any issues that block you can comment here, and we can discuss here possible solutions

**Pull request closed without merging**
