### PR TITLE
Remove useraccounts from Guide

### PR DESCRIPTION
**Pull request by StorytellerCZ**
This is a proposal to remove the `useraccounts` section from the Guide. This is due to the fact that `useraccounts` packages are no longer maintained and it is causing confusion to people thinking that these packages are official.

### CODE REVIEW

**Review by henriquealbert — APPROVED** [review]
cc @denihs

**Review by Grubba27 — APPROVED** [review]
LGTM!

**Comment by StorytellerCZ** [comment]
I have this as a draft so that there can be discussion on this topic if needed. I will make this into a ready PR in my next round of checking PRs.

**Comment by Grubba27** [comment]
I believe there is no problem in removing this section. As you said in the PR description, it is an unmaintained package.
The only possible downside is the lack of docs if any user is using this package, but I guess the things that we are removing here are also there in their Github repo.

**Review by fredmaiaarantes — APPROVED** [review]

**Pull request merged**
