### PR TITLE
Add git URL to stylus package

### PR DESCRIPTION
**Pull request by dandv**

### CODE REVIEW

**Comment by glasser** [comment]
Hey, I said before that this wasn't a good idea.  But in retrospect I was wrong; having the links on Atmosphere would be great.  Happy to take a bigger PR that adds these lines to all our devel packages.

**Comment by dandv** [comment]
:+1: for changing your mind. Let me take a stab at that.

**Comment by dandv** [comment]
BTW, what's the preferred quote style, `'` or `"`? Package.describe often uses both (e.g. in `weibo/package.js`), and sometimes you can see 

```js
  api.addFiles('accounts_tests.js', 'server');
  api.addFiles("accounts_url_tests.js", "client");
```

(accounts-base).

**Comment by glasser** [comment]
Style guide does not define a preference (though we've talked about maybe doing so).  Being consistent is nice when there's something nearby to be consistent with.

**Comment by glasser** [comment]
(closing in lieu of bigger pr)

**Pull request closed without merging**
