### PR TITLE
#9976: minify error msg 

### PR DESCRIPTION
**Pull request by uicomponent**
Bug reproduction: https://github.com/ilinyevg/meteor-minifier-bug-reproduction

I am not sure how the message should like. Please change it if it is necessary.

### CODE REVIEW

**Comment by filipenevola** [comment]
CLA is still not signed so I'm closing this.

**Comment by drone1** [comment]
Can anyone bug Eugene about signing the CLA so that this can be merged? Anyone have a contact email? I can reach out if needed. I'm guessing he just didn't see this thread?

I just lost about a week tracking down a problem with an obscure minification error. (https://github.com/meteor/meteor/issues/11930) Thanks.

**Comment by lynchem** [comment]
Could we reopen this @filipenevola ? Can we change the author or could someone at MDG resubmit it? It would be a real time saver when debugging these issues.

**Comment by denihs** [comment]
Hi @lynchem, we tried to use the changes on this PR to solve the problem on this [issue](https://github.com/meteor/meteor/issues/11930), but it didn't help that much because of the message [limitation](https://github.com/meteor/meteor/pull/10006/files#diff-75fb3b75ccbe4cb1009d7866d7df267d316d0c1ae4c379b84d5db534ef203092R152), and the error path, that's coming from the bundle and not from the code. 

I'd say it's better if this PR was started fresh, and it was tested with [this](https://github.com/meteor/meteor/issues/11930) issue and [this](https://github.com/meteor/meteor/issues/11721) one, just to see if it's really helping as we want to. It wasn't helpful when we've tried it, and even in the description, they say they didn't know if the message should be as it is.

**Pull request closed without merging**
