### PR TITLE
Fix #3540 by skipping contentBlock templates on lookup

### LINKED ISSUE #3540: Template instance custom properties inaccessible inside content blocks
Reproduction here: https://github.com/rclai/meteor-template-instance-issue

### PR DESCRIPTION
**Pull request by stubailo**
Since we decided to implement Template.contentBlock by using `new Template`, the lookup code for `Template.instance()` was returning it instead of the real enclosing template.

### CODE REVIEW

**Comment by stubailo** [comment]
@dgreensp @avital take a look? Seems pretty straightforward.

**Comment by avital** [comment]
LG2M. I'd still want @dgreensp to take another look though.

**Comment by avital** [comment]
(This is very cool! And awesome that it's an easy fix)

**Comment by stubailo** [comment]
never mind, there is a totally different fix that also fixes the parentData situation that will be applied in a different PR

**Comment by ccorcos** [comment]
I actually [posted in stackoverflow](http://stackoverflow.com/questions/28133536/template-instance-and-context-messed-with-with-blaze-block-helpers) about this before finding these issue tickets. Has a solution been integrated into meteor yet?

**Comment by ccorcos** [comment]
The data context issue is solved, but the Template.instance() still doesnt have any of the variables bound to it, like `confirmDelete` in this example.

```
Template.editRecord.created = ->
  @confirmDelete = new ReactiveVar(false)
```

**Comment by stubailo** [comment]
This is currently not solved, but we are working on it. The new PR is here: #3546

**Comment by ccorcos** [comment]
sweet. Thanks for doing this!

**Pull request closed without merging**
