### PR TITLE
Release 1.3.4.1

### PR DESCRIPTION
**Pull request by benjamn**
Adding a timeout to HTTP requests made by the `meteor` command-line tool (#7143) [caused some Galaxy deploys to fail on slower connections](https://forums.meteor.com/t/1-3-4-breaks-galaxy-deployment-etimedout/25383).

### CODE REVIEW

**Comment by mitar** [comment]
Hm, but this is strange. Because this means that somebody is deploying to Galaxy where they have not send any TCP packet for more than 30 seconds?

**Comment by mitar** [comment]
Maybe the issue is that timeout works for downloading data, not for uploading? So while uploading, timeout is not cleared on uploaded chunks?

Maybe this means that there is a need for some improvements to requests package, or some wrapper around it? Which would take into the account both uploading and downloading, and retry each if it fails, instead of just aborting?

Is this an issue also then for package publishing?

**Comment by benjamn** [comment]
@mitar yeah, I think maybe we should have restricted the default timeout to GET requests (the Galaxy publish request is a POST)

**Comment by mitar** [comment]
Yes, but this is probably an upstream bug. That it does not clear timeout while sending.

**Comment by mitar** [comment]
Because if upload really timeouts, we should be throwing an error. Here it seems that data is being send normally, only because nothing is downloaded while upload is happening, timeout triggers.

But we should have also timeout on uploading.

**Comment by mitar** [comment]
I opened: https://github.com/request/request/issues/2259

**Pull request merged**
