### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by mitar**

### CODE REVIEW

**Comment by mitar** [comment]
@benjamn, I think you can merge this one. :-)

**Comment by tmeasday** [comment]
I would merge this if it was to `devel` ;)

**Comment by mitar** [comment]
Huh, how did this happen? GitHub made this pull request automatically to `master`? That must be bug.

**Comment by mitar** [comment]
Followup: https://github.com/meteor/meteor/pull/6983

**Comment by tmeasday** [comment]
Maybe you ended up browsing master somehow when you saw the code

**Pull request closed without merging**
