### PR TITLE
Add zodern solution for Async stubs

### PR DESCRIPTION
**Pull request by Grubba27**
Relates to this forum [post](https://forums.meteor.com/t/proposal-to-fix-issues-with-async-method-stubs/60826/21?u=grubba)

Created this PR to test the code against our CI

### CODE REVIEW

**Comment by zodern** [comment]
The queue was causing methods and subscriptions to run out of order. I pushed a commit that also queues subscriptions to maintain the order.

Meteor.isAsyncCall is broken. I'm not sure what the purpose of the function is, and how it should behave with the queue's. 
1. Currently it is only true when using Meteor.callAsync. Should it also be true when using Meteor.applyAsync?
2. Currently it is true from when calling Meteor.callAsync until the server result is returned. With the queue's, do you expect it to behave the same (return true if there is at least one async call in the queue or waiting for the server result), or should it only be true while the stub is running or when waiting for the server result?

The tests copied over from the zodern:fix-async-stubs package won't pass until https://github.com/meteor/meteor/issues/12888 is fixed.

**Comment by zodern** [comment]
It seems all of the tests are now passing except for the ones copied from zodern:fix-async-stubs (which requires #12888 to be fixed first).

**Comment by Grubba27** [comment]
In your proposal @zodern, if the `stubPromise` is undefined, we would return it or return the server result?

**Comment by zodern** [comment]
> In your proposal @zodern, if the stubPromise is undefined, we would return it or return the server result?

Meteor.callAsync would always return the server promise, with an additional property for the stub promise. I would assume the stub promise would always be defined (and resolve to undefined for methods without a stub) but it doesn't have to work that way.

**Comment by Grubba27** [comment]
I have [drafted](https://github.com/meteor/meteor/pull/12907)(still working on missing tests) your proposal @zodern(server-first), I got a little bit confused while dealing with the flags for the stubs-first proposal.

**Review by denihs — APPROVED** [review]

**Pull request merged**
