### PR TITLE
Convert `utils/utils.js` to TypeScript

### PR DESCRIPTION
**Pull request by nicu-chiciuc**
This is part of the ongoing conversion to TypeScript.
The pull request was created even though the work on transforming `utils.js` to TypeScript is not finished yet so that there shouldn't be 2 people working on the same file. Creating an issue regarding this would've been another solution but it seems that a WIP pull request works better.

The file is bigger than the previous ones so it should take a little more time.

### CODE REVIEW

**Comment by nicu-chiciuc** [comment]
For some reason CircleCI is not picking up `@types/semver`.

**Comment by benjamn** [comment]
@nicu-chiciuc Try rebasing against the current `origin/release-1.8.2` branch?

**Comment by nicu-chiciuc** [comment]
There are still some rough edges (and I'll probably make some small changes if needed in the following days), but the file should pass for the first iteration. After all the files will transformed to TS, some parts of the code can be transformed further to more idiomatic TS code.

**Comment by filipenevola** [comment]
I'm closing old PRs with problems like tests failing or conflicts. If you are interested in continuing this work please mention me here.

**Pull request closed without merging**
