### PR TITLE
Fix creating symlinks on Windows April 2018 Update

### LINKED ISSUE #9863: [1.6.1.1] Windows April Update: Cannot find module 'fibers'
Long story short: After the latest Windows April Update a previously working 1.6.1.1 installation now yields this:

image

### PR DESCRIPTION
**Pull request by zodern**
`symlinkWithOverwrite` currently relies on Windows throwing an error when creating a file symlink with a source that is a folder, to know when the source is a folder and recreate the symlink as a junction. Windows 10 April 2018 Update no longer throws the error and instead creates the symlink despite it having the wrong type. This PR changes it to check if the source is a folder before creating the symlink.

Fixes #9863.

### CODE REVIEW

**Comment by lanmower** [comment]
What's the status on this issue, is meteor dropping windows support? My windows updated and now there is no way to run my project, which uses cordova.

**Comment by Markus-Mooqita** [comment]
Hi we are facing a very similar problem that we are no longer able to work on our project. 
Is there a workaround for this? Something that we can apply right now to continue working?

**Comment by benjamn** [comment]
@lanmower @Markus-Mooqita Have you tried the latest Meteor 1.7 release candidates, which include this fix?

**Comment by Markus-Mooqita** [comment]
Hi @benjamn we are working on that at the moment. I will let you know if that solves the issue.

**Comment by meteorjsbrasil** [comment]
Guys, same problem here, whats the progress on this?

**Comment by Markus-Mooqita** [comment]
Hi all,

I updated yesterday to 1.7-rc.11 it worked but had some side effects in our project that needed fixing so take this solution with a grain of salt. You can update to a working version using this:

`meteor update --release 1.7-rc.11`

Be aware it can have unexpected side effects.

Cheers,
 Markus

**Comment by meteorjsbrasil** [comment]
I'm updating right now to see what happen. do you know what are the side effects ?

**Comment by Markus-Mooqita** [comment]
Hi @meteorjsbrasil the side effects were mostly around our a little wired combination of tools, coffeescript 2.0, and the useracccounts plugin do not like each other. useracccounts requires coffeescript@1.0.4 and we needed to convert from import {component} "package" to require("package").component calls to fix another issue that appeared. These might all be very specific issues with our code base though.

**Comment by meteorjsbrasil** [comment]
No problems at the moment and I could start the application and do an small test on it and it seams all is working. When you guys will merge this fix into meteor so we dont need to update to specific release?

**Comment by Markus-Mooqita** [comment]
@meteorjsbrasil sorry I am not the right one to ask. I am just a user like you.

**Comment by andrewlorenz** [comment]
I simply regressed the windows update, and everything meteor/node just sprung magically back to life - by meteor I mean the current 1.6 production release and not the 1.7 release candidates.  The option to regress windows was rather hidden (I'd never had to use it before), but it was simple and painless.  More importantly, it took me OUT of this painful dependency of waiting/hoping for MDG to provide a fix.  Because even though 1.7 rc 11 (I think it was) solved the problem this issue identifies, it led me to encounter another different meteor related problem - one for which there appears to be no fix, and few hits on google.  I need to keep my dev project going, and I've got enough of my own bugs! so I don't have time to investigate those for meteor.  Regression back to the previous windows version seems the best bet - if its possible for you to do so.

**Comment by NitroBAY** [comment]
@jestersoftware YES !!!! +10000 Simple fix needs in emergency to be merged in 1.6. I need to deploy my app I don't think I should rely on some alpha versions...

**Comment by benjamn** [comment]
If you don't want to update to the Meteor 1.7 release candidates yet, please try running
```sh
meteor update --release 1.6.1.2-rc.0
```
to install a preview of Meteor 1.6.1.2, which was created specifically to solve this problem.

**Comment by jestersoftware** [comment]
Thank you @benjamn that worked. Really appreciate it!

**Comment by benjamn** [comment]
Oh, by the way, Meteor 1.6.1.2 is final now, so
```sh
meteor update --release 1.6.1.2
```
should work.

**Pull request merged**
