### PR TITLE
Add 'meteor console' as an alias for 'meteor shell'

### PR DESCRIPTION
**Pull request by mbrookes**
Accept "muscle memory" `console` as valid command for those coming from a Rails background.

### CODE REVIEW

**Comment by stubailo** [comment]
I don't know how we feel about aliases for commands, I'm not sure if there are possible complications down the road when names of commands don't map one-to-one with the actual command, for example if someone is writing a wrapper script or similar. What do you think @benjamn?

**Comment by sebakerckhof** [comment]
One problem of aliases is that meteor guides and tutorials might use different terms which can confuse new users. Maybe aliases could be used just to give hints what the correct command is.
E.g. somebody types; `meteor console` and gets a message: `Did you mean meteor shell?`

**Comment by mbrookes** [comment]
@sebakerckhof - that's a fair point (albeit fairly unlikely for a hidden alias), but your solution make sense. @stubailo - rework or close?

**Comment by stubailo** [comment]
Yeah I think we should do the hint that tells you to call meteor shell instead.

**Comment by day** [comment]
I agree if a command doesn't exist, it shouldn't just be silently aliased. However, 'console' was certainly the more obvious choice *for me* as well (admittedly also coming from a Rails background). Since (strictly speaking) a console is piece of hardware, and a shell is a command-line interpreter, 'shell' is the more correct. So, +1 for the hint compromise on this.

**Comment by stubailo** [comment]
Any news?

**Comment by mbrookes** [comment]
Sorry Sashko, got caught up in other things. I have submitted #5593, so will close this.

**Pull request closed without merging**
