### PR TITLE
Replace lru-cache with lru-native2

### PR DESCRIPTION
**Pull request by harryadel**
This PR replaces [lru-cache](https://github.com/isaacs/node-lru-cache) which is no longer maintained with [lru-native2](https://github.com/adzerk/node-lru-native). Both retain the same API so there's not any significant changes. 

I also thought about modernizing the code of caching-compiler especially the [Promise.await](https://github.com/meteor/meteor/blob/devel/packages/caching-compiler/caching-compiler.js#L305) which relies on fibers afaik but thought to ask you first. What do you think?

### CODE REVIEW

**Comment by harryadel** [comment]
@StorytellerCZ Could you please update the dev bundle with lru-native2?

**Comment by filipenevola** [comment]
Hi @harryadel, you are changing multiple packages.

I know the change is the same, but multiple PRs are necessary to get good coverage in the reviews.

I would like to know what issues is this PR addressing as well. It's important to keep the work around solving issues, implementing Roadmap features or in discussions that we have an agreement already. This is what our guideline for contributions say. 

Could you provide what issue this is fixing?

**Comment by harryadel** [comment]
>I know the change is the same, but multiple PRs are necessary to get good coverage in the reviews.
I do agree on the value of modular, single-purpose PRs but it's not some a divine code we have to abide by. Multiple PRs are good when we're tackling a complex problem entailing moderate to big changes to the code. 

This PR only replaces the package with *zero changes* to the code; same methods are still in the new package.    

>Could you provide what issue this is fixing?
While this PR doesn't solve an immediate problem, it aims to improve just the overall status of Meteor by replacing a less maintained package with a more active one. This is similar to what was done here: #11420

**Comment by zodern** [comment]
`lru-cache` released version 7 this month, so it seems to still be maintained..

**Comment by harryadel** [comment]
@zodern You're right. I was too quick to open up a PR without proper consideration. Sorry for the confusion.

**Pull request closed without merging**
