### PR TITLE
Release 1.9.3

### PR DESCRIPTION
**Pull request by filipenevola**
We have a few users having complicated issues with MongoDB Driver version 3.2.7 so we are doing this release just to upgrade MongoDB Driver to 3.5.4.

### CODE REVIEW

**Comment by cfnelson** [comment]
Our Web App (Meteor v1.9.2, running on Meteor Galaxy) had been running for a few days without any code changes. 

Unexpectedly we started to receive errors for login and -> `MongoTimeoutError: Server selection timed out after 10000 ms` for every query. This disabled anyone being about to login or remain connected to our Web App. 

Updating from Meteor 1.9.2 to -> 1.9.3.rc.0 `meteor update --release 1.9.3-rc.0` and redeploying resolved the issue for us. 

Many thanks 🎉 🙇

**Comment by filipenevola** [comment]
Meteor 1.9.3 is published!

**Comment by acemtp** [comment]
Are you sure it's published?

doing a "meteor update" returns:

> $ app git:(master) meteor update
> This project is already at Meteor 1.9.2, the latest release.

**Comment by jnurkka** [comment]
> Are you sure it's published?
> 
> doing a "meteor update" returns:
> 
> > $ app git:(master) meteor update
> > This project is already at Meteor 1.9.2, the latest release.

Do `meteor update --release 1.9.3`, that should work. Maybe your meteor CLI doesn't know of the newest release yet.

**Comment by hexsprite** [comment]
Just because a new update is published doesn't mean it's "recommended" yet. So `meteor update` won't automatically update, but explicitly choosing the version will. eg. `meteor update --release 1.9.3`. It might be good to change the message to indicate that it's the newest recommended version and that there may be newer versions published ?

**Pull request merged**
