### PR TITLE
Add profiling information to clearly outline slow legacy-style compilers

### PR DESCRIPTION
**Pull request by Slava**
Helps to profile apps, like wekan.

https://github.com/meteor/meteor/issues/5269

### CODE REVIEW

**Comment by mquandalle** [comment]
:+1: I removed most of legacy compilers in Wekan in c69f993 but the app still relies on some (like those exported by `tap-i18n`) and they are not easy to find in the PROFILE logs.

**Comment by Slava** [comment]
@mquandalle they won't be in the profiler logs until somebody merges this :( @stubailo

**Comment by stubailo** [comment]
Re-running the tests - they seemed to have some weird behavior. If they are in some reasonable state will merge!

**Comment by Slava** [comment]
Yeah, I don't know. The change in this PR doesn't affect any functional behavior, only profiling reporting (which doesn't have selftests)

**Comment by stubailo** [comment]
OK merged, hopefully the tests are wrong... as they often are. Why is it so hard to write reliable tests? Such an existential question.

**Comment by mquandalle** [comment]
I don’t know, but the [Circle CI logs](https://circleci.com/gh/meteor/meteor/447) are super artistic :p

Circle CI

**Pull request merged**
