### PR TITLE
fixes the runnerw output problem in non-tty windows console #5798

### PR DESCRIPTION
**Pull request by reel**

### CODE REVIEW

**Comment by reel** [comment]
this fixes #5798

**Comment by stubailo** [comment]
Seems reasonable, thanks!

**Comment by stubailo** [comment]
Hmm, it looks like this might have broken the output of Meteor in CircleCI.

**Comment by stubailo** [comment]
Actually, that doesn't seem possible since this code would only run on Windows. Perhaps our tests are just broken. Any ideas, @pcarrier or @justinsb?

**Comment by pcarrier** [comment]
(process.platform === 'win32' && process.stdout.isTTY ? new Array(249).join('\b') : '\r');

Well are those parens right? Seems to me that it should be

    (process.platform === 'win32' && process.stdout.isTTY) ? new Array(249).join('\b') : '\r';

**Comment by pcarrier** [comment]
Spurious failure maybe? Can we retrigger the job?

**Comment by pcarrier** [comment]
Re-triggered, problem solved.
Manually tested with JetBrains 11.0.2, and confirmed that everything still works with `cmd.exe`.

Thanks @reel!

**Comment by reel** [comment]
@stubailo looks like the output is messed up in circle-ci for other builds (perhaps for while). see https://circleci.com/gh/meteor/meteor/389

@pcarrier I was getting tired of this also :smile:

**Pull request merged**
