### PR TITLE
http wrapper to automatically refresh token when talking to google

### PR DESCRIPTION
**Pull request by scottburch**
Example use:

       Accounts.oauth2.http.get(Accounts.oauth2.http.GOOGLE, url, {});

### CODE REVIEW

**Comment by robertpitt** [comment]
Is this still on the agenda to be merged?

**Comment by glasser** [comment]
Well, the PR appears to be out of date, for one (it doesn't merge cleanly).

**Comment by kynan** [comment]
@glasser no surprise after more than 2 years!

**Comment by stubailo** [comment]
I don't think this is likely to be merged, and seems like something that could easily be a package anyway.

**Comment by robertpitt** [comment]
As an FYI on this, my solution was to create a package that managed the access tokens of various providers.

https://gist.github.com/robertpitt/5f0a9286a1a52d58bb18

**Pull request closed without merging**
