### PR TITLE
Make sure no user configuration is used

### PR DESCRIPTION
**Pull request by mitar**
Reproducible builds and stuff.

### CODE REVIEW

**Comment by stubailo** [comment]
Can you add a comment so that the next person who comes along knows why this is here?

**Comment by mitar** [comment]
Done.

**Comment by benjamn** [comment]
Looks good to me, and rebasing my https://github.com/meteor/meteor/tree/npm3 against these changes should be trivial. Thanks for reporting the problem and providing a solution!

**Comment by benjamn** [comment]
After thinking about this some more, I decided it's better to forbid user configuration files dynamically in https://github.com/meteor/meteor/blob/devel/tools/isobuild/meteor-npm.js than to obscure the lookup path when we build npm (which is what https://github.com/meteor/meteor/commit/adaf28b4aabd25cb2e8515bffc78a88e89dbe80b did, if I understand correctly).

**Comment by mitar** [comment]
I have not found a way to forbid user configuration files dynamically. There is no command line switch for this for it that I would found. Or am I missing something?

**Pull request merged**
