### PR TITLE
Fix _setLoggingIn(false) sometimes being called before Meteor.userAsync could return an user

### PR DESCRIPTION
**Pull request by 9Morello**
This PR fixes a behavior on `accounts-base` which could cause `loggingIn` to turn into `false` before `Meteor.userAsync()` was ready toreturn an user, causing a React App to 'flicker' for a split second before showing the user the correct screen.

Here's a terminal output of this snippet in a React app before and after the changes.
```js
const user = useTracker(() => Meteor.user());
const loggingIn = useLoggingIn();
console.log({ user, loggingIn });
```

### Before:
fix_before

### After:
fix_after

The only change is that we only call `this._setLoggingIn(false)` either when we received and error, or when `Meteor.userAsync` finally returns an user, avoiding a situation where the `useLoggingIn` hook would not return the right result.

[This issue](https://github.com/meteor/meteor/issues/13335) _may_ be related.

### CODE REVIEW

**Comment by harryadel** [comment]
Thank you for undertaking this, hopefully this can be reviewed and merged soon.

**Review by denihs — APPROVED** [review]
Nice, this will be included in the next release!

**Comment by denihs** [comment]
@9Morello, before we merge it, could you update your branch with the changes from `release-3.0.4`?

**Comment by 9Morello** [comment]
@denihs sure, give me a moment

**Comment by 9Morello** [comment]
@denihs done

**Comment by denihs** [comment]
Nice thanks!

**Pull request merged**
