### PR TITLE
Fix #6889

### PR DESCRIPTION
**Pull request by tmeasday**
See https://github.com/meteor/meteor/pull/6889

Todo: 

 - [x] Ensure tests pass
 - [ ] Add history entry
 - [ ] Make changes to `vNEXT` of docs
 - [ ] Follow up on issues linked to the #6889

### CODE REVIEW

**Comment by Ben305** [comment]
@tmeasday Thanks a lot for getting this done! Any change to see this in `1.3.3`?

**Comment by tmeasday** [comment]
Nah, we are in rc for 1.3.3 but you can expect to see a beta for 1.4 (with this in it) very soon after the 1.3.3 release

**Comment by gsonnenf** [comment]
Hi, I does the onLogout hook have an argument that returns the user who logged out or his connection? I was playing with a onLogout hook in 1.3.4 and it doesn't seem to have any of that available (perhaps im looking in the wrong place or the real update hasn't been applied yet?)

**Comment by tmeasday** [comment]
Yes, it made it into 1.3.3.1 https://github.com/meteor/meteor/blob/devel/History.md#v1331

It could make sense to add it in another PR if it's not already available.

**Pull request merged**
