### PR TITLE
fix #12642, #12628 https://jira.mongodb.org/browse/NODE-5316

### LINKED ISSUE #12642: mongo@1.16.6 continuous exceptions while polling query
Issue refers to mongo v1.16.6 package.
We identified that when both mongodb database and our application are started simultaneously (i.e. upon server restart), and connection to mongo is established when the mongodb server is still performing some boot actions.

Application is configured without MONGO_OPLOG env variable (i.e. polling strategy is used to retrieve data from subscriptions).
Relevant code from application is as follows:
```
col.find(query, { fields: _fields }).observe({
      added(p) {
        self.add(p._id, p);
        if (callback) callback('added', p);
      },
      changed(p) {
        self.mod(p._id, p);
        if (callback) callback('changed', p);
      },
      removed(p) {
        self.del(p._id);
        if (callback) callback('removed', p);
      },
    });
```

*col* being a Mongo.Collection instance.

We observe that the following log is displayed every 10 seconds

```
2023-05-19T05:21:08.249447113Z Exception while polling query {"collectionName":"_transformations","selector":{},"options":{"transform":null,"projection":{"_id":1,"template":1,"functions":1,"code":1}}} MongoTopologyClosedError: Topology is closed
2023-05-19T05:21:08.249530945Z     at processWaitQueue (/usr/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/sdam/topology.js:550:46)
2023-05-19T05:21:08.249542167Z     at Topology.selectServer (/usr/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/sdam/topology.js:297:9)
2023-05-19T05:21:08.249549679Z     at Topology.<anonymous> (/usr/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/sdam/topology.js:43:94)
2023-05-19T05:21:08.249558513Z     at internal/util.js:308:30
2023-05-19T05:21:08.249566571Z     at new Promise (<anonymous>)
2023-05-19T05:21:08.249574764Z     at Topology.selectServerAsync (internal/util.js:307:12)
2023-05-19T05:21:08.249583543Z     at executeOperationAsync (/usr/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/execute_operation.js:94:35)
2023-05-19T05:21:08.249590881Z     at /usr/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/execute_operation.js:12:45
2023-05-19T05:21:08.249601234Z     at maybeCallback (/usr/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:337:21)
2023-05-19T05:21:08.249609626Z     at executeOperation (/usr/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/execute_operation.js:12:38)
2023-05-19T05:21:08.249616987Z     at FindCursor._initialize (/usr/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cursor/find_cursor.js:54:50)
2023-05-19T05:21:08.249624232Z     at FindCursor.[kInit] (/usr/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cursor/abstract_cursor.js:444:14)
2023-05-19T05:21:08.249631453Z     at next (/usr/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cursor/abstract_cursor.js:512:22)
2023-05-19T05:21:08.249686340Z     at internal/util.js:308:30
2023-05-19T05:21:08.249695383Z     at new Promise (<anonymous>)
2023-05-19T05:21:08.249702634Z     at next (internal/util.js:307:12)
2023-05-19T05:21:08.249712398Z  => awaited here:
2023-05-19T05:21:08.249721571Z     at Function.Promise.await (/usr/app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
2023-05-19T05:21:08.249729751Z     at packages/mongo/mongo_driver.js:1134:14
2023-05-19T05:21:08.249738694Z     at /usr/app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
2023-05-19T05:21:08.249746864Z  => awaited here:
2023-05-19T05:21:08.249755726Z     at Promise.await (/usr/app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
2023-05-19T05:21:08.249764604Z     at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:1183:38)
2023-05-19T05:21:08.249773430Z     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1198:22)
2023-05-19T05:21:08.249783903Z     at SynchronousCursor.getRawObjects (packages/mongo/mongo_driver.js:1248:12)
2023-05-19T05:21:08.249793515Z     at PollingObserveDriver._pollMongo (packages/mongo/polling_observe_driver.js:156:44)
2023-05-19T05:21:08.249816641Z     at Object.task (packages/mongo/polling_observe_driver.js:93:12)
2023-05-19T05:21:08.249826011Z     at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:1026:16)
2023-05-19T05:21:08.249833743Z     at packages/meteor.js:1003:12 {
2023-05-19T05:21:08.249841510Z   [Symbol(errorLabels)]: Set(0) {}
2023-05-19T05:21:08.249849431Z }
```

Application keeps alive, but remains inoperative due to this issue. We would expect the mongo package to be able to automatically recover from this situation, or kill the application. If we restart application once the mongo database is fully started, it works fine.

Happy to share more details if required. Thanks!

### PR DESCRIPTION
**Pull request by yrambler2001**
fix #12642, #12628 https://jira.mongodb.org/browse/NODE-5316

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
@matheusccastroo 

@Grubba27 I suggest to do a patch release.

**Comment by radekmie** [comment]
_(I'll comment here, but this comment applies to #12659 as well.)_

After reading the discussion in #12642 and #12628 (most importantly https://github.com/meteor/meteor/issues/12642#issuecomment-1568224629), I find this fix much better than reverting #12593 (so #12659). Waiting for the connection to happen is _fine_, though I'm not sure if it won't break anything (some test failed on CI). At the same time, I think the ideal scenario would be for the MongoDB driver to backport a fix.

**Comment by matheusccastroo** [comment]
I think this is better than reverting #12593. Other option would be to debug and try to find the exact change from that PR that introduced this problem - but from the discussion it seems to be a driver problem.

**Review by Grubba27 — COMMENTED** [review]
LGTM!
I would argue that v5 connection lock is a better approach but this one is fine too (if it does solve the issue)

(the issue in the CI is being solved in another branch)

**Comment by StorytellerCZ** [comment]
@Grubba27 can't we do a patch release of the `mongo` package to get it out there?

**Comment by KoenLav** [comment]
@Grubba27 another request for providing this as a patch release in Meteor 2.12.x, it's currently blocking us from upgrading to Meteor 2.12, which in turn blocks us from using the Node.js Extended Support Version.

**Comment by Grubba27** [comment]
Meteor 2.13 is out!

**Pull request merged**
