### PR TITLE
Update skeletons to use React 18

### PR DESCRIPTION
**Pull request by StorytellerCZ**
Updated the following skeletons to use React 18 and the new `createRoot` function:
* Apollo
* React
* Typescript

### CODE REVIEW

**Comment by zodern** [comment]
For HMR to work with react 18 we also need to update react-refresh: https://github.com/meteor/meteor/blob/b43018cdd6a20744869a3b1f24c7a4c115fbef64/packages/react-fast-refresh/package.js#L10

**Comment by StorytellerCZ** [comment]
OK, that should be done then. Do I just need to update the npm package or is something more needed?

**Comment by zodern** [comment]
You should only need to update the npm package.

**Comment by Grubba27** [comment]
This sounds like a change for a 2.10 version instead o a 2.9.2

**Comment by Grubba27** [comment]
What is missing here @StorytellerCZ or it is done/ can be merged ?

**Comment by StorytellerCZ** [comment]
@zodern I have updated the package. Please check and let me know if things are fine. @Grubba27 once @zodern approves then it is ready.

**Review by zodern — APPROVED** [review]

**Pull request merged**
