### PR TITLE
Update Cordova up to 7.0.1

### PR DESCRIPTION
**Pull request by janowsiany**
#8686 
Tried to upgrade Cordova up to 7.0.1 release. This was not as easy as i tougth and end up with bumping the package version only.
The error which i have encountered is:
```
While adding platform Android to Cordova project:
TypeError: cordovaProject.projectConfig.getFileResources is not a function at updateFileResources
```
Any one could give me a clue so i could finish this up?

### CODE REVIEW

**Comment by skirunman** [comment]
We really need Cordova 7 support.

**Comment by skirunman** [comment]
@wojtkowiak are you interested in Cordova 7 support and/or ability to decouple Cordova from Meteor as per https://github.com/meteor/meteor-feature-requests/issues/112

@janowsiany is willing to do the work, but is looking for some guidance.

**Comment by benjamn** [comment]
[This change](https://github.com/janowsiany/meteor/blob/90a4391aa6a1857e62617337a5a0083152fe364d/scripts/dev-bundle-tool-package.js#L58) requires building a new dev bundle, which doesn't happen automatically. To rebuild the dev bundle locally, in a checkout of `meteor/meteor`:
```sh
rm -rf dev_bundle
scripts/generate-dev-bundle.sh
meteor --help
```
I'll need to rebuild the dev bundle and publish it to S3 for the tests to pass here, though.

**Comment by benjamn** [comment]
I went ahead and merged this into the `release-1.5.2` branch with a new dev bundle version, since the failing tests seemed to be fixed by updating the dev bundle:
* https://github.com/meteor/meteor/pull/8913/commits/08fdc8a6f00d18f1b46d90633edce49c109ab683
* https://github.com/meteor/meteor/pull/8913/commits/67d62dd0dc6b5f8b4a0eb906c44aeabdd95ba266
Provided all the Cordova-related tests pass on that branch, I'll publish a new beta of 1.5.2, and I would appreciate everyone's help validating it.

**Comment by abernix** [comment]
Since it's related to Cordova updates, it probably makes sense to update the [`cordova-plugin-meteor-webapp`](https://www.npmjs.com/package/cordova-plugin-meteor-webapp) npm/plugin to include https://github.com/meteor/cordova-plugin-meteor-webapp/pull/25.  Therefore, I've just published that plugin to npm as 1.4.2.  I've updated this directly on the `release-1.5.2` branch via https://github.com/meteor/meteor/commit/4fe8541fcd058c82e4c2dbd7d90c68cb50909fd6.

**Comment by benjamn** [comment]
Please test these changes with your Cordova apps after running `meteor update --release 1.5.2-beta.3`! If there are any additional changes needed, I would recommend submitting PRs against the `release-1.5.2` branch, since these changes are not yet on `devel`.

**Comment by janowsiany** [comment]
@benjamn thanks for your guidance
`meteor@1.5.2-beta.3` builds successfully for `cordova-ios`

**Comment by skirunman** [comment]
I am able to build successfully with Xcode 8.3.2 on Mac OS 10.12.5 using the 1.5.2-beta.3 release. I removed `/.meteor/local` before building, but I'm getting these warning messages:

```
WARNING: Attempting to install plugin cordova-plugin-splashscreen@4.0.1, but it should have a minimum
         version of 4.0.3 to ensure compatibility with the current platform versions. Installing the
         minimum version for convenience, but you should adjust your dependencies.
WARNING: Attempting to install plugin cordova-plugin-inappbrowser@1.6.1, but it should have a minimum
         version of 1.7.1 to ensure compatibility with the current platform versions. Installing the
         minimum version for convenience, but you should adjust your dependencies.
WARNING: Attempting to install plugin cordova-plugin-geolocation@2.1.0, but it should have a minimum
         version of 2.4.3 to ensure compatibility with the current platform versions. Installing the
         minimum version for convenience, but you should adjust your dependencies.
WARNING: Attempting to install plugin cordova-plugin-statusbar@2.2.1, but it should have a minimum version
         of 2.2.3 to ensure compatibility with the current platform versions. Installing the minimum
         version for convenience, but you should adjust your dependencies.
```
even though when I check `/.meteor/local/cordova-build/plugins/` it looks like the correct and more recent versions of the plugins are in fact installed.

**Comment by skirunman** [comment]
I was also able to build successfully for Android targeting API 25 using Android SDK tools v26.0.2. This probably means that these issues are also resolved: #8408 #8424 #8464

**Comment by benjamn** [comment]
Fully merged into `release-1.5.2`. Thanks again!

**Pull request closed without merging**
