### PR TITLE
Fix #10347

### LINKED ISSUE #10347: [BUG][meteor/oauth] Is not transpiled with ecmascript
This is a followup to #10305.

IE11 errors out on the property shorthands in `end_of_popup_response.js`:
```
SCRIPT1003: Expected ':'
end_of_popup_response.js (12,24)
```
The shorthands need to be reverted to legacy JS like the rest.

### PR DESCRIPTION
**Pull request by idmadj**
Quick fix for #10347

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
Maybe bump package patch version?

**Comment by jamesmillerburgess** [comment]
This file is included via `addAssets`, so I guess it isn't getting processed by the `ecmascript` package. Should it be getting processed or have an option to get processed?

**Comment by idmadj** [comment]
> Maybe bump package patch version?

Done!

**Comment by idmadj** [comment]
> This file is included via `addAssets`, so I guess it isn't getting processed by the `ecmascript` package. Should it be getting processed or have an option to get processed?

Hard to say. I'm not super familiar with Meteor's package system but AFAIK files added via addAssets cannot be processed.

**Pull request merged**
