### PR TITLE
Remove jQuery from default dependencies.

### PR DESCRIPTION
**Pull request by M4v3R**
This pull request removes jQuery package from default project skeletons.
Also removes it from http package because it didn't use it at all.

### CODE REVIEW

**Comment by abernix** [comment]
Thanks for opening this as a separate issue from the #8327 thread.

I think this is reasonable to consider, but we probably need to take inventory of and consider tutorials (and expectations) that may exist out there right now before merging this.

Could you actually open the `http` part as a separate PR and remove it from this one so we compartmentalize the changes?  That part to me seems like a no-brainer (thanks for finding that!). :wink:

**Comment by abernix** [comment]
Also, can you please enable your CircleCI builds for `meteor` so we can see if the tests pass?  Currently the CircleCI build did not run on this PR:

* Go to https://circleci.com/add-projects
* Click your username on the left
* Find `meteor` on the right
* Click *Build project* next to `meteor`

**Comment by M4v3R** [comment]
@abernix Done.

**Comment by abernix** [comment]
Thank you for submitting this.  I fully agree with your last statement.

Merged manually to `devel` with bf1b58e80a53863a8db505fa1252d31948614af7.  In the future, please submit PRs from the `devel` branch to the `devel` branch.

I've left this PR targeted to `release-1.5` to simply the viewing experience (to exclude 1.5 changes) of this PR. :wink:

**Comment by abernix** [comment]
This should be done in Meteor 1.4.3.2.  You can try the latest 1.4.3.2 beta and help confirm by running:

    meteor update --release 1.4.3.2-beta.0

Please report back if you encounter any problems, and thanks for taking care of this!

**Comment by haojia321** [comment]
If I add jquery from npm, does that mean I have to explicitly import jquery in every js file(assume I use jquery in every js file)?

**Comment by stubailo** [comment]
You could do `window.$ = require('jquery')` but I wouldn't recommend it, importing everywhere is a much better approach.

**Comment by abernix** [comment]
@haojia321 While I fully agree you should prefer an approach (as @stubailo recommended above) where you import in every file )which you'll likely appreciate later and avoids polluting your global namespace) if you'd like to keep the behavior where jQuery is available everywhere with no additional code you can install jQuery from npm, keep the `jquery` package in your Meteor project and it will take care of the `window.$ = require('jquery')` for you, preferring your npm-installed version of jQuery:

```sh
$ meteor add jquery
$ meteor npm install jquery --save
```

**Pull request closed without merging**
