### PR TITLE
Official roles package

### PR DESCRIPTION
**Pull request by StorytellerCZ**
Import history of the roles package.
After this will need to integrate tests and documentation.

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
@nachocodoner @denihs any idea why CircleCi fails? There are no tests added right now, so it should not be affected.

**Comment by denihs** [comment]
The issue was with the `api.versionsFrom` set. I think now everything will become green.

**Comment by StorytellerCZ** [comment]
Of course! Should have noticed that!

**Comment by StorytellerCZ** [comment]
I think we can merge this and the next step is to migrate tests and documentation.

**Comment by denihs** [comment]
Done! The first published version will be done in the next beta/rc 🙌

**Comment by StorytellerCZ** [comment]
Great! I will see if I can find some time to get documentation included, though maybe we might want to hold on that for one more version so that people in the known can be the early adopters and find bugs and in the next version we will add docs and guide for everyone. Thoughts?

**Pull request merged**
