### PR TITLE
Note that Meteor.user() does a DB lookup on the server

### PR DESCRIPTION
**Pull request by lorensr**
#6775 

Thanks @helfer. Would you also please take a look at this small doc addition? #5078

### CODE REVIEW

**Comment by helfer** [comment]
@lorensr Actually, @tmeasday just told me that he's working on moving all the docs over to hexo (in the new-hexo-based-docs branch) and should be done with it in the next few days. Could you make a pull-request against that branch or wait until it's merged and then make the PR again?

**Comment by lorensr** [comment]
Sure thanks

**Comment by tmeasday** [comment]
@lorensr can we please port this over to https://github.com/meteor/docs

**Comment by lorensr** [comment]
Fixed in https://github.com/meteor/docs/commit/db1a565763548ba6084553d8098ea088448f35fd

**Pull request closed without merging**
