### PR TITLE
Release 2.6.1

### PR DESCRIPTION
**Pull request by filipenevola**
#### Highlights
* TailwindCSS 3.x support
* Typescript `4.5.4` upgrade
* New core package: `accounts-2fa` (Docs [preview](https://deploy-preview-11886--meteor-docs.netlify.app/packages/accounts-2fa.html))
* Support for 2FA in `accounts-password` and `accounts-passwordless`
* Postcss Minifier (`minifier-css-postcss`) is now a core package.

Check all changes and issues included in the [Milestone](https://github.com/meteor/meteor/milestone/93).

#### How to use today

Update your project running:
`meteor update --release 2.6.1-beta.3`

#### Breaking Changes

N/A

#### Migration Steps

Read our [Migration Guide preview](https://deploy-preview-11886--meteor-guide.netlify.app/2.6.1-migration.html) for this version.

### CODE REVIEW

**Comment by filipenevola** [comment]
2.6.1-beta.3 is out.

The postcss support is now included in the `standard-minifier-css`, so using only this package is enough to support TailwindCSS 3.x.

**Comment by rj-david** [comment]
Are you sure about this public function: [Accounts.has2faEnabled()](https://deploy-preview-11886--meteor-docs.netlify.app/packages/accounts-2fa.html#Accounts-has2faEnabled) ?

This is a huge security risk as explained by @znewsham here:
https://forums.meteor.com/t/2fa-login-pass-username-before-user-is-logged-in/57493/2?u=rjdavid

**Comment by denihs** [comment]
Hi @rj-david, when we thought about the login flow with 2FA, we didn't see a threat in this function. But as I said in the post, @znewsham has a point, and we'll work on changing the logic there, and it won't be like this in the final version.

**Comment by StorytellerCZ** [comment]
Works fine when testing locally, but when I try to deploy I get the following error:
```
/home/storyteller/.meteor/packages/meteor-tool/.2.6.1-beta.3.hz2a2i.61jy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

TypeError: Cannot read property 'id' of null
    at InputFile.resolve (/tools/isobuild/compiler-plugin.js:405:61)
    at packages/babel-compiler.js:574:23
    at Array.some (<anonymous>)
    at requireWithPrefixes (packages/babel-compiler.js:569:26)
    at requireWithPath (packages/babel-compiler.js:487:14)
    at resolveHelper (packages/babel-compiler.js:459:24)
    at resolveHelper (packages/babel-compiler.js:450:21)
    at packages/babel-compiler.js:432:19
    at Array.forEach (<anonymous>)
    at walkHelper (packages/babel-compiler.js:431:10)
    at walkBabelRC (packages/babel-compiler.js:417:24)
    at BabelCompiler.BCp._inferHelper (packages/babel-compiler.js:514:17)
    at BabelCompiler.BCp._inferFromPackageJson (packages/babel-compiler.js:381:14)
    at BabelCompiler.BCp.inferExtraBabelOptions (packages/babel-compiler.js:334:10)
    at BabelCompiler.BCp.processOneFileForTarget (packages/babel-compiler.js:209:10)
    at packages/babel-compiler.js:123:25
    at /home/storyteller/.meteor/packages/meteor-tool/.2.6.1-beta.3.hz2a2i.61jy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Promise.await (/home/storyteller/.meteor/packages/meteor-tool/.2.6.1-beta.3.hz2a2i.61jy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
    at JsOutputResource.finalize (/tools/isobuild/compiler-plugin.js:931:12)
    at JsOutputResource.hasPendingErrors (/tools/isobuild/compiler-plugin.js:936:10)
    at JsOutputResource.reportPendingErrors (/tools/isobuild/compiler-plugin.js:941:14)
    at ImportScanner.scanFile (/home/storyteller/.meteor/packages/meteor-tool/.2.6.1-beta.3.hz2a2i.61jy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1083:14)
    at /home/storyteller/.meteor/packages/meteor-tool/.2.6.1-beta.3.hz2a2i.61jy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1142:14
    at each (/home/storyteller/.meteor/packages/meteor-tool/.2.6.1-beta.3.hz2a2i.61jy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1321:7)
    at ImportScanner.scanFile (/home/storyteller/.meteor/packages/meteor-tool/.2.6.1-beta.3.hz2a2i.61jy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1105:5)
    at /home/storyteller/.meteor/packages/meteor-tool/.2.6.1-beta.3.hz2a2i.61jy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1142:14
    at each (/home/storyteller/.meteor/packages/meteor-tool/.2.6.1-beta.3.hz2a2i.61jy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1321:7)
    at ImportScanner.scanFile (/home/storyteller/.meteor/packages/meteor-tool/.2.6.1-beta.3.hz2a2i.61jy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1105:5)
    at /home/storyteller/.meteor/packages/meteor-tool/.2.6.1-beta.3.hz2a2i.61jy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1142:14
    at each (/home/storyteller/.meteor/packages/meteor-tool/.2.6.1-beta.3.hz2a2i.61jy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1321:7)
    at ImportScanner.scanFile (/home/storyteller/.meteor/packages/meteor-tool/.2.6.1-beta.3.hz2a2i.61jy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1105:5)
    at /home/storyteller/.meteor/packages/meteor-tool/.2.6.1-beta.3.hz2a2i.61jy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1142:14
    at each (/home/storyteller/.meteor/packages/meteor-tool/.2.6.1-beta.3.hz2a2i.61jy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1321:7)
    at ImportScanner.scanFile (/home/storyteller/.meteor/packages/meteor-tool/.2.6.1-beta.3.hz2a2i.61jy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1105:5)
    at /home/storyteller/.meteor/packages/meteor-tool/.2.6.1-beta.3.hz2a2i.61jy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1142:14
    at each (/home/storyteller/.meteor/packages/meteor-tool/.2.6.1-beta.3.hz2a2i.61jy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1321:7)
    at ImportScanner.scanFile (/home/storyteller/.meteor/packages/meteor-tool/.2.6.1-beta.3.hz2a2i.61jy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1105:5)
    at /home/storyteller/.meteor/packages/meteor-tool/.2.6.1-beta.3.hz2a2i.61jy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1142:14
    at each (/home/storyteller/.meteor/packages/meteor-tool/.2.6.1-beta.3.hz2a2i.61jy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1321:7)
    at ImportScanner.scanFile (/home/storyteller/.meteor/packages/meteor-tool/.2.6.1-beta.3.hz2a2i.61jy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1105:5)
    at /home/storyteller/.meteor/packages/meteor-tool/.2.6.1-beta.3.hz2a2i.61jy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:740:14
    at Array.forEach (<anonymous>)
    at ImportScanner.scanImports (/home/storyteller/.meteor/packages/meteor-tool/.2.6.1-beta.3.hz2a2i.61jy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:738:22)
    at /tools/isobuild/compiler-plugin.js:1381:17
    at Array.forEach (<anonymous>)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:1346:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:1160:8)
    at /tools/isobuild/bundler.js:864:12
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at ClientTarget.make (/tools/isobuild/bundler.js:852:18)
    at /tools/isobuild/bundler.js:3251:14
    at /tools/isobuild/bundler.js:3411:25
    at Array.forEach (<anonymous>)
    at /tools/isobuild/bundler.js:3365:14
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at bundle (/tools/isobuild/bundler.js:3232:31)
    at /tools/isobuild/bundler.js:3175:32
    at Slot.withValue (/home/storyteller/.meteor/packages/meteor-tool/.2.6.1-beta.3.hz2a2i.61jy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.esm.js:69:29)
    at Object.withCache (/home/storyteller/.meteor/packages/meteor-tool/.2.6.1-beta.3.hz2a2i.61jy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/files.ts:1514:39)
    at Object.bundle (/tools/isobuild/bundler.js:3175:16)
    at /tools/meteor-services/deploy.js:610:36
    at /home/storyteller/.meteor/packages/meteor-tool/.2.6.1-beta.3.hz2a2i.61jy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (/home/storyteller/.meteor/packages/meteor-tool/.2.6.1-beta.3.hz2a2i.61jy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:56:12)
    at /tools/cli/commands.js:1495:19
    at Function.run (/home/storyteller/.meteor/packages/meteor-tool/.2.6.1-beta.3.hz2a2i.61jy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/tool-env/tools/tool-env/profile.ts:289:14)
    at /tools/cli/commands.js:1493:18
    at /home/storyteller/.meteor/packages/meteor-tool/.2.6.1-beta.3.hz2a2i.61jy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Promise.await (/home/storyteller/.meteor/packages/meteor-tool/.2.6.1-beta.3.hz2a2i.61jy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
    at /tools/cli/main.js:1535:7

```

**Comment by renanccastro** [comment]
Hi, everyone.
Just to be clear, I've published meteor@2.6.1-beta.4 with only the fix for [this issue here](https://github.com/meteor/meteor/issues/11905). It **does not include** all the changes we have in this 2.6.1 [branch](https://github.com/meteor/meteor/pull/11886). 

If this fix works, we will go with 2.6.1 for the fix, and the current 2.6.1 branch will turn 2.6.2.

**Comment by renanccastro** [comment]
We saw that release 2.6.1 was getting bigger than a patch version, so we decided to create a new minor.

This PR was closed in favor of the [2.7 one](https://github.com/meteor/meteor/pull/11916)

**Pull request closed without merging**
