### PR TITLE
Allow options on Uglyfier

### PR DESCRIPTION
**Pull request by PEM--**
This resolves the loss of options on Uglify discussed here #8658

### CODE REVIEW

**Comment by abernix** [comment]
While this may work temporarily, I'm not sure this is the correct solution at the moment (and I'm hesitant to merge it) because we'll need to figure out a unified mapping (translating them as necessary) of `options` which work with both minfiers to uniformly resolve things such as production source maps (#4384) and potentially for bundle analysis.

If you need the ability to pass options as you have previously (and you're confident that Uglify works for your code base, despite its ECMAScript deficiencies), another option would be to use an [older version of `standard-minifier-js`](https://atmospherejs.com/meteor/standard-minifier-js).

**Comment by PEM--** [comment]
Indeed, this is not enough for babili. In this case, users must also pass options to babel throughout their `.babelrc`. Using the old release doesn't work as the 2.0.0 is a required dependency.

**Comment by hwillson** [comment]
Good points @abernix - sorry for adding the PR encouraged label and using up some of your time @PEM--. I should have thought more about the impact this would have on some of the other Meteor features cooking behind the scenes, like bundle analysis (since this issue is a regression I was a bit "PR please" trigger happy 😳). Your contribution is really appreciated @PEM--; thanks!

**Comment by PEM--** [comment]
Ha ha, I should also add that kind of label on my open source projects 😄
Always a pleasure to help you when I can, guys.

**Comment by abernix** [comment]
While I can certainly appreciate the need for this, unless you'd be willing to work out the details with the duality of two different minifier APIs and maintaining support for that (as the need was demonstrated for with #8378), I think we'll need to not merge this for now.

It'll probably be worth following https://github.com/meteor/meteor/pull/8698 and seeing where that goes as well.  Obviously a unified minifier which handled all use cases would be ideal, but we're not quite there yet.  When this happens, I think it will make sense to re-visit this.

I realize you've run into problems with using older versions of `standard-minifier-js` due to version constraints, but it's certainly possible to replace `standard-minifier-js` with your own minifier package if necessary (as you have with your own fork).  For now, a fork of, or at least copying the [official](https://github.com/meteor/meteor/tree/master/packages/standard-minifier-js) into an app's `packages` directory and making the appropriate changes is the best suggestion for someone who needs this level of customizability.

**Pull request closed without merging**
