### PR TITLE
Added Angular2 to the example repositories

### PR DESCRIPTION
**Pull request by dotansimha**
I added a new base application example, it includes Meteor 1.3 application with Angular2 and Angular2-Meteor applications, along with basic "Hello World" example with unit tests and all the required dependencies for Angular2-Meteor applications.

The idea is to get an easy start for new Angular2-Meteor developers, by providing the command:
`meteor create angular2`.

Thanks.

### CODE REVIEW

**Comment by lorensr** [comment]
Related: https://github.com/meteor/meteor/issues/6974#issuecomment-222007671

**Comment by benjamn** [comment]
I think the command would be `meteor create --example angular2`, right? I haven't thought about this in a while, so I might be wrong…

**Comment by zol** [comment]
Great, thank you. Please rename the example to `angular2-boilerplate` and we'll merge this PR.

**Comment by lorensr** [comment]
Yep, it'll be `--example`:

image

**Comment by dotansimha** [comment]
Yeah sure it will be with `--example` flag. 
@zol - I updated the name. 
Thanks!

**Comment by zol** [comment]
Great, thanks!

**Pull request merged**
